### ISSUE TITLE
Link to Developer Guide returns 404 page not found

### ISSUE THREAD

**Issue by sanjeevkumar761** [kubernetes/website#10083]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
"Read the Developer Guide" link on Kubernetes Documentation [here](https://kubernetes.io/docs/home/?path=contributors&persona=code-contributor&level=foundational) results into a 404 Page Not Found. 

**Proposed Solution:**
Should the link point to https://kubernetes.io/blog/2018/05/01/developing-on-kubernetes/ ? I am not sure about it.

**Page to Update:**
https://kubernetes.io/docs/home/?path=contributors&persona=code-contributor&level=foundational

![404 for develooper guide link](https://user-images.githubusercontent.com/1672998/44621092-67880000-a8a0-11e8-95cd-b5652d8da416.PNG)
Kubernetes Version:
v1.11

**Comment by xmudrii** [comment]
I think the links should just redirect to non-`imported` URLs, e.g. to `https://kubernetes.io/docs/community/devel/` instead of `https://kubernetes.io/docs/imported/community/devel/`.

I've already noticed the issue and created a PR (#10084). This is my first PR to k/website, so I'm not sure is it any good, but potentially it could fix it. :)

Thanks for reporting the issue! :)
