### ISSUE TITLE
Missing jQuery and Bootstrap in API Reference

### ISSUE THREAD

**Issue by jprukner** [kubernetes/website#10385]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Click the button "curl request example" in API reference v1.11.  It does nothing. 
jQuery and Bootstrap scripts are missing.
* https://kubernetes.io/js/bootstrap.min.js 
* https://kubernetes.io/js/jquery-2.2.0.min.js

**Proposed Solution:**
Add missing scripts.

**Page to Update:**
https://kubernetes.io/js/jquery-2.2.0.min.js
https://kubernetes.io/js/bootstrap.min.js

I get 404 both in Firefox and Chromium.

**Comment by embik** [comment]
This issue is still present in the current website (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/). @tengqm any chance this will be fixed in the live website? kubernetes.io/docs is the only allowed resource for the CKA exam and non-working examples is kind of a big deal with the limited time you've got.
