### ISSUE TITLE
Explore transferring tutorial content hosting from Katacoda to K/website

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#10470]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

## Problem

Although the [Katacoda tutorials](https://kubernetes.io/docs/tutorials/) feature on kubernetes.io, the tutorial code doesn't reside in k/website. 

## Proposed solution

Shifting tutorial code into k/website may help resolve technical debt and increase editorial quality.

/cc @bradtopol @BenHall 
/sig docs
/team katacoda

**Comment by BenHall** [comment]
This would be great! 

At the moment, Katacoda expects that the content will live in it's own repository which is why it's been separate. We discussed creating a top-level repository but seemed to be more challenging.

If a top level repo is possible then that would be ideal (from our side). If not, we can update Katacoda to support subdirectories and only trigger the processing if Katacoda based content has changed.
