### ISSUE TITLE
Update Flannel manifest URL

### ISSUE THREAD

**Issue by atoato88** [kubernetes/website#10569]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Deployment cluster with Flannel is stuck at "Installing a pod network add-on" section.

As of now, instruction of this page[1](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network)(at Flannel tab) say following.
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
```
But this manifest is old. Toleration of DaemonSet is insufficient.
As a result of this, `kube-flannel` Pod doesn't run.

**Proposed Solution:**
At coreos/flannel[2](https://github.com/coreos/flannel/) repository, issue[3](https://github.com/coreos/flannel/issues/1044#issuecomment-427247749) exists and PR is merged[4](https://github.com/coreos/flannel/pull/1045).

Should change instructions at `kubectl apply -f` 
from
```
https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
```
to
```
https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
```

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

v1.12.0

**Comment by tengqm** [comment]
Should we wait for the next release of flannel?

**Comment by neolit123** [comment]
> Should we wait for the next release of flannel?

**Comment by neolit123** [comment]
@tengqm @atoato88 
> Should we wait for the next release of flannel?

the 0.11.0 release of flannel is nowhere in sight.
i agree with this change as it would unbreak flannel for k8s 1.12.

i think the tab should move to a single link instead of having the two links - one for `0.10.0` and one with a SHA having the multi-arch support.

the link:
https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
is correct.

@atoato88 would you be able to send a PR for this?

**Comment by atoato88** [comment]
@neolit123 OK, I'll create PR.
