### ISSUE TITLE
Issue with k8s.io/docs/setup/pick-right-solution/

### ISSUE THREAD

**Issue by mohitdevops3** [kubernetes/website#11024]
Hi,
Am new on kubernetes, I am using the amazon linux ami, but there are alot of issues while installation, not able to install the etcd package, please suggest me which operating system is best for setup the kubernetes.

**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by charrywanganthony** [comment]
https://kubernetes.io/docs/setup/pick-right-solution/

**Comment by DanyC97** [comment]
i think @charrywanganthony provided the url which should point to the right direction.

In addition i'd say that the etcd packages are not required anymore since tools like `kubeadm` and others are using static pods.

I'll close this issue for now however should you feel more info needs to be added to docs please open a new issue and we would love to hear your feedback
