### ISSUE TITLE
Issue with /docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by tedstirm** [kubernetes/website#1190]
Issue with /docs/getting-started-guides/scratch/

The Conformance test link under "Running the Conformance Test" results in a page not found.

**Comment by zacharysarah** [comment]
@tedstirm :wave: After some preliminary digging, it looks like this 404 points to some larger content issues.

- The 404 results from a missing file at the link target (http://releases.k8s.io/master/hack/conformance-test.sh). 

  - The `releases` subdomain is no longer part of the [k8s.io repo](https://github.com/kubernetes/k8s.io), and there's a redirect:
  - https://releases.k8s.io points to https://github.com/kubernetes/kubernetes/releases

- The `conformance-test.sh` file was [removed from the repo](https://github.com/kubernetes/kubernetes/pull/23353#r57812441).

  Conformance testing now appears to be a subset of [e2e testing](https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/devel/e2e-tests.md#conformance-tests) as defined [here](https://github.com/kubernetes/kubernetes/blob/master/hack/e2e.go).

Given that the changes to `conformance-test.sh` change this issue from a broken anchor link into a larger content issue, I'll change the [priority for this issue](https://kubernetes.io/docs/home/contribute/review-issues/#p2) from P3 to P2. Because I'm a new contributor to the repo, I'm also going to flag this for docs review.

/cc @jaredbhatti for visibility

**Comment by tengqm** [comment]
@zacharysarah looks like we can close this?

**Comment by zacharysarah** [comment]
@tengqm Agreed.
