### ISSUE TITLE
Update kubeadm setup docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#12078]
This is a
- [x ] Feature Request

**Proposed Solution:**
Update existing topics or create a new topic about setting up and getting started with kubeadm.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
and nearby topics

**Comment by Bradamant3** [comment]
Adding to this issue instead of creating a new one (at least for now). Related work:
- content audit of all of setup
- reorg of setup content based on audit

**Comment by zacharysarah** [comment]
@cody-clark @hogepodge @Bradamant3 Ping for followup 🙇

**Comment by thecrudge** [comment]
/cc @cody-clark @hogepodge @Bradamant3 

From what I can see this page has been updated with relevant information. Please confirm we can close this issue.

**Comment by hogepodge** [comment]
These instructions are most applicable to bare metal. Since cloud provider usage is common, and external cloud provider usage will be mandatory, expanding this document to cover setting —cloud-provider=external and handling the loading of the external provider and removing the scheduling taint from the API server would be very useful.

**Comment by zacharysarah** [comment]
@Bradamant3 👋 Can you provide some scope about specific improvements to do? It would be great to get this issue into an actionable state. 🙇

**Comment by zacharysarah** [comment]
Closing after discussion in the [Q2/Q3 review meeting](https://docs.google.com/document/d/10EFtv-DEIaMStLjWNiGgmLTJMG6UGY0iEOcPTfJLplY/edit#).

/close
