### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by svenkin** [kubernetes/website#12132]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Winodows Installer Links on the Minikube Installation Page are directing to a non existent page on github. 

**Proposed Solution:**
Change the links to
https://storage.googleapis.com/minikube/releases/latest/minikube-windows-amd64.exe
and
https://storage.googleapis.com/minikube/releases/latest/minikube-installer.exe

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/#windows

**Comment by tuanvcw** [comment]
Hi, I'll take this.
Regarding to proposed solution, can we point users to:
https://github.com/kubernetes/minikube/releases/

Because:
1. The users can still get the latest version and in addition, they know exactly what version it is.
2. Many users might not want the latest version, so they can choose any version they want.

Please let me know if this idea is OK :)
Thank you in advance, @svenkin
