### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/

### ISSUE THREAD

**Issue by NicklasWallgren** [kubernetes/website#12187]
- [ ] Feature Request
- [X ] Bug Report

**Problem:**
Running example gives "read-only file system" error on GKE.

```
Error: failed to start container "mysql": Error response from daemon: error while creating mount source path '/mnt/data': mkdir /mnt/data: read-only file system
```

**Comment by NicklasWallgren** [comment]
https://discuss.kubernetes.io/t/running-tutorial-mysql-example-gives-me-read-only-file-system-error/3197

**Comment by sftim** [comment]
It [turns out](https://discuss.kubernetes.io/t/running-tutorial-mysql-example-gives-me-read-only-file-system-error/3197/2) that when running on GKE there is no need to explicitly create a volume. Editing the volume claim to remove the storageclassName and deleting the persistent volume section [does] the trick.
