### ISSUE TITLE
clarify support of new features across version-skewed clusters

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#12325]
Follow up from https://github.com/kubernetes/website/pull/11060, tracked in https://github.com/kubernetes/website/issues/12329

How users are expected to manage use of new features in version-skewed clusters is not clear in user-facing documentation:
- [ ] what statement should be made about new features in version 1.x when running with a 1.x+ control plane and kubelets older than 1.x? is the user responsible for labeling nodes and workloads to only steer pods using those features to nodes with those capabilities? @kubernetes/sig-node-pr-reviews @kubernetes/sig-architecture-pr-reviews 

**Page to Update:**
https://kubernetes.io/docs/setup/version-skew-policy/

**Comment by roberthbailey** [comment]
This is difficult because it depends on the feature. Some features only require an updated control plane (e.g. things that are wholly implemented in the apiserver such as support for CRD versions or in the schedule like multiple scheduler support) while others require kubelets to pick up a new version. 

It seems like each feature should describe the minimum required version for the feature to be used, and also indicate whether that version applies only to the control plane or also to the nodes. For features that require nodes to be updated, labeling can be helpful, but it would be better if the feature owner implemented the feature to degrade gracefully in the scenario where the control plane version is ahead of the node version.

**Comment by sftim** [comment]
I see a PR got merged; is this Done?

**Comment by Aut0R3V** [comment]
Hey
I see that this issue was just opened again. Is there anything I could do here?

**Comment by divya-mohan0209** [comment]
@liggitt : Could you please elaborate if there's anything @Aut0R3V could help with here?
