### ISSUE TITLE
Incorrect defaults shown for kubelet feature-gates reference 

### ISSUE THREAD

**Issue by ojmhetar** [kubernetes/website#12634]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
The feature-gates section in the kubelet reference is not consistent with the correct defaults. 

I'm comparing https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ with 
https://github.com/kubernetes/kubernetes/blob/release-1.13/pkg/features/kube_features.go

Specifically, multiple areas of the documentation state that `PodPriority` is enabled by default in 1.11. However, the kubelet reference shows the default as `ALPHA - default=false`. This is confusing. I do not believe it is the case the apiserver and kubelet have different defaults, rather the documentation is not up to date. 

**Proposed Solution:**
I'm happy to submit a PR for this issue, but I'd just like to make sure this issue just lies with documentation. I'd like to update the documentation for 1.13 with the 1.13 release branch for kubernetes/kubernetes, but I can start with master. 

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by dashpole** [comment]
cc @bsalamat

**Comment by ojmhetar** [comment]
`kubelet --help` gives the expected defaults, so this issue is with the generated doc.

**Comment by Bradamant3** [comment]
Heh, not an issue but an open PR because other folks have tried to address the issue also. See https://github.com/kubernetes/kubernetes/pull/66034. I made sure the bot wouldn't close it, or at least not for another while anyway.

@ojmhetar if you've got ideas for how to address beyond what folks have already attempted, sig-docs would most definitely appreciate it. And feel free to ping me on Slack (where I'm jrondeau) if I can help in any way.
