### ISSUE TITLE
Docs Menu Vertical Scrolling

### ISSUE THREAD

**Issue by adrazich** [kubernetes/website#13984]
**This is a Bug Report**

**Problem:**

The menu on the documentation page scrolls vertically on some pages, not all. For example: https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

![vertical-scrolling](https://user-images.githubusercontent.com/1614075/56608165-26cfba80-65d8-11e9-82ba-16a92c28afe7.gif)

**Proposed Solution:**

```
#docs #vendorStrip { overflow-y:hidden; }
```

**Page to Update:**

https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

**Comment by daminisatya** [comment]
@adrazich This is a great find!! Would you like to fix it? 😄

**Comment by anastassia-b** [comment]
Happened upon this issue and looked around for the source of the css discrepancy between pages. 

**What pages show the discrepancy?**
This internal scrolling appears on the `vendorStrip` of all pages under `/docs/tutorials/kubernetes-basics/*`. 

**What style is causing the scrolling?**
Unlike the other pages, this strip has the css property `margin-bottom: 10px` on the `ul, ol` elements:

<img width="1432" alt="Screen Shot 2019-04-24 at 12 17 52 AM" src="https://user-images.githubusercontent.com/26614978/56639982-c74ccb80-6626-11e9-801f-197d227e352d.png">

Unchecking this 10px margin-bottom style in the chrome dev tools removes the undesirable internal scrolling with no visible changes to the page style.

**Where is this style attribute coming from?**
This property is coming from `styles.css:858`, which is a **Bootstrap v3.3.7** stylesheet. Bootstrap is imported on `Line 54262` in`/static/docs/reference/generated/kubernetes-api/v1.14/index.html`. Since it's one of the last things that's imported, could it be overriding our css resets and styles?

```html
<!-- Line 54260 in index.html -->
</DIV>
<SCRIPT src="/js/jquery-3.2.1.min.js"></SCRIPT>
<SCRIPT src="jquery.scrollTo.min.js"></SCRIPT>
<SCRIPT src="/js/bootstrap-3.3.7.min.js"></SCRIPT>
<SCRIPT src="navData.js"></SCRIPT>
<SCRIPT src="scroll.js"></SCRIPT>
</BODY>
</HTML>
```

**How to fix it?**

The source of the style issue is an additional `ul, ol {margin-bottom: 10px}` property that comes from a bootstrap stylesheet (not in the website source code). I'm not yet ramped up to speed on how the css assets are organized, decided, and compiled for this website, so I don't have an immediate solution. 

I _can_ see that all of the affected pages (53 of them --> all `tutorials/kubernetes-basics/*` in all languages) are doing a unique additional css import:

```html
<link href="/docs/tutorials/kubernetes-basics/public/css/styles.css" rel="stylesheet">
```

ex: https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html#L12

Running the website locally, I know what _doesn't_ fix this problem. 😅 If you delete `<link href="/docs/tutorials/kubernetes-basics/public/css/styles.css" rel="stylesheet">`... it *does* indeed fix the internal scrolling... but removes desired formatting on main parts of the page. Well, had some fun digging around, passing the baton back now!

**Comment by rajvaibhavdubey** [comment]
@daminisatya I would like to work on this.
Thankyou
