### ISSUE TITLE
Localize contributor cheatsheet in Italian

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13998]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Translation result will needs to be put into the `community` repo as well.

/kind feature
/language it
/cc @kubernetes/sig-docs-it-owners

**Comment by chenrui333** [comment]
checkin
/remove-lifecycle stale

**Comment by chenrui333** [comment]
ping @kubernetes/sig-docs-it-owners

**Comment by rlenferink** [comment]
We're working on including additional Italian people to speed up these kind of issues.

**Comment by chenrui333** [comment]
ok, sounds good.

**Comment by sftim** [comment]
/remove-lifecycle rotten
I hope this work continues.

**Comment by fabriziopandini** [comment]
@sftim @chenrui333  could you kindly help me in understanding what is required here?
Only changes to https://github.com/kubernetes/community/ or something on the web site as well?

**Comment by sftim** [comment]
These changes only apply to https://github.com/kubernetes/community/

There are already, for example:
- https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-ko.md
- https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-uk.md

This issue is done if you create https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-it.md and it is a good localization of the English original.

**Comment by fabriziopandini** [comment]
@sftim thanks! PR in flight
