### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-proxy/

### ISSUE THREAD

**Issue by Dionysusio** [kubernetes/website#14164]
**This is a Bug Report**

**Problem:**
kube-proxy启动报错:
flags.go:27] FLAG: --udp-timeout="250ms"
flags.go:27] FLAG: --v="2"
flags.go:27] FLAG: --version="false"
flags.go:27] FLAG: --vmodule=""
flags.go:27] FLAG: --write-config-to=""
server.go:195] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.

**Proposed Solution:**
尝试在命令行执行注入配置参数,这些执行了,但是还差2个参数无法设置, 提示建议使用config文件定义,但是不知道config文件的模板是什么样的?  请问可以给个示例吗?
kube-proxy --bind-address=192.168.188.98  --hostname-override=k8s-98  --cluster-cidr=10.254.0.0/16 --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig --logtostderr=true --v=2 

仍然报错:  还差2个参数无法设置,
[root@k8s-98 kubernetes]# kube-proxy
W0505 09:09:50.524571   93369 server.go:195] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0505 09:09:50.524805   93369 feature_gate.go:226] feature gates: &{{} map[]}
I0505 09:09:50.544302   93369 server.go:409] Neither kubeconfig file nor master URL was specified. Falling back to in-cluster config.
error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
[root@k8s-98 kubernetes]# 

**Page to Update:**
https://kubernetes.io/...

**Comment by DanyC97** [comment]
hi @Dionysusio is this related to specific language page - ie `ZH`?

**Comment by Dionysusio** [comment]
> hi @Dionysusio is this related to specific language page - ie `ZH`?

yeah, chinese. i just wanna know how to use kube-proxy config file, please could you offer an example for me? thank you very much.

**Comment by DanyC97** [comment]
/triage support

@Dionysusio fyi for this type of questions we do encourage everyone to use different discussion channels [Stack Overflow](http://stackoverflow.com/questions/tagged/kubernetes) or [Forum](https://discuss.kubernetes.io/) so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

Saying that have you seen https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/ , does it help ?  

The output of the above page is been auto generated however you can get the same output by running `kube-proxy --help` 

Also fyi you can see the [go reference code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-proxy/config/v1alpha1/types.go) in case you want to go low level.

Hope all this helps for now, however in the future please take into account the comment made about support / help questions.


Again, thanks for using Kubernetes.

**Comment by Dionysusio** [comment]
thank you.   


| |
PhantomMeer
邮箱：eyzk_1112@163.com
|

Signature is customized by Netease Mail Master

On 05/08/2019 17:22, Dani Comnea wrote:

/triage support

@Dionysusio fyi for this type of questions we do encourage everyone to use different discussion channels Stack Overflow or Forum so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

Saying that have you seen https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/ , does it help ?

The output of the above page is been auto generated however you can get the same output by running kube-proxy --help

Also fyi you can see the go reference code in case you want to go low level.

Hope all this helps for now, however in the future please take into account the comment made about support / help questions.

Again, thanks for using Kubernetes.

**Comment by DanyC97** [comment]
@Dionysusio if you happy with the response then i'll close the issue

**Comment by Dionysusio** [comment]
ok,  that's fine
thank you very much.


| |
PhantomMeer
邮箱：eyzk_1112@163.com
|

Signature is customized by Netease Mail Master

On 05/08/2019 19:18, Dani Comnea wrote:

@Dionysusio if you happy with the response then i'll close the issue
