### ISSUE TITLE
Dangling "pick-right-solution" references - Japanese

### ISSUE THREAD

**Issue by sethmccombs** [kubernetes/website#14478]
This is a Bug Report
Problem:

The link from "Cluster Administration Overview" to " Picking the Right Solution" is a 404.
docs/setup/pick-right-solution/ does not exist, as it was removed as a redundant page.

Proposed Solution:
Update the stale links to point to Setup page not the "Picking the Right Solution" page
The references on this page point both too the root of the pick-right-solution page, but also to various IDs that no longer exist, there may be better pages to point those links to.

Page to Update:
https://kubernetes.io/ja/docs/setup/
https://kubernetes.io/ja/docs/setup/on-premises-vm/

**Comment by inductor** [comment]
@sethmccombs The Japanese translation team is currently focusing on finishing the document translation for 1.14 and will start working on 1.15.

I am independently working on this PR https://github.com/kubernetes/website/pull/15590 for the setup pages since the directly structure has completely changed. I think This PR will fix the problem. Can you have a look?
