### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/

### ISSUE THREAD

**Issue by hanoisteve** [kubernetes/website#14818]
**This is a Bug Report**

IT IS NOT CLEAR FROM THE DOCUMENTATION HOW TO ACCESS KUBE-APISERVER 
IT APPEARS TO BE RUN FROM THE COMMAND LINE BASED ON THE DOCUMENTATION. BUT ITS ACTUALLY INSIDE A CONTAINER IN MASTER.

**Problem:**

**Proposed Solution:**
DOCUMENT HOW TO ACCESS KUBE-API SERVER
**Page to Update:**
https://kubernetes.io/...

**Comment by hanoisteve** [comment]
Here is an example of the confusion this is causing.
https://stackoverflow.com/questions/50352621/where-is-kube-apiserver-located
Even after reading the solution, its still not clear to me exactly how one would run the kube-api server. Is it something that can be run after modifying a yaml file? Does the cluster need to be rebuilt? etc.  Why are the features not available through kubeadmin?  I am running into this issue immediately because I am about to install Knative and it says to check if a certain controller is enabled. I then see command lines kube-apiserver to check and set this but absolutely no clue about how to run kube-apiserver itself.

**Comment by sftim** [comment]
Here's some changes that I think could help with this:
- revise https://kubernetes.io/docs/concepts/overview/ and https://kubernetes.io/docs/concepts/architecture/ to have a coherent structure
- add a diagram of a Kubernetes cluster, similar to [post-ccm-arch](https://d33wubrfki0l68.cloudfront.net/518e18713c865fe67a5f23fc64260806d72b38f5/61d75/images/docs/post-ccm-arch.png)
  - that is easily discoverable
  - and up to date
- alter the reference page for kube-apiserver and other daemons so that they link to the relevant concept documentation

**Comment by sftim** [comment]
@hanoisteve it sounds like you had a frustrating experience

I can see why you weren't sure where that component would be running.

/language en
