### ISSUE TITLE
Clarify “Each node in your cluster must have at least 1 CPU”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15123]
A couple of pages:
- [Configure Minimum and Maximum CPU Constraints for a Namespace](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/)
- [Assign CPU Resources to Containers and Pods](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/)

state that
> Each node in your cluster must have at least 1 CPU.

Based on what I know about nodes, this seems like something you could take for granted.
Consider ~dropping~ revising that text.

**Comment by sftim** [comment]
Just realized this is talking about Kubernetes' count of CPUs, rather than what (say) the Linux kernel would see. That might not be obvious to every reader&mdash;I missed it, for example.

**Comment by sftim** [comment]
Happy to help with explanations for anyone who is picking this up.

**Comment by davivcgarcia** [comment]
@sftim I was reviewing the docs and I think the statement `Each node in your cluster must have at least 1 CPU.` is referring to the minimal requirements to execute the proposed tasks (and I think this is wrong, because some exercises goes up to 2 cores'. Not sure if my understanding is the same as yours.

**Comment by sftim** [comment]
The “1 CPU” means 1.0 of Kubernetes CPU units. That's different from saying “there needs to be at least one physical CPU core available”. Readers new to Kubernetes might not grasp that Kubernetes has its own idea of CPU number and assume that a Node that runs the kubelet OK must have at least one installed core available to make code execution possible.

For example: a node with 0.5 CPU doesn't meet the 1.0 CPU requirement.


If some exercises require more than 1.0 CPU then those pages should explain that. I think addressing that might be a different issue though.

**Comment by davivcgarcia** [comment]
Honestly, I'm still don't get it. I thought the **Kubernetes CPU** reflects what the operating system reports (ex.: `grep -c processor /proc/cpuinfo`). I wasn't considering possible to have a Kubelet running on a node and reporting only 0.5 CPU (how do we do that? flags? cgroup via systemd?). 

Since the docs are not using term **physicial**, I still think the original author was referring to minimum required resource for the task examples.

**Comment by sftim** [comment]
To be honest, I might have this wrong too. I do know that the existing text is not clear.

**Comment by sftim** [comment]
An example of an instance type with < 1.0 CPU: https://cloud.google.com/compute/docs/machine-types#n1_shared-core_machine_types

**Comment by davivcgarcia** [comment]
Even those shared core instances will reports 1 vCPU, but I got your point. I'll try something here!
