### ISSUE TITLE
Migrate Connecting Applications with Services to Task page(s)

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15560]
**This is a Feature Request**

**What would you like to be added**
Migrate https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ to one or more Task pages

**Why is this needed**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ reads more like a task than it does conceptual documentation.
Seems to me that it'd be better to turn this page into one or more tasks.
As part of this work, optionally make the Service concept shorter (if it becomes possible to signpost readers to the new Task pages from the Service concept page).

**Comments**
Also see issue #14770

**Comment by shannonxtreme** [comment]
How does this page differ from https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/? That task seems to be about exposing applications to external clients while this page seems more about using Services to connect pods in a cluster. Is that about right?

**Comment by sftim** [comment]
Perhaps it's OK to combine two task pages, or simply to remove https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ and redirect it to https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/

https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#securing-the-service covers TLS; that could split into its own follow-on task page? If so, that change also helps with #14725!

**Comment by shannonxtreme** [comment]
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ is a concept page but it's mostly steps. I'm going to try to do the following: 

1. Separate the conceptual info and keep it on https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ to better describe the model.
2. Combine https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ and  https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/ into a single task.
3. [Maybe] Create a follow-on task for TLS based on https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#securing-the-service (or merge that into the task page for number 2).

@sftim what do you think?

**Comment by shannonxtreme** [comment]
Some findings: The tasks on https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ encompass the tasks in https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/ and provide more recommendations for securely exposing the app to the internet. 

Instead of separating the conceptual info (there isn't a lot of it), I'll merge the pages into https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/ as the single source, splitting out the TLS into another task. I think we can safely delete the concept page when that's done.
