### ISSUE TITLE
Discover the scope and requirements to refactor the K8s docs API generation process

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#15682]
- Start research in the [docs release playbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/docs#late-steps-weeks-9-11). Read all links and linked issues related to reference doc generation. (Make sure you understand the scope of the problem and what's required to fix it.)

- Create a new GitHub issue describing the requirements and scope of work required to refactor reference doc generation for a simple, reliable set of commands that produces output with improved, uniform formatting. (Make it easy for other stakeholders to understand the extent of the challenge and what's required to fix it.)

- Get stakeholder input, then implement a solution. (Get everyone on board, then fix the problem. The docs should be easy to generate, and the outputs should all match with better formatting.)

/sig docs
/priority important-soon
Assign to @aimeeu

**Comment by thecrudge** [comment]
This could potentially fix #15536

**Comment by aimeeu** [comment]
I learned from @kbhawkey and @tengqm that the purpose of the website/update-imported-docs/update-imported-docs tool **is** to automate the generation of the reference component docs. Once I had the correct versions of the required software installed, I ran the script locally and then updated the _Generating Reference Pages for Kubernetes Components and Tools_ page (PR 16777) to reflect those versions. 

Based on what I've learned, I'll talk to @jimangel about my updating the Docs Release Playbook to use the update-imported-docs tool. kbhawkey had a great idea - hold a training session for the docs release team (or person) since the process is new to the release team and many release team members are new to Docs as well.

**Comment by aimeeu** [comment]
Add software versions to  script documentation https://github.com/kubernetes/website/pull/16777

**Comment by aimeeu** [comment]
**Testing**

1. In directory 1, generate the API and kubectl references docs manually; process documented [here](https://github.com/aimeeu/cheats/blob/master/k8s-ref-docs/gen-api-and-kubectl.md)
2. In directory 2, clone kubernetes/website and run the website/update-imported-docs/update-imported-docs.py script 
3. Compare the two directories

`update-imported-docs.py` 
1. does not create static/docs/reference/generated/kubernetes-api/<MINOR_VERSION> directory and the style files within
2. does not add the new <MINOR_VERSION> link to  the content/en/docs/reference/_index.md
3. does not update the <MINOR_VERSION> in  content/en/docs/reference/kubernetes-api/index.md
