### ISSUE TITLE
/tutorials/clusters/apparmor/ says AppArmor is only supported by Docker

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/website#16478]
**This is a Bug Report**

**Problem:**
The website says AppArmor is only supported by Docker

> `Currently the only Kubernetes-supported container runtime that also supports AppArmor is Docker`

> `If the Kubelet contains AppArmor support (>= v1.4), it will refuse to run a Pod with AppArmor options if the runtime is not Docker.`

**Proposed Solution:**

Clarify that Kubernetes >= v1.XX supports AppArmor for non-docker CRI runtimes such as containerd/CRI >= v1.X and CRI-O >= v1.XX

**Page to Update:**
https://kubernetes.io/docs/tutorials/clusters/apparmor/

**Comment by estesp** [comment]
I just ran into this as well with someone claiming Docker is the only runtime implementation supporting AppArmor and had made a decision not to use containerd because of this. I would submit a PR with suggested wording fix, but that whole section on runtimes and apparmor profiles probably needs a healthy re-write and verification that it is correct.

**Comment by AkihiroSuda** [comment]
Seems addressed recently
