### ISSUE TITLE
review docs/tasks Access cluster for duplicate content

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#16649]
**This is a Bug Report**

Review the following pages for duplicate content. Clarify the differences.
- https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/
- https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

**Proposed Solution:**
Clean up duplicate content or condense content to a single page.

**Page to Update:**
- https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/
- https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

**Kubernetes Version:**
v1.16

**Comment by hase1128** [comment]
@kbhawkey 

I define as follows for simple explanation in my comment.

 - `access-cluster doc`: https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/
 - `access-cluster-api`: https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

 Sections above [this](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-services-running-on-the-clusterhttps://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) in `access-cluster doc` are almost same as `access-cluster-api doc`.
However, more detail explanations are described in some section in `access-cluster-api doc`.
So, my proposal is that:

 - Remove sections above [this](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-services-running-on-the-clusterhttps://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) in `access-cluster doc` 
 - Alternately, add link to `access-cluster-api doc` in `access-cluster doc`

If you like my proposal, I make PR. How do you think about it?

**Comment by kbhawkey** [comment]
@hase1128, Some ideas:
There is definitely overlap of content between the pages.
Is the content, or some content about accessing the cluster, required in both sections (access-application-cluster and adminster-cluster), or which section is the best place for the content?
This page was recently updated with the main client library information,
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

**Comment by hase1128** [comment]
@kbhawkey 
> Is the content, or some content about accessing the cluster, required in both sections (access-application-cluster and adminster-cluster), or which section is the best place for the content?

It ’s difficult to think about this. In addition, if someone updates these documents in the future, he (she) will be always bothered to update both or one. There also may be a risk to allow incompatible content(e.g. one content is latest, but another one is old).

When considering easy maintenance, is it better to combine two documents into one?
When consolidating, I think it is better to consolidate administer-scluster to access-application-cluster.

The reason is as follows:
 -Documents located in adminster-cluster category should be used for managing cluseter
 -Documents located in access-application-cluster category should be used for accessing cluster

Some idea for consolidate:
1. Completely overlapping sections:  easy to consolidate 
2. (Although it is almost the same content), a slightly different section: adopts the newer content?
3. Independent sections: easy to consolidate?
