### ISSUE TITLE
Difference between --from-env-file single vs multiple

### ISSUE THREAD

**Issue by shaktiprasadrath** [kubernetes/website#16729]
**This is a Bug Report**

If --from-env-file with multiple file will ONLY take the last file then why we have this option. this is as good as --from-env-file from a single file.

**Proposed Solution:**
There should be an option to take --from-env-file from multiple files.

**Page to Update:**
https://kubernetes.io/...

1.1.13

**Comment by christophercarney** [comment]
Page referenced: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files

I agree this is confusing for users as the documentation does mention it in passing as if it is a feature but it is actually supposed to be a warning.

**Proposed Solution:** Adjust the wording to make it clear that this is a warning rather than a feature

@shaktiprasadrath You may want to open this issue in kubernetes/kubectl but I believe the correct pattern would be to create separate config maps for each file so they can remain independent

**Comment by sftim** [comment]
The page states:
> You can pass in the --from-file argument multiple times to create a ConfigMap from multiple data sources.

I have not tried this, TBH. It sounds like kubectl ought to warn people if `--from-file` is specified more than once (that'd be a separate issue against kubectl).

If kubectl doesn't have that warning but kinda should, then the documentation should have a warning instead. IMO.

**Comment by christophercarney** [comment]
It looks like the distinction then is between `--from-file` and `--from-env-file`. For the latter:

> When passing --from-env-file multiple times to create a ConfigMap from multiple data sources, only the last env-file is used

So it looks like the `--from-file` is the more robust preferred option, but `--from-env-file` may be supported for legacy reasons, but I'd have to confirm

**Comment by lapwat** [comment]
As I understood:

`--from-file` loads filename:filecontent as a unique key:value pair
`--from-env-file` loads each line (formatted as `KEY=value`) as key:value pairs

So `--from-env-file` is not legacy. It is a way to load a set of environment variables.

I think it is a good behavior to be able to load a unique env file.

Proposed Solution:
There should be an error if `--from-env-file` option is used more than once in the same command.

**Comment by sftim** [comment]
To request an enhancement to `kubectl`, visit https://github.com/kubernetes/kubectl/issues/new/choose and file an issue. It's OK to reference the URL of _this_ issue: https://github.com/kubernetes/website/issues/16729
