### ISSUE TITLE
review federation task pages

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#16776]
**This is a Feature Request**
Review Federation task pages, for example:
https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/

**What would you like to be added**
Review and update the federation task sections. Also, the kubefed component tool page is no longer published. 

**Why is this needed**
The content appears to be outdated. Should the k8s docs maintain a task and tool reference section on k8s cluster federation?

**Comments**
https://github.com/kubernetes-sigs/kubefed

**Comment by sftim** [comment]
/priority important-longterm
Does that sound right?

**Comment by sftim** [comment]
Also see #17736

**Comment by Colstuwjx** [comment]
Hi @sftim ,

Maybe we could push things further one step, by the following guides:

1. as the [index page](https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/) of federation, we still keep the `Deprecated` block to tell users that the federation v1 is not active development anymore and the remain content of the page should tells about federation v2

2. since [kubefed](https://kubernetes.io/docs/admin/kubefed/) is invalid, we should redirect such things to the [repo doc](https://github.com/kubernetes-sigs/kubefed/tree/master/docs)

Thanks.

**Comment by sftim** [comment]
> push things one step further
:+1:

**Comment by Colstuwjx** [comment]
I'm sorry, I misunderstood before. It seems that we don't setup any pages about federation v2 on our website.

So I have taken [this PR](https://github.com/kubernetes/website/pull/17893) to make our users who are new to kubernetes no longer confused about "why the links in this page is 404 not found".

Thanks.

**Comment by kbhawkey** [comment]
The v1 federation task pages were removed.
/close
