### ISSUE TITLE
dead links in k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

### ISSUE THREAD

**Issue by smirnov-mi** [kubernetes/website#16998]
**This is a Bug Report**

**Problem:**
Dead links on the "kubeadm join" page:

kubeadm - kubeadm: easily bootstrap a secure Kubernetes cluster
kubeadm join phase - Use this command to invoke single phase of the join workflow

**Proposed Solution:**
fix them

**Comment by neolit123** [comment]
/help
/sig cluster-lifecycle
/kind bug

thanks for logging the issue

**Comment by neolit123** [comment]
/unassign
/remove-sig cluster-lifecycle
/sig docs

/assign @tengqm @jimangel 

it seems this generated file contains invalid links at the bottom under "see also":
https://github.com/kubernetes/website/blob/master/content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md

preview:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#options-inherited-from-parent-commands

**Comment by aimeeu** [comment]
The links in the markdown files are correct and point to other markdown files in github.  The generated files replaced github.com with kubernetes.io.

In https://github.com/kubernetes/website/blob/master/content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md, L224-225:
```
* [kubeadm](kubeadm.md)	 - kubeadm: easily bootstrap a secure Kubernetes cluster
* [kubeadm join phase](kubeadm_join_phase.md)	 - Use this command to invoke single phase of the join workflow
```
The links should point to GitHub files.

But in https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#options-inherited-from-parent-commands:
```
<p>SEE ALSO</p>
<ul>
<li><a href=kubeadm.md target=_blank>kubeadm</a> - kubeadm: easily bootstrap a secure Kubernetes cluster</li>
<li><a href=kubeadm_join_phase.md target=_blank>kubeadm join phase</a> - Use this command to invoke single phase of the join workflow</li>
</ul>
```
So Hugo is translating the link to be relative to kubernetes.io. Is the fix for this to change `[kubeadm](kubeadm.md)` to `[kubeadm](https://github.com/kubernetes/website/blob/master/content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm.md)` in the upstream kubeadm docs?

**Comment by aimeeu** [comment]
@tengqm, @jimangel any thoughts on how to fix this issue?

**Comment by kbhawkey** [comment]
@neolit123 , Since there are static links in the `What's next` section on each `kubeadm command` page, is the generated `See Also` section needed?

**Comment by neolit123** [comment]
I don't think it's needed. Ideally we should remove it.

**Comment by kbhawkey** [comment]
> 
> I don't think it's needed. Ideally we should remove it.

OK. Then the link errors would be resolved, correct?

**Comment by tengqm** [comment]
I'm trapped by some company projects recently. Would try allocate some time for code review though.
