### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by hobnob11** [kubernetes/website#17009]
**This is a Bug Report**

**Problem:**
At no point does this guide mention the package "kubernetes-cni", which is required for (at the very least, Kube-Router) network addons to work.
**Proposed Solution:**
Instruct users to `dnf install kubernetes-cni` during installation.
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Additional Information:
I have been following the guide closely on installing kubeadm and then going on to set up a single control-plane cluster, selecting Kube-Router as the network addon, and at no point during any of the steps in the guide does it mention to install kubernetes-cni, Causing me to get stuck at "If your network is not working or CoreDNS is not in the Running state"

I spent quite a while searching through issues and logs until I heard about this package, and noticed it seemed important, moments after installing it the core-dns pod changed from pending to running.

**Comment by neolit123** [comment]
> At no point does this guide mention the package "kubernetes-cni", which is required for (at the very least, Kube-Router) network addons to work.

we prefer to not mention the kubernetes-cni package. currently it's a transitive dependency and should have been installed for you if you used rpm instead of dnf?
https://github.com/kubernetes/release/blob/master/build/rpms/kubelet.spec#L36
is that a dnf bug?

in the very near future kubernetes-cni will be removed and its contents folded into the kubelet package.

please continue the discussion if you have further questions.
/sig release cluster-lifecycle

/close
