### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by miteshskj** [kubernetes/website#17108]
**This is a Bug Report**

**Problem:**
The feedback and create issue buttons on this page (and other pages under the k8s.io/docs/tutorials/kubernetes-basics section) are inconsistent with rest of the pages in documentation.

**Page to Update:**
Pages under - k8s.io/docs/tutorials/kubernetes-basics/

Screen shot of issue:
![Small-text](https://user-images.githubusercontent.com/47820816/67276233-daf7c280-f4e1-11e9-906b-b34d90230bba.png)

Screen shot of text on other pages:
![normal-text](https://user-images.githubusercontent.com/47820816/67276173-bef42100-f4e1-11e9-8411-06e785bda61c.png)

**Comment by kbhawkey** [comment]
@miteshskj , right, I think I noted this in PR #17051.
- The problem is that most of the tutorial pages link to styles.css, with settings that override a number of the k8s style values. The top nav bar is not correct, in addition to the problems already mentioned in this issue.
- I did some testing, locally. Many of the settings, in styles.css, are not needed. I pared down this file and the tutorial pages clean up nicely, leaving the ks8/website style intact.
@BenHall , did you by chance create the file, /content/en/docs/tutorials/kubernetes-basics/public/css/styles.css? I noticed that there are katacoda related vars in styles.css.

**Comment by vishakhanihore** [comment]
@BenHall Is the issue still open ?

**Comment by BenHall** [comment]
@vishakhanihore I think it can be closed :)

**Comment by kbhawkey** [comment]
👍

**Comment by vishakhanihore** [comment]
Cool.
