### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/kubectl-cmds/

### ISSUE THREAD

**Issue by jruales** [kubernetes/website#17180]
**This is a Bug Report**

**Problem:**
Shorthands such as "ns" for "namespace" (`kubectl create ns <name>` vs. `kubectl create namespace <name>`) aren't documented in the kubectl Command Reference (nor in the --help command, for that matter).

**Proposed Solution:**
Would it be possible to include these shortcuts in the kubectl Command Reference?

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

**Comment by christophercarney** [comment]
Almost every kubectl command has shorthand `ns`, `deploy`, `pvc`, `po`, etc. So I guess the problem here would be how to solve for adding the shorthands to _every_ command in an organized manner or if it is even worth it. The knowledge is rather tribal to the documentation but I imagine that as a new use goes through examples and other documentation they would slowly pick up on this knowledge which isn't critical but more of a nice to have, it ultimately also depends on the intended purpose of the kubetctl command reference. Is it meant to be an exhaustive list of commands or a gentle introduction to the basics of the tool?

**Comment by jruales** [comment]
I think it would be very appropriate to include these shorthands in the documentation, regardless of the experience level of the target audience. I think that it is especially useful for beginners, since beginners are especially reliant on documentation to understand commands they see in the wild. If I see a command that uses one of these shorthands, my first reaction is to look up the command reference to understand what it is, and I was confused not to find any mention of these shorthands. The fact that they weren't in the documentation even made me believe that these shorthands might not be officially supported and might be deprecated soon.

In terms of where to add them, under the "Usage" section? Something like this:

 ![image](https://user-images.githubusercontent.com/1588988/67700494-44a52000-f96b-11e9-978c-f53d64bda913.png)

**Comment by christophercarney** [comment]
Another point of note here is that this page is auto-generated, also the abbreviations are already documented elsewhere in the kubectl reference:

https://kubernetes.io/docs/reference/kubectl/overview/#resource-types

**Comment by jruales** [comment]
Cool! I didn't know about this table or about `kubectl api-resources` before. Do you think having this table justifies excluding it from the [Command Reference](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands)? If so, how about at least pointing to that table from the command reference proper to make it more discoverable?

Also, wouldn't the fact that the documentation is auto-generated be a point in favor rather than against including the shorthands, since it wouldn't incur extra effort to keep updated?

**Comment by sftim** [comment]
The fix for this will probably be a pull request against the kubectl repository, or against the tool for generating this documentation.
