### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by networkandcode** [kubernetes/website#17224]
I have installed kubeadm and kubelet separateley as mentioned in the doc.
However I have installed kubelet only on the nodes, not on the master, using apt. But after the installation, I see the kubelet binary on master too.

I am aware that master has a taint on it that prevents Pods from being scheduled on it unless a toleration is applied, such as those applied on networking Pods (calico etc.). I realise that Kubelet should also be present on the master as its scheduling Pods too on the kube-system namespace. Hope my understanding is correct?

Summarising my query:
Despite realizing late that kubelet is reqd. on the master, I haven't installed it on the master initially. I have installed the kubelet only on the nodes and not master, through apt. I am trying to understand how the kubelet binary is showing up on the master.

**Comment by neolit123** [comment]
> Despite realizing late that kubelet is reqd. on the master, I haven't installed it on the master initially. I have installed the kubelet only on the nodes and not master, through apt. I am trying to understand how the kubelet binary is showing up on the master.

hi, currently the kubeadm package depends on the kubelet.
so by installing kubeadm it also installed the kubelet. hope this answers your question.

ideally we want to remove this direct dependency on the future (package wise), yet kubeadm will still need a kubelet running so that it can add the kube-systems pods.

thanks
/close
