### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by tdsan** [kubernetes/website#17315]
**This is a Bug Report**

**Problem:**
When running the "systemctl start kubelet" it exits with an error code, even after following the kubernetes installation process.

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Proposed Solution:**
[it-gcp-rh2_issues.txt](https://github.com/kubernetes/website/files/3791405/it-gcp-rh2_issues.txt)

[it-gcp-rh2.txt](https://github.com/kubernetes/website/files/3791397/it-gcp-rh2.txt)

-- The start-up result is done.
Oct 30 18:21:56 it-gcp-rh2 kubelet[30272]: F1030 18:21:56.567801   30272 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Oct 30 18:21:56 it-gcp-rh2 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a

The file does not exist or has not been created by the application at least from the log entry from journalctl -xe

This can also be found on http://it-gcp-rh2.itcloudsec.com/docs/it-gcp-rh2.txt and it-gcp-rh2_issues.txt (they have been uploaded for your review running on a docker container).

root@it-gcp-rh2:/var/lib# apt-get install kubelet
Reading package lists... Done
Building dependency tree
Reading state information... Done
kubelet is already the newest version (1.16.2-00).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Page to Update:**
https://kubernetes.io/...

root@it-gcp-rh2:/var/lib# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Please review the attachments and website

**Comment by sftim** [comment]
On lots of Kubernetes clusters `systemctl start kubelet` does start OK. The page at https://kubernetes.io/docs/setup/production-environment/container-runtimes/ covers a specific step for setting up a new Node. I'm not clear on which part of that page might not be right.

@tdsan if you're looking for help, check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes)

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

I think this issue is best characterized as a support request. If I have misunderstood, please reply with more detail about what's wrong on that page, or the fix you have in mind.
/triage support
