### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/daemonset/

### ISSUE THREAD

**Issue by mmiara** [kubernetes/website#17336]
**This is a Bug Report**

**Problem:**
"A DaemonSet ensures that all eligible nodes run a copy of a Pod. Normally, the node that a Pod runs on is selected by the Kubernetes scheduler. However, DaemonSet pods are created and scheduled by the DaemonSet controller instead."

This is shown as the default option for a daemonset, but just above, it says the opposite is the default behavior.

**Proposed Solution:**
Change the default section or change this paragraph to show the correct behavior

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

**Comment by christophercarney** [comment]
Digging into this it looks like this paragraph does need updating. This paragraph was introduced in 1.11 via #8842 and the headings (enabled/disabled by default) were introduced in 1.12 via #9923 without updating the subsequent paragraph under the heading (this was when DaemonSet Controller was the default but then switched over to default scheduler).

That's why there is a disconnect in the language being used and what the default behavior is. Introduction paragraph in https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#scheduled-by-default-scheduler-enabled-by-default-since-1-12 should be updated to reflect the true default behavior.
