### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/controlling-access/

### ISSUE THREAD

**Issue by cliqr2015** [kubernetes/website#17475]
**This is a Bug Report**

**Problem:** 
Could you check if there is a typo on section  : 
If Bob makes a request to write (create or update) to the objects in the projectCaribou namespace, his authorization **is denied**. If Bob makes a request to read (get) objects in a different namespace such as projectFish, then his authorization is denied.

**Proposed Solution:**
If Bob makes a request to write (create or update) to the objects in the projectCaribou namespace, his authorization **is granted**. If Bob makes a request to read (get) objects in a different namespace such as projectFish, then his authorization is denied.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#authorization

**Comment by christophercarney** [comment]
I believe it's correct as written, but please confirm with me if my understanding is incorrect. This is my understanding: 

(1) _"For example, if Bob has the policy below, then he can read pods only in the namespace projectCaribou..."_

(2) _"If Bob makes a request to write (create or update) to the objects in the projectCaribou namespace, his authorization is denied."_

Since Bob's ABAC policy in (1) specifies `"readonly": true`, it follows that if he sends a request to modify a resource (write) in (2), then his authorization would be denied.

**Comment by cliqr2015** [comment]
My fault,
The attribute  "readonly": true perfectly makes seance.
Please close the case.
