### ISSUE TITLE
Issue with /docs/admin/rescheduler/

### ISSUE THREAD

**Issue by andrewgdavis** [kubernetes/website#1756]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
Documentation isn't clear on the scheduling order of a daemonset(s) when a new worker node registers with the cluster.

This is important for auto-scaling purposes, as the daemonset may be a critical network plugin that should be in a "correct" state prior to any other pods being deployed on the new node.

**Proposed Solution:**
Add a blurb about the default order of scheduling components via the kube-scheduler?

Or perhaps just add a "caveat" that things won't work under said circumstance, and its being addressed in https://github.com/kubernetes/kubernetes/issues/15310

**Page to Update:**
http://kubernetes.io/docs/admin/rescheduler/
or reference from the rescheduler page to where ever the pertinent documentation lives.

**Comment by sftim** [comment]
https://kubernetes.io/docs/admin/rescheduler/ is gone.

I logged #15908 to track improving https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/ so that it mentions these high priority classes and their use.

https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/ goes some way to explain `system-cluster-critical` and `system-node-critical` Pod priority classes.

**Comment by sftim** [comment]
@andrewgdavis is it OK to close this?

**Comment by andrewgdavis** [comment]
Yes.  Please close
