### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/assign-cpu-resource/

### ISSUE THREAD

**Issue by ddycus** [kubernetes/website#17581]
As a cluster admin, 
I need to understand what happens when CPU requests and limits are not set at the pod or namespace level,
So that I can better understand k8s CPU scheduling when pods will attempt to consume more CPU than is available. 

As a cluster admin, 
I need to understand how the above scenario impacted when autoscaling is enabled
So that I can properly administer namespace and pod requests and limits within a large landscape.

**Comment by christophercarney** [comment]
Seems like a valid thing to want to document to fully understand the behavior. Looking at the page currently there is [this section](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#if-you-do-not-specify-a-cpu-limit), which part is inadequate for your first point, is it that there is: 
1) No explicit references to CPU requests at Pod/Namespace level and only container level
2) No explicit mention of what happens if a (for example) Pod with no limit could exceed the CPUs available on the Node?

The second point seems a valid thing to document for __cluster__ autoscaling:
**Proposed Solution (for second point):** Document Pod behavior for these four scenarios:

Cluster Autoscaling Enabled | Pod CPU Requests Enabled
--- | ---
Yes | Yes
Yes | No
No | Yes
No | No

**Comment by sftim** [comment]
It sounds like readers would also like to learn about the behavior with HorizontalPodAutoscaler and VerticalPodAutoscaler.

@ddycus what did you have in mind when your reported this?
