### ISSUE TITLE
Curl command to test secured service is failing

### ISSUE THREAD

**Issue by gireeshp** [kubernetes/website#17908]
**This is a Bug Report**

[Securing the Service](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#securing-the-service) section of k8 documentation has below code towards the end of the topic.

```
kubectl exec curl-deployment-1515033274-1410r -- curl https://my-nginx --cacert /etc/nginx/ssl/nginx.crt
...
<title>Welcome to nginx!</title>
...
```

But this fails without specifying '-k' parameter to curl.

**Proposed Solution:**
Add a '-k' parameter to curl command.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#securing-the-service

**Comment by sftim** [comment]
My take on this is that the current page is accurate about that task, but not clear.

I've suggested that the fix will be to split that task out into its own page, verify that the instructions work, and possibly tweak wording for clarity.

/priority backlog
/language en

**Comment by vishal-yadav** [comment]
As I can see the -k option is also explained in the section when not specifying certificate file (-k just ignores the --cacert option to curl). 

The real issue is certificate created from [nginx-https](https://github.com/kubernetes/examples/tree/master/staging/https-nginx/) example contains "nginxsvc" as CN field while the example in the documentation creates service with name "my-nginx" and uses it access service from curl pod.
