### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by vietnguyen1254** [kubernetes/website#18079]
**This is a Bug Report**

**Problem:**
Can not run this command: 
curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/

it returns this: Error trying to reach service: 'dial tcp 172.17.0.6:80: connect: connection refused'

**Step to reproduce:**
I follow the instruction from this website: https://kubernetes.io/docs/tutorials/kubernetes-basics/

However, instead of using the simulator, i build up the environment in my computer. Everything is running fine (all commands from "Creating a Cluster" and "Deploy an App" executed perfectly). But when I try to run  **curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/** I got the above mentioned error. 

There is one thing I could see when run: "kubectl describe pods" is that the Hostport and Port are none. which is different to the simulation (Port: 0 and HostPort: 8080).

Please kindly advise.

**Comment by sftim** [comment]
One of the steps asks you to run:
```bash
echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"; 
kubectl proxy
```

Did that go OK? You need to _leave that proxy running_; maybe the page should make that clearer for any reader following along from home.

**Comment by sftim** [comment]
What's the environment that you're running `minikube` on @vietnguyen1254 ?

**Comment by vietnguyen1254** [comment]
Thanks for the answer @sftim 

Yes, I leave the proxy running. It can return a json when I call: curl http://localhost:8001/version. But when I call the pod, then, it returns: Error trying to reach service: 'dial tcp 172.17.0.6:80: connect: connection refused'

I am running in CentOS 8 in Vsphere. 

I don't know but i think the issue is with the port??. 

When I try to call server.js with bash session inside the container, it runs smoothly.

**Comment by sftim** [comment]
I'm wondering what kind of CNI you have installed into your cluster @vietnguyen1254 
I think the documentation is accurate though. These guides assume you used Minikube to set up your cluster.

/triage support

**Comment by ThomasG77** [comment]
I got the same issue using Ubuntu 18.04 64bits with local install. I also keep the proxy running. I didn't installed anything in particular for CNI (wasn't aware of it before reading this thread)

**Comment by vietnguyen1254** [comment]
@sftim Sorry for the late response. 
I have not installed any CNI... And I was not aware of it as well...

**Comment by sftim** [comment]
Hmm, this sounds like there might be an issue with the advice on the page.
Just in case:
/remove-triage support

**Comment by ThomasG77** [comment]
OK. Got a clue but need some more feedback to solve the issue.
When I connect to the pod with
```
kubectl exec -ti $POD_NAME bash
```
then I run `curl localhost:8080` and it's fine.

Then, I change within the pod the call to use

```
export $POD_NAME="mypodname" # Fake, use your own and do
curl http://172.17.0.6:8080/api/v1/namespaces/default/pods/$POD_NAME/proxy/
```
Then, I read again the feedback from the error when calling from the proxy (so outside the kubernetes network) `dial tcp 172.17.0.6:80: connect: connection refused`

So, I do

```
curl http://172.17.0.6:80/api/v1/namespaces/default/pods/$POD_NAME/proxy/
```

Then, I get the same error:

>  Failed to connect to 172.17.0.6 port 80: Connection refused

The conclusion is that the `kubectl proxy` matches external port 8001 to internal port 80 of the pod instead of matching port 8080, hence the error.

So, now what I need to know is how can I change the behavior so `kubectl proxy` matches correctly port 8001 to port 8080. Is it within the application, at pod level, at `kubectl proxy` level or elsewhere.

Thanks

**Comment by ThomasG77** [comment]
Ok. I've solved the issue by using http://localhost:8001/api/v1/namespaces/default/pods/kubernetes-bootcamp-69fbc6f4cf-tfmfs:8080/proxy/ instead of the official recommended URL

**Comment by pxmage** [comment]
@ThomasG77  thanks for your share, exactly the same here, and solved by what you said, specify the 8080 port explicitly.

Still wondering, it works inside the tutorial terminal but fails on my Mac.

**Comment by Lumikkode** [comment]
same here, finally I found a solution. I dropped the idea of learning Kubernetes a few times because everytime I'd end up stuck here.

Any idea why this is not providing a port when we create the deployment? I really don't understand why it is not working locally (linux/ubuntu) with minikube if we do not provide the port, but works fine when using the simulation.

This should be updated on the documentation, or the image should somehow declare herself the port - as i'm new to K8S i do not know how it discovers the ports, but it should spot the 8080 one.

Thanks for the solution, @thomasG77 - I can finally continue my discovery of Kubernetes.

**Comment by halmai** [comment]
I also had the same issue on Windows10. 
I have been struggling for two days until I reached the solution from @ThomasG77 (thank you). 
It is really frustrating when you want to learn something from the official manual and it is simply just wrong/incomplete. And it has been in this state for a while, this ticket has been opened several months ago.
I think the manual should say that in some circumstances the port also needs to be given. Or, just replace the example in the tutorial so that others don't waste days with this issue.

**Comment by namaggarwal** [comment]
I think the issue is that while creating the deployment we haven't specified the port. So I tried with 
```
kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port 8080
``` 
and then 
```
http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/
```
works

**Comment by ryangsteele** [comment]
Alternatively, you can use `kubectl edit deployment/kubernetes-bootcamp` after running `kubectl create deployment` and add this to the containers spec:

```
        ports:
        - containerPort: 8080
          protocol: TCP
```

After adding this, the container spec should look like so:

```
    spec:
      containers:
      - image: gcr.io/google-samples/kubernetes-bootcamp:v1
        imagePullPolicy: IfNotPresent
        name: kubernetes-bootcamp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```

**Comment by geekbleek** [comment]
@ryangsteele - I was able to edit the port config on the container spec, and after my pods reloaded, the cURL statement works fine. 

Note to others - after editing your container spec you will need to re-query for your pod name and re-export the env variable for the curl command to work correctly.

```
export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
```

**Comment by bodote** [comment]
in fact, if you use 
"kubectl edit deployment/kubernetes-bootcamp"
which opens a vim with the deployment description , you see in fact that: 
```json 
ports:
  - containerPort: 8080<
     protocol: TCP
```
is set

**Comment by kheengz** [comment]
> Ok. I've solved the issue by using http://localhost:8001/api/v1/namespaces/default/pods/kubernetes-bootcamp-69fbc6f4cf-tfmfs:8080/proxy/ instead of the official recommended URL.
> Although "it works", I have no clue why I have to change the recipe compared to the official recipe. Only possible hypothesis (untested) could be about instanciating a kubernetes cluster with port already use on the host machine may change behavior.

**before**
`http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/`

**after**
`http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME:8080/proxy/`
> all you have to do is to append the port number `8080` after then `$POD_NAME`

**Comment by FrantzT** [comment]
Would that be issue the app itself, container exposes port 8080 instead of 80 which is expected as a default http port?
For my understanding kubectl proxy forwards to port 80, but there is no response from the pod on that port.
I don't know yet the relation between pod and container ports.

ryangsteele  comment https://github.com/kubernetes/website/issues/18079#issuecomment-622011285
points that it is missing for the container port definition, so it points to the container having 8080 instead of 80.

It works in the kubernetes emulator on the website using the same deployment image, so this is a bit strange.

**Comment by FrantzT** [comment]
Funny enough the tutorial points further to server.js and the right port once you get into the container bash.

curl localhost:8080 

But, I started to investigate it as I have been running it on localhost in minikube.

**Comment by dantezhu** [comment]
curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME:8080/proxy/

**Comment by umann** [comment]
> One of the steps asks you to run:
> 
> ```shell
> echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"; 
> kubectl proxy
> ```
> 
> Did that go OK? You need to _leave that proxy running_; maybe the page should make that clearer for any reader following along from home.

The problem seems to be that up to this point, all commands could be executed by simply clicking on the grey box, but this one does not work. Here, kubectl proxy needs to be entered manually in Terminal 2, then, in Terminal 1, curl successfully returns sg like Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-fb5c67579-nvrmk | v=1

So the issue is with the tutorial IMHO.

**Comment by pealmeid** [comment]
Wow, it's unbelievable that it has been almost three years and the tutorial still has not been corrected.

Thanks @ThomasG77 for the solution.
