### ISSUE TITLE
[Question] Is there original source code of feature-gates.md file

### ISSUE THREAD

**Issue by hase1128** [kubernetes/website#18250]
**This is Question**

There are some descriptions that I would like to modify in https://github.com/kubernetes/website/blob/master/content/en/docs/reference/command-line-tools-reference/feature-gates.md

Is there original code in kubernets/kubernetes repository (and document generation process is required)?
Or, I should modify only above markdown file?

**Comment by hase1128** [comment]
Recently, I knew the document which is required regeneration procedure from original source codes.
related issue is here.(https://github.com/kubernetes/website/issues/17170)

For example, are the all of following documents generated documents?
 - Feature Gates
 - cloud-controller-manager
 - kube-apiserver
 - kube-controller-manager
 - kube-proxy
 - kube-scheduler
 - kubelet
 - Kubelet authentication/auhtorization
 - TLS bootstrapping

Above documents are located in https://kubernetes.io/docs/reference/command-line-tools-reference/

**Comment by tengqm** [comment]
feature gates, kubelet authentication/authorization, TLS bootstrapping are all manually created and maintained. Other reference docs are auto-generated.

**Comment by hase1128** [comment]
@tengqm 
thank you for the answer.
I could not find original source of feature gates in kubernetes/kubernetes, so I will modify only website document(I will issue issue later).

Regarding kubelet, I can find original source code in kubernetes/kubernetes.
so if we'd like to modify https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ due to some document bug, we need to modify upstream source code(not website document), and then we also need to website document manually. Is this right?

**Comment by sftim** [comment]
> Regarding kubelet, I can find original source code in kubernetes/kubernetes.
so if we'd like to modify https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ due to some document bug, we need to modify upstream source code(not website document), and then we also need to website document manually.

That's pretty much it. The changes to the website after you update upstream are done via a tool, but you have to invoke the tool yourself and commit the changes, then submit a pull request.

**Comment by sftim** [comment]
/triage support
(and that's OK)

**Comment by tengqm** [comment]
@hase1128 Sorry, `kubelet` is another exception IIRC. The reference doc generation was broken since several releases ago when `kubelet` was cleaning up all command line options. The movement was about to kill docker specific arguments surfaced at `kubelet` command line, however, the upstream community reworked the logic for traversing the configuration options. That change made the auto-generation of `kubelet` reference impossible. We have been forced to manually maintain the docs for every release.

**Comment by hase1128** [comment]
@sftim @tengqm 
I understand the situation.
I close this issue because I got all answers I'd like to know.
Thank you so much!
