### ISSUE TITLE
ko: Clarify how to localize terms that are both English words and names of API objects

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18402]
**Context:**

I have noticed some pages in localizations including Korean that do not clearly tell the reader the name of an API object. For example, the first mention of “ReplicaSet” in https://kubernetes.io/ko/docs/concepts/workloads/controllers/replicaset/ is inside a sample manifest. It's useful for readers to learn the name of the object, ie ReplicaSet.

**Problem:**
https://kubernetes.io/ko/docs/contribute/localization_ko/#%EC%9A%A9%EC%96%B4%EC%A7%91 lists recommended localizations for API objects, but also mentions
> 예외적으로 API 오브젝트에 대해 외래어 표기법 적용하지 않고 원문 그대로 표기

(I _think_ this means: don't localize this, it's an API object)

**Proposed Solution:**
Clarify how to localize English original documents that use English words that are also the name of API objects.
For example, the concept endpoint is worth explaining to a Korean-reading audience. However, until it's replaced by EndpointSlide, Endpoint the API object is also a thing and should remain as Endpoint.

So the guide for localization should, I think, cover both cases for terms like “endpoint” that are both normal English words and also API objects. It's more obvious in languages that don't use the roman alphabet, but actually I think this is a challenge common to several localizations.

**Page to Update:**
https://kubernetes.io/ko/docs/contribute/localization_ko/

/language ko

Also see #17388

**Comment by seokho-son** [comment]
@sftim This issue is worth to discuss. Thank you. 
First of all, Korean l10n team translate terms for localize API objects as well. 
In case of an API object, we translate it according to Korean pronunciation to make readers familiar with K8s terms. 

Recently, we made some exceptions such as "Horizontal Pod Autoscaler" with the note.
> 예외적으로 API 오브젝트에 대해 외래어 표기법 적용하지 않고 원문 그대로 표기

(this means.. an API object is supposed to be translated according to Korean pronunciation in general, but we don't translate this term exceptionally.)

Also, recently, we have a consensus on not translating terms written in CamelCase. (We know "Use camel case for API objects" is in the [Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-camel-case-for-api-objects), but it seems not strictly followed in original English documents)

In some situations those policies conflict, and I think we need to improve the policies.
I would continue the discussion in #18404 PR.

**Comment by gochist** [comment]
Korean l10n team made it a rule to localize API objects using foreign language notation so that readers can easily infer original English names. The foreign language notation established by the National Institute of Korean Language is a way of writing pronunciation in Korean, not meaning of English. So most Korean readers can infer "ReplicaSet" by looking at "레플리카셋".

However, there are some cases where exceptions may be applied if the foreign notation is not familiar to readers or if it is difficult to infer English names. One such case is the English word in parentheses after the Korean word with the foreign language notation, such as "파드(pod)." In this case, it applies only to the first use within the page, and uses only Korean in foreign notation from the second.

Another exception is when the syllable is too long. For the case, we use the original text without overly localizing, such as HorizontalPodAutoscaler.

The localization team discusses all terms individually, including API objects that are listed in the Korean glossary.
