### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/components/

### ISSUE THREAD

**Issue by cdemi** [kubernetes/website#18512]
**Problem:**
In issue #13332 a diagram was introduced. According to the accompanying documentation, the `kube-apiserver` is a scale-out component, so I think it should be represented by multiple objects. Similarly, it is not mentioned (in the docs) that the `kube-controller-manager`, `cloud-controller-manager` and `kube-scheduler` are scale-out components, so I think their representation is incorrect. 

![image](https://user-images.githubusercontent.com/8025435/71889151-d38ba100-3141-11ea-8469-efe23d483b69.png)

**Solution:**
Either the diagram or the documentation need to be updated to match each other with regards to the horizontal scalability of:  `kube-controller-manager`, `cloud-controller-manager`, `kube-scheduler` and `kube-apiserver`

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/components/

**Comment by sftim** [comment]
Good point, well made. `kube-controller-manager` and friends are written so that they _can_ run with horizontal replication; I think that for some components the replication is more for availability than throughput. I don't think there's anything in the control plane that has to run as a singleton.

/priority important-long-term

**Comment by sftim** [comment]
Note: there are other pages that use the same or similar diagrams

**Comment by sftim** [comment]
@dkypuros this might be interest you too
/remove-lifecycle rotten
