### ISSUE TITLE
Add KubeAcademy (https://kube.academy/) to the list of online trainings

### ISSUE THREAD

**Issue by bbrundert** [kubernetes/website#18607]
**This is a Feature Request**

**What would you like to be added**
Please add KubeAcademy to the list of online trainings for Kubernetes (link: https://kubernetes.io/docs/tutorials/online-training/overview/). 

**Why is this needed**
KubeAcademy (https://kube.academy/) is a free, product-agnostic Kubernetes and cloud native technology education platform.

**Comments**

**Comment by sftim** [comment]
:information_source: There's a relevant KEP: https://github.com/kubernetes/enhancements/pull/1327

and I plan to update that KEP quite soon to revise its scope.

**Comment by sftim** [comment]
The relevant KEP has merged and there is now a revised [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).

The page at https://kubernetes.io/docs/tutorials/online-training/overview/ has gone, so this issue is no longer relevant.
With that in mind @bbrundert I will close it.
/close
