### ISSUE TITLE
Korean localization is missing code of conduct

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18600]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/ko/community/code-of-conduct/ is a missing page. This page is important because it provides the CNCF code of conduct, and that is an important element of an inclusive community.

**Proposed Solution:**
- Localize CNCF code of conduct if necessary
- Add Korean code of conduct page to website

**Page to Update:**
https://kubernetes.io/ko/community/code-of-conduct/

/priority important-soon
/language ko
/kind bug

**Comment by gochist** [comment]
@sftim I agree it is important. But I think it is not a bug and priority is too high. Because we already have a [community code of conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/ko.md) in Korean according to the [localization guide](https://kubernetes.io/docs/contribute/localization/#localize-the-community-code-of-conduct).

**Comment by sftim** [comment]
Agreed.
/remove-prority important-soon
/remove-kind bug
/priority important-longterm

**Comment by ysyukr** [comment]
Finally merged to master via #20528 .

/close
