### ISSUE TITLE
deprecation policy for tracking the upstream kubernetes repo

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#18723]
**This is a Feature Request**

**What would you like to be added**
Kubernetes main repo is still in highly active development, and it has lots of features in/out, with these changes, our website should also track on this. For example, something like [heapster deprecation issue](https://github.com/kubernetes/website/issues/18658) or [federation v1 deprecation issue](https://github.com/kubernetes/website/issues/17736).

For these reasons, we may need to do some changes, like **adding `deprecation-document` label** for tracking such related issue, and **setup deprecation policy** for how to rollout deprecated features.

**Why is this needed**
As I said in the previous block, we need to setup policy about this, therefore, our contributors would be confident to remove or keep them at the next time. Another problem for this is that sometimes we need help from relative feature owner, like `kubefed v1 to v2` such issue, we may also consider about this.

**Comments**

**Comment by sftim** [comment]
I'm not sure I understand what you're recommending @Colstuwjx; can you explain that a little more?

**Comment by Colstuwjx** [comment]
Just like sth about kubernetes api: https://kubernetes.io/docs/reference/using-api/deprecation-policy/ . maybe our website documentation should also have this policy as our guide?

**Comment by tengqm** [comment]
Adding new deprecation policies to website is not gonna make things better, I suspect. We are already under staffed. We are killing ourselves if we keep adding more processes, more guidelines to follow. What we can/should do is to encourage contributions.

In an ideal world:

- Experimental (alpha, beta) features should be documented and advocated as early as possible, so the developers get quick feedbacks.
- Documents for deprecated features, resources, fields etc are not supposed to be deleted, simply because of their presence in the software.
- When something is completely dropped, we may want the related docs removed immediately.

The implication, however, is not that we should add new labels, new tags, or things like that.

**Comment by Colstuwjx** [comment]
Yes, it is a balance job. I agree with you, Adding new deprecation policies would make things complicated. My original intention was just adding some guides, that we could move on deprecate or update document without waiting for related owners slowly response.

Just like federation such issue, the new coming kubefed is **really NOT a new gamer**, it began developing [more than one year](https://github.com/kubernetes-sigs/kubefed/commits/v0.0.1), and our website even didn't have nothing for this, except a link to its repo inside the deprecation guide...

As the proposal of `setup the deprecation policy for solving such issues` sounds not good either, I'd like to close this issue and wish another better solution for fixing this.

Thanks you two for replying this issue,  @sftim  @tengqm .
