### ISSUE TITLE
Left panel navigating bar layout and link bugs

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#18737]
**This is a Bug Report**

**Problem:**
The left panel navigating bar on Chinese version website has globally a extra sub option who has the same name with the main option. The first two sub options of a main option link to the same page.
<img width="960" alt="bug" src="https://user-images.githubusercontent.com/16621880/72592105-cbe7ab80-393c-11ea-9e78-fcabeebe52ce.png">

**Proposed Solution:**
Remove the first sub option

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
looks like a hugo thing to me, but I dont have bandwidth to investigate.

**Comment by gavinfish** [comment]
This may be a bug from hugo and I have submitted an issue gohugoio/hugo#6770. And I think it is ok for us to remove simple comments like below in `_index.md` files to mitigate this issue. What do you guys think?

```
<!--
---
title: "Kubernetes Architecture"
weight: 30
---
-->
```

**Comment by tanjunchen** [comment]
I think this problem should be solved from the upstream first, I hope your [issue](https://github.com/gohugoio/hugo/issues/6770) can play a certain role. if it can't,we should reconsider this solution.what do you say?
about this series of problems, this pr https://github.com/kubernetes/website/pull/18694 , can work?

**Comment by gavinfish** [comment]
@tanjunchen if hugo can fix this, I would love it to prevent lots of unnecessary work here. But I have no idea whether hugo team will provide a fix and when is the ETA.

And for that pr, its target is totally different. Remove the alias property is to prevent short link like `kubernetes.io/security` redirects to zh version instead of en one. Indeed, we can create a new issue to track the redirect issue with at least two follow ups:

1. Whether it is necessary for different languages to have their own alias like `kubernetes.io/zh/security`?
2. Make sure all the docs are at the same page for this issue.

**Comment by tanjunchen** [comment]
@gavinfish  yes . understand

**Comment by tanjunchen** [comment]
any progress about  this issue

**Comment by gavinfish** [comment]
No updates from hugo. I will draft a PR to fix it this weekend.
