### ISSUE TITLE
Kubernetes 1.16 API documentation version mismatch

### ISSUE THREAD

**Issue by edgarlanting** [kubernetes/website#18820]
**This is a Bug Report**

**Problem:**
The API docs at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/ have a wrong version spec in the top right hand corner specifying `API Version: v1.17.0` which points to https://github.com/kubernetes/kubernetes/blob/release-1.17/api/openapi-spec/swagger.json

**Proposed Solution:**
Change the link on https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/ to show https://github.com/kubernetes/kubernetes/blob/release-1.16/api/openapi-spec/swagger.json for the version spec in the top right hand corner. This will then have the proper version specified: "API Version: v1.16.0"
**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/ 

1.16

**Comment by edgarlanting** [comment]
Suggested a change to the older 1.16.0 API docs at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/  which has a reference to https://github.com/kubernetes/kubernetes/blob/release-1.17/api/openapi-spec/swagger.json (Version mismatch).

**Comment by walterdolce** [comment]
Tracked also in kubernetes/kubernetes#87454

**Comment by kbhawkey** [comment]
@edgarlanting , Thanks for opening the issue. The version was fixed in the release-1.16 branch (PR #18587). Just checked that the version of the API ref is correct in the 1.16 snapshot:
https://v1-16.docs.kubernetes.io/.
However, the link to the 1.16 version of the API ref from https://kubernetes.io/docs/reference/  is pointing to the previous generation of API ref 1.16, not the corrected snapshot:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/
Updating the v1.16 link found on, https://kubernetes.io/docs/reference/ _should_ fix the issue.
/cc @tengqm @zacharysarah @jimangel

**Comment by edgarlanting** [comment]
> Tracked also in [kubernetes/kubernetes#87454](https://github.com/kubernetes/kubernetes/issues/87454)

whoops, was not aware of that one. Thanks @walterdolce

**Comment by edgarlanting** [comment]
> @edgarlanting , Thanks for opening the issue. The version was fixed in the release-1.16 branch (PR #18587). Just checked that the version of the API ref is correct in the 1.16 snapshot:
> https://v1-16.docs.kubernetes.io/.
> However, the link to the 1.16 version of the API ref from https://kubernetes.io/docs/reference/ is pointing to the previous generation of API ref 1.16, not the corrected snapshot:
> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/
> Updating the v1.16 link found on, https://kubernetes.io/docs/reference/ _should_ fix the issue.
> /cc @tengqm @zacharysarah @jimangel

Thanks @kbhawkey!
