### ISSUE TITLE
Proposal: Rename "Concepts -> Scheduling" to "Scheduling and Eviction"

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/website#19081]
**This is a Feature Request**

Expand the “Scheduling” section of the Concepts documentation to include Eviction and the features which support pod eviction.

**What would you like to be added**

- [x] Rename “Concepts -> Scheduling” to “Concepts -> Scheduling and Eviction”
   - [ ] Translation for Japanese (ja)
   - [ ] Translation for Mandarin Chinese (zh)
   - [ ] Translation for Korean (ko)
   - [ ] Translation for Bahasa Indonesian (id)
- [x] Move “Assigning Pods to Nodes” from “Configuration” to “Scheduling and Eviction”
- [x] Move “Taints and Tolerations” from “Configuration” to “Scheduling and Eviction”
- [ ] Move “Pod Priority and Preemption” from “Configuration” to “Scheduling and Eviction”
   - [ ] Strike content related to disabling preemption and anything that is not default behavior.
   - [ ] Move disabling of preemption to Tasks
   - [ ] Move debugging Pod Priority and Preemption to Tasks
- [ ] Create new article “Quality of Service”, to be added under “Scheduling and Eviction”
- [ ] Create new article “Eviction”, to be added under “Scheduling and Eviction”
- [ ] Retitle “Scheduler Performance Tuning” to “Advanced Topics: Scheduler Performance Tuning”
- [ ] Move “Resource Bin Packing…” from “Configuration” to “Scheduling and Eviction”. Retitle “Advanced Topics: Resource Bin Packing…”
- [ ] Move “Scheduling Framework” from “Configuration” to “Scheduling and Eviction”. Retitle “Advanced Topics: Scheduling Framework”
- [ ] Update the outline and ordering of the articles as follows:
   - Kubernetes Scheduler
   - Assigning Pods to Nodes
   - Taints and Tolerations
   - Pod Priority and Preemption
   - Quality of Service
   - Eviction
   - Advanced Topics: Scheduler Performance Tuning
   - Advanced Topics: Resource Bin Packing for Extended Resources
   - Advanced Topics: Scheduling Framework
- [ ] Fix existing links to point to new doc locations (separate PR)

**Why is this needed**

This proposal aims to create a coherent documentation narrative that explains how pods can be added to nodes (scheduled) and removed from nodes (evicted). It reorganizes existing articles and proposes new articles to help Kubernetes users answer the following questions:

1. How are my pods assigned to nodes?
2. How can I guide my pods to be scheduled on specific nodes? How can I guide my pods so 3. that they aren’t scheduled on specific nodes?
3. What happens if I want to run too many pods on a cluster?
4. What happens if the nodes on my cluster can’t run their assigned workloads?

**Comments**

Related to issues #18982 and #19025. If desired these issues can be closed and merged into this proposal.

**Comment by sftim** [comment]
I'm going to jump in and:
/priority important-longterm

**Comment by sftim** [comment]
Remember to add redirects in the PRs that move things around.

**Comment by zacharysarah** [comment]
@adambkaplan 👋 How's this coming along? Feel free to ping [#sig-docs Slack](https://app.slack.com/client/T09NY5SBT/C1J0BPD2M/) or [email](kubernetes-sig-docs@googlegroups.com) when you're ready for a review.

**Comment by adambkaplan** [comment]
@zacharysarah thanks for reaching out. I need to split out my first renaming PR so the localization changes are separate. It's been on my queue, but I haven't had a lot of time to fix lately due to COVID-19 (I'm effectively working half days).

**Comment by sftim** [comment]
Done!
/close

**Comment by alculquicondor** [comment]
There seems to be pending work here, like

>Move “Pod Priority and Preemption” from “Configuration” to “Scheduling and Eviction”

Other than that, it seems weird that when I go to https://kubernetes.io/docs/concepts/scheduling-eviction it shows the contents of https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler, which has no mentions of eviction at all. Perhaps we need another page.

There seems to be another suggestions which sig-scheduling might not agree, like:

>  Move “Scheduling Framework” from “Configuration” to “Scheduling and Eviction”. Retitle “Advanced Topics: Scheduling Framework”

How come we were not tagged?

**Comment by sftim** [comment]
I'll retroactively add the SIG label
/sig scheduling

**Comment by alculquicondor** [comment]
Is this still being worked on?

**Comment by alculquicondor** [comment]
/reopen

I question why this decision was taken in the first place.

The scheduler has very little to do with Pod eviction. The only overlap is in pod preemption, which has slightly different semantics.

Also, there is only one link in https://kubernetes.io/docs/concepts/scheduling-eviction/ that refers to Eviction https://kubernetes.io/docs/concepts/scheduling-eviction/eviction-policy/ and talks about kubelet. I believe this would fit better in https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

**Comment by sftim** [comment]
> How are my pods assigned to nodes?
> How can I guide my pods to be scheduled on specific nodes? How can I guide my pods so 3. that they aren’t scheduled on specific nodes?
> What happens if I want to run too many pods on a cluster?
> What happens if the nodes on my cluster can’t run their assigned workloads?

I agree that people will ask these questions in connection with others in that list, so putting answers close together feels like a good approach.
Of course in the API reference and that level of detail we must explain what _really_ happens.

**Comment by sftim** [comment]
Also we did rearrange some of these pages since writing the issue description - @adambkaplan would you have the time to revise it to match (I know that's quite a bit of work).

**Comment by alculquicondor** [comment]
> Scheduling is however a big enough topic to merit its own section (I wouldn't want it to be a subtopic of Pods, even though scheduling is only ever about pods).

I was not suggesting for Scheduling to be part of Pods. But I don't see any reason why https://kubernetes.io/docs/concepts/workloads/pods/disruptions/ and https://kubernetes.io/docs/concepts/scheduling-eviction/eviction-policy/ are separated. And my stance is that both should be under pods/

**Comment by sftim** [comment]
Here's a bit more of my thinking:

Disruptions happen due to things like node maintenance or zone outages.
Evictions happen for a number of reasons. A common reason is that the cluster wants those resources back to be able to place a higher priority pod - ie, https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/, which should also live in the scheduling section and not in the workloads section.
If you're reading about the process that makes your high priority pod get room to run, you might wonder that happened to the pods that got shifted out of the way. Were they migrated perhaps? No. Kubernetes' API doesn't<sup>†</sup> allow moving a pod to a different node, so what happens is eviction, recreation, scheduling. I want people to find this stuff early on in their journey through discovering Kubernetes.

† _I think - it's not clear in the API docs, but I'm pretty sure a patch that updates `.spec.nodeName` is rejected_

**Comment by alculquicondor** [comment]
cc @Huang-Wei @ahg-g

**Comment by sftim** [comment]
Also relevant https://k8s.io/docs/tasks/administer-cluster/out-of-resource/ - see https://github.com/kubernetes/website/issues/25866

**Comment by sftim** [comment]
> eviction is not preemption

I agree with this

> Scheduling and Preemption 

If we could include eviction: **Scheduling, Preemption and Eviction**
then we can describe in this section the _concept_ of eviction, and hyperlink to sections in other concept pages (eg NodeAllocatable, Pod, graceful node shutdown) etc that are relevant to eviction.

The difference is subtle and if they are easy to confused I think that strengthens the case for explaining them together, so that we can clarify what each means.

**Comment by alculquicondor** [comment]
I think pairing Preemption and Eviction sends the wrong signal when looking for support. Users might go to sig-scheduling looking for answers or filing bugs, were we will just send them to sig-node.

Instead, I propose we enhance the https://kubernetes.io/docs/concepts/workloads/pods/disruptions/ doc to describe what preemption and eviction is. Then hyperlinks for preemption send them to scheduling-and-preemption. Hyperlinks for eviction send them to other Pod and kubelet docs

**Comment by sftim** [comment]
This might be the wrong place to make a distinction about SIGs that work on features (I feel it is). Although different SIGs take different responsibilities, in the documentation we want to **hide** that level of detail from readers. To them, Kubernetes is a system that breaks down on other dimensions.

For example, you might think of all the many Kubernetes APIs in your cluster as a set&mdash;you might not even need to care which are built-in, which are aggregations and which are aggregated. You might not need to know that nodes typically run a `kubelet` and a `kube-proxy`; to you, it's a black box called a node that makes pods work. The fact that several SIGs work hard on making those node-specific behaviors happen is a detail we want to hold back from readers unless they look into Kubernetes in some detail.

**Comment by tomkivlin** [comment]
> Disruptions happen due to things like node maintenance or zone outages.

It could be argued that evictions are a disruption (i.e. the application hosted by a lower priority pod that is evicted, is disrupted).

> If we could include eviction: Scheduling, Preemption and Eviction

I like this idea, however I think the linked concepts of disruptions, scheduling, preemption, eviction, platform maintenance, etc. are already (mostly) separated in the concepts structure.  So rather than trying to fit evictions into a "scheduling & eviction" section (I know that's how it is today), and/or adding preemption into that same structure, maybe one of the following might work?  I'm thinking that there are multiple viewpoints (app dev, app ops, platform ops, etc.) all with different views of whether eviction is related to e.g. what they need to configure their container resources to, or how to perform platform maintenance, etc.
- Rename "Scheduling and Eviction" to "Scheduling and Nodes" or something similar?
  - My thinking is that there isn't a section in concepts that deals with node-specific / kubelet concepts, but it is closely related to scheduling concepts
  - Things like disruptions are covered in the [workloads/pods section](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/)
  - Eviction is also mentioned in [concepts/architecture/nodes](https://kubernetes.io/docs/concepts/architecture/nodes/#node-capacity) but not linked to any other pages for more information
- Move eviction content to the [workloads/pods section](https://kubernetes.io/docs/concepts/workloads/pods/)

We could also make sure there are links either in the text or "what's next" sections between the following related pages:
- Eviction Policy
- [Pod Priority and Preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/)
- [safely drain a node/`kubectl drain`/eviction API](/docs/tasks/administer-cluster/safely-drain-node) (or an equivalent in the concepts section)
- [configure out of resource handling](/docs/tasks/administer-cluster/out-of-resource/) with eviction signals and thresholds (or an equivalent in the concepts section)
- [configure Pod resource requests and limits](/docs/tasks/configure-pod-container/assign-memory-resource/) (or an equivalent in the concepts section)
- [configure Quality of Service for Pods](/docs/tasks/configure-pod-container/quality-service-pod/) (or an equivalent in the concepts section)

This is also usefully linked to my (delayed) PR #26916.

Final thought is that I don't really have a strong opinion on the structure as I search for everything but thought I'd share anyway given I am touching one of the affected pages.

**Comment by sftim** [comment]
> My thinking is that there isn't a section in concepts that deals with node-specific / kubelet concepts

We do have https://kubernetes.io/docs/concepts/architecture/nodes/

I did notice that https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/ currently says:
> If a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods&hellip;

What I infer from that is that pre-emption and eviction are similar, and that we should take care to let readers know that when they look deep enough they will find that the two terms refer to specific and different things.

**Comment by adambkaplan** [comment]
> If we could include eviction: Scheduling, Preemption and Eviction
then we can describe in this section the concept of eviction, and hyperlink to sections in other concept pages (eg NodeAllocatable, Pod, graceful node shutdown) etc that are relevant to eviction.

I agree with this because for preemption and eviction, the end user experience is the same (my pod is not running any more). The _why_ and _what_ are what distinguishes the two. 

> I did notice that https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption>/ currently says:
> 
> > If a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods…

It seems we have used "eviction" as the general verb for removing a pod from a node, instead something more specific. Do we reliably signal to users which component is responsible for stopping and removing a pod from a node? Example - if the scheduler preempts a pod, do we always use "Preempted" in our condition reasons, versus "Evicted" if the kubelet removes a pod due a node drain?

**Comment by alculquicondor** [comment]
> Example - if the scheduler preempts a pod, do we always use "Preempted" in our condition reasons, versus "Evicted" if the kubelet removes a pod due a node drain?

No. The scheduler just issues a DELETE. Not sure what kubelet does.

/sig node

**Comment by Huang-Wei** [comment]
I agree with @alculquicondor on the concern of using "eviction" along with scheduling. As Aldo explained, "eviction" is more used and implemented in kubelet to delete a Pod when the resource usage exceeds a Node's limitation (usually accompanied with an error such as OOM), and IIRC, this error can be explicitly observed by `k describe pod` or `k get pod -o wide` - there is an `Evicted` status.

In contrast to "eviction", preemption is a scheduling concept, indicating low-priority Pods get deleted to make room for a high-priority Pod. And unlike "eviction", you won't see an explicit status like "preempted", at least for now.

Due to this confusion, I did see some users reported issues with kubelet eviction to sig-scheduling.

So I'm wondering if we can make the following changes:

- concepts/scheduling-eviction renamed to concepts/scheduling
- move "Eviction Policy" from concepts/scheduling-eviction to concepts/policy, and make the following changes:
    - rename "eviction policy" to "kubelet eviction policy"
    - add a sub-section called "scheduler preemption policy" and link to configuration/pod-priority-preemption

**Comment by tomkivlin** [comment]
@Huang-Wei I like your suggestion, it's clean.  Re.

> add a sub-section called "scheduler preemption policy" and link to configuration/pod-priority-preemption

Do you think the additions I've started in #26916 would suffice for that?

**Comment by sftim** [comment]
Should we keep this issue for reference and open a new issue about the rename from _Scheduling and Eviction_ to _Scheduling and Preemption_?
(I would)

**Comment by damemi** [comment]
I mentioned this offline, but for reference here too I agree with the other sig-scheduling folks that eviction and preemption are different concepts, and that eviction is not related to scheduling. However, I would say the exception to the rule here is in the Descheduler which relies entirely on a combination of pseudo-scheduling logic and eviction. 

So making a hard delineation of scheduling/eviction right now may cause confusion if we decide to document the Descheduler more in the future. But that is the only risk I see here

**Comment by Huang-Wei** [comment]
> Do you think the additions I've started in #26916 would suffice for that?

@tomkivlin Most of the rewording look great. Except for one nit: for now, the following stanza is categorized under "Eviction due to resource constraints" section:

_> Preemption, which as the name suggests is the preemptive eviction of one or more pods to allow for the scheduling of a higher-priority pod and the avoidance of the resource starvation._

It'd make more sense if we put it in a new section (e.g., "Preemption to prioritize high-priority Pods"). It's because all content under "Eviction due to resource constraints" section is controlled by kubelet - as mentioned:

_> The kubelet proactively monitors for and prevents total starvation_

BTW: the idea of explaining "Eviction" in detail (in reference/glossary/eviction.md) is super neat!

> Should we keep this issue for reference and open a new issue about the rename from Scheduling and Eviction to Scheduling and Preemption?

@sftim I agree.

**Comment by sftim** [comment]
Section was renamed to Scheduling, Preemption and Eviction
/close
