### ISSUE TITLE
Docs unclear on how Kubernetes uses YAML

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19139]
**This is a Bug Report**

**Problem:**
This issue is my interpretation of [k/k#87634](https://github.com/kubernetes/kubernetes/issues/87634).

In k/k#87634, @mleonhard reports that:
> I'm learning Kubernetes. I went through the tutorials - thanks. Now I'm trying to set up services to run on minikube and my hosting provider. The kubectl command apparently takes a YAML config file. I searched for 15 mins and found no documentation for it at all. I found a helpful blog post complaining about the missing documentation. There are examples: guestbook-all-in-one.yaml, a deployment, a service, a replica set, and a replication controller. The "Getting Start / Production Environment" documentation contains no guidance on using config files to define application deployments.
> 
> Should I deploy my code with bash scripts that call kubectl create deployment ... ? Is that how Google engineers work? No, they write borgcfg files. And they learned how to write borgcfg by reading the borgcfg docs. There's even a codelab (tutorial) on writing such files. Imagine trying to onboard new Googler SWEs without letting them read the borgcfg documentation or teaching them how to write borgcfg files. Nobody would do that. Yet Google wants us to use Kubernetes, to deploy on Google Cloud, and doesn't provide this basic doc.
> 
> The kubectl config file is crucial information that everyone learning Kubernetes must learn. Please don't make us hunt for this information, guess at the meanings of examples, and read unreliable Stack Overflow answers and blog posts. Just provide usable documentation. Please?

It sounds to me like there are two questions here.
1) As a novice cluster operator, how do I set up and configure kubectl?
2) As a novice cluster operator, how do I understand manifests and learn how to author them?

Both questions are important. Novice users want to interact with their cluster via kubectl; even if a tool like Minikube sets that up for them, they will soon want to learn about switching to access a different cluster. Novice users also want to know how to reuse their knowledge from outside Kubernetes to answer questions like “how do I run a set of containers in my cluster” or “how do I manage secret data for a workload component”. You need to understand some basics so that the pages about those concepts make sense to you.

**Challenges:**
- make sure that the _Getting started_ section really does help people get started with Kubernetes
- make sure that readers understand the difference between actual manifests and YAML documents that are used with Kubernetes and that look superficially similar.
- clearly document what does into a manifest, both in reference form and as a concept.

https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/ falls between two stools. Is it a page about workload resources such as Deployment and good practise for managing those? Alternatively, is the page telling the reader about ways to use and structure manifests? I wonder if it would work better with parts of the page split off and clear hyperlinks between them.

**Proposed Solution:**
- Plan a series of changes to make the two questions identified above discoverable and answerable.
- As per plan, submit PRs to make those changes.

**Page to Update:**
Various pages inside https://kubernetes.io/docs/, perhaps including:
- https://kubernetes.io/docs/setup/
- https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/
- https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/
- https://kubernetes.io/docs/tutorials/kubernetes-basics/
- https://kubernetes.io/docs/reference/kubectl/overview/

**Related issues:**
- https://github.com/kubernetes/website/issues/275
- https://github.com/kubernetes/website/issues/5409
- https://github.com/kubernetes/website/issues/5454
- https://github.com/kubernetes/website/issues/15671

/sig cli

**Comment by sftim** [comment]
@mleonhard if you'd like to /retitle this to better capture the issue, please go ahead and do that.

**Comment by mleonhard** [comment]
https://skaffold.dev/docs/references/yaml/

That documentation represents the bare minimum.  It covers all of the available values, but it lacks coherent examples and link-able sections.  When I have to add something complicated to a config, I include an explanation comment and a link to the documentation.  That is impossible with Skaffold documentation because there are no anchors.  And it's impossible with Kubernetes because there is no online documentation.

**Comment by mleonhard** [comment]
https://skaffold.dev/docs/references/yaml/

That documentation represents the bare minimum.  It covers all of the available values, but it lacks coherent examples, link-able sections, and it thwarts search engines by putting everything on one page.

## Why Users Need Coherent Examples
If the docs mix together multiple ways to use a config section, the reader must learn all styles to be able to sort out the values required for their case. And there will be trial-and-error, which is a huge time sink. Users come to documentation to accomplish specific goals. Learning the myriad ways the tool can be used is rarely one of those goals.  That is why users need working examples for:
- common use cases
- each supported feature

## Why Users Need Link-able Docs
Code is for reading.  When I have to add something complicated to some code, I include an explanation comment and a link to the documentation so the reader can go directly to the documentation and avoid having to hunt for it.  skaffold.yaml files cannot contain such time-saving links because the Skaffold documentation contains no anchors.  Kubernetes YAML files cannot contain such time-saving links because there is no online documentation to link to.

Here is an example from our production Terraform config:
```hcl
resource "digitalocean_droplet" "main" {
  ...
    user_data = <<-EOT
    #cloud-config
    ...
    # https://github.com/tmrts/flamingo/blob/master/docs/cloud-config.md#write_files
    write_files:
    - path: /etc/docker/cert.pem
      encoding: gzip+base64
      content: ${chomp(base64gzip(module.dockerd_cert.cert_pem))}
    ...
    # Start dockerd without "-H fd://", since that conflicts with the 'hosts' daemon.json key.
    # https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd
    - path: /etc/systemd/system/docker.service.d/override.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock
    # https://docs.docker.com/config/daemon/#configure-the-docker-daemon
    - path: /etc/docker/daemon.json
    ...
    EOT
}
```

## Why Users Need Searchable Pages
Documentation exists to teach users specific things so they can use the tool to accomplish their goals.  A critical part of teaching is guiding the student to the specific information they need.  Docs that put everything on one page fail at this.
- Users arriving from search engines get a huge document and need to search inside it for their answers.  [Bazel docs](https://docs.bazel.build/versions/master/command-line-reference.html) are the worst time-wasters because they put 1,609 flags on one page.
- Users searching inside the page must sift through irrelevant content.  CTRL-F searching also becomes useless.  For example, try searching for "certificate" in the [Digital Ocean API docs](https://developers.digitalocean.com/documentation/v2/) and you will find that you must spend 5 mins sifting through 205 matches on the page.

So please please please don't put all the docs on one page.  Let users find your docs with search engines.  Let them search with CTRL-F.  Help users find what they need quickly.

**Comment by sftim** [comment]
Thanks for clarifying @mleonhard

**Comment by sftim** [comment]
Also see #22015
