### ISSUE TITLE
Document minikube Podman support

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19218]
**This is a Feature Request**

**What would you like to be added**
Update the page at https://kubernetes.io/docs/tasks/tools/install-minikube/ to mention that there is a `podman` driver, similar to the Docker driver.

I recommend that _for now_ the Kubernetes website recommends to readers that they avoid using the `podman` driver; it's an initial implementation that requires running the containers as root. This should look similar to the existing advice about `--vm-driver=none`.

**Why is this needed**
There is now a `podman` driver in Minikube: https://github.com/kubernetes/minikube/pull/6515

**Comments**
/priority backlog
/good-first-issue

(if this is your first issue, and you aren't sure how to start, reply with a comment and I will try to provide advice).

/sig cluster-lifecycle

**Comment by afbjorklund** [comment]
@sftim : the docker driver also runs containers as root, so there is no real difference there...
So the same security warnings should apply to **both** "docker" and "podman" drivers, if so ?

Users should continue to run in a VM, if they are not happy with running privileged containers.

And _nobody_ should use the "none" driver, except for special use cases. It's in the minikube docs.
https://minikube.sigs.k8s.io/docs/drivers/none/

Basically it will run `kubeadm init` on the host...

In the new documentation, the "docker" driver is missing from the list:
1) Hypervisors
2) None
3) ?
4) Podman

So it should be described, since the "podman" driver now refers to it ?

> Minikube also supports a vm-driver=podman _similar to the Docker driver_.

Also the link is wrong, it goes to "Docker Desktop" (for Mac and Win)

> You can download .deb packages from _Docker_.

~~https://www.docker.com/products/docker-desktop~~

https://www.docker.com/products/container-runtime

**Comment by sftim** [comment]
@afbjorklund would you be willing to repeat your comment https://github.com/kubernetes/website/issues/19218#issuecomment-626370798 in a new issue?

**Comment by afbjorklund** [comment]
> @afbjorklund would you be willing to repeat your comment [#19218 (comment)](https://github.com/kubernetes/website/issues/19218#issuecomment-626370798) in a new issue?

Sure thing, there seems to be several issues here. But will try go finish v1.10 with podman first...

So far it is only in beta, and "podman" driver is likely to be experimental for quite some time yet.

**Comment by afbjorklund** [comment]
Seems like there already is #15969 under way, so maybe not create any more issues ?
