### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/secret/ Incorrect references to readOnly

### ISSUE THREAD

**Issue by timothyclarke** [kubernetes/website#19611]
**This is a Bug Report**

**Problem:**
Multiple references to `readOnly` `true`.    `readOnly` defaults to `true` and it is no longer possible to set `readOnly` to `false`

**Proposed Solution:**
Remove references to `readOnly` 
Optionally comment that secrets are not editable within a pod

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/secret/

Kubernetes Version:
I'm on 1.15. I believe this change was made in 1.9

Additional Information:
https://github.com/kubernetes/kubernetes/issues/62099

Related, but not the same as https://github.com/kubernetes/website/issues/4491

**Comment by Colstuwjx** [comment]
Thanks for creating this issue, now I also learned about this! The flag `ReadOnlyAPIDataVolumes` has been removed within [k/k PR 67951](https://github.com/kubernetes/kubernetes/pull/67951/files#diff-84e72664a7cc9add01954d3a7b8cbb45L249) since v1.12, see [CHANGELOG](https://github.com/kubernetes/kubernetes/blame/9d1179360cfc9fb6e905252cccd482b987d45393/CHANGELOG/CHANGELOG-1.12.md#L1739).

I think the pages about APIDataVolumes, like secret and configMap, these content should be changed.

/language en
/kind documentation
