### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

### ISSUE THREAD

**Issue by eino-makitalo** [kubernetes/website#19668]
**This is a Minor bug/editorial report**

**Problem:**
Link is broken https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md
in text Read release notes carefully....

**Page to Update:**
https://v1-15.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

**Comment by neolit123** [comment]
/sig docs cluster-lifecycle
/kind bug
1.15 is going out of support later this month, so we might leave this particular link broken.

but this is now a problem for all of the releases because k/k moved the changelogs to a new folder: https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG

i can send a PR to fix this in 1.18 at least.

**Comment by tengqm** [comment]
The problem with changed location of CHANGELOG is tracked in a different issue.
The case with 1.15 is about a version we won't fix unless it is about a significant bug that prevents Kubernetes from functioning properly.
/close
