### ISSUE TITLE
LimitRange tutorial task included in concept page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19847]
**This is a Bug Report**

**Problem:**
The page at https://kubernetes.io/docs/concepts/policy/limit-range/ is concept-level documentation; however, it embeds a section on trying out LimitRange. The Kubernetes website usually puts that kind of step-by-step guidance in the Tasks section, and has other pages link to those tasks.

**Proposed Solution:**
- Create a new task page that includes the content of https://kubernetes.io/docs/concepts/policy/limit-range/#limiting-container-compute-resources
- Update https://kubernetes.io/docs/concepts/policy/limit-range/ to hyperlink to the new page
- Also make the new task pager refer back to https://kubernetes.io/docs/concepts/policy/limit-range/

**Page to Update:**
https://kubernetes.io/docs/concepts/policy/limit-range/#limiting-container-compute-resources

/help
/language en

**Comment by rajeshdeshpande02** [comment]
Hello @sftim , We already have 4 Task pages for Limit Range under the administration section and those pretty much cover every detail. But I agree with you, Limit Range concept document embeds a section on trying out LimitRange. So can we simply remove that from concept page instead of creating new tasks page as we already have those tasks covered.
These are existing task pages available for Limit Range

https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/

**Comment by sftim** [comment]
It'd be fine to link to those and shorten the concept page, indeed.

**Comment by davivcgarcia** [comment]
@sftim and @rajeshdeshpande02: Are you guys working on it? I think I can help on that!

**Comment by sftim** [comment]
I've logged the issue; I'm hoping that someone else - you, @davivcgarcia? - will be willing to make the changes here.

**Comment by davivcgarcia** [comment]
Sure! I'll work on it.

/assign

**Comment by davivcgarcia** [comment]
I'll clear the `help wanted` flag to avoid confusion.

/remove-help

**Comment by davivcgarcia** [comment]
@sftim @ rajeshdeshpande02 I've been exploring the docs related to concepts, and looks like all pages follow the same pattern of having explanation in text and exercises. What you are proposing is to restrict the concept docs to theoretical explanations and points to task docs for exercises/examples?

**Comment by sftim** [comment]
“It depends”.
I think just on this page it's a bit longer than it needs to be, and hyperlinking would help. Other concept pages might be fine as they are.
