### ISSUE TITLE
Feature state shortcode compatibility with CommonMark & with Hugo ≥ 0.60.0

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20336]
**This is a Bug Report**

**Problem:**
The [feature state](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#feature-state) shortcode does not render as intended when the site is generated using Hugo ≥ 0.60.0

**Proposed Solution:**
Revise and simplify feature-state shortcode.

I'm considering what's possible using HTML & CSS only, as well as what value the shortcode provides for site visitors.

**Comment by sftim** [comment]
I'm going to try fixing this. If someone else would also like to work on this, that's OK. Maybe we can collaborate?

**Comment by sftim** [comment]
Relevant to issue #20335

**Comment by kbhawkey** [comment]
Hi @sftim 
Let me know if you'd like a hand with this update (or just a review).
The descriptions for the different states are located in `/<lang>/docs/templates`.
Some of the content may be duplicated in the feature _gates_ reference page.
I am wondering if the state descriptions belong in the same _section_ as the information about version/version skew. Perhaps the shortcode could link to a new feature state content page?
Previously, I thought it might be helpful to identify the feature name with the state as some pages list multiple feature states. Otherwise, the page title could represent the feature name in the shortcode.
Another idea: Add some color to the left border of the feature state div. to give the page some pop.

**Comment by sftim** [comment]
So far I did not make a start on this work.

**Comment by jimangel** [comment]
If there hasn't been any progress on this I might take a stab at making a very basic fix.

**Comment by jimangel** [comment]
I think this is good to close.
/close
