### ISSUE TITLE
Advise contributors to limit pull requests to a single localization

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20411]
**This is a Bug Report**

**Problem:**
Pull requests that touch multiple localizations are difficult to review. Each localization team gets to pick its own workflow, that might work off _master_ or might use a long-lived branch with merges to _master_ at milestones.

The current advice to contributors does not mention limiting pull requests to a single localization.

**Proposed Solution:**
Revise https://kubernetes.io/docs/contribute/localization/#help-an-existing-localization to recommend that PR authors only touch a single localization.

**Page to Update:**
https://kubernetes.io/docs/contribute/localization/#help-an-existing-localization

/good-first-issue
/language en

**Comment by Krishan-Sharma** [comment]
I will like to assign this to myself. /assign Krishan-Sharma

**Comment by perret34** [comment]
Hello,
Excuse me for this way of contacting you, I don't think it was a coincidence that I contacted you. It is good after several days of intense prayer that I do it is that the Holy Spirit guided me towards you by the grace of God. I donate my goods to an honest and needy person of French origin and I live in France. I suffer from a serious illness which condemns me to certain death, it is throat cancer, and I have a sum of 700,000 euros which I would like to make a donation to a person of trust and honest so let him make good use of it in order to help his family and start a new life in happiness and peace. I donate these funds for free to change your life. I donate this because after all the love of neighbor is the basis of all my Christian life.
I would then like to know if you can benefit from this donation?
Contact by email for the procedures to obtain 700,000 euros for free.

Mail: Perretgerome@gmail.com

God bless you.

**Comment by perret34** [comment]
Hello,
Excuse me for this way of contacting you, I don't think it was a coincidence that I contacted you. It is good after several days of intense prayer that I do it is that the Holy Spirit guided me towards you by the grace of God. I donate my goods to an honest and needy person of French origin and I live in France. I suffer from a serious illness which condemns me to certain death, it is throat cancer, and I have a sum of 700,000 euros which I would like to make a donation to a person of trust and honest so let him make good use of it in order to help his family and start a new life in happiness and peace. I donate these funds for free to change your life. I donate this because after all the love of neighbor is the basis of all my Christian life.
I would then like to know if you can benefit from this donation?
Contact by email for the procedures to obtain 700,000 euros for free.

Mail: Perretgerome@gmail.com

God bless you.

**Comment by sftim** [comment]
Off-topic spam messages reported to GitHub.

**Comment by tengqm** [comment]
Fixed.
/close
