### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/

### ISSUE THREAD

**Issue by mahpatil** [kubernetes/website#20546]
**This is a Bug Report**

**Problem:**
The "deployment yamls" link is broken as it still points to https://github.com/kubernetes-sigs/metrics-server/tree/master/deploy
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by nevermyuk** [comment]
Might be because it is now being used only for development. [For more info, Metric server deployment README](https://github.com/kubernetes-sigs/metrics-server#deployment) 
 
**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#metrics-server

/language en
/kind bug

**Comment by tengqm** [comment]
This issue has been fixed. Feel free to reopen if the link still doesn't work.
/close
