### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-kubernetes-objects/declarative-config/

### ISSUE THREAD

**Issue by AnilPothula** [kubernetes/website#20701]
**This is a Bug Report**

**Problem:**
To print the live configuration after:
kubectl apply -f https://k8s.io/examples/application/update_deployment.yaml
**kubectl get -f https://k8s.io/examples/application/simple_deployment.yaml -o yaml**

**Proposed Solution:**
kubectl get -f https://k8s.io/examples/application/update_deployment.yaml -o yaml

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-to-update-objects

**Comment by viniciusbds** [comment]
Hi @AnilPothula, thanks for contributing.

I tested with both files and both worked. 

It doesn't really look like a bug. Probably the parameter **- f file.yaml** in the command `kubectl get -f file.yaml -o yaml` serves only to identify the deployment by its name, so we could use any of the files: 
https://k8s.io/examples/application/simple_deployment.yaml
or
https://k8s.io/examples/application/update_deployment.yaml

Still, I think the current way of displaying the live configuration is very confusing. It might be better to use the deployment name instead of the entire file. The **kubectl get deploy deploy-name -o yaml**



kubectl get deploy nginx-deployment -o yaml

**Comment by tengqm** [comment]
fixed by #20723
/close
