### ISSUE TITLE
Issue with install-kubectl.ps1 power shell command

### ISSUE THREAD

**Issue by prakashid2** [kubernetes/website#20709]
**This is a Bug Report**

**Problem:**
I'm trying to install Kubenetes as per [install-kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/) link.

Powershell is throwing error in output. First command 'Install-Script' succeeded but did not show any lines in console output.

-- Error in output of install-kubectl.ps1 --
PS D:\kubernetesInstalled> install-kubectl.ps1 -DownloadLocation D:\kubernetesInstalled
install-kubectl.ps1: The term 'install-kubectl.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS D:\kubernetesInstalled>
-- --

**Proposed Solution:**
I want someone to look into this issue rather than installing using Chocolatey package manager which is more difficult. Not sure why 'install-kubectl.ps1' command is throwing error.

**Page to Update:**
https://kubernetes.io/...

![ErrorIn install-kubectl](https://user-images.githubusercontent.com/35317036/80796980-3a840880-8bbe-11ea-9223-a3e17f413a17.jpg)
![Installing install-kubectl ps1](https://user-images.githubusercontent.com/35317036/80796981-3c4dcc00-8bbe-11ea-8635-fa4b29c4ba94.jpg)

Kubernetes version 1.18.0

**Comment by tengqm** [comment]
have you tried `Install-Script -Name install-kubectl -Scope CurrentUser -Force -Debug` and see if the `Install-Script` was a success? Sometimes PowerShell just fail silently.

I'm gonna close this issue because it doesn't look like a documentation error. Please feel free to reopen if you believe there are something the doc site needs to fix.

This list of issues tracks bug reports and feature requests for the Kubernetes documentation.

If you're looking for help, check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
