### ISSUE TITLE
Issue with shell scripts

### ISSUE THREAD

**Issue by devdatta-m** [kubernetes/website#20799]
**Problem:**
after upgrading kubernetes version from 1.14.8 to 1.15.10, it is observed that entrypoint.sh running shell scripts asynchronously. One of the script creates certificates that are to be used in IHS which is started later in entrypoint.sh

But even though the script to intialize certs is called before starting IHS server, certificate date is few seconds after IHS startup time.

**Proposed Solution:**
Provide a way to run shell scripts synchronously 

 1.15.10

**Comment by sftim** [comment]
@devdatta-m I'm not sure what part of the documentation isn't clear.

Maybe you're asking for clarification on the difference between [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) and sidecar containers (see https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#understanding-pods for context).

Is there something that needs to change about the existing documentation?
/triage needs-information

**Comment by devdatta-m** [comment]
I dont think you have undertood my question. Did Kubernetes 1.15.10 change how shell scripts are executed ?

**Comment by sftim** [comment]
@devdatta-m: GitHub is not the right place for support requests. This list of issues tracks bug reports and feature requests for the Kubernetes documentation.

If you're looking for help, check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes)

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/remove-triage needs-information
/triage support

**Comment by tengqm** [comment]
@devdatta-m I'm closing this issue since it doesn't look like a feature request or bug report related to documentation.

If you're looking for help, check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
