### ISSUE TITLE
Add search to blog pages, tag the content

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#20895]
**This is a Feature Request**
I'd like to start a search on the blogs from the blog page.

**What would you like to be added**
Add a link to the docs default search engine.

**Why is this needed**
Blog content is listed only by the year published.

**Comments**
It may be nice to develop categories to tag the blog content and provide different ways to display the blog entries (not just by year).

**Comment by shuuji3** [comment]
Hello @kbhawkey, is this PR still valid? If so, could you reopen it since fejta-bot has closed it?

**Comment by kbhawkey** [comment]
👋 @shuuji3 .
I reopened the issue. You could propose a PR with changes and reach out to the blog sub-project team or
add your ideas for the blog search component in this issue.
Should the blog pages have a search bar? Where could you add this component?
Thanks for looking into this.
/triage accepted

**Comment by shuuji3** [comment]
👋🏻 @kbhawkey Thanks for reopening!

I think it's nice to add a search component just like the documentation page. It enables readers to find the related articles when they meet unfamiliar topics in the blog post.

**Current search box in docs**
<img width="546" alt="Screen Shot 2021-03-22 at 0 05 52" src="https://user-images.githubusercontent.com/1425259/112424811-6aa93c80-8d78-11eb-8e4b-c379930b31b0.png">

**Proposed search box in blog page**
<img width="556" alt="Screen Shot 2021-03-22 at 0 05 34" src="https://user-images.githubusercontent.com/1425259/112424819-6da42d00-8d78-11eb-8666-d9bea88674db.png">

I think it's important to placing the search box in the same place with documentation like the above because it would give the consistent user experience to search and has less confusion.

I'd like to make a PR which extract search input element as a hugo partial and place the partial in both places like the above screenshots.

**Comment by kbhawkey** [comment]
Good. Have you created a PR?

**Comment by shuuji3** [comment]
No, I haven't yet. I hope to create a PR this week.
