### ISSUE TITLE
Page layout for k8s.io/docs/concepts/workloads/controllers/deployment/ is broken

### ISSUE THREAD

**Issue by supirman** [kubernetes/website#20912]
**Problem:**
Page layout for Deployment page is broken.

**Proposed Solution:**
Fix or rollback to previous version

**Page to Update:**
k8s.io/docs/concepts/workloads/controllers/deployment/

**Comment by sftim** [comment]
Hi @supirman 

Can you describe the symptoms you saw?

**Comment by SudoBrendan** [comment]
I'm glad it's not just me - I'm seeing quite a few formatting issues today across numerous pages in chromium/firefox as well. Here are some screenshots:

![image](https://user-images.githubusercontent.com/26753294/81737404-a9cee780-945d-11ea-85d8-e41bc6e01731.png) - e.g the "blockquote" stuff everywhere; text boxes are not looking right either. [Source](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/)

I happened to look at [this](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker) page today and yesterday, it used to be that the different distributions (ubuntu vs Fedora/RHEL) were tabs you could select, similar to [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime), that's now murked. The code snippets are also full of extra whitespaces for some reason.

As an aside - really loving these docs, thanks so much for maintaining them, they're excellent!

**Comment by ArtemAlagizov** [comment]
that is how Deployment page looks like right now for me in chrome in French language:

![current-deployments-french](https://user-images.githubusercontent.com/15367507/81800929-e5c48400-9513-11ea-85ab-1e5fd64ce65d.png)

the reason is broken html: there is a bunch of elements that are on the same level with **\<div id="docsContent"\>\</div\>**, although they should be inside of it

check it:
----

good html (English version): 

![good-html](https://user-images.githubusercontent.com/15367507/81800950-f117af80-9513-11ea-81a0-98ff4c5d8225.png)

----

broken html (French version):

![broken-html](https://user-images.githubusercontent.com/15367507/81800962-f674fa00-9513-11ea-9038-85f879f486f0.png)

----

only English and Chinese versions of the page have correct html in them.
English version also had broken html yesterday.

**Comment by sftim** [comment]
@ArtemAlagizov if you log the bug with the French page into its own issue, that lets the French localization team pick it up and work on it. (If you want to submit a PR directly yourself, that is also OK).

**Comment by ArtemAlagizov** [comment]
@sftim got it, thanks! i will submit a separate bug issue

**Comment by ArtemAlagizov** [comment]
fixed in #20946
/close

**Comment by ArtemAlagizov** [comment]
@k8s-ci-robot thank you robot

**Comment by sftim** [comment]
/close
fixed in #20920
