### ISSUE TITLE
Localize "Nodes" page to Italian

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/website#20955]
I would like to have the "Nodes" page to be translated into Italian
page https://kubernetes.io/docs/concepts/architecture/nodes/

/language it
/priority important-soon

**Comment by crixo** [comment]
nodes.md has already been translate for v1.17
https://github.com/kubernetes/website/blob/master/content/it/docs/concepts/architecture/nodes.md
the file belongs to the master branch but it still reflects the previous version.
the file is also part of the branch release-1.17
https://github.com/kubernetes/website/blob/release-1.17/content/it/docs/concepts/architecture/nodes.md
Not sure what has to be done. shall we simply editing the file to reflect the translation of the latest version?
File in master branch is not visible due to the front-matter property
```draft: True```

**Comment by fabriziopandini** [comment]
@crixo up to you if to edit current translation and remove draft or restart from scratch.  It really depends by the number of changes/the quality of the current translation
