### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by jandevdev** [kubernetes/website#21233]
**This is a Bug Report**

**Problem:**
I am trying to follow the documentation to deploy the Dashboard UI but it fails at the first step when executing:
``` kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml ```

It spits out the following error:
``` error: SchemaError(io.k8s.api.authorization.v1.SelfSubjectAccessReviewSpec): invalid object doesn't have additional properties ```

**Proposed Solution:**
?

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

Kubernetes Version:
kubernetes-cli v1.18.2

**Comment by tengqm** [comment]
Can you try file an issue at https://github.com/kubernetes/dashboard/issues ?
It looks like something is broken in the source code implementation since the SchemaError is not related to how you are using/documenting it.

Feel free to reopen this if there is a workaround from documentation side.

/close
