### ISSUE TITLE
Sort third party client library links

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#21563]
**This is a Bug Report**

**Problem:**
[_Client Libraries_](
https://kubernetes.io/docs/reference/using-api/client-libraries/) lists 3rd party software. Kubernetes docs allow content for third-party projects only when:
- Content documents software in the Kubernetes project
- Content documents software that’s out of project but necessary for Kubernetes to function
- Content is canonical on [kubernetes.io](https://kubernetes.io/), or links to canonical content elsewhere

**Proposed Solution:**
~Remove links to 3rd party client libraries~
Sort list alphabetically

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/client-libraries/

**Additional Information:**
Part of umbrella issue #20232
/language en

**Comment by sftim** [comment]
There was some discussion in https://github.com/kubernetes/website/pull/21509 about this.

What was the outcome?

**Comment by sftim** [comment]
This is also relevant to https://github.com/kubernetes/website/pull/21112

**Comment by sftim** [comment]
We discussed this in the 2020-06-23 SIG Docs weekly meeting.
@jimangel proposed flagging the third party client libraries with an added cautionary note about quality.
@sftim recommended ensuring that all client projects within https://github.com/kubernetes-client _are_ linked to
@zacharysarah notes that this is strictly content as outside what's allowed in the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/) but that it is useful to a wide user base
@jimangel also points out that client libraries in general (whether in-project or otherwise) _are_ useful to make Kubernetes work as you want it to?

This content is unique (there's not a good alternative page elsewhere on the web). What's important is to identifying an owning SIG and having some means to keep the list live and relevant.

Removal is held until the end of the v1.19 release cycle, so positive discussion before that date is helpful and I encourage it.

/sig community
/sig api-machinery
@mrbobbytables we are conflicted about where to put this; we're not sure it fits inside documentation any more - would SIG Community be interested in hosting this list?
@kubernetes/sig-api-machinery-misc what are your views on this list, in light of [_doc-policies-for-third-party-content_](https://github.com/kubernetes/enhancements/blob/master/keps/sig-docs/20191020-doc-policies-for-third-party-content.md)

**Comment by zacharysarah** [comment]
Raised visibility in [#sig-api-machinery](https://kubernetes.slack.com/archives/C0EG7JC6T/p1594364677058700)

**Comment by yue9944882** [comment]
> @sftim recommended ensuring that all client projects within https://github.com/kubernetes-client are linked to

sadly some projects under the org is not actively maintained. those libraries (go/java/python/dotnet/js) already linked are fairly active. can we consider to append a new link for C/C++  https://github.com/kubernetes-client/c which is newly added & active months ago?

> @kubernetes/sig-api-machinery-misc what are your views on this list, in light of doc-policies-for-third-party-content

i wonder if the community-maintained list is stale b/c it seems rarely updated. also i noticed there's a number of repos stopped maintaining for 1-2 years or even longer period of time:

- https://github.com/xh4/cube
- https://github.com/ericchiang/k8s
- https://github.com/yanatan16/clj-kubernetes-api
- https://github.com/ajpauwels/easy-k8s
- https://github.com/tonnyeremin/kubernetes_gen
- https://github.com/Ch00k/kubr

am slighting leaning on keeping the community list as most of these projects are driven by individuals instead of dedicated vendors -- the more we have the better? @brendandburns

**Comment by kbhawkey** [comment]
@sftim, Should this issue remain open? Thanks!

**Comment by sftim** [comment]
I can see one thing that still needs doing
/retitle Sort third party client library links

so the link text is clearly in alphabetical order.

**Comment by sftim** [comment]
The remaining sorting is straightforward; if it weren't for the issue history I'd say it's a good first issue.
/help
/kind cleanup
