### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/expose-external-ip-address/

### ISSUE THREAD

**Issue by kramse** [kubernetes/website#2180]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
type=LoadBalancer is only supported on some platforms.

A lot of people will try out Kubernetes on their own systems, like us. When trying to get traffic into the system, or using services from outside the cluster - pain.

**Proposed Solution:**
Create tutorial similar to the one I created this issue on, and make it about ingress controllers.

I will be happy to provide or write, since I think I got something running :-D

**Page to Update:**
http://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

not really, since I want a new page expose-external-ip-using-ingress-controller - something like that

Outline idea
kubectl create -f 00-namespace 

create deplyoment using
- image: gcr.io/google_containers/nginx-ingress-controller:0.8.3

create default backend default-deployment.yaml and default-service using 
image: gcr.io/google_containers/defaultbackend

then create Nginx service with ingress rules, and test using 
curl node_ip -H 'host: my-nginx.domain.tld'

**Comment by steveperry-53** [comment]
@kramshoej, This sounds like a good idea to me.
@pwittrock, What do you think?

**Comment by dannymk** [comment]
Same here, I have a cluster up and running and backing from the SA and the network guys.  However, getting the loadbalancer working on bare metal without ANY external providers like GC or AWS is a real pain.  Wish it was described a lot better.  I can use the ingress IP all day but that of course won't help when the users call us because the IP on the ingress changes.  Asking them to wait while the network admin tech sets the IP in DNS would be ridiculous.  The best option at the moment is:  https://github.com/kubernetes/contrib/tree/master/service-loadbalancer, however documentation is very poor.
