### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by tamas-molnar** [kubernetes/website#2218]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubernetes is spelled wrong on the image on the deploy-intro tutorial page: 'Kuberneters Cluster'

**Proposed Solution:**
fix spelling

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/

**Comment by BenHall** [comment]
Thanks for your feedback. This looks like a duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/1767

I can't find the text in the repo now so I believe it's been fixed.

**Comment by heckj** [comment]
@BenHall the mispelling is a part of the image, and it's still there - not resolved. Not sure who made the original to get a fix on the image...

**Comment by BenHall** [comment]
Maybe @jocatalin can help. He was part of the original @ContainerSolutions team who worked on the content.

**Comment by jocatalin** [comment]
I asked the designer agency who helped developing the diagrams (remembertoplay.co) to fix this, and I just got a new version that removes the typo. But what I can see is that there was a fix for this in the ticket @BenHall mentioned (#1767): https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tutorials/kubernetes-basics/public/images/module_01_cluster.svg

@heckj  I think the problem is with the browser caching. Try using a different browser or start an incognito session. It fixed it for me.

**Comment by heckj** [comment]
The image referenced is also `module_02_first_app.svg` (https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tutorials/kubernetes-basics/public/images/module_02_first_app.svg). `module_01_cluster.svg` was updated, just not the only instance of the typo would be my guess.

**Comment by tengqm** [comment]
Fixed.
