### ISSUE TITLE
Add kubeswitch to the kubectl installation page

### ISSUE THREAD

**Issue by dannyburke1** [kubernetes/website#22464]
**This is a Feature Request**

**What would you like to be added**
Add an optional description for https://github.com/steamhaus/kubeswitch to be added to the kubectl install page. This works on OSX and Linux.

**Why is this needed**
Easy to use tool for users to help speed up the install process and also helps swap versions easily for developers.

**Comments**
Happy to answer any questions if there are any. I can also add a PR of what it would look like.

**Comment by sftim** [comment]
@dannyburke1 this issue seems to suggest making changes contrary to the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/). We wouldn't accept a change that wasn't allowed by those guidelines.

If you feel I've miscategorised this, please clarify (without that clarification, a reviewer / maintainer may close this issue as invalid and triage it unresolved).

**Comment by dannyburke1** [comment]
> @dannyburke1 this issue seems to suggest making changes contrary to the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/). We wouldn't accept a change that wasn't allowed by those guidelines.
> 
> If you feel I've miscategorised this, please clarify (without that clarification, a reviewer / maintainer may close this issue as invalid and triage it unresolved).

Hey Tim, no problem at all. Apologises for raising this incorrectly.

Cheers
