### ISSUE TITLE
Investigate building a docker container officially vs. local make instructions.

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#22515]
**This is a Feature Request**

With the adoption of the theme Docsy, running Hugo locally has been known to cause bugs. The most common bug is a "too many open files" error.

To remediate these challenges, SIG Docs is updating the `README.md` and k/website contributor guides on how to use a Docker container for testing website changes.

Today, the plan involves describing how to run a `make` file to build the container and instructions on how to use that container to preview website changes.

**What would you like to be added**

Create a periodic job that [publishes](https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing) a k/websites docker image (based on a Dockerfile) in Kubernetes' official docker repository. 

**Why is this needed**

If we had a periodic job that built and published an "official" container using Kubernetes infrastructure, the end user would not have to run `make` to build a container. In addition, instructions would be more cross-platform friendly as `make` is not available on Windows.

**Comments**

The **entire scope** of this issue is for me to investigate how hard will it be to create, schedule, maintain, and support a k/website docker image.

After investing our options, we may ultimately decide to take no action if the efforts are unsustainable.

/assign
/cc @kbarnard10 @zacharysarah 
/cc @celestehorgan @sftim @kbhawkey @onlydole @adambkaplan 

Related:
https://github.com/kubernetes/website/issues/22586
https://github.com/kubernetes/website/pull/22518

**Comment by sftim** [comment]
The [`Dockerfile`](https://github.com/kubernetes/website/blob/master/Dockerfile) already exists, and has had at least informal testing with both Docker and Podman.

**Comment by sftim** [comment]
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action ?

**Comment by sftim** [comment]
The tricky bit, I think, is authorizing the image push to the official repository.

**Comment by kbhawkey** [comment]
I don't know under what circumstances there are too many open files. I guess I missed the details and explanation.
To recap, the reason for creating this issue is to investigate creating a "standard" build image, containing the accepted
version of Hugo, Linux, and related libraries? Also, contributors can skip the container image build step?
Contributors can always download a version of Hugo to test their changes locally (hopefully the instructions will remain in the docs).
Occasionally, I use `(x86)/GnuWin32/bin/make` on Windows. Though, not for building the site.
Typically I build and run the container targets on a Linux installation on the same machine.
Recently the targets changed to be container engine neutral. How will this be impacted?

**Comment by onlydole** [comment]
I do like the base image direction to make this easier, and +1 on @kbhawkey's question around impacts for Docker and Podman (how would we want to set that up for success?)

**Comment by sftim** [comment]
If you have a container image that you build locally and that works, building the same thing in CI and then fetching that from a container registry is very likely to also work fine when you use it on your PC.

**Comment by adambkaplan** [comment]
> I do like the base image direction to make this easier, and +1 on @kbhawkey's question around impacts for Docker and Podman (how would we want to set that up for success?)

Using `CONTAINER_ENGINE` as an arg in the Makefile is pretty common. Defaulting to `docker` is the safest choice - so many `podman` users alias `docker` that there is now a `podman-docker` RPM to do it for you.

I can't speak for other container engines - perhaps we need a note that the CONTAINER_ENGINE must implement the `pull`, `build`, and `run` command line interfaces?

**Comment by kbhawkey** [comment]
I don't have a problem with the current container targets in the Makefile. If an image is provided, I will use it.
I do most of my build/test on Linux (found Hugo runs best there) and split between building the site from the cmd line, and building/running the site in a container. I noticed that my local builds started to slow down around the time of the parser upgrade. And more so now with the addition of the theme. Is there a way to get data about the average build time for production builds of the site?
Thanks @jimangel .

**Comment by sftim** [comment]
> get data about the average build time for production builds of the site?

Nice idea. There are a few ways we can get that data. Either grab it from the Netlify logs (which are public) or run a separate deploy in a container, time it, and publish a metric.

Maybe Netlify already tracks this for us?

**Comment by BenTheElder** [comment]
I was actually planning to look at rewriting the makefile to automatically rebuild the image as a dependency of the other targets when the image changes, which might be worth considering still.

One issue with hosting pre-built is that Kubernetes provides GCR registries, which are not available in china AIUI, which seems extra problematic for k/website.

**Comment by sftim** [comment]
That's OK @BenTheElder I think

Anyone affected by state-level censorship can still build the container image locally if they have a tool such as Docker or Podman that knows how to do that.

**Comment by BenTheElder** [comment]
If that's the case and we're fine with that ...
/assign
We have tooling & processes for CI build Kubernetes images on official project GCR.

**Comment by jimangel** [comment]
@BenTheElder thanks! I would be happy to work with you on this. Let me know how I can help!

**Comment by BenTheElder** [comment]
Great! I sent you a brain-dump on slack, will sync more when you're on next!

**Comment by BenTheElder** [comment]
Request for a staging registry from wg-k8s-infra submitted in https://github.com/kubernetes/k8s.io/issues/1033

The process is normally to have auto-pushed images from CI go into a staging registry per-project (so we'll get one for kubernetes/website), and then you can file PRs to k8s.io to promote a digest from staging to a tag in the prod registry.

https://github.com/kubernetes/website/pull/22554 updates the image to have an automatic `:v$(HUGO_VERSION)-$(DOCKERFILE_VERSION)` tag, since we'd normally promote specific versions (and since they're normally never mutated you don't need to pull repeatedly when running them).

Next up we'll need the `cloudbuild.yaml` spec and prow trusted image build job.
See also the TODO comment in https://github.com/kubernetes/website/pull/22554

Once they're promoted users can just run `make container-build` w/o any pull and it will pull the missing image if the tag isn't already present. The auto-tag should change when the image changes (and therefore be pulled)

**Comment by BenTheElder** [comment]
For more on k8s.gcr.io, see: https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io, this has pretty good documentation now.

This coming monday we should be able to actually publish under k8s.gcr.io alongside the other kubernetes images via community infra :-)

**Comment by BenTheElder** [comment]
> The entire scope of this issue is for me to investigate how hard will it be to create, schedule, maintain, and support a k/website docker image.

*eep*. I've definitely jumped the gun on this, sorry 😞 

----

Er so, I don't think it will be mucher harder than the existing image, basically we'll leverage the community infra to host it the same way other projects are doing it, the main maintenance work will be submitting / possibly approving PRs to promote new image versions. 

Those are pretty low effort: basically you just grab the digest for the new image either from the CI log or from browsing the staging registry and file a PR to some yaml adding a line ~ like `"sha256:abcdef": ["v0.70.0-0"]` (digest: tags to publish it as).

Even if we don't pre-publish images, the Dockerfile also needs to be looked after, and the makefile.

All of the tooling for the image hosting, building, etc. is shared across the project, so k/website won't need to maintain that.

We will need to add the `cloudbuild.yaml` here initially, for the build pipeline, but that shouldn't require ongoing changes, it will just be a simple wrapper around the makefile so we can run it in the secure staging pipeline.

Builds will automatically trigger in prow, and that config typically doesn't require ongoing changes either and will be owned by the prow team (because it runs in the "trusted" cluster).

---- 

**TLDR**: It mostly requires some initial setup (well trodden already), minimal ongoing extra maintenance (filing simple PRs to specify which auto-built images should be promoted to production).

_technically_ we can also use the staging registry directly and not ever promote to production, though it's not "best practice".

The image promotion setup also comes with a community-wide backup & disaster recover plan / management, so we get that for free. There is work to add other goodies like vulnerability scanning.

**Comment by jimangel** [comment]
@BenTheElder for the record, you didn't jump the gun. I wasn't sure of what's possible and you _know_ what is possible. Really happy to see the work you've done on this.

We will need to document some of these ongoing maintenance items in k/website somewhere (contributor guide?).

Catching up now... Thanks!

**Comment by BenTheElder** [comment]
/lifecycle active
The image has automated versions now, which imho is/was a pre-requesite for this to work well.

**Comment by BenTheElder** [comment]
following up on https://github.com/kubernetes/k8s.io/issues/1033
sorry this fell behind.

**Comment by BenTheElder** [comment]
/lifecycle active
back from vacation. go away fejta-bot

**Comment by sftim** [comment]
Just a reminder that originally
> The entire scope of this issue is for [@jimangel] to investigate how hard will it be to create, schedule, maintain, and support a k/website docker image.

**Comment by sftim** [comment]
(anyone can investigate, but beyond that feels like it wants a new issue)

**Comment by BenTheElder** [comment]
Sorry about this : (

I will sync with @jimangel at the earliest convenience and see what we can do to round this out / at least braindump any relevant info I can help with.
