### ISSUE TITLE
Docs are not clear if QoS classes impact resource utilization priority or only scheduling/eviction

### ISSUE THREAD

**Issue by linjmeyer** [kubernetes/website#22531]
**This is a Bug Report**

**Problem:**
The Quality of Service (QoS) docs describe that QoS classes impact scheduling and eviction, but it is not clear if QoS also impacts resource utilization priority.  In other technologies Quality of Service does impact priority of resource usage, for example if a network router is low on bandwidth it will give priority to packets in the higher QoS class.  This is not the case for Kubernetes Quality of Service, but it could easily be assumed or misunderstood.

**Proposed Solution:**
Add a simple statement/callout to explain that QoS in Kubernetes does not prioritize CPU/Memory usage between containers and only impacts scheduling and eviction based on resource utilization.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

**Comment by seh** [comment]
Also, please see [the motivating thread from the "sig-scheduling" channel](https://kubernetes.slack.com/archives/C09TP78DV/p1594753422105100) in the Kubernetes Slack team.

**Comment by sftim** [comment]
The overall idea with Kubernetes is to bin-pack workloads - see https://kubernetes.io/docs/concepts/configuration/resource-bin-packing/ - so that there is in aggregate no contention for the node's CPUs.

You might quite legitimately want to run some task with sort of `SCHED_IDLE` priority: first to be evicted, least likely to be selected by the OS-level thread scheduler. AIUI Kubernetes does not offer any way to set the OS-level scheduling priority for a container and the threads in its cpu cgroup.

For some background on what Linux, rather than Kubernetes, offers: https://www.kernel.org/doc/Documentation/scheduler/sched-rt-group.txt
