### ISSUE TITLE
top level scheduling doc 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#2276]
We need to add a top level scheduling_overview.md file, per https://github.com/kubernetes/kubernetes/issues/33188.

*Alternatively* we can update the docs in community, but i assume that we at this point want the scheduler to be in the user docs given the increasing complexity/configuratbility w/ affinity and so on.

Suggested format:  (if we agree on this, ill submit the PR, ihave it mostly set up now, it pulls from the implemented design proposals, diagrams and other tidbits that are spread around).

@timothysc @ConnorDoyle @davidopp PTAL the format below, if SGTM, i will issue the PR in the morning.  I have a (mostly) complete overview for end users which we can start with for the 1.6 stabilization release.

# The Kubernetes Scheduler
## Ranking the nodes
# Advanced Topics:
### Taints and Tolerations

**Comment by davidopp** [comment]
@jayunit100 Can you clarify what the target audience is? Users? Admins? Developers? Today we have the following docs (unless I am forgetting some):

User documentation
* https://kubernetes.io/docs/user-guide/node-selection/
* https://kubernetes.io/docs/user-guide/compute-resources/

Admin documentation
* https://kubernetes.io/docs/admin/multiple-schedulers/

Developer documentation
* https://github.com/kubernetes/community/blob/master/contributors/devel/scheduler.md
* https://github.com/kubernetes/community/blob/master/contributors/devel/scheduler_algorithm.md

Design docs
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multiple-schedulers.md
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/nodeaffinity.md
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/podaffinity.md
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/taint-toleration-dedicated.md
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduler_extender.md

[ I have intentionally omitted the rescheduling documents because we are going to change that soon and I think the current state of affairs and terminology is super-confusing. But anyway, the current admin guide documentation for it is [here](https://kubernetes.io/docs/admin/rescheduler/). ]

The current state of affairs for documentation is not ideal, but I would suggest that the two principles we should use in changing any of the documentation is
(1) keep the "what users and admins need to know" stuff separated from the "what developers need to know" stuff, as it is today -- don't overwhelm users and admins with stuff they don't need to know (e.g. inner workings of scheduler), but it's fine to give a link to the more detailed developer docs (just as its fine to link from developer docs to design docs)
(2) build on the existing docs rather than creating more


cc/ @kubernetes/sig-docs-misc

**Comment by jayunit100** [comment]
Thanks for linking all of those, yes, much of that information is what I was consolidating.  The audience is users , but developers and admins also can be users at times: and they need a canonical place to start reading about the scheduler , even if we link some content to other places.

For users, references on how the scheduler works, without diving too deep, should be consolidated in the docs.  Right now somewhat scattered with node-selection sort of being a good starting point.

- parts of design docs (like affinity, multiple sched) should be upleveled or at least linked from a canonical scheduling page in the top level docs.

- predicate and priority workflows should be exposed to the user, since after all we expose the rollup of those via kubectl and they are the most common reason that a user fails to get an app running.  

- And of course, since scheduler extensions are a user feature, I guess those should be exposed to in the user docs.

I'm under the assumption that community/devel docs not guaranteed to be maintained for end users and so there needs to be a periodic movement into top level docs once features are hardened.  If not, community/Devel will be the de facto standard for granular docs and that may not be very convenient.

**Comment by jayunit100** [comment]
I guess the only outstanding question is: What should be the canonical reference point for the scheduler docs?
- docs: node-selection (we could rename it)
- devel: `scheduler.md` (we could promote it to the docs repo)
- other candidates

**Comment by jaredbhatti** [comment]
Is this part of a particular release? Is there existing content for it? Have you connected with anyone in the docs team?

**Comment by jayunit100** [comment]
yeah we all do have the goal of 1.6 release doc clean ups. The only real question is how to handle deduplication and sprawl across the many repos that we have now.

After David's earlier feedback, My main suggestion is a canonical source of truth which links out to other sources. Just want to make sure we are on the same page before we start the work to cleanup or consolidate as necessary

**Comment by steveperry-53** [comment]
Adding @chenopis and @devin-donnelly who are working on the structure of the Kubernetes docs.

**Comment by chenopis** [comment]
Yeah, I'm all for a canonical source of truth. Let's see where @devin-donnelly thinks that should be.

**Comment by jayunit100** [comment]
FYI from sig-scheduling meeting, we've all agreed canonical single integration point is the first step.  im pulling the data together now for that.
