### ISSUE TITLE
Tidying for Tasks section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22786]
**This is an umbrella issue**

**What is this needed**
The existing [Tasks](https://kubernetes.io/docs/tasks/) pages have a number of issues:
- some pages offer stale / outdated / incorrect advice
- there are _many_ task categories (17) on the top level list
- deeper in, the number of tasks at other levels makes the task list a little hard to navigate
  For example there are 38 tasks in [Administer a cluster](https://kubernetes.io/docs/tasks/administer-cluster/)
- Other than [Install tools](https://kubernetes.io/docs/tasks/tools/) the section overviews are autogenerated, plain, and unwelcoming.
- The ordering is unintuitive; for a good example see [Configure Pods and Containers](https://kubernetes.io/docs/tasks/configure-pod-container/) as of commit e16b0f7212f819f899e6d5bcee1d4a4d87ad3052.

**Next steps**
Identify problem areas and cleanup work, then log child issues for each of these, that link back to this umbrella issue.

**Comments**
/kind cleanup
/language en

**Comment by kbhawkey** [comment]
👋 @sftim. During the quarterly meeting, I brought up the idea of _investigating_ the `tasks` section.
I did not get around to creating an issue to discuss what needs to be done. Thanks for _starting_ this conversation.
I think this type of change warrants a number of inputs before work is started as well as deciding on whether
any organization is required (or desirable). Some questions I had in mind when I raised this issue:
- How can the docs team better serve our readers
- Do we have the right tasks to learn about the various components of Kubernetes, adminster a Kubernetes cluster, and extend a cluster
- Are there tasks that no longer provide the right information (stale information)
- Is there a better way to categorize the tasks so that readers understand the best pathway to navigate the content
- Do the tasks match the content in the concepts section
- Are the tasks presented in a uniform way so that readers can quickly walk through a task
- Does the content use commonly used setup tools (kubectl, minikube, kind, kubeadm, ...) to demonstrate concepts
- What tasks are missing or could we write new content

I think I envisioned creating a project (such as, https://github.com/kubernetes/website/projects) where we identify what needs to get done, create the work items, and then work together. How does that sound?

**Comment by tengqm** [comment]
> How can the docs team better serve our readers

+2. Do we have some rough profiles of our readers, or do we need to conduct some surveys by ourselves?

> Do we have the right tasks to learn about the various components of Kubernetes, adminster a Kubernetes cluster, and extend a cluster

I don't think I have witnessed any repeated, eager need of some thing from the issues list. 

> Are there tasks that no longer provide the right information (stale information)

We have just removed some tasks related to Federation. I'm not sure if we need to add things like operators, service mesh or vendor-neutral logging/monitoring -- they are 3rd party but they are really common practices across the community.

> Is there a better way to categorize the tasks so that readers understand the best pathway to navigate the content

There have been some proposals about skill tree or knowledge map in the issues list. Not sure how practical is it though.

> Do the tasks match the content in the concepts section

Very unbalanced , :) There are quite some fat concepts pages from which we can produce several tasks.

> Are the tasks presented in a uniform way so that readers can quickly walk through a task

We do have some structure/format guides on this, right? But I'm not very optimistic that we can fit all tasks into the same template.

> Does the content use commonly used setup tools (kubectl, minikube, kind, kubeadm, ...) to demonstrate concepts

I think so. Exceptions are being dropped as 3rd party contents, :)

> What tasks are missing or could we write new content

There are some issues related to this, I believe.

**Comment by sftim** [comment]
> I think I envisioned creating a project (such as, https://github.com/kubernetes/website/projects) where we identify what needs to get done, create the work items, and then work together. How does that sound?

:+1:
