### ISSUE TITLE
Improvement for k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-config/

### ISSUE THREAD

**Issue by ben-turner** [kubernetes/website#22885]
It is very difficult to find any links to the [kubeadm config documentation](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2). This is a huge roadblock to new users trying to do anything custom with kubeadm.

As a new user, I don't expect to have to read about [the setup phases](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-addon) to find information about configuring the tool. To someone who is unfamiliar with the project, that seems like more advanced documentation than I should need, and therefore not somewhere I would expect to find basic config file documentation. I also was able to find the [godoc with config structs](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm) long before I found the more user-friendly documentation, which made it seem like that was the only documentation that exists.

I would expect a link to those docs to be available on the kubeadm-config page, as well as where config files are mentioned in the kubeadm-init and kubeadm-join pages.

**Comment by neolit123** [comment]
@ben-turner it seems you have missed these two sections:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#config-file

and for these commands the kubeadm API is actually the most important for.

linking the `kubeadm-config` command line reference page to the API makes sense.
but instead of linking to a particular version of the API we should link to:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm
and let users navigate to a particular API version. this is done with the idea that `kubeadm config` can also migrate v1beta1 -> v1beta2.

PRs welcome.
thanks

/sig cluster-lifecycle
/priority backlog
/help wanted

**Comment by ben-turner** [comment]
[A related PR in the kubeadm repo](https://github.com/kubernetes/kubeadm/pull/2239). I will keep most of the discussion over there for now.

**Comment by neolit123** [comment]
/remove-help
/assign
/lifecycle-active

sending a PR with:
> linking the kubeadm-config command line reference page to the API makes sense.
