### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by adiezg** [kubernetes/website#23019]
**This is a Bug Report**

**Problem:**
The documentation for kubernetes v1.18 is missing the tabs with the commands to use, when installing a pod network solution (Calico, Cilium, WeaveNet, etc) 
**Proposed Solution:**
Kubernetes 1.17 has the tabs for the different network pod solutions that can be used. Please, see link below:
https://v1-17.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

![missing_tabs](https://user-images.githubusercontent.com/30748315/89667307-34e44000-d8dc-11ea-94ce-28d23d65722a.png)

**Comment by Cweiping** [comment]
After my examination, this is not a problem, it is caused by the change of https://github.com/kubernetes/website/pull/22600.
According to this line of association:
See a list of add-ons that implement the [Kubernetes networking model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model).
/triage support

**Comment by adiezg** [comment]
Thanks Cweiping for the thread #22600. I was not aware of it. 
I have seen some people affected by this change, while doing the exam for CKA, which I plan to take as well in some weeks. I will follow up in thread #22600, hoping that a good solution will be found
