### ISSUE TITLE
Add links (both directions) between main website and https://kubernetes.dev/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23417]
**This is a Feature Request**

**What would you like to be added**
- Alter https://www.kubernetes.dev/docs/guide/non-code-contributions/ to link to pages within https://kubernetes.io/docs/contribute/
- On https://k8s.io/, signpost Kubernetes developers to https://www.kubernetes.dev/docs/guide/

**Why is this needed**
These links help all developers find relevant contribution guides.

**Comments**

/language en
/kind feature

**Comment by celestehorgan** [comment]
@mrbobbytables and I had a chat about this yesterday – I think the idea is to deprecate & remove the current Community page and instead link off to kubernetes.dev?

Some thoughts:
1. Judging by the commit history on the community page, it's mostly LF folks who've made changes in the past year or so. @zacharysarah @idvoretskyi – are there any issues on our side if we remove/replace this page?
2. Personally I'd like to see an external link icon (i.e. [this](https://fontawesome.com/icons/external-link-alt?style=solid)) sit beside this link in the top header and have the link target set to `_blank` , so that we're clear with people that we're linking off-site. This will require a bit of Docsy layout-wrangling, I think?

**Comment by sftim** [comment]
Community is more than contributors: there are also events for Kubernetes users, KubeCon / CloudNativeCon, online discussions, physical meetups†, etc.
I got the impression that https://www.kubernetes.dev/ is just for people doing development on Kubernetes.
Is that difference important?


† consult your physician before scheduling :wink:

**Comment by sftim** [comment]
BTW the Docsy layout wrangling part shouldn't be too difficult, if that's the approach taken.

**Comment by celestehorgan** [comment]
Per discussion in the 9/22 SIG Docs meeting:

- We are going to get rid of the `/community` page and re-home the Events & Meetups content and Code of Conduct content.
- We'll link via the top nav to kubernetes.dev

**Comment by sftim** [comment]
> We'll link via the top nav to kubernetes.dev

Hmm, this might not be as easy as I thought it would be. I'm sure it's feasible though.

**Comment by sandipanpanda** [comment]
@sftim can you please reopen this, if this is still an issue.

**Comment by sftim** [comment]
I think this is done.
