### ISSUE TITLE
k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/ should document the Prometheus metrics

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#23554]
**This is a Bug Report**

**Problem:**
I went looking for documentation of the Prometheus metrics provided by kube-apiserver, and could not find any.

**Proposed Solution:**
Recognize that the reference documentation for a program needs to include more than the command line flags.  The reference documentation should include a definition of each Prometheus metric provided.  And more.

**Page to Update:**
https://k8s.io/docs/reference/command-line-tools-reference/kube-apiserver

current

**Comment by Cweiping** [comment]
As you said, it should be found on [this page](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/), but there is no metric list for other components. I guess there is no list because the metrics index is not easy to maintain.Do we need to maintain this list?

/kind feature
/priority backlog

**Comment by sftim** [comment]
/sig api-machinery
right?
