### ISSUE TITLE
Ubuntu Linux instructions do not work

### ISSUE THREAD

**Issue by rizekmWWT** [kubernetes/website#23654]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by celestehorgan** [comment]
Hi @rizekmWWT,

We need more information to triage this. Could you please tell us where specifically you ran into problems so we can recreate this and attempt to fix it?

Also, I'm going to retitle your issue so that you don't get spam email.

/retitle Ubuntu Linux instructions do not work 
/triage needs-information

**Comment by rizekmWWT** [comment]
Hi Celeste,

https://kubernetes.io/docs/tasks/tools/install-kubectl/    : Ubuntu 18 Linux instructions do not work.   “kubectl cluster-info” returns connection refused.

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/  : all installs fine; however the Dashboard never comes up.



I was able to ad-hoc an installation from various internet resources to install Kubernetes and this works fine so far; however disappointed that I can’t just follow the Official K8s website instructions and make it work.

The Dashboard remains a blocking issue.

Thanks,
Mike

**Comment by sftim** [comment]
@rizekmWWT have these symptoms disappeared now?
