### ISSUE TITLE
Update Korean localization for v1.19

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23774]
**This is a Clean Up Request**

**What would you like to be added**
Update the ~Japanese~ Korean localization for changes since v1.18

**Why is this needed**
The ~Japanese~ Korean documentation is largely based on documentation for older versions of Kubernetes. Ideally, the master-branch documentation would include the changes that were made for the v1.19 release, including [feature gate status](https://kubernetes.io/ko/docs/reference/command-line-tools-reference/feature-gates/) and feature-state details within pages.

**Comments**
Maybe some tooling could help to detect which changes need making, perhaps even to recommend the replacement?
/language ko
/kind cleanup

**Comment by pjhwa** [comment]
@sftim We've done for this. #23533 
This PR will merge to master within this week.

**Comment by sftim** [comment]
Is this OK to close?

**Comment by pjhwa** [comment]
@sftim Yes, close please.

**Comment by seokho-son** [comment]
@sftim Thank you for checking outdated contents in Korean docs! 
(Thank you. quick response ! @pjhwa)

I guess this issue is about Korean l10n not about Japanese l10n. 
(the description of this issue mentions Japanese l10n)

Korean l10n team has updated outdated files for Korean contents (1.18->1.19, PR: #23702)

[FYI] Korean l10n team uses [a script](https://github.com/kubernetes/website/blob/master/scripts/diff_l10n_branches.py) to check outdated contents as follows.
```
python3 scripts/diff_l10n_branches.py ko dev-1.18-ko.10 dev-1.19-ko.1 
```

Also, the Korean work branch (dev-1.19-ko.1) has been merged into master branch. (PR: #23814) Currently, we can check the updates through the Website.

So, I think this issue can be closed. Thank you!
