### ISSUE TITLE
Explain in context the kind of principal making a (persistent) volume claim

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#23902]
On this page: https://kubernetes.io/docs/concepts/storage/persistent-volumes/

> A PersistentVolumeClaim (PVC) is a request for storage by a user. 

It would be very nice if **user** would be a hyperlink to a definition/documentation about what a user is for you in this context.

**Comment by sftim** [comment]
Possible fix: add “user” to the glossary, reference that definition here.

The page could also explain what this means for organizations that separate development and IT operations into separate activities; in those cases, the IT operations team need to ensure that the storage is available for claiming.

Documentation is owned by
/sig storage

**Comment by guettli** [comment]
@sftim thank you for looking at this. There is no progress since some days. How to contact sig/storage?

**Comment by sftim** [comment]
@guettli the vast majority of contributors are volunteers. If you wanted to _pay_ for someone to work on it then there are certainly firms who'll take your money. Otherwise, it's on the backlog of improvements that people could pick up.

/priority backlog
/language en
/kind feature

What I will do is retitle this to try to explain what work is required.
/retitle Explain in context the kind of principal making a (persistent) volume claim
