### ISSUE TITLE
Configure Pod Initialization

### ISSUE THREAD

**Issue by SystemicEmotions** [kubernetes/website#24105]
The very first example for pod with init container is failing, pod goes to Init:CrashLoopBackOff, it supposed to be in Running Status. 
Not sure what has changed !

**Comment by sftim** [comment]
I think you're reporting that you're having trouble following https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/ @SystemicEmotions 

I think that's right, and I can replicate these symptoms. The `busybox` container's `wget` command does not provide TLS certificate verification.

I think that if we amend https://github.com/kubernetes/website/blob/29e13ed527659898c14d0d95acbceea1fcb1ca61/content/en/examples/pods/init-containers.yaml to fetch http://info.cern.ch/ rather than http://kubernetes.io/, then that will fix it.
/triage accepted
/language en
/kind bug
/priority backlog

Thanks @SystemicEmotions

**Comment by sftim** [comment]
/good-first-issue
(if anyone is interested in fixing this, but isn't sure where to start, see https://kubernetes.io/docs/contribute/ or reply with your question here)

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/24529

**Comment by Tej-Singh-Rana** [comment]
Okay, I will replace it with the "http://info.cern.ch/".

Regards,

**Comment by salva-gglez** [comment]
Hello, I would like to start contributing and I was thinking about solving this issue but I would like to know why this issue still open if after replacing the Url with "http://info.cern.ch" sample works again. Is there anything pending?

Thanks

**Comment by sftim** [comment]
This is fixed
/close
