### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/falco/

### ISSUE THREAD

**Issue by walidshaari** [kubernetes/website#24184]
**This is a Bug Report**

**Problem:**
missing from latest documentation for 1.19

**Proposed Solution:**
test and update for latest documenation 

**Page to Update:**
https://v1-17.docs.kubernetes.io/docs/tasks/debug-application-cluster/falco/

1.19 and 1.20

could not find procedure how to update and create a pull request for documentation

**Comment by sftim** [comment]
@walidshaari the page you mention was [removed](https://github.com/kubernetes/website/pull/22313) because it does not fit with the website [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).

You can find documentation for Falco's integration with Kubernetes at https://falco.org/docs/event-sources/kubernetes-audit/.
/close

**Comment by walidshaari** [comment]
thank you @sftim I guess I can add for non k8s software a blog post
