### ISSUE TITLE
Clearly explain impacts of imagePullPolicy

### ISSUE THREAD

**Issue by briandealwis** [kubernetes/website#24782]
**This is a Feature Request**

[_Concepts > Containers > Images_](https://kubernetes.io/docs/concepts/containers/images/#updating-images) would seem to be the canonical location for an explanation of the various permutations of `imagePullPolicy`.  But it is very hard to understand.

I read it 3 times trying to understand the impact of an unspecified `imagePullPolicy` for an image without a tag.

**What would you like to be added**

The explanation on the [_Configuration Best Practices > Container Images_](https://kubernetes.io/docs/concepts/configuration/overview/#container-images) page, which explains the resolution process in a step-by-step manner, is much more clear.

**Why is this needed**

The [Kubernetes API Reference's doc for `imagePullPolicy`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core) directs viewers to this  [_Concepts > Containers > Images_](https://kubernetes.io/docs/concepts/containers/images/#updating-images) page.

**Comment by sftim** [comment]
/language en
/triage accepted

Yep - it needs work!

**Comment by sftim** [comment]
I would migrate content from https://kubernetes.io/docs/concepts/configuration/overview/#container-images to https://kubernetes.io/docs/concepts/containers/images/#updating-images

This is because “configuration” is a very general topic - configuring nodes, configuring your cluster, configuring networks, configuring image pull policies, configuring TLS&mdash;I could go on.

In the tasks section it makes sense perhaps to let readers find tasks grouped under a heading of “configuration”; for concepts I don't think it does.
