### ISSUE TITLE
Kubernetes core API concepts could be described more clearly and consistent

### ISSUE THREAD

**Issue by lfrancke** [kubernetes/website#24882]
We've been digging in to the K8S code and documentation to get clarification on the exact definition of these concepts:

* Group
* Version
* Namespace
* Kind
* Resource Type
* Resource
* (API) Object
* resourceVersion

There are a few documentation pages covering this:
* [1] https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#kubernetes-objects
* [2] https://kubernetes.io/docs/reference/using-api/api-concepts/#standard-api-terminology
* [3] https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#custom-resources
* [4] https://kubernetes.io/docs/reference/kubectl/overview/#resource-types
* [5] https://book.kubebuilder.io/cronjob-tutorial/gvks.html

But they seem to be using slightly different terminology for the same thing. And if they are not then the distinction is not made clear.

The most problematic ones are *resource*, *resource type* and *object*.

[1] "Kubernetes objects are persistent entities in the Kubernetes system."
[2] calls a resource "a single instance of the resource type".
[3] says "A resource is an endpoint in the Kubernetes API that stores a collection of API objects of a certain kind; for example, the built-in pods resource contains a collection of Pod objects."
[5] "A resource is simply a use of a Kind in the API."

These are all slightly different to me and contradict each other.

The exact definitions of Group and Version are also not quite clear (I can go into detail as to why I believe so).
It'd be great to keep the usage of all these terms consistent across the documentation. But as that's a hard task it'd be good to at least define them clearly in one single place, like an ontology of Kubernetes concepts.

**Comment by MadhavJivrajani** [comment]
Hi @lfrancke 👋🏻 thank you for raising this issue

The relevant discussion for this can be found [here](https://kubernetes.slack.com/archives/C5P3FE08M/p1625351774115600?thread_ts=1625351774.115600&cid=C5P3FE08M).

As @sftim suggested, this issue can be used as a tracking issue to discuss and help carve out tasks that can document these concepts in an authoritative manner. 

> an ontology of Kubernetes concepts.

As mentioned in the slack thread, this can be done either in k8s.dev or https://kubernetes.io/docs/reference/using-api/api-concepts/#standard-api-terminology. 

My thoughts on documenting these concepts -- it might be better to go top-down rather than bottom up with explanations, meaning that starting with explaining on an abstract level what the API achieves followed by how it achieves it. Therefore, before the documentation of these concepts start, it might be helpful to have a few lines on Kubernetes following a declarative  model of doing this and what that means "user describes their desired state to Kubernetes, and Kubernetes tries to drive the system towards that desired state" (docs has a section on controller pattern which can be linked along with the original architecture design docs). Doing so is important mainly because this would set the context for API objects, which would set the tone for API kind, resource type, resource, group, and also to some extent help with explaining `resourceVersion`.

I can get started trying to break things down into well-defined sub-tasks that folks can work on after we reach consensus on:
- Where do we put this? Does it reside in k8s.dev along with a. summary in the official docs or should it be made available in the official docs in full detail 
- Whether the approach mentioned above is fair and acceptable

**Comment by lfrancke** [comment]
Thank you for the update.
I'm happy to provide input as an end-user (kinda) on any PRs to see if it helps me understand.
