### ISSUE TITLE
submodule google/docsy need to update

### ISSUE THREAD

**Issue by zhaojizhuang** [kubernetes/website#25114]
**This is a Bug Report**

**Problem:**

Submodule `google/docsy` need to update，current version lack of i18n translation for `Create child page`

Upgrade of `google/docsy` can solve this problem, see it in https://github.com/google/docsy/tree/master/i18n

![image](https://user-images.githubusercontent.com/3124692/99692063-d3c82d00-2ac4-11eb-99c4-a0c8f0e24304.png)

**Comment by sftim** [comment]
/kind bug
/triage accepted
/priority backlog
/good-first-issue

This issue is a good first issue because the single step needed to fix it is to update the version of the [Docsy](https://www.docsy.dev/) submodule.
[`git submodule`](https://git-scm.com/docs/git-submodule) has some contextual information; the command to use is `git submodule update`.

**Comment by sftim** [comment]
:information_source: Note that PR #25116 is already open to address this.
