### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by smartin1296** [kubernetes/website#25174]
When I was executing the following code: -- [source](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports)

$sudo apt-get update && sudo apt-get install -y apt-transport-https curl
$curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
$cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
$sudo apt-get update
$sudo apt-get install -y kubelet kubeadm kubectl
$sudo apt-mark hold kubelet kubeadm kubectl`

I had two errors. **FIRST** at line 6:

`sudo apt-get update`

Hit:2 https://download.docker.com/linux/ubuntu focal InRelease  
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal InRelease      
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Get:1 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main arm64 Packages
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main arm64 Packages
Ign:7 https://packages.cloud.google.com/apt kubernetes-xenial/main arm64 Packages
Err:7 https://packages.cloud.google.com/apt kubernetes-xenial/main arm64 Packages
  404  Not Found [IP: 172.217.2.78 443]
Fetched 8993 B in 2s (3741 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-arm64/by-hash/SHA256/061c4f3069d5516796bdc315f0330fccfbda70f67f7fd9b052b6fd0ccf570e32  404  Not Found [IP: 172.217.2.78 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**SECOND** at line 7:

`sudo apt-get install -y kubelet kubeadm kubectl`

E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl
E: No packages found

I was able to resolve this by upgrading to root at line 2:

`sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -`

instead of:

`curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -`

**Comment by smartin1296** [comment]
For additional clarity:

The above errors occurred on machine 2 of 4. I used the "sudo" change I mention on machine 3 and downloaded all three packages - kubelet kubeadm kubectl - without any problems. On machine 4, the error occured even with the sudo change. Still looking for a solution for my last node, all help is welcome 8-)

**Comment by smartin1296** [comment]
I resolved the issue this time by changing the order of execution of lines. Most important was executing my sudo change above:

`sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -`

prior to:

`sudo apt-get update && sudo apt-get install -y apt-transport-https curl`

I am still unsure why this worked / why the computers acted differently considering they are identical images. Hope this helps someone else!

**Comment by sftim** [comment]
@smartin1296 the docs mostly assume that when you encounter an error you fix or address that error before continuing

I think that's a reasonable approach and the existing documentation is fine.

**Comment by nickborges** [comment]
Try it

`echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main/binary-arm64" | sudo tee /etc/apt/sources.list.d/kubernetes.list`

and than, run again!!

Note: The path of repository change, https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-arm64. Just put on **main/binary-arm64**

**Comment by emmanuel-sonalake** [comment]
I'm trying to download the google cloud signing key but I'm using an AMI machine AWS . I can only find the command for Linux Machine but how can this be downloaded with yum?: 
`sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/a-key.gpg`

**Comment by camilamacedo86** [comment]
Hi @smartin1296, 

> sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
We should no longer use apt-key it is deprecated and has security concerns. 

[1] - https://sites.google.com/site/installationubuntu/home/ubuntu-22-04/apt-key-is-deprecated?pli=1
[2] - https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key

I am facing the same errors trying to install in unbutu:22.04

```
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
Reading package lists...
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
```

I do not know why it is closed since the instructions are not fixed in the website. Could we re-open this one?

**Comment by emmanuel-sonalake** [comment]
I fixed the issue

**Comment by mhmdunl1** [comment]
> I fixed the issue

How ?

**Comment by emmanuel-sonalake** [comment]
You need to create a script since you're running a Linux AMI machine.

`cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=[https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch](https://packages.cloud.google.com/yum/repos/kubernetes-el7-%5C$basearch)
enabled=1
gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF
# Set SELinux in permissive mode (effectively disabling it)sudo setenforce 0sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/'/etc/selinux/config
sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
sudo systemctl enable--now kubelet`

Save the script and use the command below to make the script executable 

`sudo chmod +x kubeadm-install.sh`

Afterwards run the script to install kubeadm -->   `./kubeadm-install.sh`

**Comment by sftim** [comment]
I'm going to lock this conversation. https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ has changed quite a bit since this issue was filed.
