### ISSUE TITLE
Article Pods translate to russian

### ISSUE THREAD

**Issue by mshalmanov** [kubernetes/website#25531]
Hello.
When will be russian translate this article and how  i can help to translate this article ?

**Comment by tengqm** [comment]
@mshalmanov You may want to join the https://kubernetes.slack.com/archives/CPZ9KD9TN Slack channel and see if you can make some friends there and collaborate on Russian localization. For high-level guidelines on localization, please see https://kubernetes.io/docs/contribute/localization/. Otherwise, you can jump on to the subject and start getting your hands dirty, sign the CLA and submit a PR for your translation.
