### ISSUE TITLE
Confusing advice in “Configuring Redis using a ConfigMap”

### ISSUE THREAD

**Issue by MorrieAtElastic** [kubernetes/website#25638]
See https://stackoverflow.com/questions/56818074/get-error-json-unknown-field-metadata-error-when-i-follow-tutorial-of-kub. 

This is still a problem and there remains confusion as to how to build the initial Redis cache in this example.

**Comment by sftim** [comment]
Sounds like a bug. Anyone able to confirm and accept this issue?

**Comment by sftim** [comment]
/retitle Confusing advice in “Configuring Redis using a ConfigMap”

**Comment by sftim** [comment]
I don't think it's a _bug_ as such.

Overall, the existing page is confusing because it shows the contents of files that the reader needs to download _before_ then showing them a command to download it (but without really explaining what is happening).

I'm not sure that this guide is really explaining ConfigMaps; it's confusing matters by also introducing kustomization. I recommend rewriting the example to:
1. not use `kubectl -k`
2. have the reader amend the ConfigMap after first creating it, and show what happens after the ConfigMap is changed.
    - does that immediately take effect, or only after recreating the Pod?
3. _Maybe_ make a single-instance StatefulSet rather than a Pod.

/kind cleanup
/priority backlog
/language en
/help

**Comment by jai** [comment]
🙋🏽‍♂️ I'm going to give this a go

**Comment by jai** [comment]
@sftim let me know your thoughts https://github.com/kubernetes/website/pull/25712

I tried to follow the style guide in terms of separating commands and output - it leads to a bit of verbosity in some areas, especially the part where we walk the reader through checking the Redis config, but it's not that bad I guess. The previous version combined commands/output - I'm not sure if this style guide rule is definitive or is applied on a case-by-case basis?
