### ISSUE TITLE
Chinese Docs--which branch 

### ISSUE THREAD

**Issue by Mac24** [kubernetes/website#25671]
**This is Support**

I want to do docs Chinese localization work, I don’t know which branch I should choose to start working

**Comment by tengqm** [comment]
Hi, @Mac24, welcome to the zoo. Please raise similar questions on Slack channel #sig-docs.
For Chinese localization, we work on the master branch. You may want to check the localization guide (https://kubernetes.io/zh/docs/contribute/) for overall guidelines, and the Chinese specific styles (https://kubernetes.io/zh/docs/contribute/localization_zh/).

Since this is a doc issue, I'm gonna close it.
/close
