### ISSUE TITLE
Translate concepts/scheduling-eviction/scheduling-framework in Korean

### ISSUE THREAD

**Issue by djatkdgus789** [kubernetes/website#25673]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/scheduling-eviction/scheduling-framework in Korean

**Why is this needed**
No Translation with concepts/scheduling-eviction/scheduling-framework in Korean

**Comments**

Page to Update: 
https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/

**Comment by seokho-son** [comment]
@djatkdgus789 Hello ! Thank you for contribution !

I noticed that there is a duplicated issue (#20328))
However, since #20328 seems not resolved, I would like to check the status of #20328 before assign this issue to you. 
(If we don't check, duplicated contributions :) )

So, unassign for this moment.
/unassign @djatkdgus789 

Hello ~~ @ysyukr . Cloud you let us know the status of #20328 ?

**Comment by djatkdgus789** [comment]
@seokho-son Hello! Thank you for your comment!

I will keep track of this issue :-)

Thank you~

**Comment by ysyukr** [comment]
hello,
In the case of #20328 , I have not been able to proceed with this, so someone else can proceed.

**Comment by seokho-son** [comment]
Current Korean localization dev branch is `dev-1.20-ko.2`
#25910

**Comment by djatkdgus789** [comment]
Hi,
Thanks for mail.
I will not able to contribute due to personal circumstance. Please release
the task assigned to me. If there is a chance, I will participate again.

Thank you. 감사합니다. :)

= Sanghyeon, Eum =

2021년 10월 21일 (목) 오전 10:16, Seokho Son ***@***.***>님이 작성:

**Comment by seokho-son** [comment]
@djatkdgus789 Thank you ! please feel free to re-initiate contribution :)
