### ISSUE TITLE
Configure a Pod to Use a Volume for Storage

### ISSUE THREAD

**Issue by ocmvin** [kubernetes/website#26127]
Step #6 In your shell, kill the Redis process: is not so clearly mentioned for how to get process id especially using minikube installed on windows 
ps -ef | grep redis doesnt show up process id 
Page location 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/

**Comment by sftim** [comment]
/kind support
/language en

@ocmvin I suspect that you have missed out a detail from steps 1 to 5. If you're sure that you followed each step correctly, please paste in the output from the stage where you used `apt-get` to install procps and from the subsequent command to list processes inside the container. The PID of redis is `1` (as per the sample output), by the way.

**However:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/ does not follow the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/) for commands the reader should type.

Rather than including the prompt, I recommend including a comment in each block that the reader should run inside the Redis container, eg `# Run this in the shell inside the redis container that you opened earlier`

I'd be happy to see that cleaned up to avoid confusion. If we shift the focus of this issue to that cleanup, I would recommend (to Kubernetes org members): /remove-kind support
and: /kind cleanup
