### ISSUE TITLE
Manual Rotation of CA Certificates

### ISSUE THREAD

**Issue by andy-ning** [kubernetes/website#26188]
In step 3, it says "If any pods are started before new CA is used by API servers, they will get this update and trust both old and new CAs." and in step 4 it says "Restart all pods using in-cluster configs (ex: kube-proxy, coredns, etc) so they can use the updated certificate authority data from ServiceAccount secrets."

1. The existing pods before new CA is used by API servers will get this update, why we need to restart all pods in step 4?
2. What's exactly "pods using in-cluster configs"? What's "in-cluster configs"?

**Comment by sftim** [comment]
/sig auth

I think this is half support (ie, /kind support), half defect.
We could clarify “in-cluster configs”: does this mean “add-on pods that rely on service account tokens”? I'm not sure myself.

@kubernetes/sig-auth-misc would you be willing to triage this issue?

**Comment by sftim** [comment]
/language en
BTW the page is https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

**Comment by liggitt** [comment]
> 3. Update all service account tokens to include both old and new CA certificates.

this step is not needed... the controller-manager (updated and restarted in step 2 - `Update kube-controller-manager's --root-ca-file to include both old and new CA. Then restart the component.`) will update the CA in existing token secrets on its own

> What's exactly "pods using in-cluster configs"? What's "in-cluster configs"?
> ...
> We could clarify “in-cluster configs”: does this mean “add-on pods that rely on service account tokens”? I'm not sure myself.

Yes, pods using injected service account tokens and CAs. There is no way to tell from the API which pods these are :-/

**Comment by Swetad90** [comment]
I was referring to the same doc & have the below questions. Could someone clarify them for me?

Point 8,2: `If your kubelet is not using client certificate rotation update client-certificate-data and client-key-data in kubelet.conf on all nodes along with the kubelet client certificate file usually found in /var/lib/kubelet/pki.` 
 Q1 - When it says update, does it mean use certificate signed by new CA? If yes, then restarting the kubelet will fail because apiserver has not yet had the ca-bundle yet. It happens in step 8.3. Point 5 just says to have the bundle at the right location, restart doesn't take place untill point 8.3.
 Q2 - The certs under /var/lib/kubelet/pki comes into picture, when the rotatecertificate is turned on. Why do we have to update the certs both in kubelet.conf and under /var/lib/kubelet/pki ?

 Point 11,3: `Restart kubelet by removing the old CA from file against the clientCAFile flag and kubelet kubeconfig file.`
 Q1 - If the rotateCertificate in kubelet is turned on, at which step would kubelet regenerate the client certificates signed by new CA? Step 8.2 says to update the client certs only when auto-rotate is turned off.

**Comment by Swetad90** [comment]
At this point, I'm almost sure that the kubelets don't use the client certs in kubelet.conf but rather the ones under /var/lib/kubelet/pki. The conf file is only used for the CA validation. The client certs embedded should be this bug - https://github.com/kubernetes/kubeadm/issues/1753 . And this should answer my point 3 above.
