### ISSUE TITLE
tab list component should use the cached bootstrap-4.3.1.min.js

### ISSUE THREAD

**Issue by qianyong-2005** [kubernetes/website#26286]
It‘s Content have no change  from following link:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-0
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-1
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-2

**Comment by neolit123** [comment]
hi, can you better explain the problem and re-open the issue after that?
thanks

/sig docs cluster-lifecycle
/priority awaiting-more-evidence
/close

**Comment by tengqm** [comment]
After some testing and guessing, I think the problem is that the fancy tab list on the install-kubeadm page doesn't work for people from China. The reason behind that is the "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" is not loaded by the browser. The damn firewall blocked the site used for serving bootstrap JS module.

Back to the website, I can see the script reference comes from `themes/docsy/layouts/partials/scripts.html`, which can be overridden. Maybe we should do that because we already have one cached (`static/js/bootstrap-4.3.1.min.js`) which is a newer version.

**Comment by neolit123** [comment]
> Back to the website, I can see the script reference comes from themes/docsy/layouts/partials/scripts.html, which can be overridden. Maybe we should do that because we already have one cached (static/js/bootstrap-4.3.1.min.js) which is a newer version.

this seems like a good idea.

/reopen
/retitle tab list component should use the cached bootstrap-4.3.1.min.js

**Comment by qianyong-2005** [comment]
> After some testing and guessing, I think the problem is that the fancy tab list on the install-kubeadm page doesn't work for people from China. The reason behind that is the "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" is not loaded by the browser. The damn firewall blocked the site used for serving bootstrap JS module.
> 
> Back to the website, I can see the script reference comes from `themes/docsy/layouts/partials/scripts.html`, which can be overridden. Maybe we should do that because we already have one cached (`static/js/bootstrap-4.3.1.min.js`) which is a newer version.

Yes, I cann't open this link(https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js) from china.  even through vpn.

**Comment by qianyong-2005** [comment]
> hi, can you better explain the problem and re-open the issue after that?
> thanks
> 
> /sig docs cluster-lifecycle
> /priority awaiting-more-evidence
> /close

The problem is that switching tab page from ubuntu16.04 to ubuntu 18.04/20.04 content no change.  access this 
 link https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js  failed.
