### ISSUE TITLE
pause image upgraded to 3.5 in kubelet and kubeadm for both Linux and Windows

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#26335]
Just wanted to note that when this lands, this changes the owner and location of the Windows default pause image from MS to Kubernetes, and [the docs](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#pause-image) will need to be updated to reflect that.

I noticed this PR because the current MS-supplied pause image does not have a 20H2 build yet, and was trying to work out who owned it to request a new build, but I guess the k8s pause image will make that obsolete soon enough anyway, and I assume I can override `--pod-infra-container-image` in the meantime to point to the multiplatform pause 3.4.1 image in the meantime.

_Originally posted by @TBBle in https://github.com/kubernetes/kubernetes/issues/98205#issuecomment-770322724_

**Comment by pacoxu** [comment]
As https://github.com/kubernetes/kubernetes/pull/100292 is updating it to  3.5, I changed the title.

**Comment by pacoxu** [comment]
Still some users are not know this: https://github.com/kubernetes/kubernetes/issues/100708#issuecomment-818027455

**Comment by neolit123** [comment]
/sig docs
for advice on where on k/website it would be best to document the pause image what and it contains.

**Comment by TBBle** [comment]
At least for Windows Support, the ["Pause Image" on the Windows support page](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#pause-image) seems like a good place to document what it is. I hope that once that is updated to indicate that the pause image is k8s.gcr.io/pause:3.5 and is maintained as part of Kubernetes, that will help reduce confusions like that which resulted in https://github.com/kubernetes/kubernetes/issues/100708#issuecomment-818027455.

**Comment by TBBle** [comment]
![image](https://user-images.githubusercontent.com/138397/126480140-0748eac6-f56b-437e-802f-30247be98906.png)

[That](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#pause-image) looks reasonable to me, so perhaps we can close this now, since the docs refer to `k8s.gcr.io/pause:3.5` for use on both Linux and Windows.

That said, it [looks like](https://mcr.microsoft.com/v2/oss/kubernetes/pause/tags/list) `mcr.microsoft.com/oss/kubernetes/pause:3.5` also exists, and is multi-platform, as were the 3.4 and 3.4.1 tags. Unlike `k8s.gcr.io/pause:3.5` it is not multi-arch (only amd64), so `k8s.gcr.io/pause:3.5` covers a superset of supported hosts.

So it might be worth working out if the MCR-hosted pause image is diverged from the GCR-hosted pause image in any particular way, or was just built for fewer targets, and either way, the page could be updated to refer to `mcr.microsoft.com/oss/kubernetes/pause:3.5`.

I'd also probably list MCR second, since I assume the intention is that GCR-hosted image becomes the primary one, unless a specific use-case for the MCR-hosted image is known that means it should be preferred in some circumstances.

**Comment by TBBle** [comment]
I suspect k8s-ci-robot doesn't honour commands in edits. ^_^

/close
