### ISSUE TITLE
ko: translate Dockershim Deprecation FAQ into Korean

### ISSUE THREAD

**Issue by Brian-Kwon** [kubernetes/website#26377]
I'd like to translate below into Korean to spread about dockershim deprecation via FAQ
https://kubernetes.io/blog/2020/12/02/dockershim-faq/

A couple of members in sig-doc-ko has translate a page related to docker panic theme.
FAQ page is more technical to-do behaviours for this community

These are the draft version of Korean page
I hope this will be available for next release (dev-ko-1.20.4)

**Comment by Brian-Kwon** [comment]
@seokho-son @pjhwa
FYI~ Please let me know what I have to do before starting translation about dockershim deprecation FAQ
Thanks for your support.

**Comment by seokho-son** [comment]
@Brian-Kwon Thank you for the suggestion !!

Since there is no duplicated issue regarding the suggested document, it looks good to go. :)
(you can check Korean issues by filtering issues: https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Alanguage%2Fko)

I have minor comment regarding ISSUE template (style) for suggesting new Korean translation. 
Please check a general style of ISSUE from previous ISSUEs (such as https://github.com/kubernetes/website/issues/24980)

/triage accepted
/assign @Brian-Kwon
