### ISSUE TITLE
compute-device-assignment.md is not found 

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/website#26382]
**This is a Bug Report**

**Proposed Solution:**
[Support Device Monitoring](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/compute-device-assignment.md) in this page is linked to a dead url. 
**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by sftim** [comment]
/kind bug
/sig node
/language en
/triage accepted

Rather than linking to a KEP, we should really add a new page to the documentation (maybe in Concepts, maybe in Reference) and then link to that.

**Comment by ydFu** [comment]
@sftim @MartinForReal 
The fail link in Support Device Monitoring due to [this page changed](https://github.com/kubernetes/enhancements/commit/7b3fdb6ed9d3f6fa95989ab9fe2ee5c25b6857ab#diff-3328a21626dec544a559603b80e0df6be4fb0bdeec9a9dfaaa235870d48c052a).
This root cause in the kind/bug is the repo of kubernetes/enhancements url that move `keps/sig-node/compute-device-assignment.md` to `keps/sig-node/606-compute-device-assignment/README.md` .
I had a look at it and sent in a pull request for fix this.(PR #26412)

/assign
