### ISSUE TITLE
Mention PDB updates in PodDisruptionBudget task page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26385]
**This is a Feature Request**

**What would you like to be added**
~https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets mentions PodDisruptionBudget.~

~Verify that this documentation is:~
~- current~
~- correct~
~- relevant~

~Also check whether https://kubernetes.io/docs/tasks/run-application/configure-pdb/ should have any changes in light of improvements such as: https://github.com/kubernetes/kubernetes/pull/69867~

Revise https://kubernetes.io/docs/tasks/run-application/configure-pdb/ to mentioning how you can update a PodDisruptionBudget.

Add a section headed eg *Update PDB* that gives an example of how you can update the configuration of an existing PDB using `kubectl`.

**Why is this needed**
PodDisruptionBudget is slated to go GA in v1.21 and PDBs are no longer immutable.

**Comments**
/language en
/sig apps

**Comment by kbhawkey** [comment]
Is this issue related to issue https://github.com/kubernetes/website/issues/22391?

**Comment by sftim** [comment]
Both issues are about the same web page. _This_ issue is about making sure the docs are ready for the PodDisruptionBudget API to graduate to stable.

**Comment by kbhawkey** [comment]
OK. Possibly address both issues in one PR.
/triage accepted

**Comment by sladyn98** [comment]
@sftim  In light of these changes https://github.com/kubernetes/kubernetes/pull/69867 it would be great to add a section to this https://kubernetes.io/docs/tasks/run-application/configure-pdb/ like `Update PDB` and then give an example of how one can update the configuration and then hit `kubectl apply` which would now apply since the immutability aspect has been removed.Apart from that it looks current :+1:

Furthermore https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets looks good since the configuration aspect is not mentioned anywhere in this doc that PR does not affect it. It looks to be current

**Comment by sftim** [comment]
> https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets &hellip; looks to be current

Thanks, that's useful to know.

> [adding a section to https://kubernetes.io/docs/tasks/run-application/configure-pdb/]

That sounds like a good idea. Thanks.

**Comment by sftim** [comment]
/retitle Mention PDB updates in PodDisruptionBudget task page

**Comment by sladyn98** [comment]
I can probably add this

**Comment by sftim** [comment]
Cool, thanks @sladyn98!

**Comment by sftim** [comment]
Relevant to #27053

**Comment by sladyn98** [comment]
@sftim https://github.com/kubernetes/website/pull/16738 Looks like this PR already added the update section, however it was added under the heading `Create PDB Object` which kind of cause me to miss it. So it looks good overall.
