### ISSUE TITLE
[META] Documentation Locale PT-BR

### ISSUE THREAD

**Issue by bryanasdev000** [kubernetes/website#26622]
As discussed in the Brazilian Kubernetes community on the Telegram, the idea is to translate the documentation into Brazilian Portuguese.  For this I created this issue with the main objective of mapping what needs to be done, subsequently creating the issues for each section with their proper PR.

**Comment by rikatz** [comment]
/assign
/triage accepted

I'll tackle this with the group, to improve the portuguese translation coverage and other parts. 

We will sync during this week to define this umbrella issue approach and also how to sync the section translations and assignees.

**Comment by bryanasdev000** [comment]
I already did a simple diff between `content/en` and `content/pt` with `vimdiff <(cd pt; find . | sort) <(cd en; find . | sort)` and saving it to HTML, it's available here https://gist.github.com/bryanasdev000/086c9768f45f2e18f615fdb0588448f2 .

**Comment by sftim** [comment]
BTW, I wouldn't worry about localizing the blog. That's something we'd only really suggest if a localization team feels like they are running out of other things to cover. Maybe for really notable posts like the discussion about Dockership.

**Comment by bryanasdev000** [comment]
> BTW, I wouldn't worry about localizing the blog. That's something we'd only really suggest if a localization team feels like they are running out of other things to cover. Maybe for really notable posts like the discussion about Dockershim.

I agree, but as you said about Docker, I believe there are some that are worth it, even for historical reasons. But these can be of low priority.

**Comment by rikatz** [comment]
So my approach to this would be:

1) We need to map the docs that already exists, but needs some attention / evolution (got deprecated over time). Like, do we still recommend somewhere extensions/v1beta1? Can we make the tutorials better?
2) We need to map the pages that does not exists (@bryanasdev000 did this!) and organize them per section. This would turn things easier for folks willing to contribute, to self assign a specific section or bunch of pages to translate and not generate conflict with someone already translating other parts
3) I think it would be good to this group, specifically, to have some sort of 'reconciler' that checks the last commits of content/en over time, and generate an alert to us in some telegram group or here, so someone can take a look and say 'ok, this commit is only a nit correction' or 'wow, we need to get some attention into this because is something new', like the warning mechanism inserted in v1.20
4) We can, overtime, localize the blog posts and case studies, keeping the reference to the original author and adding the person who take the effort to translate. 

I don't know if is there some special label that says 'this docs is about a new feature' or we could use kind/feature and kind/bug for those, so we can somehow ignore kind/cleanup but pay attention to those in an 'automatic' way. 

@kubernetes/sig-docs-leads I would really like to have some opinion of you here folks, as there's some past experience in translating and maintaining the localization of docs

**Comment by bryanasdev000** [comment]
> So my approach to this would be:
> 
> 1. We need to map the docs that already exists, but needs some attention / evolution (got deprecated over time). Like, do we still recommend somewhere extensions/v1beta1? Can we make the tutorials better?
> 2. We need to map the pages that does not exists (@bryanasdev000 did this!) and organize them per section. This would turn things easier for folks willing to contribute, to self assign a specific section or bunch of pages to translate and not generate conflict with someone already translating other parts
> 3. I think it would be good to this group, specifically, to have some sort of 'reconciler' that checks the last commits of content/en over time, and generate an alert to us in some telegram group or here, so someone can take a look and say 'ok, this commit is only a nit correction' or 'wow, we need to get some attention into this because is something new', like the warning mechanism inserted in v1.20
> 4. We can, overtime, localize the blog posts and case studies, keeping the reference to the original author and adding the person who take the effort to translate.
> 
> I don't know if is there some special label that says 'this docs is about a new feature' or we could use kind/feature and kind/bug for those, so we can somehow ignore kind/cleanup but pay attention to those in an 'automatic' way.
> 
> @kubernetes/sig-docs-leads I would really like to have some opinion of you here folks, as there's some past experience in translating and maintaining the localization of docs

Your first point is very relevant and enters my question, are we going to update / refine existing documentation too?

**Comment by jailton** [comment]
Hi! 

There is an open issue to tracking the translation into Portuguese:  #13939.

**Comment by sftim** [comment]
I'd be happy to: /triage duplicate
on this.

**Comment by sftim** [comment]
Thanks for mentioning it @jailton 

(if we want to track different localizations for _two kinds_ of Portuguese, I suspect that first we should check about how SIG Docs wants that implementation to look in general).

**Comment by rikatz** [comment]
yes me too :D I didn't checked if this was duplicated, oops :)
/triage duplicate
/close 
Let's follow on #13939
