### ISSUE TITLE
Modify Korean translation for configuration/secret.md

### ISSUE THREAD

**Issue by yimcd** [kubernetes/website#26815]
In Korean version,
https://kubernetes.io/ko/docs/concepts/configuration/secret/#tls-%EC%8B%9C%ED%81%AC%EB%A6%BF

Last sentence of this section is:
두 가지 방식 모두에 대해서, PEM의 시작과 끝 라인(예를 들면, 인증서의 --------BEGIN CERTIFICATE----- 및 -------END CERTIFICATE----) 은 포함되면 안 된다.

Original:
 In both cases, the initial and the last lines from PEM (for example, --------BEGIN CERTIFICATE----- and -------END CERTIFICATE---- for a cetificate) are not included.
 
"포함되면 안 된다." means like "you should not include (since it isn't validate one for secret)". So I think it makes confusing. I think it should change to "포함되지 않는다". Because k8s only store tls value other than "---BEGIN CERTIFICATE---" and "---END CERTIFICATE---"

**Comment by sftim** [comment]
/language ko

The original text is:
> The public key certificate for --cert must be .PEM encoded (Base64-encoded DER format), and match the given private key for --key. The private key must be in what is commonly called PEM private key format, unencrypted. In both cases, the initial and the last lines from PEM (for example, `--------BEGIN CERTIFICATE-----` and `-------END CERTIFICATE----` for a cetificate) are not included.

NB “cetificate” is a typo in the original.

Just for reference: the format of _these_ Secret fields is DER, _not_ PEM. The base64 encoding is done by Kubernetes itself so the data are DER. However there is a clear link to PEM because the particular kind of DER document is exactly what's used in PEM (for certificates). There is a _de facto_ convention for representing private keys which is often called PEM, even though that's not actually standardized. The private key in a `tls` secret is the same as taking a PEM private key and decoding it to DER.

**Comment by seokho-son** [comment]
/retitle Modify Korean translation for configuration/secret.md

**Comment by seokho-son** [comment]
/triage accepted

Hello @yimcd , thank you for the suggestion!
I agree with you :)

Do you want to contribute to resolve this issue? then, I will assign you to this issue.

**Comment by yimcd** [comment]
Sure, it would be my pleasure.

**Comment by seokho-son** [comment]
FYI: https://github.com/kubernetes/website/issues/26907
