### ISSUE TITLE
Issue with k8s.io/es/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by WHK102** [kubernetes/website#27048]
When `kubectl cluster-info` show the error `The connection to the server <server-name:port> was refused - did you specify the right host or port?`, the command `kubectl cluster-info dump` says same error. The second option is not a valid option when have this error message.

**Comment by sftim** [comment]
/language es

@whk102 I'm not sure I understood whether you are reporting a defect in kubectl, reporting a defect in the Spanish documentation for Kubernetes, or asking for advice on how to configure cluster access. Could you reply with more detail so that it is really clear how to take this issue forward?

Related: at some point we should update https://k8s.io/es/docs/tasks/tools/install-kubectl/ to match https://k8s.io/docs/tasks/tools/#kubectl

**Comment by raelga** [comment]
@sftim Issue create to update `kubectl` at https://github.com/kubernetes/website/issues/27078

**Comment by raelga** [comment]
@WHK102 The issue described looks more like a problem with your current `kubectl / kubeconfig` setup than a problem with the documentation.

Feel free to comment the issue slack channels at https://kubernetes.slack.com/archives/C09NXKJKA (English), https://kubernetes.slack.com/archives/C4UQB8SBS (Spanish) or just ping me on slack at `rael`.

/assign

**Comment by raelga** [comment]
@WHK102 the issue is going to be closed due to inactivity. Feel free to reopen it if necessary.

/close
