### ISSUE TITLE
Missing details on "Managing Resources - Canary Deployments"

### ISSUE THREAD

**Issue by mjbright** [kubernetes/website#27150]
In the Canary Deployments section it is described how a "track" label could be used to differentiate between "stable" and "canary" versions of a deployment.

A new kubernetes user might imagine that this is sufficient to manage Canary Deployments.

At a minimum it should be explained that such a label convention would need to be taken into account by some external system actually implementing the canary, e.g. a CI/CD system controlling an API-gateway, or a Service Mesh.

**Comment by sftim** [comment]
I think this issue is about https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#canary-deployments

**Comment by sftim** [comment]
> such a label convention would need to be taken into account by some external system actually implementing the canary

Kubernetes has a built-in resource, [Service](https://kubernetes.io/docs/concepts/services-networking/service/) that can send traffic based on selectors as explained here. [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) is another built-in API that would work for this case provided you used a suitable ingress controller.

I don't think this issue is correct. Maybe the page could explain more about setting up the Service and its selector though.

**Comment by sftim** [comment]
If you want to automate canary deployments, that's a different story. We might also want to explain the difference between _continuous_ deployment (as explained in https://continuousdelivery.com/) and _automated_ deployment.

**Comment by sftim** [comment]
/remove-lifecycle rotten
We should triage this properly. @mjbright can you clarify the feedback you wanted to report?
