### ISSUE TITLE
TaintNodesByCondition incorrectly marked as beta (?)

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#27204]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#taintnodesbycondition mentions that the admission controller is beta; however the related feature gate is now GA.

**Proposed Solution:**
Verify the feature status of the TaintNodeByCondition feature _for the admission controller specifically_. If 
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#taintnodesbycondition is in fact stable, update the page.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#taintnodesbycondition

**Additional Information:**
/sig node
/language en

**Comment by sftim** [comment]
@kubernetes/sig-node-bugs could you confirm whether that admission controller is still beta?

**Comment by jai** [comment]
@sftim is this just a matter of getting a "yes" from someone on SIG Node to confirm that `TaintNodesByCondition` is GA? It seems to be as you mentioned, since 1.17 (https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) but let me know if we need explicit confirmation and I'll chase it down.

**Comment by jai** [comment]
Confirmed GA since 1.17 by @ehashman 

https://kubernetes.slack.com/archives/C0BP8PW9G/p1619709771318900?thread_ts=1619707338.315200&channel=C0BP8PW9G&message_ts=1619709771.318900

Will update the page
