### ISSUE TITLE
Client Libraries

### ISSUE THREAD

**Issue by notjames** [kubernetes/website#27458]
They `ruby-k8sclient` library is mildly defunct now 

The following project: https://github.com/k8s-ruby/k8s-ruby/ has been forked and is meant to replace the former per https://github.com/kontena/k8s-client/issues/172

Please update the documentation

**Comment by sftim** [comment]
Thanks for the suggestion @notjames 

I think we'd be happy to link to an extra project. I'm more wary of removing a project from the list because someone has forked it. If https://github.com/kontena/k8s-client were marked as archived, it'd be easy to agree with the removal. If not, well, maybe we should leave it in and let the reader decide.

**Comment by sftim** [comment]
OK, with the understanding that we'll add an extra link but won't remove the old one:
/triage accepted
/language en
