### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by woter1832** [kubernetes/website#27740]
Hi,

Just started the tutorial and getting the following error when trying run `minikube version`:
```
W0426 23:57:27.668845    9700 main.go:170] Unable to make log dir /root/.minikube/logs: mkdir /root/.minikube/logs: input/output error
log: exiting because of error: log: cannot create log: open /tmp/minikube.minikube.root.log.WARNING.20210426-235727.9700: read-only file system
```

Thanks

**Comment by sftim** [comment]
Hi @woter1832 

If you try again, are those symptoms still present? It may already have been fixed.

**Comment by mtardy** [comment]
It seems that the user had a problem because they were running minikube on a read-only mounted file system, and minikube needed to write some logs to the fs.

This issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the #kubernetes-users channel in [Kubernetes slack](https://slack.k8s.io/). You can also search resources like [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) for answers to similar questions.

/close
