### ISSUE TITLE
Missing redirect for https://kubernetes.io/de/docs/setup/minikube/

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#27946]
I am on this page: https://kubernetes.io/de/docs/setup/minikube/

Although I am German, I prefer to read the English version and choose "English" at the top.

Now I get redirected to https://kubernetes.io/

That's a bit strange. 

Expected: An English page about "minikube".

**Comment by sftim** [comment]
GitHub is not the right place for support requests @guettli.

If you're looking for help, check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes)

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/kind support

**Comment by sftim** [comment]
/area web-development
/triage accepted
/kind feature
/priority backlog

Thanks for suggesting this improvement @guettli

**Comment by jihoon-seo** [comment]
It seems that this happens because
the English version of https://kubernetes.io/de/docs/setup/minikube/ page (=> https://kubernetes.io/docs/setup/minikube/)
does not exist anymore.

When you try to reach https://kubernetes.io/docs/setup/minikube/, 
an redirection to https://kubernetes.io/docs/tasks/tools/ occurs.

One possible solution is that
German localization team update these pages:

- https://kubernetes.io/de/docs/setup/minikube/
- https://kubernetes.io/de/docs/tasks/tools/
- and so on..

according to the English version of those pages.

**Comment by sftim** [comment]
Ah, right. That makes sense.

/retitle Missing redirect for https://kubernetes.io/de/docs/setup/minikube/ 

/remove-area web-development
/language de
/remove-kind feature
/kind bug

**Comment by sftim** [comment]
https://kubernetes.io/de/docs/setup/minikube/ should redirect to https://kubernetes.io/de/docs/tasks/tools/

**Comment by guettli** [comment]
While learning Kubernetes, I found and created above issue. 

After relaxing some days I came to the conclusion that I don't need Kubernetes at the moment.

I will keep on using Linux virtual private server for the next month.
