### ISSUE TITLE
Install and Set Up kubectl on Linux

### ISSUE THREAD

**Issue by waldo323** [kubernetes/website#27951]
Using the Red Hat-based Distrobutions I got to "Verify kubectl configuration", and upon first reading and trying I believe I need to run kube-up.sh or have kubeadm installed to create a cluster, however neither of these were installed with the package manager installation of kubectl (which makes sense for kubeadm since there are instructions are further into the guide. I don't know which package may have kube-up.sh).
I will proceed with installing kubeadm and using the associated guide.
Adding further clarification in the "Verify kubectl configuration" section would help others in the future.

**Comment by Priyankasaggu11929** [comment]
Referred doc ~ https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

**Comment by mehabhalodiya** [comment]
@sftim @kbhawkey Can you guide me how to get started with solving this issue?

**Comment by jihoon-seo** [comment]
The `kube-up.sh` script is deprecated.

The `README.md` in [k/k/cluster directory](https://github.com/kubernetes/kubernetes/tree/master/cluster) (where the `kube-up.sh` and `kube-down.sh` scripts exist) says that
> Deprecation Notice: This directory has entered maintenance mode and will not be accepting new providers. Deployments in this directory will continue to be maintained and supported at their current level of support.

**Comment by mehabhalodiya** [comment]
Hey, I want to add further clarification.
But, will anyone from you let me know what type of clarification is needed?
Which command and text needs to be inserted in [this section](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#verify-kubectl-configuration)?

**Comment by sftim** [comment]
The text I'd change is “In order for kubectl to find and access a Kubernetes cluster, it needs a kubeconfig file, which is created automatically when you create a cluster using kube-up.sh or successfully deploy a Minikube cluster.”

Instead of mentioning minikube and `kube-up.sh` we should signpost readers towards https://kubernetes.io/docs/setup/ and make it clear that they need to either:
- connect to a cluster that someone else set up, using the details that an operator for that cluster has provided to them
- set up their own cluster _this is where we should signpost them to Getting Started_

Some of this detail belongs in the prerequisites section right at the top of the page (and the same for the macOS and Windows pages). I think it's fine to repeat the same thing pretty much verbatim at the point where we explain how to verify that `kubectl` is set up OK.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#what-s-next does tell you what to do next, but doesn't mention a `~/.kube/config` file specifically. There _is_ a link to https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#what-s-next.

Does this need any further work?
