### ISSUE TITLE
[zh] 'namespace' is not translated consistently

### ISSUE THREAD

**Issue by chenxuc** [kubernetes/website#28459]
Some pages translates 'namespace' to ‘命名空间’([e.g.](https://kubernetes.io/zh/docs/tasks/administer-cluster/declare-network-policy/)), other pages '名字空间‘ ([e.g.](https://kubernetes.io/zh/docs/concepts/overview/working-with-objects/namespaces/)). This is confusing for new learners.

We should use consistent name, or at least add a note that these two names are synonyms.

**Comment by chenxuc** [comment]
@tengqm Do you know if we have previous discussion for this issue? Thanks!

**Comment by tengqm** [comment]
@chenxuc We had such discussions previously when drafting and reviewing the https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7 page. I personally prefer "名字空间”，because that is what namespace for ... a space for names. There are other voices arguing that "命名空间” is very popular in many articles or books.

**Comment by chenxuc** [comment]
Ok, the arguement for which name is better seems won't be resolved. I suggest we add an explicit statement to clarify these two names are synonyms. I will draft the changes.
