### ISSUE TITLE
[l10n] Sub-items are not displayed in sidebar tree

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#28616]
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/ ,
sub-items are not displayed in sidebar tree.
![image](https://user-images.githubusercontent.com/46767780/123369388-a2629300-d5b8-11eb-839d-d966105d76dc.png)

FYI
Chinese version:
https://kubernetes.io/zh/docs/reference/setup-tools/kubeadm/
![image](https://user-images.githubusercontent.com/46767780/123369545-e81f5b80-d5b8-11eb-94c6-4042fdbf7907.png)

Japanese version:
https://kubernetes.io/ja/docs/reference/setup-tools/kubeadm/
![image](https://user-images.githubusercontent.com/46767780/123369601-fff6df80-d5b8-11eb-974c-e24582d97236.png)

English version:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/
![image](https://user-images.githubusercontent.com/46767780/123369661-1c931780-d5b9-11eb-90f7-11c17c16c5f9.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/

**Comment by jihoon-seo** [comment]
- zh: Some Chinese-translated files exist in `content/zh/docs/reference/setup-tools/kubeadm/generated/`
- ko: No Korean-translated file exists in `content/ko/docs/reference/setup-tools/kubeadm/generated/`

I guess this is the reason why the sidebars of `zh` version and `ko` version are displayed differently.

FYI: On 2021-03-19, the `ko`-version sidebar was like this: (screenshot is from the issue #27132)
Even if no Korean-translated file exists in `content/ko/docs/reference/setup-tools/kubeadm/generated/`,
sub-items are displayed (which are the links to the English version of `kubeadm` subcommands).
![image](https://user-images.githubusercontent.com/46767780/111715884-332e2200-8898-11eb-9c58-f8b635cfa0bd.png)

**Comment by sftim** [comment]
This will affect all localizations
/priority important-soon

**Comment by jihoon-seo** [comment]
/retitle [l10n] Sub-items are not displayed in sidebar tree

**Comment by a-mccarthy** [comment]
/assign

I'd like to take a look at this

**Comment by a-mccarthy** [comment]
To summarize: Localizations should have the same links listed in their side nav as in the english language docs, regardless of whether the pages have been translated. This is because there is a "fallback" set up to display a link to the english language docs if a page has not yet been translated. The fallback links to english docs for generated reference docs (kubeadm docs) are missing in localize docs sets. 


@sftim (or anyone else), does this sound accurate? I'd like to make sure i understand whats broken before trying to troubleshoot hugo/docsy/mystery code section :)

**Comment by a-mccarthy** [comment]
I've been spending time investigating this and learning how the navigation is built :)  I believe i've found the issue. I'll try to summarize below, but I think this is a template issue which should be addressed by docsy. 

There is a check in https://github.com/kubernetes/website/blob/main/layouts/partials/sidebar-tree.html  ([lines 49-51](https://github.com/kubernetes/website/blob/main/layouts/partials/sidebar-tree.html#L49)) that compares all the pages and sections and then filters out pages that have [`toc_hide=true`](https://www.docsy.dev/docs/adding-content/navigation/). We then test for the number of child pages, to determine if we continue to build the next level down in the navigation tree. 

``` 
 {{ $pages_tmp := where (union $s.Pages $s.Sections).ByWeight ".Params.toc_hide" "!=" true -}}
  {{ $pages := $pages_tmp | first $sidebarMenuTruncate -}}
  {{ $withChild := gt (len $pages) 0 -}}
```

At this point, because some localizations have the Kubeadm page translated, this check will only find the translated _index.md file (files in the kubeadm/generated folder are filtered out bc the [generated/_index.md](https://raw.githubusercontent.com/kubernetes/website/main/content/ko/docs/reference/setup-tools/kubeadm/generated/_index.md) file has `toc_hide=true`). The logic as written determines that kubeadm has no child pages, because it doesn't know about the English pages at this point. This means the rest of the kubadm sub pages links will not be built in the navigation. Theres

There is a check later in https://github.com/kubernetes/website/blob/main/layouts/partials/sidebar-tree.html that merges the localized pages with the missing the English language pages and to inserts links to untranslated pages in the side nav. ([lines 67-75](https://github.com/kubernetes/website/blob/main/layouts/partials/sidebar-tree.html#L67)). But it only gets to this point if there are child pages, because its wrapped in a `{{ if $withChild -}}` conditional ([line 64](https://github.com/kubernetes/website/blob/main/layouts/partials/sidebar-tree.html#L64)).

```
{{ $pages := where (union $s.Pages $s.Sections).ByWeight ".Params.toc_hide" "!=" true -}}
        {{ with site.Params.language_alternatives -}}
          {{ range . }}
            {{ with (where $.section.Translations ".Lang" . ) -}}
              {{ $p := index . 0 -}}
              {{ $pages = where ( $pages | lang.Merge (union $p.Pages $p.Sections)) ".Params.toc_hide" "!=" true -}}
            {{ end -}}
          {{ end -}}
        {{ end -}}
```
In my testing i added the checking for untranslated pages, replacing lines 49-51 to be the following.

```
  {{ $pages_tmp := where (union $s.Pages $s.Sections).ByWeight ".Params.toc_hide" "!=" true -}}
  {{ with site.Params.language_alternatives -}}
    {{ range . }}
      {{ with (where $.section.Translations ".Lang" . ) -}}
        {{ $p := index . 0 -}}
        {{ $pages_tmp = where ( $pages_tmp | lang.Merge (union $p.Pages $p.Sections)) ".Params.toc_hide" "!=" true -}}
      {{ end -}}
    {{ end -}}
  {{ end -}}
  {{ $pages := $pages_tmp | first $sidebarMenuTruncate -}}
```

This appears to add in the links that were missing.

<img width="1569" alt="Screen Shot 2022-09-09 at 11 27 38 AM" src="https://user-images.githubusercontent.com/20771501/189386572-1df53a3e-bb91-4888-ba49-b62099c0e3e4.png">

If we agree that this looks 👍 and is a docsy issue, I can open an issue there and propose the solution. 

 cc: @sftim I would appreciated your thoughts on this, thanks!
