### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by cawoodm** [kubernetes/website#28639]
> To stop the proxy, run Ctrl+C to exit the process. The dashboard remains running.

Nope, when you press Ctrl+C after running `minikube dashboard` the dashboard stops working.

**Comment by chenxuc** [comment]
@cawoodm Thanks for the first issue here!
By saying "when you press Ctrl+C after running minikube dashboard the dashboard stops working", do you mean the web browser cannot access the dashboard page after Ctrl+C?
This is the expected behavior. After the proxy is stopped, the current web browser session stops working. But the dashboard server is still running in the background, you can open another proxy connection to access it again.

I can try to improve the doc if the original sentence confuses new learners.

**Comment by cawoodm** [comment]
Hello,
From a user perspective the dashboard is unusable after Ctrl+C and if you start it again it’s on a different port so it looks very mich like it’s stopped. The real question is why starting the dashboard should block the CLI like this. I’d say the behaviour is unnecessarily confusing for beginners and the documentation compounds this.

**Comment by chenxuc** [comment]
Let me improve the doc to clarify this.
/triage accepted
/kind feature
