### ISSUE TITLE
Configure a Security Context for a Pod or Container

### ISSUE THREAD

**Issue by ybykov-a9s** [kubernetes/website#28667]
The link to the page "[Overview of Linux Kernel Security Features](https://www.linux.com/learn/overview-linux-kernel-security-features)" is present, but most of the links on this page are not working now.

**Comment by sftim** [comment]
Hi @ybykov-a9s 

Would you be willing to give an example of a hyperlink in https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ that isn't work? That'd help us know exactly what to fix.

/language en

**Comment by ybykov-a9s** [comment]
Hi @sftim 

Here is a page: [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/). In the first part of it the last sentence sounds like "For more information about security mechanisms in Linux, see [Overview of Linux Kernel Security Features](https://www.linux.com/learn/overview-linux-kernel-security-features)". Of you go to this page, you'll notice that POSIX (2 links), SELinux, TOMOYO, Seccomp and DMverify links on this page don't work anymore.

So this link is not as useful as it was.

**Comment by sftim** [comment]
Got it. Linking to the article at https://www.linux.com/training-tutorials/overview-linux-kernel-security-features/ is now a poor choice because https://www.linux.com/training-tutorials/overview-linux-kernel-security-features/ is dated and has many broken links.

I'm not sure there's a better public article than that from the last 8 years though, which is a shame.
We could:
- try to encourage someone with the right background to write a new, current article (and then link to that)
- keep that link, but move it to the What's Next section of https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ *and highlight that the information is out of date*
- something else

/kind bug
/priority backlog
/triage accepted

**Comment by ybykov-a9s** [comment]
It's not important
