### ISSUE TITLE
Error while trying to preview the website locally on Windows

### ISSUE THREAD

**Issue by niteshseram** [kubernetes/website#28910]
**This is a Bug Report**

**Problem:**
When I try running the website locally using any of the commands as _hugo serve_ or _make serve_ or  _make container-serve_, it gives me the below error:

`Error: add site dependencies: load resources: loading translations: "D:\Opensource\website\i18n\de.toml:1:1": failed to load translations: (1, 1): parsing error: keys cannot contain / character`

**System**: Windows

**Comment by jihoon-seo** [comment]
`website/i18n/xx.toml` files are symbolic links.

e.g. https://github.com/kubernetes/website/blob/main/i18n/de.toml
```
../data/i18n/de/de.toml
```

I guess that this happens because Windows cannot handle (or, handles differently) the symbolic links created on UNIX.

Maybe, deleting `website/i18n/xx.toml` symbolic links and creating new ones on your environment might solve the problem

See:
- [Symlinks in Windows 10!](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/)
- [The Complete Guide to Creating Symbolic Links (aka Symlinks) on Windows](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/)

**Comment by niteshseram** [comment]
@jihoon-seo  actually after deleting the whole i18n folder it works fine in windows. I think it is a common issue that Windows users are facing when trying to run it locally.
I am not sure what these symbolic links do because everything works just fine even after deleting them.

**Comment by jihoon-seo** [comment]
@niteshseram
As far as I know,
`i18n/xx.toml` files are symbolic links to `../data/i18n/xx/xx.toml`.

And `../data/i18n/xx/xx.toml` files contain i18n strings for the translation of each language.

For example, `data/i18n/ko/ko.toml` contains i18n strings for the Korean translation.
![image](https://user-images.githubusercontent.com/46767780/125546214-999356e8-8d5a-4ec1-b0fd-3b56b72c63d4.png)

Since your profile says you are in India,
I checked [`data/i18n/hi/hi.toml`](https://github.com/kubernetes/website/blob/main/data/i18n/hi/hi.toml) and
I noticed that all the i18n strings in this file is in English, not in Hindi.

So I guess that since your deleting i18n directory did not affected the i18n strings of Hindi pages in your dev environment,
you could not catch any difference between before deleting and after deleting the i18n directory.

But it is kind of weird that deleting i18n directory did not cause any error in website-building process.

**Comment by sftim** [comment]
> But it is kind of weird that deleting i18n directory did not cause any error in website-building process.

The website can render (badly) without these strings.

**Comment by sftim** [comment]
/retitle Error while trying to preview the website locally on Windows

**Comment by sftim** [comment]
Maybe https://www.joshkel.com/2018/01/18/symlinks-in-windows/ might be helpful?

**Comment by sftim** [comment]
/remove-kind bug

Not sure if we count this as a request for help with development, or a bug.

**Comment by sftim** [comment]
/reopen

Folks are experiencing this issue

**Comment by sftim** [comment]
/triage accepted
/priority important-longterm

It would be nice to help people who use Windows so that they can preview changes locally, with an official guide about how to set up their PC to do that.

**Comment by wjkhappy14** [comment]
mklink /J "E:\source\code\k8s-website\i18n" "E:\source\code\k8s-website\data\i18n"
