### ISSUE TITLE
Kubernetes Components :: Misleading and confusing diagram.

### ISSUE THREAD

**Issue by sgpinkus** [kubernetes/website#29071]
The opening diagram [here](https://kubernetes.io/docs/concepts/overview/components/) is misleading and adds to the confusion about *what is the control-plane exactly?*. It shows etcd, kube-apiserver, kube-controller-manager, kube-scheduler, cloud-controller-manager all existing in some mysterious blue box not associated with any node. These things run on "nodes" don't they?? Where else would they run? If so they should be shown deployed on a node. I think people get control-plane services can be distributed across the cluster nodes, but trying to avoid pinning down an association between nodes and control-plane just confuses things - if indeed that is what is going on here. Or maybe "node" vs "control-plane" just needs a much clearer explanation.

**Comment by sftim** [comment]
You don't have to run the control plane on a node. We could mention in this page that sometimes (probably quite often) you do, but it's by no means required.

**Comment by sftim** [comment]
The components have to run on _something_ but if that turns out to be a cluster of bare metal Raspberry Pi boards, that's fine. Also, you don't have to run the same control plane components on every host that participates in the control plane; again, it's common to do that, but not required.

**Comment by sftim** [comment]
@sgpinkus does this help you frame the improvement you'd like made?

**Comment by sgpinkus** [comment]
@sftim yes helps a bit. Thanks.

My understanding is control plane components except for etcd have to run on a "node" where "node" is a networked host with a container runtime, kubelet, and kube-proxy on it. This is because they actually run as Pods. I thought about if it's possible to run the required control-plane component over different nodes such all are running but not all are running on the same node. My take is that this is possible, but I haven't come across any discussion of this in the Kubernetes docs or anywhere else.

Re changes I'd like to see made: I just think even though it's technically possible to do the above scenario, and to run etcd on different hosts (which seems more common), the diagram should show a common deployment scenario rather than something that is ambiguous, just because it's trying to be consistent with every possible deployment scenario out there. Showing one common deployment scenario would be more helpful to the uninitiated. Then can qualify with "The diagram shows a common non deployment scenario. For more info on HA setups see https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/ ..". Or a HA deployment diagram could be show as well.

**Comment by sftim** [comment]
It's tricky because this is a concept people meet early on. We want to be accurate and helpful whilst offering the chance to dig deeper into the topics that interest the reader.

One learning outcome I have in mind is that readers are clear that the control plane doesn't have to run as Pods. I'm happy to hyperlink to another page that shows an example the control plane components running on specially marked nodes - _we don't have that page yet, but someone could add it_ - but I don't want readers mistakenly believing that Kubernetes insists on placing the control plane within Pods. 

See https://docs.k0sproject.io/v1.21.2+k0s.1/architecture/ for an example of a project that uses the Kubernetes architecture (and is certified Kubernetes) and that _doesn't_ run the control plane within Pods.

**Comment by sgpinkus** [comment]
Yeah it is tricky. All I can say is, as someone learning k8, I had the question "where do the things in that blue dash box actually run, and how are they related to the "nodes"?" firmly stuck in my head for a day or two, and I feel that could  be alleviated with some clarifications at this point in the doc.
