### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by clincha** [kubernetes/website#29263]
The NFS volume section in the Kubernetes storage concepts documentation contains a broken link to an example in the last line of the section. Specifically this line: See the NFS example for more details.

NFS volume section: https://kubernetes.io/docs/concepts/storage/volumes/#nfs

Broken link: https://github.com/kubernetes/examples/tree/main/staging/volumes/nfs

**Comment by haardikdharma10** [comment]
I see a lot of broken links on the same page.

An example broken link: `https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/staging/volumes/nfs`

The issue is happening because of the `{{< param "githubbranch" >}}`, which I believe is set to `main` and we need to change that to `master`. Is this the right approach for the solution or just changing the above link to 

`https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs` should be the approach?

cc @sftim

**Comment by yuswift** [comment]
/assign
@sftim Could you tell me how to specify the `param ` globally? Or do we just need to update it to `master`?

**Comment by yuswift** [comment]
friendly ping @sftim . A lot of links are broken.

**Comment by sftim** [comment]
My take on this: https://github.com/kubernetes/website/issues/29298#issuecomment-895218446
