### ISSUE TITLE
Labels on cluster diagram are hard to read

### ISSUE THREAD

**Issue by joaocfernandes** [kubernetes/website#29340]
The high level overview of the kubernetes components uses a .svg file for the presentation. The content is clearly presented but some of the labels for each components are too small.

I suggest that either the labels are made bigger or a diferent logo is used for each of these components. API Server, Cloud control manager , controller manager.

Example screenshoot on Full HD screen.
![image](https://user-images.githubusercontent.com/2494410/129172723-dbf21da7-e176-4287-b5b6-245421637cb2.png)

**Comment by sftim** [comment]
/retitle Labels on cluster diagram are hard to read

**Comment by sftim** [comment]
These are the official icons for each component. We should continue to use the official icons.

One thing I considered when drawing this diagram, but left because its extra work: use flexbox to allow laying out the key to the diagram below if the viewport is not big enough to show it clearly.

Less effort: add a mechanism to let people click on a diagram to see it enlarged (and then click again to go back). Good implementations of this work with the [History](https://developer.mozilla.org/en-US/docs/Web/API/History_API) API so that the Back button also returns you to the page you were viewing.

**Comment by AvineshTripathi** [comment]
I would like to do this
