### ISSUE TITLE
Tutorial Warning or fix

### ISSUE THREAD

**Issue by mojoa** [kubernetes/website#29580]
For:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

I am a new student and find the tutorial/task for configuring persistent volume storage as written, does not work. I found other people having the same problem as I am. I was able to change the storageClassname to "standard" in both the pv-volume.yaml and pv-claim.yaml and got a "bound" indication, but I have no idea whether this is proper for this tutorial. If the task can not be made to work for some reason, a warning to users that it does not work would be appreciated.

**Comment by shannonxtreme** [comment]
Hi mojoa@! Could you please point out where you had issues, and what the exact problem was? It sounds like you got up to [Create a Pod](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-pod) without issues. 

Please provide any relevant output as well as the exact steps you followed so that one of us can try and replicate the issue.

/triage needs-information

**Comment by mojoa** [comment]
Hi, @shannonxtreme , Thanks for taking the time to reach out. I had problems getting bound status from get pvc. But have restarted my cluster and its working now. I will take this opportunity to request a BOLD FONT in the [before-you-begin](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#before-you-begin) section when it mentions "single node" cluster requirement. I missed this and am operating on a 3 node cluster and the pod can't find index.html.
