### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by alexeyerm** [kubernetes/website#29590]
"Flag --record has been deprecated" (c) kubectl

But still used in recommendations and examples (10 times in this article).

**Comment by shannonxtreme** [comment]
@sftim, is this a candidate for a good first issue?

**Comment by sftim** [comment]
I'm afraid for this to be a good first issue we'd need to provide more advice to people reading this so that we had lowered the barrier to entry enough.
@alexeyerm if you'd like to revise the issue description with the [guidelines](https://www.kubernetes.dev/docs/guide/help-wanted/#good-first-issue) in mind, that'd be lovely. We can still work on the issue if that doesn't happen though.

**Comment by sftim** [comment]
Should we also fix https://kubernetes.io/docs/tasks/manage-daemon/rollback-daemon-set/ ?

**Comment by sftim** [comment]
BTW https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/859-kubectl-headers doesn't mention the annotation.

**Comment by alexeyerm** [comment]
Sorry, i am not experienced in Kubernetes to write docs.

BTW i don't think that "good first issue" badge should be achieved for expired documentation remarks.

**Comment by shannonxtreme** [comment]
> BTW https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/859-kubectl-headers doesn't mention the annotation.

@sftim from what I understood, including the kubectl subcommand in the header replaces the need to use `--record` to write to the annotation, since the cause of the change is now recorded in the header.

**Comment by vaibhav2107** [comment]
Fixes in #29593

**Comment by shannonxtreme** [comment]
Closing this because it was fixed. Thanks @vaibhav2107 !

/close
