### ISSUE TITLE
Query about removal of dockershim from Kubernetes

### ISSUE THREAD

**Issue by sdputurn** [kubernetes/website#29718]
why docker is still in the list of supported runtimes. kubernetes 1.22 has removed support for docker as runtime. right?

if i understand correct. kubernetes support contianerd and not docker. dockerd now uses continerd for container management and containerd comes bundled with docker installation. so the relationship seems like this

docker client --> dockerd --> containerd -->runc --> running container.

can kubernetes still work with containerd that comes bundled with dockerd?

**Comment by RA489** [comment]
Docker as an underlying runtime is being removed in favor of runtimes that use the Container Runtime Interface (CRI) created for Kubernetes. Docker-produced images will continue to work in your cluster with all runtimes, as they always have.

**Comment by RA489** [comment]
If you’re using a managed Kubernetes service like GKE, EKS, or AKS (which defaults to containerd) you will need to make sure your worker nodes are using a supported container runtime before Docker support is removed in a future version of Kubernetes.

**Comment by sftim** [comment]
As per https://kubernetes.io/blog/2020/12/02/dockershim-faq/ 
> [The Docker shim] will not be removed before Kubernetes 1.22, meaning the earliest release without dockershim would be 1.23 in late 2021. 

Because the latest Kubernetes release includes the Docker shim, it's entirely reasonable to document how to set up Docker as a container runtime.

Separately, it might be useful for https://kubernetes.io/docs/setup/production-environment/container-runtimes/ to include extra detail about how installing Docker gets you both Docker itself and a working containerd, as well as about the timeline for deprecation.

Most of that detail is more about Docker than Kubernetes. I recognise that a lot of people reading these docs will arrive with Docker experience than Kubernetes, so extra clarity here feels reasonable. For some specific details relating to this, we should direct readers to Docker docs (even though they don't cover this topic particularly well).

/language en

@sdputurn was this issue more of:
- a feature request / suggestion to change the page
- a query (support request)

?

If your main aim is to get the page improved, would you be willing to revise the issue description to describe the improvement you had in mind?

**Comment by sdputurn** [comment]
thanks @sftim  for detailed explanation. my assumption after reading here - https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/ was docker as runtime will be removed from 1.22. 

it was more a query after seeing docker as supported runtime in k8s 1.22 docs. but you made it clear why docker as runtime still showing up there.

**Comment by sdputurn** [comment]
hi @sftim  i still see docker as supported runtime for kubernetes version 1.23. when is this support for docker as runtime is actually going to end?

thanks,
Sandeep

**Comment by sftim** [comment]
You can find the information you wanted if tou carefully read all of https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/ and the [FAQ](https://kubernetes.io/blog/2020/12/02/dockershim-faq/) that it links to.

(If you're _not_ planning to read a Frequently Asked Questions document, @sdputurn, the folks who triage these issues might not be willing to do that for you).

**Comment by sftim** [comment]
The v1.24 release for Kubernetes is likely to happen either this month or next month.

/close
/retitle Query about removal of dockershim from Kubernetes
