### ISSUE TITLE
[PodSecurity] Document webhook installation & use

### ISSUE THREAD

**Issue by tallclair** [kubernetes/website#30133]
- [x] Webhook installation guide
  - [ ] How to manage webhook certificates
  - [ ] Kustomization
- [ ] When to use the webhook
- [ ] Limitations of the webhook
- [ ] ~~Extending the webhook (full guide to API & extension points should probably be part of the README documentation on the PodSecurity repo)~~ (https://github.com/kubernetes/kubernetes/issues/106561)

/cc @sejr @liggitt 
/sig auth
/milestone v1.23

**Comment by souvikrajsingh** [comment]
@tallclair  hey I would love to work on this issue, can you please assign it to me ? thank you!

**Comment by souvikrajsingh** [comment]
> @souvikrajsingh  you can assign by yourself too by just commenting **/assign**

Since you mentioned , can you please tell me about this issue a bit , do I need to make documentation or I need to add these in some particular file? I'm actually new to this

**Comment by sejr** [comment]
@souvikrajsingh @AvineshTripathi hey there! We have an initial Task page for installing the webhook located here: https://github.com/kubernetes/website/pull/30122

It's possible that other pages, such as Concepts, will be required, but I'll defer to both Tims to clarify what they expect.

This issue is essentially tracking the topics that need to be added. I'd be happy to help you get involved; it's possible we could divide and conquer on these. Sections like _extending the webhook's functionality_ definitely need expanding on.

**Comment by souvikrajsingh** [comment]
> @souvikrajsingh yes! Check out slack.kubernetes.io -- you can join the SIG Auth channel and/or send me a direct message (I'm Sam on there)

Thanks again, Sam! Will connect with you on Slack !!

**Comment by liggitt** [comment]
https://github.com/kubernetes/website/issues/28867 open to add basic steps for webhook installation. It does not cover extending the webhook, which seems like a significantly different / more advanced topic

**Comment by tallclair** [comment]
This was resolved by https://github.com/kubernetes/website/pull/30351

Punting the extension documentation to https://github.com/kubernetes/kubernetes/issues/106561
