### ISSUE TITLE
etctutl command name incorrectly “fixed”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30215]
**This is a Bug Report**

**Problem:**
PR https://github.com/kubernetes/website/pull/28601 introduced a command, `etcdutl`, that a reader can use to work on etcd.
You can read more about `etcdutl` in https://etcd.io/blog/2021/announcing-etcd-3.5/#developer-experience.

PR https://github.com/kubernetes/website/pull/30202 revised that text to change the name from `etcdutl` to `etcdctl`. I think that the #30202 revisions were well intended but incorrect.

**Proposed Solution:**
Revert changes from PR https://github.com/kubernetes/website/pull/30202 / commit https://github.com/kubernetes/website/commit/64b5b16bac9abb0de3d22fc5489134a5cb8ec5a8.

**Page to Update:**
https://k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

**Additional Information:**
/cc @RA489 
/kind bug
/language en

**Comment by RichieMcG** [comment]
Sorry this is my bad. I didn't notice line 328 and also I have never come across etcutl. 
I do think it is confusing how etdutl is suddenly introduced in the docs, as it not even mentioned previously on the page or elsewhere in the docs (that I could find). 

Perhaps rephrasing that line 328 to actually introduce the reader to the fact that etcdutls exists and can be used instead of etcdctl and also link the documentation to the you metioned?

I'm happy to do this if it is acceptable?
