### ISSUE TITLE
Konnectivity docs have likely incorrect instructions

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/website#30317]
**This is a Bug Report**

**Problem:**

The konnectivity docs: https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

Include the following instruction:

```
Make sure that the ServiceAccountTokenVolumeProjection feature gate is enabled. You can enable service account token volume protection by providing the following flags to the kube-apiserver:

--service-account-issuer=api
--service-account-signing-key-file=/etc/kubernetes/pki/sa.key
--api-audiences=system:konnectivity-server
```

Setting `--api-audiences` to `system:konnectivity-server` doesn't seem right:
- This will break authentication for all tokens that use the default audience value (taken from the `--service-account-issuer` value), which is most tokens.
- This will allow tokens with `system:konnectivity-server` in them to authenticate directly to kube-apiserver. I don't think we want that. Instead, we should just depend on konnectivity-server specifying the right audience in [its TokenReview request](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/57df1484a81a85c6984436e35f50003e7cccea3e/pkg/server/server.go#L555).
- Also: `api` is unlikely to be a valid value for `--service-account-issuer`. In practice `--service-account-issuer` is typically an `https` URL. 
 

**Proposed Solution:**

Instead of including incorrect flag values inline, just link out to the correct documentation at https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection. 

**Page to Update:**
https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

**Comment by cheftako** [comment]
https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/extend-kubernetes/setup-konnectivity.md

**Comment by kvaps** [comment]
Hi @mtaufen thanks for pointing this out.


> Setting `--api-audiences` to `system:konnectivity-server` doesn't seem right:
>  * This will break authentication for all tokens that use the default audience value (taken from the `--service-account-issuer` value), which is most tokens.


I just wanted to link this issue with the unfinished discussion in https://github.com/kubernetes/website/pull/24141#discussion_r498008017

BTW, wouldn't it be more correct to specify both audiences:

```ini
--api-audiences=https://kubernetes.default.svc.cluster.local,system:konnectivity-server
```

\- where `cluster.local` is `dnsDomain` value for the cluster

>  * This will allow tokens with `system:konnectivity-server` in them to authenticate directly to kube-apiserver. I don't think we want that. Instead, we should just depend on konnectivity-server specifying the right audience in [its TokenReview request](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/57df1484a81a85c6984436e35f50003e7cccea3e/pkg/server/server.go#L555).

Please correct me if I'm wrong but do you suggest to specify already existing audience for konnectifity-server, eg. this one which is used in kubeadm clusters by default:

```ini
--api-audiences=https://kubernetes.default.svc.cluster.local
```
\- where `cluster.local` is `dnsDomain` value for the cluster


> * Also: `api` is unlikely to be a valid value for `--service-account-issuer`. In practice `--service-account-issuer` is typically an `https` URL.

Agree on that. I have the following setup in my [kubernetes-in-kubernetes](https://github.com/kvaps/kubernetes-in-kubernetes) project right now:

##### option A:
```ini
# kube-apieserver
--api-audiences=system:konnectivity-server
--service-account-signing-key-file=/pki/sa/tls.key
--service-account-issuer=https://kubernetes.default.svc.cluster.local

# konnectivity-server:
--authentication-audience=system:konnectivity-server
```

I'd like to change it to be more correct.

Based on said above. I suppose we have few more options:

##### option B:
```ini
# kube-apiserver
--api-audiences=https://kubernetes.default.svc.cluster.local # or missing
--service-account-signing-key-file=/pki/sa/tls.key
--service-account-issuer=https://kubernetes.default.svc.cluster.local

# konnectivity-server:
--authentication-audience=https://kubernetes.default.svc.cluster.local
```

##### option C:
```ini
# kube-apiserver
--api-audiences=https://kubernetes.default.svc.cluster.local,system:konnectivity-server
--service-account-signing-key-file=/pki/sa/tls.key
--service-account-issuer=https://kubernetes.default.svc.cluster.local

# konnectivity-server
--service-account-issuer=system:konnectivity-server
```

All three configurations are working, now we need to choose the most correct one.

>
> **Proposed Solution:**
> 
> Instead of including incorrect flag values inline, just link out to the correct documentation at https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection.


Of course we can link to the documentation page, but as for now it has no any usable examples to allow user simple start using this.

I'm not big fan of leaving user without proper examples because they will just start using random configuration which works.
Let's define correct defaults instead. Other services (eg. istio, vault) can rely on this configuration snippets as well.

**Comment by mtaufen** [comment]
> BTW, wouldn't it be more correct to specify both audiences

The audience `system:konnectivity-server` is meant for the konnectivity server, not kube-apiserver directly, correct? In other words, seems like those tokens should require proxying through the konnectivity server, kube-apiserver shouldn't accept them directly? (@mikedanese this was the impression I got in our offline conversation - did I get that right?)

> Please correct me if I'm wrong but do you suggest to specify already existing audience for konnectifity-server

I'm suggesting we can probably just leave `--api-audiences` unset and let it inherit from `--service-account-issuer`.

**Comment by mtaufen** [comment]
This is what I'm proposing:
```bash
# kube-apiserver
# --api-audiences not set
--service-account-issuer=${choice_of_cluster_admin} # for example, hosted providers commonly serve this from a public per-cluster URL

# konnectivity-server
--authentication-audience=system:konnectivity-server
```

**Comment by kvaps** [comment]
> I'm suggesting we can probably just leave `--api-audiences` unset and let it inherit from `--service-account-issuer`.

Okay this is **option B**, but this way we would need to configure konnectivity-server with the flag:

```
--authentication-audience=https://kubernetes.default.svc.cluster.local
```

And konnectivity-agent with the volume:

```
      - name: konnectivity-agent-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: https://kubernetes.default.svc.cluster.local
              expirationSeconds: 3600
              path: konnectivity-agent-token
```

would it be correct configuration, or maybe better to use separate audience `system:konnectivity-server` (**option C**)?

**Comment by mtaufen** [comment]
My current understanding is that we can use `--authentication-audience=system:konnectivity-server`, since the konnectivity-server can tell kube-apiserver which audiences to validate against when it makes the `TokenReview` request, and those apparently don't have to match kube-apiserver's `--api-audiences`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#tokenreviewspec-v1-authentication-k8s-io

**Comment by mikedanese** [comment]
I agree that we should link to the canonical documentation for setting up service account token issuer vs copying it here. These are now required flags so widespread adoption is imminent.

We should leave Konnectivity server configured with `--authentication-audience=system:konnectivity-server`. This means that Konnectivity server identifies as `system:konnectivity-server` and will only accept tokens that are meant for audience `system:konnectivity-server`.

We shouldn't add `--api-audiences=system:konnectivity-server` to kube-apiserver, because we don't want kube-apiserver to accept tokens meant for connectivity server.

Looking at the other docs, we likely don't have enough documentation on how to pick a value for `--service-account-issuer`. `--service-account-issuer=api` isn't great. `--service-account-issuer=https://kubernetes.default.svc.cluster.local` is slightly better. Ideally, this is a globally unique URL (i.e. no private DNS or IPs) that supports OIDC discovery. In GKE, this is something like `https://container.googleapis.com/v1/projects/mikedanese/locations/us-central1-c/clusters/test-cluster` for `test-cluster` in project `mikedanese` in location `us-central1-c`. EKS is something similar.

**Comment by kvaps** [comment]
> We shouldn't add --api-audiences=system:konnectivity-server to kube-apiserver, because we don't want kube-apiserver to accept tokens meant for connectivity server.

Oh, got it! I don't remember exact reason why I started using this flag, but I just checked and confirm that it is working fine without it.
  Suppose it was just a configuration mistake. I'll prepare PR to fix this.

**Comment by sftim** [comment]
Hi, I was copied in. How can I help?

**Comment by kvaps** [comment]
@sftim you're member of `sig-docs-en-owners`, we need an approval for https://github.com/kubernetes/website/pull/30385, to get it merged.

**Comment by sftim** [comment]
Best thing usually is to contact the [PR wrangler](https://github.com/kubernetes/website/wiki/PR-Wranglers) if a review is urgent / not happening. Although, this week I'm sharing cover for that. So, consider me informed. I'll take a look.
