### ISSUE TITLE
[zh] Issue with k8s.io/zh/docs/tasks/debug-application-cluster/resource-metrics-pipeline

### ISSUE THREAD

**Issue by hechunping** [kubernetes/website#30544]
deployment yamls:https://github.com/kubernetes-sigs/metrics-server/tree/master/deploy does not exist

**Comment by jihoon-seo** [comment]
/retitle [zh] Issue with k8s.io/zh/docs/tasks/debug-application-cluster/resource-metrics-pipeline

**Comment by jihoon-seo** [comment]
In English page, the links goes to
https://github.com/kubernetes-sigs/metrics-server/releases

**Comment by mengjiao-liu** [comment]
The reason is that the Chinese version link is not synchronized with the English version.

However, when I synchronized the pipeline page, I found that there was a problem with other content  that needed to be synchronized #31035, and I needed to wait for this issue to be solved before I could synchronize.
