### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/components/

### ISSUE THREAD

**Issue by vinodjujaray** [kubernetes/website#30582]
Service Controller definition is not given any where in this page

**Comment by sftim** [comment]
https://k8s.io/docs/concepts/overview/components/ doesn't list all the controllers; that's intentional.

I did have a go at adding this (https://github.com/kubernetes/website/pull/15374) but it's quite a lot of work to document all the controllers built in to Kubernetes. If / when we add that documentation, it'd be appropriate for https://k8s.io/docs/concepts/overview/components/ to link there.
