### ISSUE TITLE
document kubeadm annotations,labels,taints

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30613]
**This is a Feature Request**

**What would you like to be added**
Document the annotation keys that `kubeadm` uses, on the page [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/)/

**Why is this needed**
`kubeadm` uses annotations within `kubernetes.io`, for example `kubeadm.kubernetes.io/etcd.advertise-client-urls`

per https://kubernetes.io/docs/reference/labels-annotations-taints/ we document all annotations, labels and taints that are in `kubernetes.io`

**Comments**
/priority backlog
/lifecycle frozen
/sig cluster-lifecycle
/kind feature
/language en

This isn't a big priority. I've made it insta-frozen because we should nevertheless do it.

**Comment by sftim** [comment]
@neolit123 FYI

**Comment by neolit123** [comment]
here is what kubeadm has currently:

**annotations**

`kubeadm.alpha.kubernetes.io/cri-socket`

Annotation that kubeadm uses to preserve the CRI socket information given to kubeadm at init/join time for use later. kubeadm annotates the node object with this information. The annotation remains "alpha", since ideally this should be a field in KubeletConfiguration instead.

`kubeadm.kubernetes.io/etcd.advertise-client-urls`

Annotation that kubeadm places on locally managed etcd pods to keep track of a list of URL where etcd clients should connect to. This is used mainly for etcd cluster health check purposes.

`kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint`

Annotation that kubeadm places on locally managed kube-apiserver pods to keep track of the exposed advertise address/port endpoint for that API server instance.

`kubeadm.kubernetes.io/component-config.hash`

Annotation that kubeadm places on config maps that it manages. It contains a hash used to determine if the user has applied settings different from the kubeadm defaults for a particular config map.

**labels**

Note: Starting in v1.20, this label is deprecated in favor of `node-role.kubernetes.io/control-plane`.

`node-role.kubernetes.io/master`

Label that kubeadm applies on the control plane nodes that it manages.

**taints**

Note: Starting in v1.20, this label is deprecated in favor of `node-role.kubernetes.io/control-plane`.

`node-role.kubernetes.io/master`

Taint that kubeadm applies on control plane nodes to allow only critical workloads to schedule on them.

/retitle document kubeadm annotations,labels,taints
/help

**Comment by ashish-jaiswar** [comment]
@sftim is anyone working on this issue? if not please assign me.

**Comment by mehabhalodiya** [comment]
/assign @ashish-jaiswar 
Go ahead!

**Comment by ashish-jaiswar** [comment]
Hi, @sftim I need your help, can you tell me How can I resolve this issue?

**Comment by sftim** [comment]
Hi @ashish-jaiswar 

If you can take the information from https://github.com/kubernetes/website/issues/30613#issuecomment-977922126 and edit https://kubernetes.io/docs/reference/labels-annotations-taints/ to include those details, that should resolve the issue when your pull request merges.

To get started with code contributions to our docs, check out https://www.k8s.dev/docs/guide/ and https://k8s.io/docs/contribute/new-content/

**Comment by sftim** [comment]
Duplicated by #31952

**Comment by neolit123** [comment]
> https://github.com/kubernetes/website/pull/31391

merged
/close
