### ISSUE TITLE
[Migration off Dockershim] Migration guide for users configured private registries/mirrors

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#30843]
/sig node

It is very common that people set up private registries on Docker. Step by step migration guide on how to configure the same on Containerd or other runtimes would be useful for smooth migratioon

Fork of https://github.com/kubernetes/website/issues/29665#issuecomment-920176362

> Also we might extend this issue (or maybe create another one) explaining how to configure registry mirrors. If one has it configured for Docker, it is different for other runtimes here: https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry

**Comment by chris-short** [comment]
How is this issue any different than #30951?

I'm open to splitting up work but this is confusing. Can we capture what we need here and add it to #30951?

**Comment by a-mccarthy** [comment]
From working on #30951, we determined that its best to remove the `Configuring nodes to authenticate to a private registry` section from https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry and point folks to this page, https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/, instead. The general consensus was that the steps on the Images page were still valid, a relatively common use case, and not directly affected by the dockershim removal. More info on this conversation can be found in [this comment](https://github.com/kubernetes/website/issues/30951#issuecomment-1047876538), and slack [thread](https://kubernetes.slack.com/archives/C0BP8PW9G/p1644334662322659) & [thread2](https://kubernetes.slack.com/archives/C02PZMA3R6E/p1644943378795249).

As @chris-short noted above, this issues seems very close to https://github.com/kubernetes/website/issues/29665 and https://github.com/kubernetes/website/issues/30951. And i'd like to make sure we aren't having multiple conversations about the same page and drawing different conclusions. I opened https://github.com/kubernetes/website/pull/31895 to address #30951.  

Do we still feel like a migration guide is needed as part of the dockershim removal work? 

I am not an export on container registries, so i would value some insight here, @SergeyKanzhelev @chris-short @chrisnegus

**Comment by pinkertonpg** [comment]
@a-mccarthy On the page https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry, it outlines 4 ways to set up private image registry auth:
- Configuring Nodes to Authenticate to a Private Registry
- Pre-pulled Images
- Specifying ImagePullSecrets on a Pod
- Vendor-specific or local extensions

Your comment suggests that the decision is to remove the first of these sections, and instead point folks to https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ (it's actually already pointing to that doc right now...but the below is still valid).

However, that tasks/ page linked to describes setting up imagePullSecrets in a Pod, which is already described on the previous page here: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod.

My understanding of https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry, based on the outline provided above in the doc, is that this section is supposed to describe how to configure the underlying nodes to authenticate to a private registry, e.g. writing a docker/config.json file directly to hosts. This and imagePullSecrets are two very different methods of setting up registry auth, so I'm trying to figure out why we're replacing the former with the latter.

What's also not clear to me at all is if injecting a docker/config.json onto hosts will still work with the dockershim deprecation, or if we'd have to inject runtime-specific files e.g. `containerd/config.toml`. That question was asked here by @SergeyKanzhelev  https://github.com/kubernetes/website/issues/29665#issuecomment-920176362 but as far as I can tell, never answered. It's confusing because of Kubelet's built-in credentials provider that reads a docker/config.json - does that continue to work when not using docker?

**Comment by sftim** [comment]
/priority important-soon

It will become an increasingly relevant topic.

**Comment by tigerinus** [comment]
Just upgraded to Kubernetes 1.24 and got it running without Docker on the bare metals. It'd be nice to see a how-to guide on how to pull images from private reg using `containerd`. Thanks.

**Comment by sftim** [comment]
We already have the guide at https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ but we don't have a _migration_ guide.

**Comment by sftim** [comment]
I hope we get this done before Kubernetes v1.28; if we don't, we can close this as not planned.

**Comment by SergeyKanzhelev** [comment]
/close

since dockershim was removed that long ago, this is not relevant any longer. We can open it as a different issue as just an instruction. But I think it is not the k8s's role to have instructions how to configure registries in runtimes
