### ISSUE TITLE
Action on Docker mentions in Tasks > Install Tools

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30900]
Umbrella issue: #30771 

URL: https://kubernetes.io/docs/tasks/tools/
File: /docs/tasks/tools/_index.md

The KinD section mentions Docker.

Action: Do not change

---

URL: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/
File: /docs/tasks/tools/install-kubectl-windows.md

Description: There's a note about how Docker Desktop for Windows adds its own version of kubectl to PATH. 

Action: Not sure, but leaning towards do not change. 

/sig docs
/language en

**Comment by PurneswarPrasad** [comment]
@shannonxtreme In the 2nd one (installing kubectl on windows), it mentions how Docker Desktop for Windows adds its own version of kubectl to its path. But it can also be done independently as mentioned in the earlier steps. 
So, should we change:
`Note: Docker Desktop for Windows adds its own version of kubectl to PATH. If you have installed Docker Desktop before, you may need to place your PATH entry before the one added by the Docker Desktop installer or remove the Docker Desktop's kubectl.` 
to
`If you have Docker Desktop for Windows installed, remove it as it adds its own version of kubectl to the PATH since starting from v1.24, Docker support is being dropped` ?

**Comment by sftim** [comment]
> If you have Docker Desktop for Windows installed, remove it as it adds its own version of kubectl to the PATH since starting from v1.24, Docker support is being dropped ?

@PurneswarPrasad that wording needs careful thought. The original note wording is more appropriate IMO. People are welcome to have both Docker Desktop and `kubectl` installed on their laptop / desktop PC, and we're not advising anyone not to.

**Comment by mehabhalodiya** [comment]
> The KinD section mentions Docker.
Action: Do not change

> Description: There's a note about how Docker Desktop for Windows adds its own version of kubectl to PATH.
Action: Not sure, but leaning towards do not change.

So, anything needs to be modified?
