### ISSUE TITLE
kubectl get/describe defaults to returning the GA API version for a K8s object.

### ISSUE THREAD

**Issue by JoshuaFox** [kubernetes/website#31142]
`kubectl get/describe` defaults to returning the GA API version for a K8s object.

It seems to be strange -- we expect the `kubectl` command to give a **true** answer. In many case, the false answer actually has implications about what is and is not supported  in the API.

As an example,   you set up a `HorizontalPodAutoscaler` in `v2beta2`. You chose this rather than `v1` specifically for the new  API it gives you, custom metrics. Yet `kubectl get/describe` tells you that it is `v1`!
 
But regardless,  is this fact documented? If so, where? If not, please document it.

**Comment by sftim** [comment]
The place that _should_ explain this is https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups-and-versioning

However, some of the details are instead in https://kubernetes.io/docs/reference/using-api/#api-versioning and https://kubernetes.io/docs/reference/using-api/deprecation-policy/ (sic)


My proposed fix:
- update https://kubernetes.io/docs/reference/using-api/#api-versioning to clarify whether and why Kubernetes prefers stable API versions over newer, not yet stabilized APIs.
- clearly signpost readers to read about round-tripping (rule #2 from https://kubernetes.io/docs/reference/using-api/deprecation-policy/) **or** repeat that detail within https://kubernetes.io/docs/concepts/overview/kubernetes-api/
- update https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups-and-versioning to link to the updated reference pages that are now more helpful because of these revisions.

/language en
/wg api-expression
