### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by rajeev2509** [kubernetes/website#31300]
this documentation is so confusing....
Why section for Draining a node is in the middle when we talk about it at the begining? How one would drain first master node? After 'sudo kubeadm upgrade apply'?

**Comment by neolit123** [comment]
this is the second report i've seen about this so maybe we can improve the structure a little but i need to understand how..

> Why section for Draining a node is in the middle when we talk about it at the begining?

by "beginning" do you mean https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#additional-information ?

this simply explains why draining nodes is required.

> How one would drain first master node? After 'sudo kubeadm upgrade apply'?

if you look at the structure on the right you will see that "calling kubeadm upgrade" is meant for all control plane nodes, since it's under the parent "Upgrading control plane nodes". this means you have to go to all of them and first call "upgrade apply" or "upgrade node".

then "Draining the node" is a separate section also means - do it for all control plane nodes.

![summary](https://user-images.githubusercontent.com/331852/149144998-c583f160-eecf-4d12-bc8a-9ee42597eb4d.gif)

Also under "Upgrading control plane nodes" there is this text:
> The upgrade procedure on control plane nodes should be executed one node at a time

as a user, what would you like to see as an improved here?

/triage accepted
/priority awaiting-more-evidence

**Comment by neolit123** [comment]
>> The upgrade procedure on control plane nodes should be executed one node at a time

perhaps this text can be adjusted to the following:

> The upgrade procedure on control plane nodes should be executed one node at a time for each step below.

**Comment by rajeev2509** [comment]
Hi,

'Additional information' section at the beginning confirms that 'Draining
nodes' is the very first thing to do: but that is not the case

'draining a node is a necessary step before upgrading a kubelet on a node
for all node types': This is an important point and to be mentioned in the
document else assumption is to drain the node before initiating upgrade
action.

Regards,
Rajive

**Comment by neolit123** [comment]
ok, i can see how that can be confusing.

> [Draining nodes](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/) before kubelet MINOR version upgrades is required. In the case of control plane nodes, they could be running CoreDNS Pods or other critical workloads.

the text has a link and it sounds like a prerequisite. this can be clarified that the steps below instruct exactly *when* to do the drain during upgrade.

**Comment by neolit123** [comment]
proposed fix is here: https://github.com/kubernetes/website/pull/31323
