### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by QWERTY92009** [kubernetes/website#31526]
The instructions as written result in this error: 

```
Err:3 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
Reading package lists... Done
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by neolit123** [comment]
hi, what distribution / version are you using?
i have not seen this error on different Ubuntu versions.

does this solution work for you?
https://jonamiki.com/2019/11/09/ubuntu-the-following-signatures-couldnt-be-verified-because-the-public-key-is-not-available-no_pubkey/

we could add the solution in the docs if it works before the "Download the Google Cloud public signing key" step, but it's odd that only some users see this error.

/sig cluster-lifecycle
/kind support

**Comment by neolit123** [comment]
no response.
/close

please reopening if needed.
