### ISSUE TITLE
Allow exempting blog articles from staleness notice

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31778]
**This is a Feature Request**

**What would you like to be added**
Add a mechanism that lets us update the front matter of a blog article to show that it is never considered stale, and use that to suppress the notice for stale content.

**Why is this needed**
An article such as https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/ is old, but by its nature doesn't really need an offputting “Outdated article” notice.

It would be nice to be able to mark some articles as never stale, or possible to set a custom freshness duration? Something, anyway.

**Comments**
/kind feature
/area web-development

This would build on the work from PR #31594

**Comment by liggitt** [comment]
Agreed that some posts are evergreen and should be able to be exempted. I regularly send https://kubernetes.io/blog/2020/09/03/warnings/ as a nice summary, and was surprised to see a bold definitive pronouncement the page was considered outdated (it makes it sound like a specific judgement of that page more than an automated notice).

I'd also consider softening the language a bit on pages where it is displayed. Maybe something like "This article is more than one year old. Older articles may contain content that is outdated. Check that the information in the page has not become incorrect since its publication."

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/website/pull/31932 to tweak the language and shrink the header a bit

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/website/pull/31934 to allow marking blog posts as evergreen

**Comment by sftim** [comment]
I'm OK with marking https://kubernetes.io/blog/2020/09/03/warnings/ as evergreen _but_ I also note that it says that Jordan Liggitt is a software engineer at Google.

We should avoid including such implicitly forward-looking statements in any article that we mark as evergreen.
