### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/

### ISSUE THREAD

**Issue by AnthonyKeydel** [kubernetes/website#31824]
Update the aliasing instructions on this page to reflect the limitations listed in this issue:
https://github.com/kubernetes/kubernetes/pull/105141

There should be a footnote notifying users that setting flags/options in your alias requires the = format.
It is a simple fix, but hard to find.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/ is served due to a bug. This page should actually be [headless](https://gohugo.io/content-management/page-bundles/#headless-bundle).

We should fix that first, then consider the issue that you reported @AnthonyKeydel. That issue also applies to the intended page: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#optional-kubectl-configurations-and-plugins

/language en
/kind bug

**Comment by sftim** [comment]
I'm not sure that _Install and Set Up kubectl on Linux_ is the right place to document the caveat you're mentioning, though @AnthonyKeydel 

How about making the change to https://kubernetes.io/docs/reference/kubectl/overview/ instead?
