### ISSUE TITLE
kube-scheduler

### ISSUE THREAD

**Issue by GioBVVF** [kubernetes/website#31834]
i didn't find option "--scheduler-name"

**Comment by sftim** [comment]
Hi @GioBVVF 

Which web page didn't have the option that you mentioned?
/triage needs-information

**Comment by sftim** [comment]
I'm not sure what the bug is. In Kubernetes v1.23, the `kube-scheduler` doesn't support setting `--scheduler-name` on the command line.

If you are using a different version of Kubernetes, consult the version of that reference page that matches version of Kubernetes you are running. There is a version selector top right.

/remove-triage needs-information
/triage support

**Comment by GioBVVF** [comment]
what's the last version that support this setting ?

**Comment by tengqm** [comment]
https://github.com/kubernetes/kubernetes/commit/c13c3ebc793013c1f6ccd4c28312f63edadc5c54
