### ISSUE TITLE
目录安排问题

### ISSUE THREAD

**Issue by JunjieLl** [kubernetes/website#32194]
目录安排比较混乱，好好的入门硬是不在入门那里，给个安装教程就入门了？

**Comment by 1qiqiyang** [comment]
> 目录安排比较混乱，好好的入门硬是不在入门那里，给个安装教程就入门了？

确实 混乱

**Comment by mengjiao-liu** [comment]
The Chinese version is synchronized with the English upstream version, so if you need to change the site directory structure, the upstream English directory needs to be changed.

Feel free to reopen this issue, preferably in English so that people who review the English upstream version can discuss it.

/close
