### ISSUE TITLE
Missing /docs/tutorials/clusters/seccomp page or this link is incorrect

### ISSUE THREAD

**Issue by javadoors** [kubernetes/website#32273]
**This is a Bug Report**
There is a link /docs/tutorials/clusters/seccomp on line 481 of the page content\en\docs\reference\labels-annotations-taints\_index.md,but this link does not exist.

**Problem:**
There is a link /docs/tutorials/clusters/seccomp on line 481 of the page content\en\docs\reference\labels-annotations-taints\_index.md,but this link does not exist.

**Proposed Solution:**
Confirm this link /docs/tutorials/clusters/seccomp  is correct or not,
1) if it is correct, you need to supplement the content related to the link.
2) If it is incorrect, you need to modify the link address.

**Page to Update:**
https://kubernetes.io/docs/reference\labels-annotations-taints\_index.md
https://kubernetes.io/docs/tutorials/clusters/seccomp

v1.23

NA

**Comment by sftim** [comment]
https://kubernetes.io/docs/tutorials/clusters/seccomp/ redirects to https://kubernetes.io/docs/tutorials/security/seccomp/

We should update https://kubernetes.io/docs/reference/labels-annotations-taints/ so that it hyperlinks to https://kubernetes.io/docs/tutorials/security/seccomp/ instead.


/language en
/help
/triage accepted

**Comment by tewarig** [comment]
can I work on this?

**Comment by PriyanshuAhlawat** [comment]
#32279

**Comment by mehabhalodiya** [comment]
Closing this issue as it got resolved in #32279 
/close
