### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-linux/

### ISSUE THREAD

**Issue by CarlosMendozaB** [kubernetes/website#32424]
It would be good to count link/instructions to install curl: "**sudo apt install curl**"

**Comment by sftim** [comment]
Instead of providing (Debian-specific) instructions, we can - maybe should - explicitly state that the `curl` tool is a prerequisite for the _Install kubectl binary with curl on Linux_ method.

Readers should be able to figure out for themselves how to install `curl`; if not, I dare say they won't find Kubernetes easy overall.
