### ISSUE TITLE
Network Policies

### ISSUE THREAD

**Issue by goombah88** [kubernetes/website#32801]
While working through the Killer Shell scenario for NetworkPolicies to prep for my CKA, I used the example [HERE](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource) but it failed validation. When I looked at their solution it had one tiny difference, they had a - in front of "ports:" and you guys didn't. Based on the reference docs it appears ports does expect an array which would mean that you are missing the hyphen.

docs:
----------------------
```
ports:
- protocol: TCP
  port: 5978
```

solution from [killercoda.com](https://killercoda.com/killer-shell-cka/scenario/networkpolicy-namespace-communication)
----------------------------------------------------------------------------------------------------------------------------------------
```
- ports:
  - protocol: TCP
    port: 53
```

**Comment by tengqm** [comment]
@goombah88 The indentation of list items may be the source of confusion. Once you indent all list items under a given key, the parent element of the 'ports' attribute becomes more evident. The example on the website is correct. I'm not sure about the solution from killercoda.com. If you put `ports` as the first key of a list item object, if will carry the `-` bar **for that list item**, if `ports` is not the the first key, you will indent it rather than adding another `-` before it.

Anyway, I'm fixing the example in hope things become clearer for readers.
