### ISSUE TITLE
What is the difference between various DaemonSet statuses ?

### ISSUE THREAD

**Issue by bigdatasourav** [kubernetes/website#33503]
What is the difference between various DaemonSet statuses like currentNumberScheduled, desiredNumberScheduled, numberAvailable, numberMisscheduled, numberReady and numberUnavailable. The normal description for these statuses is not very clear. https://docs.okd.io/latest/rest_api/workloads_apis/daemonset-apps-v1.html#status

**Comment by sftim** [comment]
/kind support
/language en

@bigdatasourav you might like to frame this as a request to improve the docs, rather than for advice. GitHub is not the right place for support requests.

If you _are_ looking for help, you might ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
