### ISSUE TITLE
Install and Set Up kubectl on Linux - No set of instructions actually works for WSL + Ubuntu

### ISSUE THREAD

**Issue by Asvarduil** [kubernetes/website#34224]
None of the sets of instructions is working on Windows Linux Subsystem / Ubuntu.

1. CURL
The CURL instructions receive an error `Permissions Denied`, likely due to my default path being `mnt/c/windows/windows32`. Something that could make these instructions more helpful is telling us a better place to install kubectl to.

2. Native Package Management
Step 3 of this set of instructions does _not_ create a valid GPG entry, therefore the final step does not work correctly.

3. 'Other' Package Management
After running these steps, I get the error message `E: Cannot locate package kubectl` as if they outright did not work.  No further information is given.

I highly recommend updating these steps with more descriptive information on how to overcome these error states.  I attempted to search StackOverflow and other developer resources, but could find no information on what to do if kubernetes fails to install.

**Comment by jihoon-seo** [comment]
Related page: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

**Comment by NitishKumar06** [comment]
@Asvarduil I think you need to be a root user first. Use `sudo -i` command first and then execute the other commands.

**Comment by sftim** [comment]
The issue with the PGP keys is a Kubernetes issue rather than a documentation bug. At the moment, package generation and signing happens outside the Kubernetes project as a best-effort activity by some Google staff.
I'm not sure if there's an issue specifically to track this for `kubectl`. https://github.com/kubernetes/release/issues/913 is perhaps the closest that exists.
@Asvarduil that information doesn't help you so much but perhaps it provides context at least? You're welcome to upvote https://github.com/kubernetes/release/issues/913 to highlight the shortcoming.

We _could_ update these instructions to mention that the Windows instructions are for Windows itself, and that the Linux instructions are for typical Linux systems.

**This** issue could become a feature request to enhance the Install and Set Up kubectl on Windows page to also cover installing kubectl within WSL.

Separately, but related, we could add a prerequisitive comment for less experienced readers, at the start of https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux
The comment should explain that before you try to download `kubectl`, you must be in a directory to which you have write access.

**Comment by sftim** [comment]
BTW, you don't need superuser access to install kubectl

**Comment by Asvarduil** [comment]
@sftim - Thank you for the info, recommendations and responses!  

I am a newcomer to kubernetes and cloud technology writ large.  As a newcomer, additions of clarifications are simply too valuable to folks in my position.  Adding more clarification doesn't just help me, but other people in my position.  

I also upvoted kubernetes/release#913 as requested - I didn't know that the PGP step of the Native Package Management instructions had an actual problem, but hopefully this helps advance the fix that issue.

I appreciate all the help, thank you all very much!

**Comment by sftim** [comment]
Anyone reading this: it's not a simple fix. Please bear that in mind before opening PRs with a fix.

That said, improvements really are welcome; you just might need to think them through a bit. Try hard _not_ to advise people to skip PGP checks; these security checks exist for a good reason. It's OK to tell people that the repository signatures are invalid due to a bug.

/language en
/triage accepted

**Comment by BenTheElder** [comment]
> It's OK to tell people that the repository signatures are invalid due to a bug.

See https://github.com/kubernetes/kubernetes/issues/110667#issuecomment-1160787376 for more discussion on why the signatures should be valid but yum can't handle them / yum's repo signature check is broken. Since yum is deprecated perhaps the path forward is to point people towards a non-deprecated tool (and if it is also broken, to fix it / file an issue upstream).

Independently, we should be moving to a community controlled package host as sftim already mentioned, help with https://github.com/kubernetes/release/issues/913 would be very welcome.

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/35868 (I think)

**Comment by sftim** [comment]
Rather than set `gpgcheck=0`, let's just not specify a value for `gpgcheck`.

**Comment by sftim** [comment]
/priority important-longterm

At a minimum, we could tell readers that there are snags.

**Comment by mrgiles** [comment]
@sftim, I think that this issue should be retitled from: **Install and Set Up kubectl on Linux - No set of instructions actually works** -> to: **Install and Set Up kubectl on WLS Linux - No set of instructions actually works**. The current title suggests that the installation instructions don't work on _ANY_ Linux distribution, which I think it's inaccurate, this looks like an issue with Windows Subsystem for Linux (Note: I don't have a Windows system to test this).

**Comment by sftim** [comment]
I've gone for
/retitle Install and Set Up kubectl on Linux - No set of instructions actually works for WSL + Ubuntu

**Comment by BenTheElder** [comment]
NOTE: Package hosting has moved to the community package host since this was filed.

This should probably be re-evaluated in light of the current package hosting / signing / ...

**Comment by sftim** [comment]
@Asvarduil is this still a concern?
