### ISSUE TITLE
Linux kubectl package install instructions recommend dummy package

### ISSUE THREAD

**Issue by dhs-rec** [kubernetes/website#34275]
Hi,

apt-transport-https is a dummy package since apt 1.5, means it's not needed anymore as of Debian 10 and Ubuntu 18.04.

**Comment by sftim** [comment]
/retitle Linux kubectl package install instructions recommend dummy package
This issue is about https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

/kind cleanup
/language en

The fix would be to omit mentioning `apt-transport-https`, provided that we are confident that all readers are using at least Debian 10. I think the Ubuntu side of things we can take for granted.

/priority awaiting-more-evidence

**Comment by Rishit-dagli** [comment]
> The fix would be to omit mentioning `apt-transport-https`, provided that we are confident that all readers are using at least Debian 10. I think the Ubuntu side of things we can take for granted.

We can also rather add a piece of text, something like:

```
If you use Debian 9 (stretch) or earlier you would also need to install `apt-transport-https`:
```sh
sudo apt-get install -y apt-transport-https
'``
```

**Comment by sftim** [comment]
@dhs-rec - would you be willing to update the issue description to incorporate the idea from https://github.com/kubernetes/website/issues/34275#issuecomment-1155993890 ?

**Comment by akankshakumari393** [comment]
I have this PR #35083 raised. I hope that helps.

**Comment by dhs-rec** [comment]
> @dhs-rec - would you be willing to update the issue description to incorporate the idea from [#34275 (comment)](https://github.com/kubernetes/website/issues/34275#issuecomment-1155993890) ?

Sorry, didn't see this earlier. However, looks like @akankshakumari393 already did exactly this in #35083.
