### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by rbeldin** [kubernetes/website#34479]
I'm learning kubernetes and stepping through the various scenarios.   I came across an issue that I can't tell if it is my own fault or some subtle issue with the yaml file. 

When I try to execute: 

kubectl apply -f https://k8s.io/examples/application/mysql/mysql-statefulset.yaml

After successfully doing the previous steps, I get: 

kubectl apply -f https://k8s.io/examples/application/mysql/mysql-statefulset.yaml
The StatefulSet "mysql" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mysql", "app.kubernetes.io/name":"mysql"}: `selector` does not match template `labels`

Should the mysql-statefulset.yaml be altered on line 15 (app: mysql) to match line 8 (app: mysql-server)?  Or is there some other subtlety about label matching that will break how this app is structured? 

Thanks

**Comment by NitishKumar06** [comment]
HI @rbeldin , Edit your YAML files and set the same key-value pairs in both `selector.matchLabels` and` metadata.labels.`

**Comment by jihoon-seo** [comment]
@NitishKumar06 I am afraid to say that your suggestion is not a proper solution. 
If K8s doc has bug, then it would be great to fix that.

@rbeldin This is reproducible for me.
/triage accepted

```
❯ kubectl apply -f https://k8s.io/examples/application/mysql/mysql-configmap.yaml
configmap/mysql created

❯ kubectl apply -f https://k8s.io/examples/application/mysql/mysql-services.yaml
service/mysql created
service/mysql-read created

❯ kubectl apply -f https://k8s.io/examples/application/mysql/mysql-statefulset.yaml
The StatefulSet "mysql" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mysql", "app.kubernetes.io/name":"mysql"}: `selector` does not match template `labels`
```

And rather than your suggestion (`mysql-statefulset.yaml` L15 `mysql` → `mysql-server`),
I suggest this:

[L8 in `mysql-statefulset.yaml`]
```diff
-app: mysql-server
+app: mysql
```

This will make the [following command `kubectl get pods -l app=mysql --watch`](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#:~:text=progress%20by%20running%3A-,kubectl%20get%20pods%20%2Dl%20app%3Dmysql%20%2D%2Dwatch,-After%20a%20while) work.

**Comment by Rishit-dagli** [comment]
I'd love to work on this
/assign
