### ISSUE TITLE
Cannot find page about adding Windows nodes

### ISSUE THREAD

**Issue by cqpr-nnit** [kubernetes/website#34476]
Everytime I try to go to https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ I get redirected to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ - Where is the guide to adding windows nodes?

**Comment by neolit123** [comment]
/sig docs windows cluster-lifecycle
/kind bug

seems like a link problem?
old page for 1.23 is here
https://v1-23.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes

**Comment by sftim** [comment]
/remove-kind bug

There is now no specific guide for creating Windows nodes (nor is there one for creating Linux nodes). SIG Windows opted to remove the guide that did exist, in PR #33324

If someone wants to write a **new** task page about adding a node to an existing cluster, we (SIG Docs) welcome it. That page could use [tabs](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs) to cover Linux-specific vs Windows-specific details.

If the redirect is confusing, we could remove it.

/remove-sig windows
/remove-sig cluster-lifecycle

**Comment by sftim** [comment]
/retitle Cannot find page about adding Windows nodes

**Comment by neolit123** [comment]
> There is now no specific guide for creating Windows nodes (nor is there one for creating Linux nodes). SIG Windows opted to remove the guide that did exist, in PR https://github.com/kubernetes/website/pull/33324

as discussed in the sig windows meeting yesterday, the removal of the old page with idea to have single linux / windows page might have been a bit too early. the windows setup is still quite different around cni.

we may have to have to link to external resources such as the Calico for Windows guide and tagging these parts as 'third party' at a k8s.io page.

@marosset @jsturtevant

**Comment by sftim** [comment]
A couple of things:
- We could use a tutorial or task page on adding a node to your cluster anyway. https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md could be an inspiration
  I don't want something GCE-specific, but I am happy to go into more detail **specifically for nodes** (we've decided as a project that we won't yet host an entire KTHW-style walkthrough of setting up a working cluster with a control plane, addons, etc).
  Adding a custom node is a task that folks legitimately might want to learn independently from the rest of those steps.
  - If we had that page, we could split it into the Windows and Linux versions as these stories are pretty different.
  - we _wouldn't_ cover much about network plugin setup, because you're adding one node to a cluster and I assume your cluster was working before you started. We'd instead list prerequisites.
- :thought_balloon: a **blog article** about setting up your cluster to include Windows nodes?
  - would be very welcome (especially if it focused on deploying a hybrid cluster, so we're neutral on the Pod OS)

**Comment by marosset** [comment]
> There is now no specific guide for creating Windows nodes (nor is there one for creating Linux nodes). SIG Windows opted to remove the guide that did exist, in PR #33324
> 

@sftim - IIRC SIG-Windows opted to remove this content based on some of the review comments in https://github.com/kubernetes/website/pull/32862#pullrequestreview-938361343

The way we interpreted these was pages in k/website were discouraged from providing step-by-step instructions for configuring none K8s-owned components (like CNI solutions). Did we mis-understand that?

SIG-Windows is in the process of moving a lot of the docs that got removed to https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/ and were hoping to link to this guide from k/website.
Our thinking here was that having these guides hosted in a k-sigs repository would have more of a community-owned feeling.

**Comment by sftim** [comment]
> The way we interpreted these was pages in k/website were discouraged from providing step-by-step instructions for configuring none K8s-owned components (like CNI solutions). Did we mis-understand that?

It's OK to provide step-by-step guides, but we don't like to give details where we're picking a particular solution from the ecosystem.
For example, https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#preparing-the-hosts says that you need a compatible container runtime. What we don't say is something like:

> For this example, we'll use Acme Containers.
> Go to acmecontainers.com and download it, then run `acmesetup.sh`.
> We'll walk you through configuring this interactively, but you can also do a scripted deploy…

because that's not very fair on every other CRI-compatible container runtime that we didn't pick.
Node OS, different story. We support 2 OS kernel flavors, so we can document the story for a Linux node and for a Windows node.

There'll come a point where we suggest setting up networking, and that's where ideally we send folks off to https://landscape.cncf.io/ to pick something (if we're not happy with https://landscape.cncf.io/ then the fix is to work on improvements to that site instead - it's open source IIRC).

The existing guide for setting up a Windows-compatible clister did need work - it covered lots of detail outside the specific topic of cluster setup - and I'm glad it got looked at, but that doesn't mean we can never have a guide to deploying a Windows node. A page on that, that follows our style and content guides, would be a nice addition to this site.

Hope that's more clear.

**Comment by sftim** [comment]
If we do add a page on setting up a Windows node, this should be part of an ambition to also document adding a Linux node (in about the same detail).

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/37266

**Comment by tengqm** [comment]
This issue is still there to be resolved.
/remove-lifecycle stale

**Comment by twity1337** [comment]
Instead of redirecting, could we at least temporarily insert a warning page that hints about this issue (or the [SIG windows guide](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/ ) respectively)?
For me, it was very confusing because it is not clear that the target page ("Creating a cluster with kubeadm") is not focused on Windows. Especially when following links from search engines or forums, this is not resulting in a good user experience.

If a warning page is too much effort, at least drop the redirect and let it result in a standard 404.

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/37266#issuecomment-1274509225 explains how - as I see it - things stand with regard to documenting node setup. 

@twity1337 please consider filing a separate issue that covers the improvement you'd like to see - https://github.com/kubernetes/website/issues/new/choose
It helps if you can frame it by describing the outcome (eg: “there is a tutorial that explains how to run PowerShell commands to set up an existing Windows server as a node in my existing Kubernetes cluster”). It's also OK to propose an approach to how we achieve the outcome.

_This_ issue is mostly framed as a support query (and, because we've answered the question, it's less helpful to use this for tracking related requests).

**Comment by marosset** [comment]
We have some guides here https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md and are still working on cleaning them up.

After the cleanup we can revisit linking to the guides from www.k8s.io

**Comment by sftim** [comment]
> linking to the guides from [www.k8s.io](http://www.k8s.io/)

We'd much prefer to have that documentation within the Kubernetes docs themselves.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/ has task pages for node _upgrades_.

Ideally we'd have two more task pages:
1. adding a Linux node to your cluster
1. adding a Windows node to your cluster

This issue is about the second page (adding a Windows node)

/language en
/triage accepted

**Comment by jsturtevant** [comment]
The Linux tutorial was removed and so we followed suit with removing [windows](https://github.com/kubernetes/website/pull/33324).  

We [removed the windows task pages](https://github.com/kubernetes/website/pull/33324) based on [feedback ](https://github.com/kubernetes/website/pull/32862#pullrequestreview-938361343) when we tried to update the doc that had the "adding a windows node to your cluster" section, in particular feedback around the third party content that specified how to [set up CNI](https://github.com/kubernetes/website/pull/32862#discussion_r847575421).  In a call, we were given direction to host tutorials outside of the kubernetes docs.

What would the expected content of the two pages be?  Does it include scripts? Does it mean installing and configuring the runtime? [CNI](https://github.com/kubernetes/website/pull/32862#discussion_r847574719)?  If all the other things are in place then it really is as simple as `kubeadm join` which was the intent of moving towards just pointing to the `kubeadm join` docs.

**Comment by sftim** [comment]
The best approach _ceteris paribus_ would be to start with the Linux task page, get that written or at least outlined, and then write Windows equivalents for the same section.

We can and should define reasonable prerequisites including having the OS already installed, swap turned off on Linux, networking (but not CNI plugin) up, enough RAM and enough local storage, etc.

I'm fine if there's a big overlap with https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes; however, someone who has a 4 node cluster and wants there to be 5 nodes probably won't look at a page titled “**Creating a cluster with kubeadm**”. That's why these task pages are worth adding.

**Comment by jsturtevant** [comment]
> The best approach _ceteris paribus_ would be to start with the Linux task page, get that written or at least outlined, and then write Windows equivalents for the same section.

+1 We can follow that as the example, it is required for windows to join a node anyways.

**Comment by sftim** [comment]
Anyway, there are compromises that don't set the problematic precedent. For example:

New suggestion:
- drop the existing redirect
- redirect to a new page explaining that the documentation for Windows node setup is incomplete, and that (if you read through it) does help people discover what's available

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/34476#issuecomment-1482727975

**Comment by neolit123** [comment]
i don't disagree that that proposed separate tasks pages are the way to go, it's just not clear to me how would the Windows task page look like given the tight coupling with external solutions.

> In other works, I soft disagree with hyperlinking to external docs like https://github.com/kubernetes/website/issues/34476#issuecomment-2340637658 suggests. Every other GA feature we either document appropriately or are tracking work to fix that.

the page literally branches into 3 pages with external dependencies for CNI installation:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes

are you suggesting that the contents of the page should be in a k8s.io task but at the end of it we are still going to link to the sig-windows tools repo for CNI installation?

should we also talk about the Windows CNI story here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network
and again, link to the sig-windows-tools guides?

**Comment by sftim** [comment]
If Microsoft have advice about Windows and Kubernetes, we _can_ link to that (eg if Microsoft recommend a particular network plugin), because Microsoft clearly are the OS vendor and you need an OS in order to install Kubernetes nodes.

See https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed for the formal policy.

**Comment by sftim** [comment]
Ideally, move this discussion to another issue, and close this support query.

**Comment by neolit123** [comment]
> That's the precedent we don't wish to set. If a SIG wants to document a feature, they should put the docs on the Kubernetes website itself.

i'm bit confused how that is degrading to the documentation.

today we still link to external pages for CNI installation.
i.e. if someone wants kubeadm + Callico they go to the kubeadm "create a cluster page", reach the CNI step, open the "addons page" click Callico which takes them externally.

the difference here is that SIG Windows owns a wrapper guide located at sig-windows-tools.

> (relevant detail: the Linux Foundation exams permit reading the docs, but don't allow following such hyperlinks)

not relevant to Windows nodes i would assume.

**Comment by neolit123** [comment]
i can send a PR that:

- creates the Linux task page by moving / refactoring the existing "join node" contents from the "create a cluster" page:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes
- creates the Windows task page by taking the content from https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md
- at the end of the Windows page we add note/disclaimer whatever that says that CNI on Windows needs special handling and we link to the various CNI choices at:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md#networking-configuration
- adds tabs in the https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes to choose between OS for joining nodes.

if that doesn't sound right i don't understand how the Windows documentation can improve anytime soon.
also i don't think it's a GA blocker given CNI setup is external to kubeadm.

**Comment by sftim** [comment]
Yep, that sounds good.

>  i.e. if someone wants kubeadm + Callico they go to the kubeadm "create a cluster page", reach the CNI step, open the "addons page" click Callico which takes them externally.

This is fine; you need a network plugin to have a working cluster, and the install guide for Calico is (should be) external. We wouldn't dual source it.

> wrapper guide located at sig-windows-tools

We cannot - even at a stretch - call that linking to canonical vendor documentation.

@neolit123 I think you're correct to surmise that the Linux Foundation exams don't expect you to manage Windows nodes, but I also don't want to find that there's a CKWA qualification coming or something and that we now need to change our docs policies. The policies aim to be vendor neutral and that's as it should be. We try not to pick winners, even if the winner is down to the Linux Foundation using Linux.

**Comment by tengqm** [comment]
I'd vote for adding a task for Windows nodes, documenting whatever people need to know from Kubernetes's side. Speaking of external dependencies, especially CNI or similar stuff, it is still fine to install hyperlinks.

**Comment by divya-mohan0209** [comment]
Summarizing my understanding of the situation here (please correct me if I'm wrong):

- Currently, we do not have a section in our docs dedicated to adding Windows/Linux nodes. We are discussing how to create one for Windows because kubeadm support for Windows is becoming generally available. However, we are faced with two problems:
  - Problem 1: Lack of a page dedicated to Linux
  - Problem 2: There are very specific steps required for the installation of the CNI (i.e. Calico, Flannel) as outlined [here](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md#networking-configuration). While our [docs policies](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed) allow including content that's needed for Kubernetes to function, the Linux Foundation exams do not allow following hyperlinks to external links. 
  
My two cents: As SIG Docs, we do not want to set the precedent of having GA features incompletely documented or be prescriptive about vendors/projects. Therefore, In the spirit of staying vendor-neutral, I mostly agree with the approach outlined in [this comment](https://github.com/kubernetes/website/issues/34476#issuecomment-2340895434), even though it isn't 100% ideal. This is, of course, with the caveat of special handling being documented explicitly and hyperlinking to the GitHub repo for sig-windows-tools. If and when we find a better way to refer to those documents in the future, we improve the documentation by adhering to our policies.

**Comment by neolit123** [comment]
thanks for the comments.

now tracked in:
https://github.com/kubernetes/website/issues/47884

/close
