### ISSUE TITLE
Query about whether Prometheus, Grafana etc are Kubernetes add-ons

### ISSUE THREAD

**Issue by younaman** [kubernetes/website#34485]
When Reading the installing addons pages, I am a little confusing that why Prometheus and Grafana are not listed in the add-on pages?

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/concepts/cluster-administration/addons/

**Comment by sftim** [comment]
I'd say that a Kubernetes add-on extends Kubernetes and isn't useful by itself. We could clarify the concept page so that it's more obvious why Prometheus is not an add-on (you can use it without Kubernetes).

The same is true of Grafana.

**Comment by younaman** [comment]
@sftim Thanks for your reply! So the Prometheus and Grafana can be only called "Kubernetes third party applications?"

By the way, can I separate these third-party applications to Networking and Network Policy, Service Discovery, Visualization & Control, and Infrastructure?

From the third-party applications view, can the Prometheus be called "Infrastructure" and Grafana be called "Visualization & Control"?

I am looking forward to your reply!

**Comment by reylejano** [comment]
Hi @younaman, since Tim has clarified why Prometheus and Grafana are not listed on the add-ons page, I'm closing this issue 

Prometheus is an open source monitoring tool
Grafana visualizes the Prometheus data

Here's a few other resources: 
- [#prometheus channel](https://kubernetes.slack.com/archives/CD0T3TQUR) 
- [#kubernetes-users channel](https://kubernetes.slack.com/archives/C09NXKJKA) on the Kubernetes Slack
