### ISSUE TITLE
Assigning Pods to Nodes - example missing mentioned values

### ISSUE THREAD

**Issue by xeberth** [kubernetes/website#34573]
![Screenshot 2022-06-24 4 18 37 PM](https://user-images.githubusercontent.com/54719682/175677544-c98b5151-ea15-4e44-8608-773077b8a8e3.png)
The label with the key topology.kubernetes.io/zone not exist in the example for node affinity:

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity

**Comment by sftim** [comment]
/kind bug
/language en
/triage accepted

Thanks for reporting this.

I would fix this discrepancy by copying the example manifest to make a _new_ example, that **does** use the key `topology.kubernetes.io/zone` key. The Git history might show a previous version that already did, which would make it easier to write the copy.

The reason I'd make that copy is because I suspect that more than one page relies on the same example (and that's why an unhelpful change has slipped through).
