### ISSUE TITLE
Improvement for k8s.io/docs/tasks/job/automated-tasks-with-cron-jobs/

### ISSUE THREAD

**Issue by aarashy** [kubernetes/website#34652]
I would've liked to see the full resource definition of CronJobs on this page, including the Spec and the Status.

**Comment by aarashy** [comment]
The information I was looking for was here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#cronjobstatus-v1-batch

Maybe would be nice to have a link to from the page in question

**Comment by utkarsh-singh1** [comment]
Hi @aarashy , Just curious where do you want to add the full resource definition of CronJobs because the config file is already provided, we can find the spec in the same [here](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#creating-a-cron-job).

However we can always add this link in the 

> Whats Next 

section.

**Comment by sftim** [comment]
+1 to adding a link to the API reference in the What's Next section. 

I notice that https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#what-s-next already links to the API reference so this is about saving readers one click.

/kind feature
/priority backlog
/language en
/triage accepted

I'm not marking this as a good-first-issue because it's a very low priority improvement to make.

**Comment by utkarsh-singh1** [comment]
Hi @aarashy, would you like to attend this issue further, or also you can close it down .
