### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by pesseguita** [kubernetes/website#34795]
Please explain all fields in yaml files

**Comment by utkarsh-singh1** [comment]
Hi @pesseguita, you can find about all fields in yaml file here https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

**Comment by pesseguita** [comment]
Hi @utkarsh-singh1 , but you are not explaining in the tutorial (and it is a tutorial), and then of the yaml is scattered all over.

**Comment by divya-mohan0209** [comment]
@pesseguita : If you see how our tutorials are structured at - https://kubernetes.io/docs/tutorials/ and have gone through them, you'll notice that we start from the basics and build on those foundational elements. You're expected to have gone through the others and understood the basics since the stateful applications section is intermediate level. 
Also, we've explicitly recommended that the [Standard Glossary](https://kubernetes.io/docs/reference/glossary/?fundamental=true) page be bookmarked for further reference. 
Given the context above, if there are further suggestions on how we could improve, we'd welcome them. 
/remove-lifecycle rotten
