### ISSUE TITLE
Add a Bionic Reading® toggle for nuerodivergent readers

### ISSUE THREAD

**Issue by jdbohrman** [kubernetes/website#34852]
Hey team,

I'm both ADHD and Autistic and I recently came across this really cool accessibility tool for ND individuals and tested it out for myself and was amazed at how much easier it made reading content. 

It should be pretty simple to add a toggle that turns highlighting from [Bionic Reading ](https://bionic-reading.com/) to enable neurodivergent readers to more easily parse documentation.

**Comment by jdbohrman** [comment]
> /kind feature
> /area web-development
> 
> @jdbohrman would you be confident to enhance the issue description to explain how a contributor could make a start on this work?
> 

I'd be happy to make an attempt! It's been awhile since I dove into the internals of the k8s site but I'll follow up in the morning. It should be pretty easy! 🙂

**Comment by a-mccarthy** [comment]
hey @jdbohrman are you still willing to update this issue with more details on how to implement this? Seems like cool functionality to offer our readers, i'd be interested in hearing more about how we can make this a possibility :)

**Comment by jdbohrman** [comment]
@a-mccarthy Hey Abagail! I am more than happy to dive deeper into this. Let me follow up next week after I've done a bit of research!

**Comment by jdbohrman** [comment]
I apologize for the delay in getting back to you all. I've been swamped lately 😅

**Comment by divya-mohan0209** [comment]
Hello @jdbohrman , we appreciate that you took time to flag this issue and have been awaiting further details for implementation so that we can open it up to our contributors for ~6 months now. We understand that you may not have the bandwidth to get back and are closing it off right now. Whenever you do have some free cycles, please consider reopening it & initiating the discussion with the details. We'll be happy to pick it up where we left off :) 
/close
