### ISSUE TITLE
Ambiguity in minimum number of nodes to maintain redundancy

### ISSUE THREAD

**Issue by SamarthMayya** [kubernetes/website#35156]
The [documentation](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/), in my opinion needs a better explanation as to why 3 nodes would eliminate redundancy. If I'm not wrong, redundancy refers to data of one node being present in at least one more node right? Then why is it necessary to have a third node?

**Comment by RA489** [comment]
@SamarthMayya It might be due to maintaining quorum odd number of nodes are required.

**Comment by RA489** [comment]
It will have fault tolerance of 1 node in case of network separation/partition.

**Comment by SamarthMayya** [comment]
You mean it would be okay to let go of one node in case a network partition happens between the control plane and the node?

**Comment by sftim** [comment]
With a two-host cluster, a single node failure leaves the cluster with one healthy node that cannot form a [voting quorum](https://en.wikipedia.org/wiki/Quorum_(distributed_computing)). Essentially, two nodes costs twice as much as one node but provides no extra resilience to node-level failure.

For the distributed fault tolerance model that Kubernetes uses, you need three.

Why does the introduction page need to explain this? The docs provide the right answer (three); we're giving the reader a basic introduction to Kubernetes itself, not teaching theories of distributed computing.

We could hyperlink to https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/ so that folks who are interested can go there to learn more and to discover even more background reading.

/language en
/priority awaiting-more-evidence

**Comment by RA489** [comment]
> You mean it would be okay to let go of one node in case a network partition happens between the control plane and the node?

In case of network partition in case of 3 nodes if one node is not available for somewhat reasons the cluster will function because it has fault tolerance of 1 node.

**Comment by sftim** [comment]
I think the tutorial is OK for the audience we have.

/close not-planned
