### ISSUE TITLE
[fr] Releases page in French is blank

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#35207]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/fr/releases/ is blank for the main page content.

**Proposed Solution:**
Delete https://kubernetes.io/fr/releases/ (fall back to English)

**Page to Update:**
https://kubernetes.io/fr/releases/

Additional Information:
/language fr

**Comment by bishal7679** [comment]
@sftim It have to be deleted https://kubernetes.io/fr/releases/
and what do you mean by fall back to english? Could you please elaborate?

**Comment by shurup** [comment]
I guess falling back means the menu link of the French website should lead to `/releases/` (i.e. its English version) instead of `/fr/releases/` since there is no content in the French version.

However, I don't understand what is the source of this URL (`/fr/releases/`). The `navbar-version-selector.html` partial seems to be incorrect as it **always** links to the `/releases/` page (despite the website's language currently in use), isn't it?

https://github.com/kubernetes/website/blob/2b53353e1eb688e028231a7ccdb217de4dc059a4/layouts/partials/navbar-version-selector.html#L6

E.g., there is the [/releases/_index.md](https://github.com/kubernetes/website/blob/main/content/pl/releases/_index.md) content for the `pl` locale, but the navigation menu on https://kubernetes.io/pl/ still leads to the `/releases/` page, not `/pl/releases/`.

**Comment by mtardy** [comment]
There are 2 issues here:
- I took a look and indeed, [this addition](https://github.com/kubernetes/website/pull/30233) introduced the issue since it added a new page under the `releases` subfolder.
- Moreover, @shurup is correct, you can get to these translation by going on the page https://kubernetes.io/releases/ and clicking the language dropdown, and selecting Français but the `navbar-version-selector.html` always redirect to the English version.

**Comment by mtardy** [comment]
> There are 2 issues here:
> 
> * I took a look and indeed, [this addition](https://github.com/kubernetes/website/pull/30233) introduced the issue since it added a new page under the `releases` subfolder.
> * Moreover, @shurup is correct, you can get to these translation by going on the page https://kubernetes.io/releases/ and clicking the language dropdown, and selecting Français but the `navbar-version-selector.html` always redirect to the English version.

Both issues were resolved and merged!
https://github.com/kubernetes/website/pull/36901
https://github.com/kubernetes/website/issues/36903
