### ISSUE TITLE
[ko] Translate untranslated glossary terms and description of each tag into Korean

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#35259]
**This is a Feature Request**

**What would you like to be added**
Translate untranslated glossary terms and description of each tag into Korean.

link to `en` entry: https://kubernetes.io/docs/reference/glossary/?all=true
link to `ko` entry: https://kubernetes.io/ko/docs/reference/glossary/?all=true

**Why is this needed**
It has not been translated into Korean yet.

**Comments**

/language ko
/assign

**Comment by seokho-son** [comment]
Hi @kyungjin99 
Thank you for rising this issue :)
I am sure there are several terms (docs) which are not localized into Korean yet.

- https://github.com/kubernetes/website/tree/main/content/en/docs/reference/glossary
- https://github.com/kubernetes/website/tree/main/content/ko/docs/reference/glossary

I hope to note that this issue can be separated into several specific issues since each term can be localized individually.

**Comment by kyungjin99** [comment]
Hi @seokho-son, thank you for letting me know :)
I am also working on other untranslated pages, so I will open a new issue regarding that.
For glossary terms, I will create a new issue individually next time.
Should I close it with `Close as not planned`?

**Comment by seokho-son** [comment]
@kyungjin99 
Maybe we can utilize this issue to accomplish localizing all glossary terms. :) 
(in this case, we need to update this issue with actual task list)

or.. close this issue and open individual issues.

to close this issue, you can simply leave `/close` comment. k8s ci bot will close this issue on behalf of you :)
