### ISSUE TITLE
prioritize minikube documentation for new developers

### ISSUE THREAD

**Issue by klaases** [kubernetes/website#35519]
This issue attempts to prioritizes the documentation recommendation of **minikube** ahead of **kind** as the very first tool that new developers should use when initially learning kubernetes.

In addition, the goal is to ensure that developers have an easier time in getting started with Kubernetes by adopting **minikube** from the start.

We have found that **kind** is oriented more towards testing kubernetes rather than for application development by new software engineers.

**Comment by klaases** [comment]
Hi @divya-mohan0209 and @sftim, I have created this issue in response to your comments on the related PR #35461 and I do appreciate your feedback.

**Comment by sftim** [comment]
Some people prefer `kind`; others prefer `minikube`. We've listed those two in alphabetical order; maybe we could make it extra clear that the docs are giving these equal footing.

We could also add either a blog article, extra context to the docs, or both, in order to help newcomers pick which tool to use depending on their work context. Along with `kind` and `minikube` a blog article could mention 3rd party distributions of Kubernetes that are relevant to learners.

@klaases would you be interested in making those improvements? If no, we can leave this issue open as a place to discuss what appetite other contributors might have, and maybe to plan out some work.
/language en

**Comment by klaases** [comment]
> @klaases would you be interested in making those improvements?

Hi @sftim, yes, I would certainly be interested:  

- equal footing for both `kind` and `minikube`
- blog article on minikube
- extra content in the docs*

For "extra content in the docs", do you have an example of which docs to start with first?

I'd like to keep the issue open a little longer in case anyone else has feedback, and to help with planning.

**Comment by sftim** [comment]
> I think as Kubernetes and CNCF we need to have single message toward what is Kuberente's recommended tool for local users. to avoid fragmentation and confusion for the users.

Perhaps we could start a GitHub Discussion about the options we have:
- favor neither
  - and sub-options, such as some JavaScript to randomize which is shown first
- favor kind
- favor minikube

I'm up for someone starting that discussion, however it will need involvement from folks willing to moderate and to report back. It's then also more than just a docs issue.

**Comment by sftim** [comment]
> For "extra content in the docs", do you have an example of which docs to start with first?

We could improve https://kubernetes.io/docs/setup/ to give folks more of a guide to picking a tool (minikube or kind) for learning; we could also reinstate https://kubernetes.io/docs/setup/learning-environment/ with a new focus on that page being about _choice_.

We leave the actual how-do-I-use-X to the projects themselves; this avoids duplicating effort.

If someone has the appetite for it, wouldn't it be nice to update both kind and minikube to use the same customised Docsy theme as https://k8s.io/ (with some tweaks), so that navigation between the three sites feels consistent?

**Comment by cliffbr-dv** [comment]
I'm sorry to say that, but given the current state of minikube it's not the best idea to recommend it to anyone, I believe

**Comment by medyagh** [comment]
> of minikube it's not the best idea to recommend

Why is that do you mind sharing the data to back up that opinion ? according to the CNCF surveys minikube is the most popular way to start Kubernetes

**Comment by medyagh** [comment]
> > I think as Kubernetes and CNCF we need to have single message toward what is Kuberente's recommended tool for local users. to avoid fragmentation and confusion for the users.
> 
> Perhaps we could start a GitHub Discussion about the options we have:
> 
> * favor neither
>   
>   * and sub-options, such as some JavaScript to randomize which is shown first
> * favor kind
> * favor minikube
> 
> I'm up for someone starting that discussion, however it will need involvement from folks willing to moderate and to report back. It's then also more than just a docs issue.

That seems lime a fair thing to do, who would be a good person to start this discussion ?

**Comment by mrbobbytables** [comment]
FWIW - in general we've tried to point end users to minikube and developers/contributors to kind, and I'm in favor of making that distinction. Minikube is meant for people to spin up, learn and do local development with Kubernetes. Kind if purpose built for CI and for serving the Kubernetes project (see [scope](https://kind.sigs.k8s.io/docs/contributing/project-scope/)). It's just been useful as something for people to use and quickly spin stuff up; that hasn't stopped people from opening up issues in the kind repo for things that are very clearly out of scope for it. :|

**Comment by divya-mohan0209** [comment]
@klaases : It's been quite some time. Just checking in if you're still interested in working on this issue?

**Comment by medyagh** [comment]
hi @divya-mohan0209 @spowelljr is working on this, there is a WIP https://github.com/kubernetes/sig-release/pull/2088

**Comment by divya-mohan0209** [comment]
Thanks @medyagh for confirming!

**Comment by medyagh** [comment]
thank you, and hopefully there should be follow up PRs in the reset of the Kubernetes website, may I suggest to add label help-wanted ?

**Comment by sftim** [comment]
I'm somewhat wary of highlighting this issue.

It's actually not a high priority for SIG Docs. See https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Acritical%2Furgent%2Cpriority%2Fimportant-soon for issues we'd prioritize (one of which _is_ labelled as Help Wanted).

Also, there's a potential to attract contributions of a “Minikube forever” or “kind is the best” nature, whereas that's not really the outcome we want as a project.

**Comment by BenTheElder** [comment]
This sort of discussion I'd have expected at least a nominal ping to any of the KIND maintainers 🤷‍♂️ 

KIND was built first and foremost to test Kubernetes but has found other uses.
We do support local development use cases and they are [in scope but explicitly lower priority](https://kind.sigs.k8s.io/docs/contributing/project-scope/). I think it works pretty well because there's overlap in requirements for both.

I'm not really interested in arguing which tool is "better" and we've pointedly closed any issues about this subject in the KIND repo, however, I also don't appreciate the FUD on this issue.

We've collaborated between these projects before and users will even find the default "docker" driver is highly dependent on work we've done and continue to do in KIND to make this work and I'm perfectly happy to see that working well for everyone, we can let users determine which workflow suits them best without flaming fellow projects.

> I think as Kubernetes and CNCF we need to have single message toward what is Kuberente's recommended tool for local users. to avoid fragmentation and confusion for the users.

Kubernetes thrives on having extensive user choice at all levels, from container runtime up to install tools and package management, see somewhat infamously https://landscape.cncf.io/. We don't select a single option for any other level of the stack, E.G. you'll find kOps, kube-spray, kubeadm, CAPI, etc. all mentioned.

microk8s, k3s, minikube, kind, local-up-cluster.sh, docker desktop, rancher desktop, lima/colima and more all have their trade-offs and use-cases.

> https://minikube.sigs.k8s.io/docs/benchmarks/imagebuild/minikubevsothers/

This benchmark is only relevant for single node clusters (which is not even conformant) and will be increasingly irrelevant as docker falls out of favor as a poorly supported Kubernetes CRI option ...

Using a local registry will persist across clusters with better performance and support multi-node, but isn't tested here. `kind load` is convenient but not the most performant option due to docker limitations.

There are again a LOT of options for doing local development and managing container images in clusters, YMMV.

**Comment by aojea** [comment]
> I think as Kubernetes and CNCF we need to have single message toward what is Kuberente's recommended tool for local users. to avoid fragmentation and confusion for the users.

Kubernetes and CNCF are not the same, Kubernetes as an OSS project should not enter the business of declaring winners or losers, that will hurt the community, it can suggest or recommend what is the best tool for each case based on objective reasons, but I really dislike the idea of using the Kubernetes trademark as a tool to promote specific projects.

**Comment by afbjorklund** [comment]
There were some hard feelings after the "learning environment" was removed and the tool order was reshuffled, but I thought there was some kind of agreement (or: truce? :white_flag:) in all the _other_ doc issues about the same topic...

* https://github.com/kubernetes/website/issues/31186

* https://github.com/kubernetes/website/issues/36048
  * https://github.com/kubernetes/website/pull/24533

Basically the Kubernetes project will list "all" tools (minikube/kind/kubeadm) and "all" container runtimes (docker/containerd/cri-o) and the user will pick the one that suits them. Quoted "all", because only top three fit.

* https://kubernetes.io/docs/tasks/tools/
  * kind
  * minikube
  * kubeadm

* https://kubernetes.io/docs/setup/production-environment/container-runtimes/
  * containerd
  * cri-o
  * docker
 
* https://kubernetes.io/docs/setup/production-environment/tools/
  * kubeadm
  * kops
  * kubespray

----

Maybe an actual meeting would sort it out better?

Could organize something through Slack perhaps.

**Comment by sftim** [comment]
@afbjorklund:

> Some people prefer kind; others prefer minikube. We've listed those two in alphabetical order; maybe we could make it extra clear that the docs are giving these equal footing.
> 
> We could also add either a blog article, extra context to the docs, or both, in order to help newcomers pick which tool to use depending on their work context. Along with kind and minikube a blog article could mention 3rd party distributions of Kubernetes that are relevant to learners.

This was my position in https://github.com/kubernetes/website/issues/35519#issuecomment-1201123646 and I feel it represents a position for SIG Docs and for Kubernetes. There is not strong consensus but it's there.

@divya-mohan0209 I believe you may have triaged this as accepted (which indicates an endorsement of minikube over kind) without all the context. I'm going to remove that triage _but_ if I've misunderstood then please feel free to put it back, ideally with an explanatory comment.

/remove-triage accepted

**Comment by sftim** [comment]
> Basically the Kubernetes project will list "all" container runtimes (docker/containerd/cri-o) 

Nope. See https://github.com/kubernetes/enhancements/tree/master/keps/sig-docs/1326-third-party-content-in-docs for our actual policy in this area.

**Comment by afbjorklund** [comment]
What I meant to say was not pick a single solution.
