### ISSUE TITLE
Pod Priority and Preemption - Negative value not documented

### ISSUE THREAD

**Issue by Socolin** [kubernetes/website#35640]
Hello,

Please can you document negative value for priority in https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/ 

This is only explain in this blob, https://kubernetes.io/blog/2019/04/16/pod-priority-and-preemption-in-kubernetes/ but not in the main documentation

> The non-critical workload may have many more pods that can fit in the cluster. If you give a negative priority to your non-critical workload, Cluster Autoscaler does not add more nodes to your cluster when the non-critical pods are pending. Therefore, you won’t incur higher expenses. When your critical workload requires more computing resources, the scheduler preempts non-critical pods and schedules critical ones.

**Comment by sftim** [comment]
> A PriorityClass object can have any 32-bit integer value smaller than or equal to 1 billion. Larger numbers are reserved for critical system Pods that should not normally be preempted or evicted. A cluster admin should create one PriorityClass object for each such mapping that they want.

I agree. It is not clear enough that you can have a negative priorioty. We should make the actual maximum and minimum permitted values clear.

However, the meaning of a negative priority is a _convention_. Different clusters can use their own interpretations. In the docs, we shouldn't make it appear as if the sign of the pod priority value is meaningful to core Kubernetes.

/language en
/triage accepted
/help

**Comment by mehabhalodiya** [comment]
@vaibhav2107 I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @vaibhav2107

**Comment by dipesh-rawat** [comment]
I have noticed that this issue is currently unassigned and I would be more than happy to work on this.

/assign

**Comment by dipesh-rawat** [comment]
Changes to address this issue have been merged as part #39640

**Comment by sftim** [comment]
Done

/close

**Comment by yoshigev** [comment]
Hi @sftim,

I know this is an old issue, but I want to hear your opinion.

You wrote [above](https://github.com/kubernetes/website/issues/35640#issuecomment-1202832187):

> However, the meaning of a negative priority is a _convention_. Different clusters can use their own interpretations. In the docs, we shouldn't make it appear as if the sign of the pod priority value is meaningful to core Kubernetes.

The documentation has a recommendation for using negative values for [overprovisioning](https://kubernetes.io/docs/tasks/administer-cluster/node-overprovisioning/).

After reading it, my next step was to understand what exactly the meaning of a negative value. I stumbled over your above answer, and thought that there is no special meaning.

But after implementing the recommendation, and realizing that it doesn't work, I found the FAQ of autoscaler, which had two interesting answers:

1. [How does Cluster Autoscaler work with Pod Priority and Preemption?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-work-with-pod-priority-and-preemption) - this answer states that by default, the autoscaler has special behavior for priorities < -10.

2. [How can I configure overprovisioning with Cluster Autoscaler?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler) - this answer states that the recommendation for overprovisioning is to use priority >= -10.

Given those two answer, maybe the documentation should be changed:
1. Fix the overprovisioning doc to use -10 priority instead of -1000.
2. Add a note on the preemption doc that when autoscaler is used, negative values below -10 have a special behavior.

Thanks!
