### ISSUE TITLE
Improve formatting of API reference for ServiceAccount

### ISSUE THREAD

**Issue by mstergianis** [kubernetes/website#36023]
The section directly below the title, containing the text "ServiceAccount binds together: * a name, understood by users, and perhaps by peripheral systems, for an identity * a principal that can be authenticated and authorized * a set of secrets" is formatted in such a way that the list is not rendered as a list, but as a bunch of sentences delimited by asterisks (*)

**Comment by mstergianis** [comment]
Apologies: https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/

Additionally here's the link to the highlight: https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/#:~:text=ServiceAccount%20binds%20together%3A%20*%20a%20name%2C%20understood%20by%20users%2C%20and%20perhaps%20by%20peripheral%20systems%2C%20for%20an%20identity%20*%20a%20principal%20that%20can%20be%20authenticated%20and%20authorized%20*%20a%20set%20of%20secrets

**Comment by sftim** [comment]
/retitle Improve formatting of API reference for ServiceAccount

/kind bug

We automatically generate these reference pages, and the upstream code is only sort of Markdown.

**Comment by divya-mohan0209** [comment]
@sftim This might be a stupid question but does this mean we'd have to fix something in the generator itself? Or would this be directly in the upstream code?

**Comment by sftim** [comment]
This is an area where a GitHub Discussion might be a good fit: there's more than one way to do it.

Some ecosystems have lots of heuristics in the generator so that pages nearly always come out right.
Other ecosystems have strong(er) conventions for doc comments which means the translator code has an easier time. 

We can also:
- make ad-hoc fixes to the generator code
- manually or semi-manually tweak or patch the generated docs, to look how we want them to

Probably some other options too. I have my own preference; because there's a few different ways, we should make sure to pick an approach that people - in this SIG and in the wider project - broadly consent to.

**Comment by divya-mohan0209** [comment]
Point noted. To summarise my understanding of the issue, we currently do not have a standardized way of doing this within the project. Standardizing the approach would probably help with ensuring consistency in formatting for not only this specific doc but for the wider ref docs we generate, as well. 

That being said, I'd be happy to document it as a discussion and close the issue out in favour of the discussion. Once we have consensus on the way forward, we will need to open implementation-specific issues and PRs. Does that sound fair?
