### ISSUE TITLE
[fr] http://localhost:1313/fr/releases/ is blank

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#36362]
https://kubernetes.io/releases/ affiche cinq options de langue : français, anglais, chinois, coréen et polonais.
Le site Web affiche la rubrique "release" dans quatre de ces langues. Cependant, https://kubernetes.io/fr/releases/ est vide.

https://kubernetes.io/releases/ displays five language options: French, English, Chinese, Korean, and Polish.
The website displays the "release" topic in four of these languages. However, https://kubernetes.io/fr/releases/ is blank.

**Comment by rolfedh** [comment]
![Screenshot from 2022-08-27 15-03-53](https://user-images.githubusercontent.com/350907/187054060-eaac363d-e886-4c76-b230-a4ce92efe85f.png)

**Comment by rolfedh** [comment]
![Screenshot from 2022-08-27 21-50-26](https://user-images.githubusercontent.com/350907/187054087-d0b85691-6e17-4df8-abd9-5fd7232c30e1.png)

**Comment by mtardy** [comment]
Merci pour l'issue et les détails avec les screenshots mais il s'agit d'un doublon avec [[fr] Releases page in French is blank #35207](https://github.com/kubernetes/website/issues/35207). Je vais regarder si on peut pas juste fixer ça en redirigeant sur la version anglaise dans un premier temps.

Je me permets de fermer cette issue puisqu'elle est un peu plus récente que l'autre.

---

Thanks for the issue and the details with the screenshots but it's a duplicate with [[fr] Releases page in French is blank #35207](https://github.com/kubernetes/website/issues/35207). I'll see if we can't just fix it by redirecting to the English version first.

I'll close this issue since it's a bit more recent than the other one.

---

/triage duplicate
/close
