### ISSUE TITLE
Issue with k8s.io/docs/concepts/containers/images/

### ISSUE THREAD

**Issue by hanweisen** [kubernetes/website#36696]
[This issue](https://github.com/kubernetes/website/issues/36696) mention this page in:
> Yes exactly. The idea is to authenticate the complete node (in this case the minikube vm) against the private registry, so you don't need to define imagePullSecrets on pods. But after some more playing around and rereading [this documentation](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry) I eventually got it to work.
the problem was that minikube ssh "docker login ... places the resultingconfig.json in /home/docker/.docker, which is not read by kubelet when pulling images. Moving that file to one of the paths specified in mentioned documentation solved the problem.

I can not find any path mentioned in [this page](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry)
where should i put config.json. kubelet can load

**Comment by tengqm** [comment]
@hanweisen Maybe you want to check https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/. You may want to create a Secret for pulling images rather than relying on the `config.json` file on each node.

If the above link resolves your problem, you can close this issue.

/kind support

**Comment by hanweisen** [comment]
Thanks for your reply，I need configure nodes to authenticate to a private registry , not use secret. I think [another document](https://stackoverflow.com/questions/60661249/kubernetes-ignores-config-json-while-doing-docker-pull) also methioned this page, but he pasted the path put config.json this resolved my problem. 
May be put these path in [Configuring nodes to authenticate to a private registry ](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry) will be more better

**Comment by akankshakumari393** [comment]
```
but he pasted the path put config.json this resolved my problem.
May be put these path in [Configuring nodes to authenticate to a private registry ](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry)will be more better
```
Hey @hanweisen I did not get this part. Could you please rephrase it?

**Comment by hanweisen** [comment]
> Hey @hanweisen I did not get this part. Could you please rephrase it?
Configuring nodes to authenticate to a private registry[https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry](url) describes how we can configure node authentication via config.json. But there is no description of where to put the config.json to be read by the kubelet. This [document](https://stackoverflow.com/questions/60661249/kubernetes-ignores-config-json-while-doing-docker-pull) show the paths, they are:
```
{--root-dir:-/var/lib/kubelet}/config.json
{cwd of kubelet}/config.json
${HOME}/.docker/config.json
/.docker/config.json
{--root-dir:-/var/lib/kubelet}/.dockercfg
{cwd of kubelet}/.dockercfg
${HOME}/.dockercfg
/.dockercfg
```
I put config.json under all the paths described above. k8s successfully pulled the image from my private repository

**Comment by reylejano** [comment]
Since Docker's config.json is out-of-scope of the Kubernetes documentation website, this issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](https://slack.k8s.io/). You can also search resources like [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) for answers to similar questions.

You can also open issues for Kubernetes functionality in https://github.com/kubernetes/kubernetes.

If this is a documentation issue, please re-open this issue.

/close
