### ISSUE TITLE
Unable to build website locally using docker

### ISSUE THREAD

**Issue by nitishfy** [kubernetes/website#36754]
I've been trying to build K8s website locally using the image (gcr.io/k8s-staging-sig-docs/k8s-website-hugo) . Before running the website locally, it's required to build the website using docker . Hence I ran the command `docker build -t gcr.io/k8s-staging-sig-docs/k8s-website-hugo .` but received the following error.

![image](https://user-images.githubusercontent.com/86051118/189636946-37f883b0-559c-46e5-8bdf-cf93205c12a7.png)

Any solution for that would be appreciated.
Thank you!

**Comment by mk46** [comment]
/kind support
I think you have to pass `HUGO_VERSION` as build arg.
May be `docker build -t gcr.io/k8s-staging-sig-docs/k8s-website-hugo  --build-arg HUGO_VERSION=0.101.0 .`  will run without any error

**Comment by shurup** [comment]
Hi @NitishKumar06! Did this recommendation fix your issue?

**Comment by NitishKumar06** [comment]
No! I'm still figuring out how to fix it. Although I've docker image yet
the contents on the localhost i describe are empty.

**Comment by shurup** [comment]
@NitishKumar06 did you take the `docker build` command you're using from `make container-image`? I think it's an outdated way to build & run a local website. Can you, please, run `make container-serve` (as instructed [here](https://github.com/kubernetes/website#running-the-website-using-a-container)) instead of this and see if the magic happens?

**Comment by shurup** [comment]
Hi @NitishKumar06! Did my last suggestions help you to run the website locally?

**Comment by NitishKumar06** [comment]
@shurup Here's the report:
![dockerError](https://user-images.githubusercontent.com/86051118/195589318-be990cc7-ba85-4588-8b54-d46bab69f259.png)

**Comment by shurup** [comment]
Hi @NitishKumar06! Can you please provide the exact command you're executing now (is it `make container-serve`?) and the full output listing (the text format for this listing is preferable since it allows you to copy the complete output, which can be longer than your full screen, please)?

**Comment by NitishKumar06** [comment]
@shurup I type the command you mentioned above:

docker build . \
        --network=host \
        --tag gcr.io/k8s-staging-sig-docs/k8s-website-hugo:v0.101.0-426136dad23d \
        --build-arg HUGO_VERSION=0.101.0

**Comment by shurup** [comment]
@NitishKumar06 can you, please, also provide the complete output of this command? I guess it is not actually finished with the `go: downloading github.com/spf13/pflag v1.0.5` line, as in your screenshot above. Most likely, there should be something else going on that fails there.

E.g., the last `go: downloading` line should normally refer to the `github.com/mailru/easyjson` package — when it's downloaded, the most time/disk/CPU-consuming step of the whole building process starts. On my laptop, I need to be patient here and wait for 8 minutes for this specific step, but then everything goes through successfully, and the output and process proceed to the next steps (`Step 6/12 : FROM golang:1.18-alpine` and so on).

Please, also be sure there's at least 3 GB of space available on your disk when you launch the `docker build`; otherwise, it might not be enough to perform all the steps correctly.

**Comment by divya-mohan0209** [comment]
@nitishfy : Please can you advise on the last comment by @shurup ?

**Comment by divya-mohan0209** [comment]
Since there has been no comment by the requester on this for ~10 months, we'll be closing the issue off. Please feel free to reopen it if the problem persists.
/close
