### ISSUE TITLE
CVE Feed: JSON feed should pass jsonfeed spec validator

### ISSUE THREAD

**Issue by kevincox** [kubernetes/website#36808]
**This is a Bug Report**

The CVE Feed (https://kubernetes.io/docs/reference/issues-security/official-cve-feed/index.json) is not valid JSON Feed (https://validator.jsonfeed.org/?url=https%3A%2F%2Fkubernetes.io%2Fdocs%2Freference%2Fissues-security%2Fofficial-cve-feed%2Findex.json)

**Problem:**

There are two problems listed:

1. One entry has an `id` of null. (IPv4 only clusters susceptible to MitM attacks via IPv6 rogue router advertisements)
2. One entry has an `external_url` of null (IPv4 only clusters susceptible to MitM attacks via IPv6 rogue router advertisements)
3. All entries are missing content (either `content_text` or `content_html`).

**Proposed Solution:**

1. Give it an ID.
2. Link to the GitHub issue.
3. Add some simple content such as a link to the GitHub issue.

**Page to Update:**
https://kubernetes.io/docs/reference/issues-security/official-cve-feed/index.json

**Comment by sftim** [comment]
/sig security
/triage accepted

Part of the fix here will be about making sure that the upstream data are correct.

**Comment by sftim** [comment]
@kevincox I have lightly edited the issue description to highlight which fields are wrong.

/priority important-longterm

**Comment by mtardy** [comment]
We looked at it with Pushkar and [as far as we understood](https://kubernetes.slack.com/archives/C01CUSVMHPY/p1665505979577459?thread_ts=1664842404.584089&cid=C01CUSVMHPY) the specification only allows for custom fields starting with an underscore. Search for "Extensions" [in the spec](https://www.jsonfeed.org/version/1.1/), it seems that it's a bit restrictive (especially because any custom extension **must** be an object, not a string or a number).

So because people actually asked for other features, leading to adding arbitrary fields, we thought that maybe we could implement an RSS feed and keep a custom JSON object that does not follow the specification for now. So perhaps we can have the best of both worlds, an RSS feed for staying up to date and a JSON object for people that want a casual object to parse with a lot of info to retrieve.

**Comment by kevincox** [comment]
If you want custom data can't you just add something like `_kubernetes.io: { /* whatever you want here */ }`? That seems plenty flexible for me.

But I have no objection to switching to RSS (or Atom) either.

**Comment by kevincox** [comment]
I don't think JSON Feed is particularly popular (certainly far behind RSS and Atom) but I do think that it can serve as a dual-purpose for easy adding structured data in a way that developers are familiar with so they can easily access while combining with the well-speced semantics of a feed so that people can get general-purpose readers and tools to provide good results. I think it does make sense in this case to combine the two needs into one feed. However I think that two separate feeds, one generically consumable and one specific to Kubernetes is also a reasonable approach (although I would marginally recommend the former).
