### ISSUE TITLE
Add an explanatory comment to `post_create_issue`

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#36838]
It's duplicated with upstream, I think we should remove it from `en.toml` and use Docsy version.

https://github.com/google/docsy/blob/main/i18n/zh-cn.toml#L44

_Originally posted by @Sea-n in https://github.com/kubernetes/website/pull/36774#discussion_r969683131_

**Comment by sftim** [comment]
/retitle `post_create_issue` string already localized in upstream Docsy

Does Docsy cover all the localizations we have? If not, then I suspect that we should _not_ remove it. We can add an explanatory comment though.

**Comment by rolfedh** [comment]
> Does Docsy cover all the localizations we have? If not, then I suspect that we should _not_ remove it. We can add an explanatory comment though.

The strings in the Docsy file are mostly different from the ones in `data/i18n/<lang>/<lang>.toml`.
Other than de-duplication, I'm not sure what the reasons for preserving or removing `post_create_issue`might be.
We can change the purpose of this issue to something like "Add an explanatory comment to `post_create_issue`".
@sftim It looks like you contributed `post_create_issue` as part of [a PR you did](https://github.com/kubernetes/website/commit/06e7be5ff3c4f73be806a415a9f6fc32286b32a5) a couple of years ago. What explanation would you proffer?

**Comment by rolfedh** [comment]
Given @sftim 's comment, and lack of further discussion (lazy consensus) it seems like we should preserve `post_create_issue` and add an explanatory comment. 

@sftim what should the explanatory comment say?

**Comment by rolfedh** [comment]
/retitle "Add an explanatory comment to `post_create_issue`"

**Comment by sftim** [comment]
We should explain that we have `post_create_issue` in our localization text so that people remember to customize it for their localization (even though in English we could rely on Docsy to provide this).

However, we only need to do this if we have at least one localization target that Docsy does not have.

**Comment by sftim** [comment]
I wonder if there are other strings we include for the same reason. I haven't checked.

**Comment by sftim** [comment]
BTW, if we want to find its history, we need to look at the history of the localization files in the [parent commit](https://github.com/kubernetes/website/commit/80a91d7b6b92d493787a3e608791e0b6b3efd071) before https://github.com/kubernetes/website/pull/27408 merged.

**Comment by seokho-son** [comment]
Hi @rolfedh @sftim 

I don't consider adding an explanatory comment to post_create_issue as urgent or important. This is because, like post_create_issue, there are many other strings in a similar situation. In fact, we can infer the purpose of a string without comments to some extent, and many languages' *.toml have been localized in this way so far.

We could reuse the strings in *.toml from upstream Docsy, but this might extend the management scope for localization teams. While each team can choose, I don't think it's necessary for all localization teams to adopt this, considering the current localized *.toml are not problematic and not extensive.

Considering this, I intend to close this issue for now. If further discussion is needed, we can reopen it for discussion. :)

/close
