### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by pcbadger** [kubernetes/website#36860]
this is not a "cheat sheet" this is a massive page with a bajillion commands. I'm looking for something with a quick overview "top 10 most used commands" "bare essentials" sort of thing

**Comment by sftim** [comment]
We could add a separate page with the 10 most commonly used Kubernetes commands. I'm not sure how useful that'd be because there are so many different ways to use Kubernetes and what is common for one user persona might not be common for another user persona.

(and then the cheat sheet page could link to that new page)

Potentially, we could add more than one 10-most-used-commands pages, one for each user persona that we identify.

I recommend waiting to see if other readers also want this improvement.

If this issue gets plenty of votes, we should reprioritize it and triage it as accepted.

/language en
/kind feature
/priority awaiting-more-evidence

**Comment by utkarsh-singh1** [comment]
Hi @pcbadger, as the @sftim mentioned there can be multiple top 10 commands for different tasks, and you mentioned bare essentials which could include, 
`kubectl get/describe/run/apply [type] [name] [flags]`   commands. 

Also, there are multiple websites where they show beginner commands for getting started in Kubernetes and minikube and kubeadm tutorial also have their own docs for beginner commands.

**Comment by sftim** [comment]
We'd welcome a blog article: 10 kubectl commands you need to know (or similar).

**Comment by akankshakumari393** [comment]
Where would we link that blog to?

**Comment by utkarsh-singh1** [comment]
+1 from me as it would imporove reader experience and also imporove k8s docs.

**Comment by sftim** [comment]
> Where would we link that blog to?

I'm imagining an article that we publish to https://k8s.io/blog/
I don't know if the article body needs to contain any hyperlinks. I don't mind if it does, though.

**Comment by akankshakumari393** [comment]
Hey @sftim I would like to work on it. 🙂. Could you please point me, on process of adding a blog, if documented?

**Comment by Shubham82** [comment]
Hi @akankshakumari393 
Please look at this process [Submitting blog posts and case studies](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/) for contributing to the new blog.
This will help you.

**Comment by akankshakumari393** [comment]
Ok thanks i will go through it.
