### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by ramansankar** [kubernetes/website#36926]
explain what is an etcd member. That term is introduced in the middle of an otherwise well written explanation.

**Comment by mtardy** [comment]
This issue is referring to the sentence:
> [A Kubernetes cluster that handles production traffic should have a minimum of three nodes because if one node goes down, both an etcd member and a control plane instance are lost, and redundancy is compromised.](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/#:~:text=A%20Kubernetes%20cluster%20that%20handles%20production%20traffic%20should%20have%20a%20minimum%20of%20three%20nodes%20because%20if%20one%20node%20goes%20down%2C%20both%20an%20etcd%20member%20and%20a%20control%20plane%20instance%20are%20lost%2C%20and%20redundancy%20is%20compromised.)

In the ["Using Minikube to Create a Cluster"](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) tutorial. That effectively seems to appear before etcd as been properly introduced.

Please provide a bit more context next time for reviewers :)!

/triage accepted
/priority backlog
/kind bug

**Comment by akankshakumari393** [comment]
I think having a hyperlink to etcd would be good
