### ISSUE TITLE
Upgrading kubeadm clusters

### ISSUE THREAD

**Issue by bradotlin** [kubernetes/website#36969]
On page https://v1-21.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

None of these links work:

- [Upgrading a kubeadm cluster from 1.19 to 1.20](https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
- [Upgrading a kubeadm cluster from 1.18 to 1.19](https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
- [Upgrading a kubeadm cluster from 1.17 to 1.18](https://v1-18.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
- [Upgrading a kubeadm cluster from 1.16 to 1.17](https://v1-17.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)

**Comment by jihoon-seo** [comment]
/triage accepted
This is because the Kubernetes websites for <= v1.20 are not live anymore.
Removing those links might be one possible solution.

Similarly,
- In https://v1-22.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ , those links are not working:
  - [Upgrading a kubeadm cluster from 1.19 to 1.20](https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
  - [Upgrading a kubeadm cluster from 1.18 to 1.19](https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
  - [Upgrading a kubeadm cluster from 1.17 to 1.18](https://v1-18.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
- In https://v1-23.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ , those links are not working:
  - [Upgrading a kubeadm cluster from 1.19 to 1.20](https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
  - [Upgrading a kubeadm cluster from 1.18 to 1.19](https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
- In https://v1-24.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ , those links are not working:
  - [Upgrading a kubeadm cluster from 1.19 to 1.20](https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)

**Comment by neolit123** [comment]
/sig cluster-lifecycle
we could add a note that the links may stop working for old releases. manually cleaning up the links does not seem sustainable.

**Comment by RA489** [comment]
IMO adding note will be better.

**Comment by sftim** [comment]
I recommend removing the stale hyperlinks.

**Comment by sftim** [comment]
I now agree with https://github.com/kubernetes/website/issues/36969#issuecomment-1256009693

/remove-triage accepted

**Comment by sftim** [comment]
/triage unresolved

We won't remove those links and we won't expect to do the toil for each release for tidying things up.
It would be better to put effort towards serving archived versions of the docs for longer.
