### ISSUE TITLE
Improvement for k8s.io/docs/concepts/cluster-administration/system-traces/

### ISSUE THREAD

**Issue by npnwdev** [kubernetes/website#37053]
The instruction provided on this page looks incomplete or very high level. Could you add an end-to-end demo from configuration, deployment, and seeing traces from one of the system components? It'll be much helpful for newbies like me.

**Comment by mtardy** [comment]
Hey! I don't know if you saw it but there is [a suggested getting started guide](https://kubernetes.io/docs/concepts/cluster-administration/system-traces/#:~:text=For%20a%20complete%20guide%20to%20collecting%20traces%20and%20using%20the%20collector%2C%20see%20Getting%20Started%20with%20the%20OpenTelemetry%20Collector.) that might be more complete.
> For a complete guide to collecting traces and using the collector, see [Getting Started with the OpenTelemetry Collector](https://opentelemetry.io/docs/collector/getting-started/).

However, if it's not enough, or not Kubernetes specific enough, that could be an interesting addition to this rather young doc page!

/triage accepted
/kind feature

**Comment by sftim** [comment]
We can't really add an end-to-end demo because to do so requires third party software. See https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed

What we could do instead is add a blog article that demos how to use the tracing feature. How about that? It would need someone to step forward to write that article, and somebody else to step forward to review it.

/remove-triage accepted
as we should discuss the details further.

/language en

**Comment by npnwdev** [comment]
@sftim Yes, that would help. could you please include me in the review process? Thanks!

**Comment by sftim** [comment]
/remove-lifecycle rotten

Not yet triaged
