### ISSUE TITLE
Feature Gates (removed) - Typo in RootCAConfigMap

### ISSUE THREAD

**Issue by tgdfool2** [kubernetes/website#37316]
This is probably a typo:
![image](https://user-images.githubusercontent.com/66017789/195987271-e87e22b0-91f7-43f6-8b88-52978531f836.png)

Should probably be `1.22`?

**Comment by pwnb0y** [comment]
I would like to work on it can you assign to me

**Comment by mengjiao-liu** [comment]
page: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

/triage accepted


- The deprecated RootCAConfigMap feature-gate has been removed, since the RootCAConfigMap feature graduated to GA in 1.21 and was unconditionally enabled. ([#101579](https://github.com/kubernetes/kubernetes/pull/101579), [@carlory](https://github.com/carlory)) [SIG Auth]

see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md

/assign @pwnb0y

**Comment by sftim** [comment]
/good-first-issue

PRs to fix this are welcome!

**Comment by debdeepsanyal** [comment]
@tgdfool2 hi! this would be my first contribution and hence i would love an insight into this issue. can you kindly guide me on how to proceed?

**Comment by mayankA47** [comment]
Fixed in #38217

**Comment by Shubham82** [comment]
resolved in #38217
/close
