### ISSUE TITLE
Interactive Tutorial - Updating Your App

### ISSUE THREAD

**Issue by olekszhel** [kubernetes/website#37325]
You should demonstrate here 
![image](https://user-images.githubusercontent.com/10630843/196004617-f7dc4b8f-1d89-46fc-a023-9f442738c782.png)

**Comment by mengjiao-liu** [comment]
page: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

/triage accepted


- The deprecated RootCAConfigMap feature-gate has been removed, since the RootCAConfigMap feature graduated to GA in 1.21 and was unconditionally enabled. ([#101579](https://github.com/kubernetes/kubernetes/pull/101579), [@carlory](https://github.com/carlory)) [SIG Auth]

see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md

**Comment by utkarsh-singh1** [comment]
Hi @olekszhel, is this issue a duplicate of #37324 ?

**Comment by sftim** [comment]
/triage needs-information

I don't think contributors would be able to work out what you're saying needs a fix, @olekszhel.
