### ISSUE TITLE
Horizontal scroll not working for code snippet

### ISSUE THREAD

**Issue by bishal7679** [kubernetes/website#37419]
## Description
In this section https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#init-containers-in-use
the yaml block is not slidable horizontally which should be.

**Comment by jihoon-seo** [comment]
For me, this issue is reproducible.
/area web-development

[When the browser window's width is about 2500px]
![image](https://user-images.githubusercontent.com/46767780/197086894-a1bdc36f-0c26-4e39-860f-b1b8d93496a2.png)

[When the browser window's width is about 1240px]
![image](https://user-images.githubusercontent.com/46767780/197087040-04e21363-cefc-4db0-a639-a82fc331c2bf.png)

**Comment by sreeram-venkitesh** [comment]
I had faced the same issue while working on #37339. I had to get around this by splitting the comments into multiple lines.

**Comment by sftim** [comment]
/retitle Horizontal scroll not working for code snippet

**Comment by sftim** [comment]
/kind bug
/triage accepted

Fixes are welcome

**Comment by yoji-kojio** [comment]
@sftim hey! can you assign to me? :D I'll make a PR
