### ISSUE TITLE
[zh] Use appropriate localization(s) for term “namespace”

### ISSUE THREAD

**Issue by aimuz** [kubernetes/website#37694]
**This is a Bug Report**

In reading the k8s documentation, I found that a large number of documents translate namespace to `名字空间` 
在阅读k8s文档中，发现大量的文档将namespace 翻译成 `名字空间`

but in practice, people are more used to using `命名空间`
而大家的实际使用过程中，更加习惯使用`命名空间`

There is a dispute here that
在此发生了争议，

https://github.com/kubernetes/website/pull/37665

In my view k8s issue, there is also a large amount of controversy, everyone's point of contention are `名字空间` 
在我查看 k8s 问题，也出现了大量的争议，大家的争议点都是 `名字空间`

https://github.com/kubernetes/website/pull/33179
https://github.com/kubernetes/website/issues/28459
https://github.com/kubernetes/website/issues/35798

Would there be these controversies if it were a `命名空间`？People who raise these controversies are feeling doubtful about `名字空间`

Regarding the reason why it was modified to a namespace, I think it might be as follows
关于为什么修改成名字空间的原因，我觉得可能如下

https://github.com/kubernetes/website/issues/28459#issuecomment-863623927

>We had such discussions previously when drafting and reviewing the https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7 page. I personally prefer "名字空间”，because that is what namespace for ... a space for names. There are other voices arguing that "命名空间” is very popular in many articles or books.

In the k8s ecosystem, they all actually use the `命名空间`
在k8s生态系统中，它们实际上都使用了  `命名空间`

例如，他们（包括CNCF项目)
For instance, they (Includes CNCF projects):

- [rancher](https://docs.ranchermanager.rancher.io/zh/how-to-guides/new-user-guides/manage-namespaces)
- [istio](https://istio.io/latest/zh/docs/tasks/security/authentication/authn-policy/#namespace-wide-policy)
- [volcano](https://volcano.sh/zh/docs/installation/#%E6%AD%A5%E9%AA%A4-1)
- [kubeEdge](https://kubeedge.io/zh/docs/setup/keadm_zh/#master)

In addition, when I took the CKA certificate, the topic descriptions in it also used `命名空间`

https://github.com/kubernetes/website/pull/37665#issuecomment-1301839124
>Those discussion history can serve a background why we don't want to invest time on this issue again. We had discussions on this and we articulated the reason why "名字空间" is acceptable, or even a better option.

>When deciding how to translate a term, we consider whether a translation is good not by how it is used in other fields or contexts. We were and we are still trying to find the best Chinese word for an English word. In other words, we honor the true facts rather than how others are doing.

>作为严谨的科技工作者，我们的职责不是人云亦云，不是根据事物的流行度来做判断，而是在工作中（包括社区工作中）去重新审视所有即成事实的、已被认定的事物。这一过程并不是轻松的、写意的，而是天人交战的、绞尽脑汁的。毕竟，Kubernetes 的官方文档会是很多下游社区的信息源；毕竟，大家在社区中所做的贡献都要在阳光下晾晒。

In my opinion, it is not a matter of people's clouds
在我认为，这不是人云亦云的问题

This is not academic research; the role of official documentation is to be able to teach users, and it is using statements that are more acceptable to users that will keep them from getting confused.
这并不是学术研究，官方文档的作用在于能够教授使用者，而使用使用者更加容易接受的说法，才会让使用者不会感到困惑。

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/retitle [zh] Use appropriate localization(s) for term “namespace”

**Comment by wenerme** [comment]
`名字空间` feels fine to me

**Comment by windsonsea** [comment]
+1 @wenerme 

One of reasons that you discussed much before is that you also know `名字空间` refers to `namespace`. The reverse derivation is also correct, no other options.

```
namespace = 名字空间, 命名空间
名字空间, 命名空间 = namespace
```
It's not necessary to force everyone to follow the old way. `命名空间` is the legacy and old way in my opinion.

**Comment by aimuz** [comment]
In my opinion there is no consideration of ecological issues, for those who know, they are a thing. But for learners, newbies, it can be confusing for them

The existing textbook materials, are written in namespace, in the search engine query, query `名字空间`, the exact match is very rare, the use of `名字空间` is not very short time, I check the commit, he submitted also more than two years, but we are still more accustomed to `命名空间`

If you don't care about ecology, then it doesn't matter

It's like the unification of China into Mandarin, not because it sounds good, but because Mandarin is more widely used by people

**Comment by aimuz** [comment]
You are not forcing everyone to use it, but you are forcing everyone to accept your solution, can you find the documentation for using `命名空间` in the documentation?

**Comment by mengjiao-liu** [comment]
I basically agree with @wenerme 

In the Chinese dictionary `辞海`, the meanings of  `名字` and `名称` are as follows:
```
名字： 1.人的名与字。 2.指姓名。 3.名称;名号。 4.命名;称其名。 5.犹名誉;名声。 6.即名词。
名称： 1.名号称谓。亦指事物名。"
```
In daily practical use, `名字` is mainly used for people in general use, while `名称` is mainly used for affairs. I feel like this is where everyone gets confused about `名字空间`.
在日常实际使用中，`名字` 在一般使用中多用于人或者拟人化的事务，而名称则多用于物品或事务。我感觉这也是大家对于`名字空间`的困惑所在，会下意识感到有点别扭。

So I tend to translate `名字空间` to `名称空间`.
因此我倾向于将 `名字空间` 翻译为 `名称空间`。

**Comment by wenerme** [comment]
Any context will create a namespace, but if you mean the Namespace in kube, I prefer 名字空间

https://github.com/wenerme/wener/blob/923ca381eb26fc7a9a917cf132ab4aa64e5436e5/notes/dev/dict.md#namespace-%E7%BF%BB%E8%AF%91-namespace

**Comment by sftim** [comment]
When we localize a reference to a Linux kernel process namespace, what Chinese word should we prefer?

**Comment by correctzh** [comment]
Kubernetes product:

Azure Kubernetes Service (AKS) - 命名空间
https://learn.microsoft.com/zh-cn/azure/aks/concepts-clusters-workloads#namespaces

Amazon EKS - 命名空间
https://docs.aws.amazon.com/zh_cn/eks/latest/userguide/sample-deployment.html

Red Hat OpenShift - 项目和命名空间
https://access.redhat.com/documentation/zh-cn/openshift_container_platform/4.3/html/authentication/rbac-projects-namespaces_using-rbac#doc-wrapper

CNCF projects:

rancher
https://docs.ranchermanager.rancher.io/zh/how-to-guides/new-user-guides/manage-namespaces

istio
https://istio.io/latest/zh/docs/tasks/security/authentication/authn-policy/#namespace-wide-policy

volcano
https://volcano.sh/zh/docs/installation/#%E6%AD%A5%E9%AA%A4-1

kubeEdge
https://kubeedge.io/zh/docs/setup/keadm_zh/#master

CNCF Ambassadors:

Jimmy Song - blog: 不同命名空间中的服务要绑定到同一个网关中的情况在实际情况下经常出现，而入口网关无法在多个命名空间中共享；
https://jimmysong.io/blog/why-gateway-api-is-the-future-of-ingress-and-mesh/

Lei Zhang - special column: 其解释了如何利用命名空间（Namespace）这一概念来组织 K8s 租户的资源。
https://www.infoq.cn/article/fsmwwgyknsgwpegjho4g

sig-docs-zh-reviews:

chenxuc
https://github.com/kubernetes/website/pull/37665
kubernetes Contributor:

yinyicao
https://github.com/kubernetes/website/pull/33179

linruikai
https://github.com/kubernetes/website/issues/35798

google search results(命名空间>名字空间):
k8s+"命名空间" - About 246,000 results
https://www.google.com/search?q=k8s+%22%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4%22

k8s "名字空间" - About 20,300 results
https://www.google.com/search?q=k8s+%22%E5%90%8D%E5%AD%97%E7%A9%BA%E9%97%B4%22

---
All discussions are based on references, rather than creating a vocabulary without any expert endorsement and then explaining it.
In official commercial Kubernetes product(Azure Kubernetes Service,Amazon EKS,Red Hat OpenShift), in CNCF projects(rancher,istio,volcano,kubeEdge), in K8S experts(CNCF Ambassadors:Jimmy Song,Lei Zhang),in sig-docs-zh-reviews(chenxuc) ,in enthusiastic contributors(yinyicao,linruikai,aimuz),All are used correct(命名空间).

**Comment by tengqm** [comment]
I wasn't insisting that '名字空间' is the only acceptable translation. I also shared my reason why I myself believe '名字空间' could be a better choice. I'm NOT forcing others to accept this opinion, and I don't accept that '名字空间' is a wrong translation. With all those background information provided, we had achieved a consensus -- both are acceptable in the docs. In other words, WE AGREED TO DISAGREE.

Because this word translation doesn't hurt that much for people to learn Kubernetes, we always tried to redirect contributors to other more valuable fixes. That is the reason I closed the PR which prefers one word to another.

If we can achieve the consensus -- both are acceptable -- again, we can close this issue and add a comment to localization style guide.

**Comment by correctzh** [comment]
**To insist that the argument is correct, provide references, not unfounded explanations.**
On the premise that there are reference materials, replace all '名字空间' with '命名空间', I believe no one will have an opinion.
You can even see that there is no PR that needs to change '名字空间' to '命名空间' only PR that replaces  '命名空间' with '名字空间'.
It can even be seen that there is no PR to change '名字空间' to '命名空间', only PR to replace  '命名空间' with '名字空间'.

No namespace('名字空间') is used in official commercial Kubernetes product(Azure Kubernetes Service,Amazon EKS,Red Hat OpenShift), in CNCF projects(rancher,istio,volcano,kubeEdge), in K8S experts(CNCF Ambassadors:Jimmy Song,Lei Zhang) , so it is a new vocabulary('名字空间') created by myself, without expert approval, **and cannot guarantee its correctness.**

>This is not academic research; the role of official documentation is to be able to teach users, and it is using statements that are more acceptable to users that will keep them from **getting confused**.

In fact, this issue was raised only by readers who were confused.
I do not support random creation of new words to confuse readers,
If you can create new words at will, why not use '名空间','姓名空间','名称空间'.

The first focus of localization is correctness.
This is a wrong translation('名字空间'),please adjust it to be correct('命名空间').
---
Google Kubernetes Engine (GKE): 命名空间
https://cloud.google.com/kubernetes-engine/docs/how-to/restrict-resources-access-by-namespace?hl=zh-cn

**Comment by aimuz** [comment]
>Because this word translation doesn't hurt that much for people to learn Kubernetes, we always tried to redirect contributors to other more valuable fixes. That is the reason I closed the PR which prefers one word to another.

If you think this is of little value, why are namespaces being replaced with namespaces in the documentation

If both nouns can be used, why does only one usage exist in the documentation? So who modified him to merge in such worthless ones?

If it was just not worth much to begin with, then why recognize you would modify him? Change it to what you think is the right way?

**Comment by aimuz** [comment]
I looked through the linux kernel documentation and found the following information

In the Linux kernel localization, the process namespace has not been translated for localization yet, but there is another namespace in Linux that I think can be used as a reference


**Symbol Namespaces**

https://www.kernel.org/doc/html/latest/core-api/symbol-namespaces.html

https://www.kernel.org/doc/html/latest/translations/zh_CN/core-api/symbol-namespaces.html

**Comment by aimuz** [comment]
I searched for related Linux-related books

 - Professional Linux Kernel Architecture - 《深入Linux内核架构》 译者: [郭旭](https://book.douban.com/search/%E9%83%AD%E6%97%AD)
    In the Chinese version `1.3 内核的组成部分 5`
<img width="825" alt="image" src="https://user-images.githubusercontent.com/17666471/201025939-13f72cf8-1b6c-4e6b-a1c7-34a8d8f7ac2e.png">

-  The Linux Programming Interface: A Linux and UNIX System Programming Handbook - 《Linux/UNIX系统编程手册》译者: [孙剑 许从年 董健](https://book.douban.com/search/%E5%AD%99%E5%89%91%20%E8%AE%B8%E4%BB%8E%E5%B9%B4%20%E8%91%A3%E5%81%A5) / [孙余强 郭光伟 陈舸](https://book.douban.com/search/%E5%AD%99%E4%BD%99%E5%BC%BA%20%E9%83%AD%E5%85%89%E4%BC%9F%20%E9%99%88%E8%88%B8)
<img width="806" alt="image" src="https://user-images.githubusercontent.com/17666471/201034617-687859b7-5431-4eae-b4a4-35bb677e94d7.png">


These books are some of the highest rated Linux related books

**Comment by aimuz** [comment]
In the course of reviewing the books, no relevant books were found that used the `名字空间`

**Comment by aimuz** [comment]
If both uses were actually allowed, then the document would not contain only `名字空间`

Another quote from @windsonsea 

> I call my father as daddy, papa, old man, Mr.Y. If somebody gives a command to me: "You only can call your father BABABABABA", I might be unhappy ... lol ... just a joke.


If both uses were really allowed, then PR should not be negated by way of priority.

When you change `命名空间` to `名字空间`, don't negate other PRs in a worthless way. please don't double standard.

**Comment by wenerme** [comment]
Use `名字空间` more, may attract more newer doc and book to use it if they feel better about it, how about just let this doc use `名字空间`.

**Comment by cyclinder** [comment]
Agree with `名称空间`

**Comment by aimuz** [comment]
In the case of existing sources that are using `命名空间`, I think there is no need to check your own correctness and should avoid causing more disturbance to the reader, especially for noun changes where you feel you are correct and you get satisfaction inside, but have not considered whether the reader buys it.

Whether the upstream or downstream material is using `命名空间`, there should be no idiosyncrasy in translation.

Another word about the value of @tengqm , I think as long as there are contributors involved, it is valuable, it may not be valuable to you, but without value then contributors do not submit relevant questions.

In addition, I would like to share a quote that I think is good

https://www.figma.com/resources/learn-design/research/#firsthand-research

> Stop looking at what other companies are doing. Start spending more time with existing/potential customers.
