### ISSUE TITLE
Setting up Worker Node (Windows) with Master Node (Linux) using Kubeadm 

### ISSUE THREAD

**Issue by anandarajr** [kubernetes/website#37758]
We are trying to set up the kubernetes network on on-premise using the Kubernetes tool "KubeAdm" 

We are able to set up the master node (linux)

For setting up windows node (windows), we followed the steps in the below link
             https://keyvatech.com/2020/03/26/step-by-step-guide-set-up-a-windows-worker-node-for-kubernetes-cluster/

Executing the powershell scrip for joining between worker node(windows os)  and master node (linux). Here we are facing the error "parameter is in incorrect". It looks like we are passing incorrect values to AddessPrefix and Gateway. 
Kindly let us know what is the value needs to be passed to those parameter

New-HNSNetwork -Type $NetworkMode -AddressPrefix "XXX.XXX.XXX.X" -Gateway "XXX.XX.XXX.X" -Name "External" -AdapterName "$InterfaceName" -SubnetPolicies @(@{Type = "VSID"; VSID = 9999; })
             
        

https://github.com/kubernetes/website/issues/37758#tasklist-block-98287d4d-b3f7-4556-af7a-3eb242715628

**Comment by jihoon-seo** [comment]
/kind support
The article you linked was posted on 2020-03-26, so it might be outdated for now.
Recently in the K8s docs, some Windows-specific guides are removed or reorganized to the general ones,
(e.g., https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ was removed and merged to
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ .)
since users can join their Windows worker nodes to the Linux control plane with (nearly) the same way they do with the Linux worker nodes.

So how about refer to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ ?

**Comment by anandarajr** [comment]
Thanks for your reply. Both the above links (ref below) redirecting to the same page. Here it is explained about on how to add the linux worker node. But our requirement is adding the windows worker node. Kindly share your inputs which would helps us a lot. 

![image](https://user-images.githubusercontent.com/13455396/200502856-cf616230-f639-4a15-8c1b-30f25c9aca71.png)

**Comment by neolit123** [comment]
please see

https://github.com/kubernetes/website/issues/34476


/close
