### ISSUE TITLE
kube-apiserver Audit Configuration (v1) - Stage should be `enum` of values instead of alias of string

### ISSUE THREAD

**Issue by distortedsignal** [kubernetes/website#37795]
Presently, [the documentation of the `Stage` type](https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/#audit-k8s-io-v1-Stage) says that it is

> Alias of string

and I do not believe that this is correct. If `Stage` were a true alias of `string`, this would imply an infinite number of stages, which seems... implausible. Unlike with the `Level` issue that I filed earlier, I cannot find a list of valid `Stage` values.

**Comment by distortedsignal** [comment]
I've been informed that the documentation page for the `Stage` type was autogenerated, and that I should mention this fact in any tickets that I open.

**Comment by sftim** [comment]
We don't yet encode every restriction or combination of restrictions into the API definition(s).

That configuration format might let you define auditing for a stage of `end-of-universe` (but that doesn't then mean that the audit configuration works how you want, or even loads).

https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/ lists the defined stages in Kubernetes v1.25

**Comment by distortedsignal** [comment]
Thanks @sftim - would it be possible to link that from the docs for the Stage type?

**Comment by sftim** [comment]
It's not super easy to add this. The way to do that is to edit the [source code](https://github.com/kubernetes/kubernetes) of Kubernetes itself. The trade off of the automatic generation is that if we make manual edits, they don't last.

:thought_balloon: If you want a mechanism to let one page link to another page, where the link is declared by the _target_, that might be possible. Do you think that could cover the outcome you want @distortedsignal ? Imagine if the link is right at the start or 
end of the page and not inline next to the field definition.

Otherwise, you'd like to file an issue against https://github.com/kubernetes/kubernetes to get that change made @distortedsignal
