### ISSUE TITLE
Katacoda scenarios run old / unsupported Minikube and Kubernetes version

### ISSUE THREAD

**Issue by medyagh** [kubernetes/website#37817]
in this minikube tutorial I see Katakoda
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

but the minikube version in it is ancient it is v.1.18.0
the latest minikube version is 1.28.0
<img width="1046" alt="Screen Shot 2022-11-09 at 1 32 43 PM" src="https://user-images.githubusercontent.com/4564227/200946284-7a61d49f-7888-43da-a702-f58e2d329263.png">

is there a way to update Katakoda in Kubernetes website?

**Comment by sftim** [comment]
/retitle Katacoda scenarios run old / unsupported Kubernetes version

**Comment by jihoon-seo** [comment]
If someone improves this, then the minikube version used by "Interactive Tutorials" might be updated as well, if needed.

e.g., https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/
```
$ minikube version
minikube version: v1.18.0
commit: ec61815d60f66a6e4f6353030a40b12362557caa-dirty

$ kubectl version --short
Client Version: v1.20.4
Server Version: v1.20.2
```

GitHub repo: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

**Comment by Ritikaa96** [comment]
Hi @jihoon-seo , Katacoda is not maintained anymore so highly unlikely the scenarios will be updated.

**Comment by sftim** [comment]
Katacoda for Kubernetes is maintained a bit. The main thing we're short of is contributor time.

**Comment by medyagh** [comment]
> Katacoda for Kubernetes is maintained a bit. The main thing we're short of is contributor time.

is there a repo you could point us to , we could contribute a PR for it

**Comment by sftim** [comment]
The repo is https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios - as mentioned in https://github.com/kubernetes/website/issues/37817#issuecomment-1309793010

**Comment by nikitar** [comment]
@BenHall You were the [last](https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/33) person to upgrade katacoda k8s images (minikube, minikube-builder and minikube-running). Could you tell us about the process? I'd be happy to update the scenarios themselves, but it appears the images, and the katacoda sources generally, are not public.

**Comment by nikitar** [comment]
I also looked into killercoda (mentioned in another thread as an alternative) and it seems a migration should be doable. We would need to contact them to add minikube however, as none of their images appear to include it.

**Comment by JFMeeks** [comment]
Hello, I am the product manager responsible for Katacoda here at O'Reilly and I am happy to put this team in touch with the Katacoda devs on our side in an effort to help you to migrate to Killercoda. 

It is correct that the public facing Katacda.com site is not longer supported and it is our intent to take the site down entirely by the end of the year, though this is something Id like to discuss.

Kubernetes.io is the last remaining service running from the public Katacoda hosts and, in fact, has been seeing quite a bit of activity lately. This activity, while fantastic for Kubernetes.io, unfortunately has prompted some scrutiny and increased urgency around finalizing the shut down Katacoda.com. Because Katacoda will only be offered as a private service to O'Reilly customers upon shut down of the Katcoda.com site, there won't be a way for us to embed a publicly accessible Katacoda scenario outside of Oreilly.com, effectively breaking the terminal in your documentation. 

As I mentioned, I'd like to be on the same page with regards to a shut down date, I certainly don't want to leave the team in a compromised position. If it is helpful to do so, I am happy to jump on a call or correspond via email: jmeeks@oreilly.com

**Comment by sftim** [comment]
See https://github.com/kubernetes/website/issues/33936#issuecomment-1346832443

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
