### ISSUE TITLE
'Image Pull Policy: Always' docs state that kubelet uses cached images but it doesn't

### ISSUE THREAD

**Issue by adamkgray** [kubernetes/website#37926]
**This is a Bug Report**

**Problem:**

The kubernetes documentation for `ImagePullPolicy: Always` states:

"every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image [digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier). If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved digest, and uses that image to launch the container."

But it is not true that kubelet will used a cached image. Looking at the [source code](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L848) the `Always` policy pulls the image every time.

**Proposed Solution:**

Udpdate the documentation to reflect what the source code actually does.

Created [PR 37927](https://github.com/kubernetes/website/pull/37927)

**Page to Update:**
https://kubernetes.io/...

**Comment by adamkgray** [comment]
Created [PR 37927](https://github.com/kubernetes/website/pull/37927)

**Comment by sftim** [comment]
I'm not sure that the fix you're advocating is strictly accurate either @adamkgray. I think the container runtime has a big say in what image layers do or don't get fetched.

> every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image [digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier). If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved digest, and uses that image to launch the container.

This broadly matches what I've observed in actual Kubernetes clusters. I think it blurs the lines a bit between what the kubelet does and what the container runtime does.

https://www.ianlewis.org/en/container-runtimes-part-4-kubernetes-container-run explains the process and shared responsibilities in some more detail.

**Comment by sftim** [comment]
Docker Hub _may_ treat validating that an image is fresh against its rate limit. On its own, reaching a rate limit at Docker Hub is not evidence that the docs are wrong.

I can see three options here:
- the docs are right, Kubernetes is working as designed
- the docs are right, Kubernetes has a bug (we'd want to know which kubelet version is affected)
- the docs are wrong, Kubernetes does not behave as documented

My baseline assumption is that the docs are right: these have been reviewed by contributors already. However, if the facts change, then of course we as Kubernetes contributors ([SIG Docs](https://github.com/kubernetes/community/tree/master/sig-docs)) are willing to change our opinion to match.

If the docs are accurate but readers are getting confused, we still want to know - maybe we can improve the docs so that readers work out the true situation and have enough context to understand any surprising details.

**Comment by rinocata** [comment]
>My baseline assumption is that the docs are right

Well you're not entirely wrong because [they say](https://kubernetes.io/docs/concepts/containers/images/#required-image-pull):

>If you would like to always force a pull, you can do one of the following:
>Set the imagePullPolicy of the container to Always.

Which is both expected and actual behavior, and contradicts the [section on Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy).

**Comment by rinocata** [comment]
So after some debugging with the Docker rate limit REST API it looks like images are indeed cached, even with `Always`. 
_(In which case I'm baffled as to what caused me to go over the quota as I did **not** download 100 different images)_
In the end, it seems to be a terminology issue, since "forcing a pull" doesn't actually force anything but just calls `crictl pull` (in the same sense, kubelet simply delegates to `crictl` instead of the rather more involved procedure described in the docs). It *might* be better to make the wording a bit less ambiguous, but I do not insist on it. Not sure if @adamkgray agrees.

**Comment by xmcqueen** [comment]
Probably this page here: docs/concepts/containers/images.md

**Comment by xmcqueen** [comment]
Gathering some of the above facts, since this is assigned to me so I have to make sense of this.  This comment is not a verdict on the question:

### kubeadm

* the above code links can be confusing when presented like this, but they are links to `kubeadm` code, and the discussion seems to be about `kubelet`.

The below comment is about kubeadm:

> `kubeadm` appears to run `crictl` in the background. `crictl pull` in turn appears to indeed skip downloading the image if it is already present on a node. Nevertheless, when setting the policy to `Always` in a Pod, Deployment etc. an image is seemingly pulled every time a pod is restarted (evidence: my running out of free Docker Hub pulls). Is there an easy way to debug this?

The comment below is describing kubeadm behaviour and attributing it to kubelet. It [looks like kubelet uses the cri-api](https://github.com/kubernetes/kubernetes/blob/a12dd4189e88621b6632fab788e49401e6e7a358/pkg/kubelet/cri/remote/remote_image.go#L89) to talk to the container-runtime, and does not exec `crictl`.  It is a bit challenging to find the source code for this.

> kubelet simply delegates to crictl

The below seems to be about **pod-restarts** so is clearly about `kubelet` (or what is running behind `kubelet`), and ** seems to be the primary complaint.**:

> an image is seemingly pulled every time a pod is restarted

However, the evidence presented is not conclusive:

> evidence: my running out of free Docker Hub pulls

### docs

> section on Image pull policy

the docs linked for `ImagePullPolicy` for `Always` do **not** indicate it always pulls, but that it uses the cache:

> ... with that exact digest cached locally, the kubelet uses its cached image; otherwise, ...

but the doc for *[Required Image Pull](https://kubernetes.io/docs/concepts/containers/images/#required-image-pull)* does conflict with that:

> If you would like to **always force a pull**, you can do one of the following:
>      * Set the imagePullPolicy of the container to Always.

So there is **at least a conflict in the docs** on this subject.

Regarding the question where  **kubelet ... pulls the image every time**

- what [container runtime](https://kubernetes.io/docs/setup/production-environment/container-runtimes/) is being used?
- what kubernetes version?
- @adamkgray can you please get some data from `crictl` queries showing something conclusive, or from some other source like a **tcpdump** or log lines that clearly indicate cri calls to pull for each pod-restart, and even. better would be **log lines from the container runtime** showing the actual pulls.

**Comment by xmcqueen** [comment]
* needs-info: @adamkgray 
* needs doc change: @xmcqueen
