### ISSUE TITLE
Document scaling a kubeadm-deployed control plane

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#37974]
**This is a Feature Request**

**What would you like to be added**
Document two new tasks:
- add another control plane node to a cluster that you deployed using kubeadm
- remove an existing control plane node from a cluster that you deployed using kubeadm

**Why is this needed**
Cluster operators might need to scale their control plane on a running cluster.
I couldn't find existing task documentation for this.

**Comments**
/language en
/sig cluster-lifecycle
/kind feature

Some background info in https://archive-docs.d2iq.com/dkp/konvoy/1.8/troubleshooting/replace-failed-control-plane-node/

**Comment by jdbarnes-isi** [comment]
Hi, I have a use-case for this.

We were tasked with moving from a Debian-based OS to a Fedora-based OS on our kubernetes cluster, and due to the state of the hosts and applications on the system, the decision was made to scale down the old control plane from 3 to 1 node and create a new cluster with a single node control plane, deploy the updated applications in a green-blue type of environment for testing, then scale up to 2, and finally, when applications are migrated, to a full 3-node control plane again.

The old cluster was created with a step by step manual deployment: create certificates, create etcd cluster, utilize systemd-activated kubernetes components (kube-apiserver, kube-scheduler, kube-controller-manager, etc).

In an effort to utilize tools and processes that will simplify managing cluster operations including green-blue style migrations, or even scaling down or up the cluster to add or replace components, we are utilizing kubeadm and keeping all deployment information and process in a configuration repository, but  have run into some issues with scaling, and were trying to find some documented information around this process while we are trying to do virtualized testing, including scaling down, so we can move forward with hardware deployments.

Thank you for documenting these amazing tools and features, we are extremely grateful for all the efforts of the teams involved.
