### ISSUE TITLE
Trouble finding legacy PodSecurityPolicy documentation

### ISSUE THREAD

**Issue by cccsss01** [kubernetes/website#38234]
The documentation should not be removed for pod security policies, nor difficult to obtain.  But should still have the deprecation listed.
https://kubernetes.io/docs/concepts/security/pod-security-policy/

Specifically, If you are not running Kubernetes v1.25, check the documentation for your version of Kubernetes.  Can this be a link i'm finding it difficult to find this, in the confines of kubernetes.io

**Comment by sftim** [comment]
The page https://kubernetes.io/docs/concepts/security/pod-security-policy/ is in fact still there, and has links to documentation for PodSecurityPolicies in Kubernetes v1.21 through to Kubernetes v1.24 (hint: click on **Versions**).

To help readers who don't work it out, we could:
- add some text that explains how to click on Versions in order to see older versions of the page
- link to https://kubernetes.io/docs/home/supported-doc-versions/

I think it's also reasonable to file a related issue, that readers have trouble discovering that documentation for other Kubernetes versions is available. @cccsss01 would you be willing to do that.

/retitle Trouble finding legacy PodSecurityPolicy documentation
/language en
