### ISSUE TITLE
Wrong example in (generated) kubectl command reference

### ISSUE THREAD

**Issue by mrajus02** [kubernetes/website#38626]
The Usage for creating a secret* missing the keyword "secret", while the example is correct.
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-secret-generic-em-

Usage
$ kubectl create generic NAME [--type=string] [--from-file=[key=]source] [--from-literal=key1=value1] [--dry-run=server|client|none]

Usage
$ kubectl create docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-file=[key=]source] [--dry-run=server|client|none]

**Comment by mpuckett159** [comment]
I believe that this is an issue with the website and how it generates the commands, not with kubectl itself. When using kubectl v1.23 I see the proper output in the kubectl create secret help messages.

```
kubernetes on 🌱fix/command [$!] via 🐹 v1.19.4 on ☁️  (us-west-2) 
❯ kc version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

kubernetes on 🌱fix/command [$!] via 🐹 v1.19.4 on ☁️  (us-west-2) 
❯ kc create secret -h
Create a secret using specified subcommand.

Available Commands:
  docker-registry Create a secret for use with a Docker registry
  generic         Create a secret from a local file, directory, or literal value
  tls             Create a TLS secret

Usage:
  kubectl create secret [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).

kubernetes on 🌱fix/command [$!] via 🐹 v1.19.4 on ☁️  (us-west-2) 
❯ kc create secret generic -h
Create a secret based on a file, directory, or specified literal value.

...

Usage:
  kubectl create secret generic NAME [--type=string] [--from-file=[key=]source] [--from-literal=key1=value1]
[--dry-run=server|client|none] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

The `kubectl create secret` and it's subcommands are pretty highly nested so that might be what's causing issues? The nesting is as follows:

1. cmd.go - top level kubectl cobra.Command object
2. create/create.go - NewCmdCreate which adds on to the top level kubectl command object
3. create/create_secret.go - NewCmdCreateSecret adds the secret subcommand to create
4. create/create_secret.go - there are three subcommands added here for Docker Registry, TLS, and Generic. The generic secret command is defined in this file and the other two have their own files called create_secret_docker.go and create_secret_tls.go respectively.

I dunno if this is helpful, but trying to change kubectl a la [this PR](https://github.com/kubernetes/kubernetes/pull/114737) results in broken kubectl help messages:

```
kubernetes on 🌱fix/command [$!] via 🐹 v1.19.4 on ☁️  (us-west-2) 
❯ ./_output/bin/kubectl create secret -h
Create a secret using specified subcommand.

Available Commands:
  secret        Create a secret for use with a Docker registry
  secret        Create a TLS secret
  secret        Create a secret from a local file, directory, or literal value

Usage:
  kubectl create secret [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).

kubernetes on 🌱fix/command [$!] via 🐹 v1.19.4 on ☁️  (us-west-2) 
❯ ./_output/bin/kubectl create secret generic -h
Create a secret using specified subcommand.

Available Commands:
  secret        Create a secret for use with a Docker registry
  secret        Create a TLS secret
  secret        Create a secret from a local file, directory, or literal value

Usage:
  kubectl create secret [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

Cobra appends the usage of subcommands so that the final output is correct, I'm not sure if the website takes this into account or not or is using something else to generate these example commands.

**Comment by sftim** [comment]
/retitle Wrong example in (generated) kubectl command reference

**Comment by ChayanSD** [comment]
I am new in opensource.
i would like to contribute on this projects.
Can anyone give me some resource ?
i will study on this project than contriute.

**Comment by tengqm** [comment]
@ChayanSD The reference is generated using the tool https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-kubectldocs

**Comment by mpuckett159** [comment]
Oh I think I see where the issue is. In `read_cmd.go` it looks like the NewSubCommands func just generates a list of subcommands, so it has a list of top level commands that includes create (thus `kubectl create` is given properly) but then it doesn't differentiate between the subcommand secret and the subcommands of secret, it just views them all as subcommands of the same "level" and so it just appends the commands with each other so you get `kubectl create secret` and `kubectl create generic` instead of `kubectl create secret generic`. We need something that will properly walk the tree of subcommands and append any subcommands of subcommands properly.

**Comment by Zhuzhenghao** [comment]
Hi, @mpuckett159 , I really appreciate your assistance.

I've submitted a pull request and I'm looking for feedback. Would you help me with it?

**Comment by mpuckett159** [comment]
Apologies but I don't have any input in that repo I don't think, just some specific directories owned by sig-cli in the kubernetes/kubernetes repo. It does look like (based on the generated website content) that you got it fixed though. Thank you for getting this resolved :)

**Comment by aj11anuj** [comment]
Issue is fixed
/close not-planned

**Comment by aj11anuj** [comment]
Oops
/reopen
