### ISSUE TITLE
Trouble configuring containerd on Ubuntu 22.04 for CRI integration with Kubernetes

### ISSUE THREAD

**Issue by dominiksr** [kubernetes/website#38675]
Under Configuring the systemd cgroup driver there is to set one parameter in the /etc/containerd/config.toml file. This entry could be found in ubuntu 18.04 unfortunately it is not in ubuntu 20.04 or 22.04. 

Currently in 20.04 I insert
```[plugins. "io.containerd.grpc.v1.cri".containerd.runtimes.runc]```

at the beginning of this file and
```  [plugins. "io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]```
```    SystemdCgroup = true```
at the very end of this file.

systemd works without problems. Is this what the config.toml file should look like?

**Comment by sftim** [comment]
Hi @dominiksr 

It sounds like you want help with containerd and / or Ubuntu, so that you can set up a Kubernetes cluster on Ubuntu using containerd as the container runtime.
https://containerd.io/ is the main website for containerd, and https://ubuntu.com/ documents Ubuntu.

For help combining these different projects to get a running cluster, consider asking on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

This repo is really for reporting issues specifically with the existing Kubernetes documentation, or to suggest improvements to it.
Right now, we don't have a page specifically about setting up Kubernetes on Ubuntu with containerd. Perhaps if we (Kubernetes SIG Docs) get a lot more help, we'll have capacity to add and maintain a page that does cover that. We'd need to be fair to other OSs and other container runtimes, so it's actually a lot of work to add all the different combinations and then keep them maintained.

You could also search the web for “set up Kubernetes on ubuntu 22.04 with containerd” - there are a bunch of pages out there that other people maintain.

**Comment by sftim** [comment]
/retitle Trouble configuring containerd on Ubuntu 22.04 for CRI integration with Kubernetes

**Comment by dominiksr** [comment]
> Hi @dominiksr
> 
> It sounds like you want help with containerd and / or Ubuntu, so that you can set up a Kubernetes cluster on Ubuntu using containerd as the container runtime. https://containerd.io/ is the main website for containerd, and https://ubuntu.com/ documents Ubuntu.
> 
> For help combining these different projects to get a running cluster, consider asking on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).
> 
> This repo is really for reporting issues specifically with the existing Kubernetes documentation, or to suggest improvements to it. Right now, we don't have a page specifically about setting up Kubernetes on Ubuntu with containerd. Perhaps if we (Kubernetes SIG Docs) get a lot more help, we'll have capacity to add and maintain a page that does cover that. We'd need to be fair to other OSs and other container runtimes, so it's actually a lot of work to add all the different combinations and then keep them maintained.
> 
> You could also search the web for “set up Kubernetes on ubuntu 22.04 with containerd” - there are a bunch of pages out there that other people maintain.

Thanks I understand. I wrote here because it seemed to me that the documentation as such is not dependent on the distribution. And the description that is there indicates that in the /etc/containerd/config.toml file there should be a line:
```[plugins. "io.containerd.grpc.v1.cri".containerd.runtimes.runc]``` 
after installation of containerd. 

I thought such information might be useful. Because I myself, as a beginner, was misled by this inaccuracy. I thought that the problems I had when installing k8s on ubuntu 22.04 were caused by containerd. Which after installation did not have these entries in the configuration file.
