### ISSUE TITLE
Text colour should be black

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes/website#38730]
### What would you like to be added?

![Screenshot from 2023-01-02 12-59-51](https://user-images.githubusercontent.com/109643863/210204230-9205bd5d-6882-4db1-a567-f525782c25a2.png)
when I landed on this page. I need to highlight the text in order to see them. The box stroke, fill and text color all are in same color which is white. I am not from front-end but I think we can collaborate and make this issue done.

### Why is this needed?

It will make website better and help others.

**Comment by sftim** [comment]
The style sheet for this website typically uses black text on white. That diagram then uses white text on blue.

If you set a user style sheet or otherwise customize how the site is displayed, make sure that your customization leaves it readable. This also applies when you have a browser plugin for doing that customization.

/triage not-reproducible
/remove-kind feature
/kind bug

**Comment by Sajiyah-Salat** [comment]
Ohk I got this
