### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by rinocata** [kubernetes/website#38835]
The [documentation](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster) inadequately explains how to restore `etcd` from a snapshot. Namely, it is not stated that running 
`etcdctl snapshot restore` doesn't actually _"restore"_ the snapshot and that further configuration is needed (e.g. modifying the `etcd` pod manifest).

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster
/language en

**Comment by divya-mohan0209** [comment]
@rinocata thank you for flagging this and I fully agree with what you've said. However this is potentially out of scope for the Kubernetes project to document in its website since the etcd project should ideally be recording these steps in their [disaster recovery section](https://etcd.io/docs/v3.6/op-guide/recovery/#restoring-a-cluster). We can only link and recommend what has been documented by them since that is a project we're dependent on.

**Comment by tengqm** [comment]
I agree we don't fix it here. Users are encouraged to refer to etcd official docs.
/close
