### ISSUE TITLE
Object Names and IDs

### ISSUE THREAD

**Issue by KastenMike** [kubernetes/website#38907]
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

`Each object in your cluster has a [Name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names) that is unique for that type of resource` makes me think that if someone cannot create a CronJob named xyz in `batch/v1beta1`  and then upgrade kubernetes to where it is deprecated that they wouldn't be able to create a 2nd resource with the same name but with `batch/v1` is this correct? 

I tried to reproduce without upgrading (1.21 apparently has both versions) but Kubernetes seems to automatically alter my `BatchV1beta1().CronJobs` create command and instead create a V1 version

`/api/v1/pods/some-name` is mentioned along with `kind` without specifically mentioning that names are unique across API versions of the resource. If so it would be nice to add for clarity

**Comment by sftim** [comment]
This mostly feels like a support query.

If you create a CronJob named `foo` with an available API version, eg `batch/v1beta1`, then you can use any other API version for CronJob to read back a CronJob named `foo`. The API server automatically converts from the stored representation to the field meanings for the API that you use. You don't have three CronJobs named `foo` if you have three versions of CronJob active in your cluster. You have one CronJob and several different URIs that you can use to interact with it.

**Comment by KastenMike** [comment]
It's about potentially adding clarity to the specified doc. If on an older version of kubernetes and you create a cronjob then the `-oyaml` would say `batch/v1beta1`. What if you then upgrade the cluster? Presumably it's still `batch/v1beta1`? I guess an attempt to `create -f` the same with `batch/v1` would then fail due to the name clash?

**Comment by sftim** [comment]
The API version that `kubectl` prefers to ask for depends on **`kubectl`**, not on the cluster. Although, `kubectl` will never request a version that your cluster's API server(s) aren't offering.

If you have a CronJob and try to create a new CronJob with the same name, that create operation fails regardless of what API version you use. That's because you already have a CronJob with that particular `.metadata.name`

Versions of Kubernetes don't matter here.

Maybe https://kubernetes.io/docs/concepts/overview/working-with-objects/names/ could link to a doc that explains how there are different APIs that nevertheless let you access the _same_ object (literally, the backing data are the exact same bytes in the persistence layer).

**Comment by KastenMike** [comment]
ah ok thanks for clarifying; [#api-groups-and-versioning](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups-and-versioning) seems a good option for a cross reference

**Comment by Sajiyah-Salat** [comment]
I got the issue. Let me know where this changes will be relatable. I will add that. Thank you.

**Comment by tengqm** [comment]
Maybe add a link to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/ that points to https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups-and-versioning, so that users know **API resources are distinguished by their API group, resource type, namespace (for namespaced resources), and name.**.
In other words, API version is irrelevant here.

**Comment by Sajiyah-Salat** [comment]
Great will do shortly. Thank you.

**Comment by tengqm** [comment]
Resolved.
/close
