### ISSUE TITLE
kubernetes my issue

### ISSUE THREAD

**Issue by AppleKevin1106** [kubernetes/website#39084]
What happened?
Hi Team!
Thank you for your support.

I was in following the documentation with the link goes [here](https://kubernetes.io/blog/2015/04/borg-predecessor-to-kubernetes/).
But when I tried to go through the details about 1. [Pods] https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pods.md), 2. [Services](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md) and 3. [Labels](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md) on Github, it redirected to the 404 pages.

Maybe the Markdown documentations are missing...

Thanks.

What did you expect to happen?
https://kubernetes.io/blog/2015/04/borg-predecessor-to-kubernetes/

How can we reproduce it (as minimally and precisely as possible)?
Adding restore the missing Markdown documentations.

**Comment by tamilselvan1102** [comment]
@AppleKevin1106 
How did you navigate the pages that you mentioned above?
if you directly enter any unimplemented pages, it will show same error.

**Comment by divya-mohan0209** [comment]
Hello @AppleKevin1106 

On [this page](https://kubernetes.io/blog/2015/04/borg-predecessor-to-kubernetes/), the following terms and their respective redirects have been pasted below. These are as-is visible on my browser.

Pods : https://kubernetes.io/docs/concepts/workloads/pods/
Services: https://kubernetes.io/docs/concepts/services-networking/service/
Label: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

Please could you clear your cache & retry since your browser probably uses a cached version of the Kubernetes blog.

These have been updated recently via #38945 and are correctly reflected on the website. 

/triage-not-reproducible

**Comment by tamilselvan1102** [comment]
@divya-mohan0209 
@AppleKevin1106 trying to accessing the page through Github link, that's why it is throwing the error.

**Comment by tengqm** [comment]
Those are very old blog pages. We typically don't fix them due to lack of resources.
