### ISSUE TITLE
State that users have to disable firewalld and enable iptables after setting up cluster on a fresh CentOS install

### ISSUE THREAD

**Issue by ngthanhtrung** [kubernetes/website#3943]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

For now it's quite unclear that after setting up Kubernetes cluster on CentOS with `kubeadm`, we have to disable `firewalld` and enable `iptables`.

**Proposed Solution:**

We should state clearly to users that after setting up things on a fresh install of CentOS, they have to disable `firewalld` and enable `iptables`.

**Page to Update:**

[https://kubernetes.io/docs/getting-started-guides/kubeadm/](https://kubernetes.io/docs/getting-started-guides/kubeadm/).

**Comment by kkirsche** [comment]
Since firewalld uses iptables under the hood, is that the case even with the Limitations item which states:

Some users on RHEL/CentOS 7 have reported issues with traffic being routed incorrectly due to iptables being bypassed. You should ensure `net.bridge.bridge-nf-call-iptables` is set to 1 in your sysctl config, eg.
```
cat /etc/sysctl.d/k8s.conf
```
Should have:
```
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
```

Just want to make sure that doesn't address this issue
