### ISSUE TITLE
More info about installation method without package manager 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes/website#39444]
## What happened?

By looking at the documentation: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ we see an option to install the kubeadm without the package manager. 

However, it is not a static compilation. In this way:

- a) Should it not describe what libs should be present in the host before installation? 

> NOTE: Just for clarifications the concern here is about the shared libs, i.e:
> 
> ```
> $ ldd /usr/bin/kubelet
> 	linux-vdso.so.1 (0x00007ffc1b3c7000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f74ef2d3000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f74ef2cd000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f74ef0db000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f74ef2fe000)
> ```

- b) Could the binaries be static so they could be entirely self-contained?
- c) Is that an option recommended for prod envs, or is it more like installing from the source for testing purposes? 
- d) When/and for what situations would it be recommended install kubeadm via binaries? Would that address more needs of toolings and other projects that use kubeadm to do the installation against many OSs and do not want to care about the target OS? 

## What you expected to happen?

It would be great to have further information regards the above questions.

PS.: It also might to be related to: https://github.com/kubernetes/kubernetes/issues/26093

**Comment by camilamacedo86** [comment]
Hi @Tim Bannister, 

You transfered this issue to the docs. However, will the docs team be able to answer the questions for them we are able to add the info there? Or would this info better gathered checked by the kubeadm maintainers?

**Comment by sftim** [comment]
This is the right repo. SIGs including cluster lifecycle work in this repo and do see issues against the pages they maintain.

**Comment by jpetazzo** [comment]
Hi!

I was curious so I took a look; some binaries (like `kubeadm`) are static, while others (like `kubelet`) are dynamic.

This seems to be controlled by `KUBE_STATIC_LIBRARIES` in [hack/lib/golang.sh](https://github.com/kubernetes/kubernetes/blob/release-1.26/hack/lib/golang.sh#L327) (with some overrides in [is_statically_linked_library](https://github.com/kubernetes/kubernetes/blob/release-1.26/hack/lib/golang.sh#L358) a few lines below).

As an experiment, I tried to add `kubelet` to `KUBE_STATIC_LIBRARIES`, and `make kubelet` then gave me a static binary which seemed to run fine. That being said, I didn't run any extensive tests on it, and I don't know what's the rationale for having some binaries linked dynamically vs statically. (In my experience, with Go binaries, dynamic linking is necessary when enabling CGO, which is used by some dependencies; for instance to use a custom DNS resolver using avahi/bonjour configured through nsswitch instead of Go's built-in resolver; but again, I don't know the rationale for kubelet.)

From my perspective, it would be acceptable to mention in the docs something like the following:

> If you choose to install from binaries, please note that some binaries (e.g. kubelet as for Kubernetes 1.26) use dynamic linking and assume that your system provides glibc. This is a reasonable assumption on many Linux distributions (including Debian, Ubuntu, Fedora, CentOS, and many others) but it is not the case on Alpine (which uses musl). If you get a brief error message like `kubelet: no such file or directory` or `kubelet: not found` when trying to run kubelet, double-check with e.g. `ldd kubelet` that the dynamic libraries that it requires are found correctly on your system.

WDYT?

**Comment by tengqm** [comment]
The (fake) libraries you listed are all from the glibc package on Linux. The glibc package is there to be able to parse and load all Linux standard binaries (ELF format). They are not real dependencies to any add-on type of libraries or packages. I would not see them as an extra dependency for installation. For example, without ld-linux.so, the operating system won't be able to load your binary from disk into memory for execution. That library is a parser for your ELF binary. It knows how to layout your code, you data and your stack in memory. It knows how to make the 'open' syscalls linked to the OS kernel so that when your binary (kubelet) wants to open a file, the kernel is properly invoked to get it done.

**Comment by sftim** [comment]
I agree - `glibc` has alternatives, but `ld-linux`, `libdl` and `linux-vdso` are unavoidably part of the OS.

**Comment by sftim** [comment]
`glibc` as `libc.so.6` dates from January 1997. You won't be able to run Kubernetes on computers running an older Linux. Do we need to document this?

**Comment by tengqm** [comment]
`libc.so.6` is a generic symbol for portability's purpose. Is there a real scenario where we a Linux doesn't support `libc.so.6`? My understanding is that all Linux distributions (including their minimal install variants) have to have a library (which in theory doesn't have to be `glibc`) that provides the `libc.so.6` symbol. By Linux distribution, I'm also referring to those base OS images built for a cloud environment.

**Comment by sftim** [comment]
I'd like to know why we should do this.

/priority awaiting-more-evidence

**Comment by jpetazzo** [comment]
What @sftim and @tengqm wrote above is mostly correct, but not totally correct, in the sense that `ld-linux`, `libdl`, and `linix-vdso` are *not* unavoidably part of the OS, and they are *not* necessary to run Linux binaries. They are necessary to run *dynamic* Linux binaries, and 99% of the binaries shipping with 99% of the distros are dynamic, so it's mostly correct; but these files are not necessary to run *static* binaries (see all the `scratch`-based container images for examples; or the fact that some distros ship a static `busybox`, which you can use as an `init` replacement for troubleshooting/salvage purposes, in case your libc or linker are corrupted).

Furthermore, the linker (`ld-linux` and `libdl`) are libc-specific; i.e. the glibc one won't work with musl dynamic binaries and vice-versa (although I've read that there are compatibility things that can be done on the musl side to let the musl linker load glibc binaries with some limitations).

Some folks building custom Kubernetes distributions (e.g. based on Alpine, to be more space-efficient, e.g. to load the whole system in RAM and operate without a local disk) might want binaries that don't rely on glibc. But, I'd argue that these folks should usually know what they're doing - in the sense that they should know that they're using Alpine (or a glibc-less system) and they should know how to figure out if the binaries are static or dynamic, and which steps to follow to obtain static builds, for instance.

I don't have a particular opinion about what should be included in the install docs. I think it's fair to mention that some binaries rely on glibc, but it's also fair to leave that out since it might confuse more folks than it will help :-)

**Comment by camilamacedo86** [comment]
Hi Everybody, 

Thank you a lot for all info provided. So, I think we have a conclusion for the raised questions as follows. Please, let me know if I misunderstand something.


> a) Should it not describe what libs should be present in the host before installation?
> NOTE: Just for clarifications the concern here is about the shared libs, i.e:
> 
> $ ldd /usr/bin/kubelet
> 	linux-vdso.so.1 (0x00007ffc1b3c7000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f74ef2d3000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f74ef2cd000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f74ef0db000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f74ef2fe000)

We could add a small note just to help out advanced users without bring confusion. Something like: (Following a suggestion)

_NOTE: This installation is done via binaries that uses dynamic linking and assume that your system provides glibc. This is a reasonable assumption on many Linux distributions (including Debian, Ubuntu, Fedora, CentOS, and many others) but it is not the case of custom and light distributions which are glibc-less system such as Alphine._

> b) Could the binaries be static so they could be entirely self-contained?

We raise an issue to check that: https://github.com/kubernetes/kubernetes/issues/115757 and can leave the discussion there. 

> c) Is that an option recommended for prod envs, or is it more like installing from the source for testing purposes?

I think we can assume that is supported for production env and we do not need change the docs.
If that was not supported then, I would expected the docs have an WARNING say that should not be used on those. 

> d) When/and for what situations would it be recommended install kubeadm via binaries? Would that address more needs of toolings and other projects that use kubeadm to do the installation against many OSs and do not want to care about the target OS?

I do not think that we need to address it in the docs. However, I would assume that the big motivation for we provide binaries and does not use the package manager is when we want to automate the install. Please, let me know if I am wrong. 

Thank you a lot for all your inputs and time so far.

**Comment by tengqm** [comment]
+1 for adding a note.

**Comment by sftim** [comment]
I'd add that note in the “Before you begin” section:
- https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin

and then maybe have a couple of words (maybe four or five) linking back to that, just at the point we tell people to download binaries.

**Comment by sftim** [comment]
/reopen
/triage accepted
/remove-lifecycle rotten
/priority backlog

@camilamacedo86 please consider updating the issue description to either:
- link to https://github.com/kubernetes/website/issues/39444#issuecomment-1431136947
- summarize that thinking

**Comment by sftim** [comment]
I would add that we document
>  The Kubernetes project provides generic instructions for Linux distributions based on Debian and Red Hat, and those distributions without a package manager.

We can clarify, if we want, that we expect a Linux distribution that provides glibc or a compatibility layer providing the expected symbols. Remember, the docs explain how Kubernetes works _now_ and not how we might hope it works in the future. Right now at last some release binaries do assume that glibc is available.

**Comment by neolit123** [comment]
commented on the linked website PR:
https://github.com/kubernetes/website/pull/42124#discussion_r1271252481

before merging the note, this thread needs feedback from a kubelet maintainer to confirim if the CGO / dynamic linking is expected. IIRC, in the past the kubelet had a CGO dependency by mistake, it was resolved, and it currently it may have re-appeared.
