### ISSUE TITLE
Clarify updates to `deletionTimestamp` during object removal

### ISSUE THREAD

**Issue by feldentm-SAP** [kubernetes/website#39490]
https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/ states that finalizers can be used to block deletion indefinitely. However, there is no explicit statement on updates to deletionTimestamp.
It would make sense to prevent updates other from zero to some value, but if that's the case, it should also be mentioned here.
This might look like a detail, but it is an important one when designing controller deletion protocols.

**Comment by sftim** [comment]
/retitle Clarify updates to `deletionTimestamp` during object removal

/sig api-machinery
/language en

**Comment by Ritikaa96** [comment]
Hi @feldentm-SAP there is a very good [blog](https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/) regarding finalizers that mention deletionTimestamp. PTAL. If I'm understanding right this blog might help.

> In short, what’s happened is that the object was updated, not deleted. That’s because Kubernetes saw that the object contained finalizers and blocked removal of the object from etcd. The deletion timestamp signals that deletion was requested, but the deletion will not be complete until we edit the object and remove the finalizer.

**Comment by feldentm-SAP** [comment]
Hi @Ritikaa96, I get how the deletion protocol works in Kubernetes. I also get why that's the case. What I ask is to extend the documentation with the guarantee that, once a deletion timestamp has been set to a nonzero value, it will never get another value thereafter.
The issue is that there are guides to use finalization for indefinite deferral of the actual delete. But, there is no mechanism to actually abort the delete. Thus, if someone decides to manually delete a resource that cannot be deleted that way, the only fix for this is either to have a protection finalizer and completely ignore deletion timestamp or to replace the resource with an equivalent copy.
Furthermore, I ask for a specific documentation, because the interaction with ownership is non-trivial and one should be assured that whatever is implemented will stay that way in future versions.

**Comment by sftim** [comment]
When you `DELETE` an object, Kubernetes makes that object _almost_ read-only. If the object has no finalizers then the read-only object can disappear right away. Otherwise, the “read only” object is changed to record the timestamp that it was frozen.

It's _almost_ read-only because:
- the `metadata.deletionTimestamp` field gets set
- you can remove, but not add or change, finalizers

As far as I know, admission control checks still apply. For example, if there's a ValidatingAdmissionWebhook that restricts removal of a particular finalizer, the restrictions still happen even for an object that's being deleted.


Let's clearly document that objects being finalised are read-only with the exceptions I've mentioned. Then the immutability of `deletionTimestamp` goes without saying.

If we want to we can explain the implication: you cannot resurrect an object that is has already had deletion requested; you can only delete it and then make a new similar object.

**Comment by feldentm-SAP** [comment]
Thanks, that clarification would be great.

**Comment by Ritikaa96** [comment]
/triage accepted
Hi @feldentm-SAP !contribution is welcome regarding this issue.
As it has been long time without any comments , i''d like to ask if you want to work on this?

**Comment by Ritikaa96** [comment]
Raised PR: #41304 for the same.PTAL is this what you expected @feldentm-SAP ? please let me know

**Comment by feldentm-SAP** [comment]
> Raised PR: #41304 for the same.PTAL is this what you expected @feldentm-SAP ? please let me know

yes, thanks; left a comment in the PR
