### ISSUE TITLE
Issue with /docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by danieljcosta** [kubernetes/website#3974]
**This is a...** 

- [ x ] Feature Request
- [ ] Bug Report

**Problem:**
Unable to find how is it possible to associate a persitentStorage with the StatefulSet in the documentation.

**Proposed Solution:**
Add an example.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by tengqm** [comment]
By "persistentStorage", you meant "persistent volumes"?
The document does contain a sample that shows how to dynamic provision persistent volumes to a StatefulSet. There are links to the persistent volume concept.
So I'm wondering if this is still an issue. Is it possible that the issue was filed before the dynamic provisioning doc was written?

Can we close this?
