### ISSUE TITLE
“Safely Drain a Node” states that you need Kubernetes 1.5 or later

### ISSUE THREAD

**Issue by wsmelton** [kubernetes/website#40453]
The PR #23755 improperly set the minim version to 1.5 when there is no such version.

Public link: https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/
Markdown file: https://github.com/sftim/kubernetes-website/blob/main/content/en/docs/tasks/administer-cluster/safely-drain-node.md

![image](https://user-images.githubusercontent.com/11204251/229378533-b5a946b3-5a04-4ab4-b307-742e7c270be7.png)

![image](https://user-images.githubusercontent.com/11204251/229378552-57791473-9b4f-4af3-954a-0710496b042e.png)

**Comment by kundan2707** [comment]
kubernetes 1.5 release end of life (1 October 2017) already passed so this page needs updation

**Comment by Ritikaa96** [comment]
I guess it is mentioned because :
https://github.com/a0x8o/kubernetes/blob/master/CHANGELOG-1.5.md

**Comment by Ritikaa96** [comment]
I guess it is mentioned because in v1.5:
[beta] PodDisruptionBudget has been promoted to beta, can be used to safely drain nodes while respecting application SLO's ([docs](http://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)) (https://github.com/kubernetes/enhancements/issues/85)

As per release [page](https://kubernetes.io/releases/)
The Kubernetes project maintains release branches for the most recent three minor releases (1.26, 1.25, 1.24). Kubernetes 1.19 and newer receive [approximately 1 year of patch support](https://kubernetes.io/releases/patch-releases/#support-period). Kubernetes 1.18 and older received approximately 9 months of patch support.

It totally depends upon the docs and 
/sig node
what they want to mention. If it is mentioned because of the time this feature went beta this page might be right.

**Comment by sftim** [comment]
/retitle “Safely Drain a Node” states that you need Kubernetes 1.5 or later
/language en

That statement is correct and its inclusion does not, to me, feel misleading.

/priority awaiting-more-evidence

**Comment by wsmelton** [comment]
When is 1.5 to be released?

**Comment by wsmelton** [comment]
Just to confirm the version indicates the complete functionality is not available until v1.5 is released?

PDB is [noted released in stable 1.21](https://kubernetes.io/docs/tasks/run-application/configure-pdb/). Only confusing area is what functionality in the document is for 1.5 and what is available now?

**Comment by sftim** [comment]
Try this: https://www.google.com/search?q=when+was+kubernetes+1.5+released

The page does not say you need to wait for an _upcoming_ release. I think you have misunderstood what is actually a clear statement @wsmelton.

We _could_ drop the `version-check` shortcode as we assume everyone is using Kubernetes 1.21 or later.

**Comment by tengqm** [comment]
/triage accepted
Drop the version-check would be desireable.

**Comment by sftim** [comment]
For SIG Docs, this is only a backlog priority I think. We've other work that we'd want to prioritize.

Help here is still very welcome!
