### ISSUE TITLE
“Define Environment Variables for a Container” does not show example for using `envFrom`

### ISSUE THREAD

**Issue by shirady** [kubernetes/website#40572]
It is written ([here](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)):

> This page explains how to use env.

What about `envFrom` example?

**Comment by dipesh-rawat** [comment]
Page: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/

/retitle “Define Environment Variables for a Container” does not show example for using `envFrom`
/language en

**Comment by dipesh-rawat** [comment]
In the docs on a different page _(https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables)_  we do have an example that is using `envFrom`. 

We could reuse/repurpose the same example for [Define-environment-variable-container](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/) page or we could also provide a link to the existing [example page](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables) to view usage of `envFrom`.

**Comment by KhushPatibandha** [comment]
Hey, I worked on a similar issue where I had to define "env" and "envFrom" so I would like to work on this.
/assign

**Comment by KhushPatibandha** [comment]
so instead of reusing the same examples and explaining the same thing that is already written in the doc can we just provide a link to already existing examples? 
because I think using same examples again is sort of bad practice since we already have that explained OR we can move all of those examples and the explanation where we are trying to add the examples, but that would create chaos 
So in my opinion I think we should just add a link to the examples 
Do let me know if there is anything I am missing or am wrong about.
