### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by ekeoch** [kubernetes/website#4073]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
This is more of an update to the documentation, or something that was omitted. The example persistentVolumeClaim Doesn't bind to its corresponding persistentVolume. At least based on the yaml definitions. I also tried it out in a minikube environment and the PVC kept spawning an entirely new PV using a standard storage class with a retention policy of "Delete".  

**Proposed Solution:**
i. To fix This I had to explicitly specify the volumeName in the spec of the PV yaml. Like so.

```kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  volumeName: task-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

ii. I am not sure if that's how it works in production, but assigning a storage class (that is not the default specified by the user) can lead to problems. At the very least I believe it should be mentioned in the docs.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by aburdenthehand** [comment]
Thanks for raising the bug @ekeoch 
The task-pv-claim.yaml has changed a bit since this was raised. I tested it today and it bound as expected. 
The content re: PVs and PVCs had an update the same day this was raised (can't tell if before or after; sorry if this was there was already present when you encountered this) and the content now links to the Storage Classes topic:
https://kubernetes.io/docs/concepts/storage/storage-classes/

Based on that, I think this issue can be closed - but let me know if the current content is still incomplete or erroneous.
