### ISSUE TITLE
Kubelet Configuration (v1beta1) - LoggingConfiguration leads to 404

### ISSUE THREAD

**Issue by afro-coder** [kubernetes/website#40731]
Hi,

The link below `Refer to Log Options` leads to a [404](https://github.com/kubernetes/component-base/blob/master/logs/options.go)
![image](https://user-images.githubusercontent.com/8469842/232486958-f7b4c06d-a861-4ecc-be06-3403beaea2bb.png)

I'll gladly submit a PR for this, however, I'm not sure which file this should point to anymore since the `options.go` has been removed completely after 1.24

**Comment by tengqm** [comment]
We don't fix it in the docs because the docs are generated from the upstream source code: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L686.

Please read https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/ if you want to help fix this issue.

**Comment by afro-coder** [comment]
Oh gotcha thanks for sharing, so if I'm understanding this correctly I need to make changes there and it will auto-generate the docs. Let me see the changelog for any hints on why this file was removed that may help.
