### ISSUE TITLE
replace all references to https://storage.googleapis.com/kubernetes-release with https://dl.k8s.io

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/website#41069]
**This is a Bug Report**

**Problem:**

There are still references to `https://storage.googleapis.com/kubernetes-release` instead of `https://dl.k8s.io`

dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket

ref: https://github.com/kubernetes/k8s.io/issues/2396

**Proposed Solution:**

Replace `https://storage.googleapis.com/kubernetes-release` with `https://dl.k8s.io`

Also replace any `gs://kubernetes-release` references with using https://dl.k8s.io if applicable.

**Page to Update:**

Assorted https://cs.k8s.io/?q=%2Fkubernetes-release&i=nope&files=&excludeFiles=&repos=kubernetes/website
e.g. [tasks/tools/install-kubectl.md](https://github.com/kubernetes/website/blob/c104c207390af7c3ad6f2fbb7742378fe6b69eb0/content/de/docs/tasks/tools/install-kubectl.md), [setup/production-environment/tools/kubeadm/install-kubeadm.md](https://github.com/kubernetes/website/blob/c104c207390af7c3ad6f2fbb7742378fe6b69eb0/content/id/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md)

**Comment by 9bany** [comment]
sorry @pranav-pandey0804, i had fixed this

**Comment by pranav-pandey0804** [comment]
> sorry @pranav-pandey0804, i had fixed this

hi @9bany Not a problem, didn't see anyone assigned to this issue.
I am unassigning myself and assigning it to you.

/unassign

**Comment by shurup** [comment]
Hi, @9bany! I found a small issue with your proposed changes regarding one of the URLs, which is mentioned twice in the `install-kubectl.md` file.

While `curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt` returns `v1.27.1` as expected, I am getting an nginx-rendered HTML page saying `302 Found` for the new command (`curl -s https://dl.k8s.io/release/stable.txt`) instead.

As I understand, it happens due to the redirect configured on the new web server. Thus, `curl -LS https://dl.k8s.io/release/stable.txt` works fine for me (it returns `v1.27.1` as expected).

**Comment by 9bany** [comment]
Just done, please review all of PRs @approvers

**Comment by BenTheElder** [comment]
Thanks!
