### ISSUE TITLE
Init Containers bash typo in examples

### ISSUE THREAD

**Issue by johnnydevops** [kubernetes/website#41144]
This example...

`for i in {1..100}; do sleep 1; if dig myservice; then exit 0; fi; done; exit 1`

has an issue.  dig always returns true "0" regardless of whether the name resolves, so if the intent is that 'dig myservice' should be replaced with the dns name of the services this will always loop to 100 and end.

perhaps this should be:
`for i in {1..100}; do sleep 1; if dig myservice |  grep -q 'NXDOMAIN' ; then exit 0; fi; done; exit 1`

`grep -q 'NXDOMAIN'` will filter NXDOMAIN (failing DNS)

**Comment by niranjandarshann** [comment]
Ref Link : https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#examples
/sig docs
/language en

**Comment by AmarNathChary** [comment]
@johnnydevops I agree with you about this modification of command. the script will exit successfully when it detects a failed DNS resolution (NXDOMAIN)

**Comment by able8** [comment]
Agree that the `dig myservice` always returns true "0" regardless of whether the service exists. 

But the scenario is [Wait for a Service to be created, using a shell one-line command like:](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#examples).
The `dig myservice |  grep -q 'NXDOMAIN'` still does not work, because If the `myservice` does not exist, the command returns 0, and the  script exits 0. We can not wait for the service.
To wait for the service to be created, we can replace `dig` with `nslookup` since "nslookup returns with an exit status of 1 if any query failed, and 0 otherwise."

**Comment by johnnydevops** [comment]
Thanks abel8!  nslookup is better with its exit behavior.  And the example reads cleaner without the extra pipe and complexity.  Nice!  Thanks!

**Comment by niranjandarshann** [comment]
> Agree that the `dig myservice` always returns true "0" regardless of whether the service exists.
> 
> But the scenario is [Wait for a Service to be created, using a shell one-line command like:](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#examples). The `dig myservice | grep -q 'NXDOMAIN'` still does not work, because If the `myservice` does not exist, the command returns 0, and the script exits 0. We can not wait for the service. To wait for the service to be created, we can replace `dig` with `nslookup` since "nslookup returns with an exit status of 1 if any query failed, and 0 otherwise."

@able8  you had raised the PR to fix the issue so you can assign this issue to yourself.
/assign @able8
