### ISSUE TITLE
hi i am using laravel with kuberner with postgres it show error

### ISSUE THREAD

**Issue by Prem-kumar007** [kubernetes/website#41411]
driver not found

**Comment by T-Lakshmi** [comment]
Hey @Prem-kumar007,
GitHub is not the right place for support requests.

If you're looking for someone to help you learn how to configure your Kubernetes cluster, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

These places are better to resolve support queries fast.

**Comment by divya-mohan0209** [comment]
Hello @Prem-kumar007 , please provide more information around this issue because as-is, the content is not enough to ascertain whether changes are needed in the docs or if this is a support issue. Since there has been no response from your end from quiet some time, I'll be closing this off. In the event, you would like to recommend a change to the docs, please reopen the issue and provide more context.
/close
