### ISSUE TITLE
Assistance required for running website locally on Windows

### ISSUE THREAD

**Issue by rohan9024** [kubernetes/website#41436]
This is the error I'm facing-->

![image](https://github.com/kubernetes/website/assets/64919642/e89e377b-18bd-4b08-a703-1288c1d5fe5b)

I'm using windows and I have installed the prerequisites

**Comment by dipesh-rawat** [comment]
/retitle Assistance required for running website locally on Windows

**Comment by dipesh-rawat** [comment]
@rohan9024 Based on the provided information, I can see that there is an issue indicated in the shared logs that Windows is unable to locate the program `hugo`. This could likely be caused by a disparity in the value of `%PATH%` (or similar environment variables) when the `make` command initiates a shell.

Did a quick search on Google, I stumbled upon a potential solution that might be of assistance. Feel free to explore the following link and see if it addresses the issue you encountered: [makefile-error-make-e-2-the-system-cannot-find-the-file-specified](https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified)

**Comment by dipesh-rawat** [comment]
Alternatively, if you have Docker installed on your computer, you can try running the website inside a Docker container on your computer. You can find instructions at [running-the-website-using-a-container](https://github.com/kubernetes/website#running-the-website-using-a-container).

**Comment by sftim** [comment]
BTW, the `Makefile` approach isn't something we support on Windows. You're welcome to try it.

At some point it'd be nice to have a PowerShell script that does a similar job (so far, nobody has made one).

**Comment by rohan9024** [comment]
@sftim Is there any way to run the project on windows ? Or should I use linux in case?

**Comment by rohan9024** [comment]
> Alternatively, if you have Docker installed on your computer, you can try running the website inside a Docker container. You can find instructions at [running-the-website-using-a-container](https://github.com/kubernetes/website#running-the-website-using-a-container).

Yeah sure. Trying it now. Thank you so much for your assistance😄

**Comment by rohan9024** [comment]
@dipesh-rawat @sftim 

![image](https://github.com/kubernetes/website/assets/64919642/2b833252-e8b2-4e2c-aeca-3d69025612c9)


Tried using the docker approach by setting up the image but I'm facing this error.

**Comment by rohan9024** [comment]
@utkarsh-singh1 Yeah I tried the same; still facing the same error

**Comment by niranjandarshann** [comment]
After 30d of inactivity since lifecycle/stale was applied, the issue is closed
