### ISSUE TITLE
Provide a per-page outdated notification for localized content

### ISSUE THREAD

**Issue by nasa9084** [kubernetes/website#41519]
**This is a Feature Request**

**What would you like to be added**

It would be awesome if we can have a per-page outdated notification. Maybe providing a shortcode that shows the page is outdated is enough.

**Why is this needed**

We're working on updating outdated localization, of course, however, updating all outdated documents takes time. In that case, we will try updating the page though, in the meantime we would like to route users to the original English source.

**Comments**

Context: https://kubernetes.slack.com/archives/C0191RDKHU1/p1685979435036859

**Comment by Ritikaa96** [comment]
Hey @nasa9084 seems like this issue is similar to https://github.com/kubernetes/website/issues/41446

**Comment by sftim** [comment]
/priority backlog
/retitle Provide a per-page outdated notification for localized content

I worry that a shortcode would have similar maintenance challenges to pages: someone has to go through each stale page and update it, then get the proposed change reviewed.

Any automation we can offer will help. For example, if at least 6 months have passed between any update to the English page, without a localized page being updated, that might be relevant.

We could track by releases. For example, if an English page was updated for v1.25 and it's now v1.27 with no bump for the localized page, we can automate a way to detect that and mention it to readers.
(a separate change would detect all changes updated since a previous release and mark this in their front matter - that's feasible to implement)

**Comment by morix1500** [comment]
Is the idea to put a message at the top of the page saying "that the information on this page may be out of date"?
It seems possible and I would like to be allowed to work on it.

**Comment by sftim** [comment]
As a SIG we haven't decided on what we want to achieve. You're welcome to start on an implemementation @morix1500; please bear in mind that with an unclear preferred outcome, it's more difficult for you to deliver what we eventually decide we do want.

Consider working on an issue that has a higher priority - see https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Atriage%2Faccepted+label%3Apriority%2Fcritical-urgent%2Cpriority%2Fimportant-soon%2Cpriority%2Fimportant-longterm+sort%3Aupdated-asc for a list.

**Comment by sftim** [comment]
Done in  #41768
/close
