### ISSUE TITLE
Add hover animation for navbar contents

### ISSUE THREAD

**Issue by MohamedMafaz** [kubernetes/website#41568]
We need to add hover animation on navbar contents. Please assign me this issue. I'll work on it

**Comment by malehacker** [comment]
please add the source code link and Give info related this issue !!

**Comment by MohamedMafaz** [comment]
I also don't know the source code link. If I have I may assign this issue to myself.

**Comment by MohamedMafaz** [comment]
We need to achieve that when user hover into the navbar links there we need to add an animation. If you found the source code link, kindly let me know. It will be useful for upcoming issues

**Comment by niranjandarshann** [comment]
> We need to achieve that when user hover into the navbar links there we need to add an animation. If you found the source code link, kindly let me know. It will be useful for upcoming issues

@MohamedMafaz  You wants to change the look and feels of the current kubernetes page?
Refer link : https://github.com/kubernetes/website/tree/main/layouts
You can find source code for the kubernetes page here.

**Comment by dipesh-rawat** [comment]
/retitle Add hover animation for navbar contents

**Comment by dipesh-rawat** [comment]
Kubernetes website utilizes the [Docsy](https://www.docsy.dev/) Hugo theme.

**Comment by sftim** [comment]
Why should we make this change @MohamedMafaz

/priority awaiting-more-evidence

**Comment by rishuraj1708** [comment]
Hii ! I want to know that is any one working on this ? is this open or closed ?
If it open then assign it to me I want to work on this .

**Comment by sftim** [comment]
At the time of writing, this issue is open:
![issue header screenshot](https://github.com/kubernetes/website/assets/22591623/cebf0480-b91d-45cb-ac01-309189a16061)

---

@rishuraj1708 you, or anyone, can work on this issue by opening a pull request. However, I recommend another option: please work on issues that are important to the Kubernetes project. Visit [[filtered issues]](https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Apriority%2Fimportant-soon%2Cpriority%2Fimportant-longterm%2Cpriority%3Acritical-urgent) to see a list of those issues.

**Comment by niranjandarshann** [comment]
@MohamedMafaz  Due to inactivity in this issue from more than ~3months I will be closing this issue.
Feel free to raise the issue or reopen it if you wants to continue on it.
/close
