### ISSUE TITLE
Incorrect spacing in `Kubernetes Federation Evolution (2018)` blog article

### ISSUE THREAD

**Issue by Nitishupkr** [kubernetes/website#41578]
**This is a Bug Report**

![kubernetess](https://github.com/kubernetes/website/assets/95420063/7f7bc624-cd3a-4a7c-8635-7bb34740e113)

**Problem:**
There is not having space between .com and will .
**Proposed Solution:**
provide some space to it
**Page to Update:**
https://kubernetes.io/blog/2018/12/12/kubernetes-federation-evolution/

I will rise PR for this

**Comment by Nitishupkr** [comment]
assign it to me

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/blog/2018/12/12/kubernetes-federation-evolution
/language en

**Comment by dipesh-rawat** [comment]
/retitle Incorrect spacing in `Kubernetes Federation Evolution (2018)` blog article

**Comment by dipesh-rawat** [comment]
@Nitishupkr  This post is quite old, we have a policy in place of not making changes to blog articles that are over a year old. Therefore, I feel this update is not considered urgent. While we will consider implementing the fix you suggested, please understand that we cannot prioritise reviews for this PR due to our policy regarding older articles.

Additionally, I encourage you to take a look at our Trivial Edits guidelines, which can be found at this link: https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits.

**Comment by Nitishupkr** [comment]
Thank you @dipesh-rawat

**Comment by Nitishupkr** [comment]
Thank you @dipesh-rawat
