### ISSUE TITLE
Housekeeping of inactive approvers/reviewers for Hindi Localization

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#41598]
Context: Per review of devstats for the past 10 months, the following approvers/reviewers from the Hindi localization have reported low review/approval activity (<25). 

- @verma-kunal
- @Garima-Negi 

After an initial discussion over private DM, this issue has been opened for seeking community consensus on the housekeeping of the above reviewers from the Hindi localization.

Timelines: If there's no input/feedback by **26th June, 2023**, there'll be a PR opened to the k/website & other repos within Kubernetes for offboarding the above members as reviewers and/or approvers.

cc: @natalisucks @reylejano @seokho-son @a-mccarthy @anubha-v-ardhan

**Comment by verma-kunal** [comment]
Hey @divya-mohan0209 , I apologise for being in-active & not being able to adequately contribute to the review work, due to some other commitments at the moment!

I believe it would be best for now to off-board me as part of the reviewing team, due to my time commitments at the moment & also to not be disrespectful of other members being involved in the process.

Will surely reach out in the future, when I'll be able to dedicate proper time for the work!

Hope you understand & thanks for pointing this out :)

**Comment by seokho-son** [comment]
This issue has been resolved by  #41810 and https://github.com/kubernetes/org/pull/4314

/close
