### ISSUE TITLE
[ja] learning environment redirect

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41724]
**This is a Bug Report**

**Problem:**
The Japanese documentation does not apply a redirect from Getting Started > Learning Environment to Tasks > Tools. Without this redirection, there will be inconsistencies in information access compared to the English documentation

**Proposed Solution:**
Add a redirect from https://kubernetes.io/ja/docs/setup/learning-environment/ to  https://kubernetes.io/ja/docs/tasks/tools/

**Page to Update:**
https://kubernetes.io/ja/docs/setup/learning-environment/

**Additional Information:**

/language ja
/assign

**Comment by s-kawamura-w664** [comment]
This Issue seems to point out the differences between EN and JP.
* On the EN page, When we click on "Getting started" - "Learning environment" in the Left-sidebar, it will jump to docs/tasks/tools/.
* On the JP page, When we click on the same item in the Left-sidebar, it does not jump to docs/tasks/tools/.

**Comment by atoato88** [comment]
@s-kawamura-w664 
It's a helpful clarification!

**Comment by atoato88** [comment]
I think this issues is related to bug, not feature.
So could you update the description?

**Comment by tuibeovince** [comment]
@atoato88 I have updated the description to reflect the issue as a bug.
