### ISSUE TITLE
Externalizing config using MicroProfile, ConfigMaps and Secrets

### ISSUE THREAD

**Issue by vijay-jangir** [kubernetes/website#41875]
This shoudl be fixed as interactive tutorial is not available, maybe a walkthrough will help?

**Comment by AmarNathChary** [comment]
**Page**: https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/
/language en

**Comment by AmarNathChary** [comment]
Can you please explain something more on this issue

**Comment by dancer1325** [comment]
Hi @AmarNathChary , 

* Maybe the whole page https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/  /language en could be refactored, since barely adjustments in the last 3 years 

https://github.com/kubernetes/website/commits/main/content/en/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice.md

* In fact, what "kubernetes.yml" mean in the part of the page

> There are several ways to set environment variables for a Docker container in Kubernetes, including: Dockerfile, kubernetes.yml, Kubernetes ConfigMaps, and Kubernetes Secrets.

**Comment by AmarNathChary** [comment]
@vijay-jangir if you want to work on this issue you can raise PR reviewers who will review it.
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`
Mark the issue as fresh with `/remove-lifecycle rotten`

**Comment by AmarNathChary** [comment]
Closing this issue as it has been inactive for a long time feel free to re-open.
