### ISSUE TITLE
[ko] Translate content\en\docs\reference\access-authn-authz\node.md into Korean

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#42133]
**This is a Feature Request**

**What would you like to be added**

Translate `content\en\docs\reference\access-authn-authz\node.md` into Korean.
- Page: https://kubernetes.io/docs/reference/access-authn-authz/node/
- File: https://github.com/kubernetes/website/blob/dev-1.27-ko.1/content/en/docs/reference/access-authn-authz/node.md

**Why is this needed**
This not been translated into Korean yet.

**Comments**

/assign
/language ko

**Comment by deepak4566** [comment]
Where to add this translated content ?

**Comment by jihoon-seo** [comment]
@deepak4566 Please do not assign yourself to issues that someone else has been already assigned.
And it seems that you are neither native Korean speaker, nor one that fluent in Korean.
Since localization is not just translation, please avoid assign yourself to issues or PRs that are not related with your language.
Instead, you can contribute by localizing existing contents into your language.
/unassign @deepak4566
