### ISSUE TITLE
Horizontal Pod Autoscaling - documentation page error

### ISSUE THREAD

**Issue by taufik-rama** [kubernetes/website#42238]
![image](https://github.com/kubernetes/website/assets/19818873/3516d6c3-17a7-4b00-88d4-ce188534dc06)

[Page](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)

**Comment by Ritikaa96** [comment]
I believe you are talking about the image [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#how-does-a-horizontalpodautoscaler-work)
This image is visible to me. Might be possible it s because of the mermaid parser.
Please read the discussion [here](https://github.com/mermaid-js/mermaid/issues/2963) for further reference.
This issue is not from k8s or website.

**Comment by sftim** [comment]
Duplicate of https://github.com/kubernetes/website/issues/31960

(This _is_ a Kubernetes docs issue)

/triage duplicate

**Comment by taufik-rama** [comment]
Got it, I tried searching for "HPA docs error" but can't find any (opened) issues, I'll redirect this to #31960 then
