### ISSUE TITLE
Assistance Needed: Nginx Ingress controller not handling status code 303

### ISSUE THREAD

**Issue by vivekjava** [kubernetes/website#42284]
Hello , 
     Currently we are trying to integrate our sso login mechanism with nginx ingress controller (auth-url). in case of no cookie our authservice will return a status code 303 with redirect SSO login URL . 
     As i observed nginx ingress controller only handles 200 / 401 . in the current suituation it throws 500 Internal Error in the browser 
     
   Nginx-controller logs says : 
   2023/07/27 18:59:50 [error] x2xxx #x2xxx: *11xxxxx auth request unexpected status: 303 while sending to client, client: xx.xx.1xx.1xx, server: abcd.compcorpintra.net , request: "GET /login HTTP/2.0", host: "abcd.compcorpintra.net"
   
   any idea how we can handle this suitutation , since its a usual case of redirecting the user to the login page

**Comment by dipesh-rawat** [comment]
/retitle Assistance Needed: Nginx Ingress controller not handling status code 303
/kind support

**Comment by dipesh-rawat** [comment]
@vivekjava It appears you're seeking assistance rather than reporting any issues in Kubernetes documentation. We appreciate your question, but the GitHub issue tracker might not be the ideal place to seek Kubernetes advice. Instead, consider checking out the Kubernetes Slack (http://slack.k8s.io/) or the Discuss Kubernetes (https://discuss.kubernetes.io/) forum for the assistance you need.

(Refer: https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md)

**Comment by vivekjava** [comment]
Understood thanks.. Will close this issue
