### ISSUE TITLE
[ja] Localization of StatefulSet concept uses wrong term

### ISSUE THREAD

**Issue by shu-tec** [kubernetes/website#42310]
The sentence "Manages the deployment and scaling of a set of Pods," is translated as "StatefulSetはDeploymentとPodのセットのスケーリングを管理し、".  
However, this "deployment" should be translated as "デプロイ", not "Deployment" because it does not mean as Deployment resource of kubernetes.

**Comment by sftim** [comment]
/area localization
/language ja

/retitle Localization of StatefulSet concept uses wrong term
/kind bug

**Comment by sftim** [comment]
Page to fix: https://k8s.io/ja/docs/concepts/workloads/controllers/statefulset/

**Comment by seokho-son** [comment]
/triage accepted

Hi @hemantmm 
I hope to check you are working on this Issue. :)

**Comment by Okabe-Junya** [comment]
Hi folks!! 

It seems there has been no response for about 2 months. I think it might be better to un-assign so that someone else can work on the issue. WDYT @seokho-son ??

Of course, feel free to re-assign yourself to this issue if you decide to work on it again :)

**Comment by Okabe-Junya** [comment]
Let me unassign @hemantmm so that anyone else could work on this issue :) Feel free to re-assign when you work, thank you

/unassign hemantmm

**Comment by Okabe-Junya** [comment]
I think this issue is a good first contribution to k/website. Let me note some useful information for contributors (in Japanese) and assign the good-first-issue label.

/good-first-issue

---

### 修正する箇所

当該ページは https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/workloads/controllers/statefulset.md ですが、修正が必要な箇所は別のファイルから取り込んでいる部分であるため、以下の2箇所を修正してください。

https://github.com/kubernetes/website/blob/6dd5e893d9e8306c9617cfbbe62c7f51287244d9/content/ja/docs/reference/glossary/statefulset.md?plain=1#L7

https://github.com/kubernetes/website/blob/6dd5e893d9e8306c9617cfbbe62c7f51287244d9/content/ja/docs/reference/glossary/statefulset.md?plain=1#L17

### 翻訳元

翻訳元の "deployment" は、Kubernetesの"Deploymentリソース" を指しているわけではなく、単に "デプロイ" の意味なので、それを反映してください

https://github.com/kubernetes/website/blob/6dd5e893d9e8306c9617cfbbe62c7f51287244d9/content/en/docs/reference/glossary/statefulset.md?plain=1#L7

https://github.com/kubernetes/website/blob/6dd5e893d9e8306c9617cfbbe62c7f51287244d9/content/en/docs/reference/glossary/statefulset.md?plain=1#L16

### その他

翻訳する際は以下のドキュメントを参考にしてください

- https://kubernetes.io/ja/docs/contribute/localization

**Comment by Okabe-Junya** [comment]
/retitle [ja] Localization of StatefulSet concept uses wrong term
