### ISSUE TITLE
An image issue about virtualized deployment in concepts/overview/

### ISSUE THREAD

**Issue by bigfacefatcat** [kubernetes/website#42399]
时光回溯里面的图片“虚拟化部署”里面，操作系统和 hypervisor 两个层次正好画反了

**Comment by dipesh-rawat** [comment]
Hi @bigfacefatcat, we track issues in English. If feasible, kindly describe the [issue](https://github.com/kubernetes/website/issues/42399#issue-1837831734) in English language.

/triage needs-information

**Comment by bogarams** [comment]
@bigfacefatcat ,  I am taking initiative to describe your issue in english. 

@dipesh-rawat  , the issue is described below in english:
@bigfacefatcat  points out that the  'Virtualized Deployment' diagram in the below page https://kubernetes.io/docs/concepts/overview/  has issue. The aligment of  rectangle diagram components labelled as 'Hypervisor' and 'Operating System' is currently wrong and should be reversed.

**Comment by bogarams** [comment]
If this issue is confirmed as a real issue, I would like to work on this by opening PR request.

/assign @bogarams

**Comment by windsonsea** [comment]
/retitle An image issue about virtualized deployment in concepts/overview/

**Comment by bogarams** [comment]
@dipesh-rawat , @windsonsea who can confirm this indeed an issue and need correction? Thank you.

**Comment by sftim** [comment]
The diagram in the page doesn't seem wrong as such; some hypervisors run inside an OS. For example, Linux KVM works like this. Some other hypervisors such as Hyper-V work differently, with the management OS running in ring 0 and ring 3 of a partition created by the Hyper-V system that runs in ring 1.

Both designs are valid ways to achieve virtualization.

**Comment by tengqm** [comment]
This really depends on the hypervisor used.
/close
