### ISSUE TITLE
Improper variable usage in 'Using kubectl to Create a Deployment' example with `$POD_NAME`

### ISSUE THREAD

**Issue by pzi123** [kubernetes/website#42616]
The variable $POD_NAME as assigned contains a series of POD names. It is used as it contains just a single POD name.

**Comment by thisisharrsh** [comment]
_Page related to the issue: _https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/_ 

sig/docs

**Comment by thisisharrsh** [comment]
Hi @pzi123, as mentioned in the command `range.items` is a Go template expression which iterates over the list of pods returned from the `kubectl get pods` command.

**Comment by pzi123** [comment]
That is correct - the $POD_NAME contains the list of POD names.  The following statement in the documentation
`curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/` will not work with the list.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Improper variable usage in 'Using kubectl to Create a Deployment' example with `$POD_NAME`

**Comment by sftim** [comment]
How many Pods are in the default namespace? There should only be one.

My fix: have the learner create a new namespace and use that (eg `tutorial`), rather than `default`. Then we can better predict what is running there.

We can also advise them to check that there is only one Pod in the namespace.

I don't think that the variable is used incorrectly; the problem is that the assumptions that once held (brand new cluster in Katacoda) no longer do.

**Comment by pzi123** [comment]
@sftim two wrong statements: 1. "There should only be one pod per default namespace", 2. "I don't think that the variable is used incorrectly".
In documentation if you want to indicate a value that needs to be replaced you use a token like <this> instead of variable like $this.  Especially if you quoted a script before that was assigning a value to that variable.

**Comment by sftim** [comment]
> There should only be one pod per default namespace

This tutorial was written for a context where there is only one Pod in the default namespace. Because we no longer use Katacoda, I'm recommending a change where we get the learner to make a new namespace.

> I don't think that the variable is used incorrectly

As me, I can assure you that this is (still) my opinion. If we control the environment so that only one Pod exists when the learner looks it up, the list of one Pod will interpolate OK.
