### ISSUE TITLE
Page: Install and Set Up kubectl on Linux, missing content under tab: Red Hat-based distributions 

### ISSUE THREAD

**Issue by ehmad11** [kubernetes/website#42651]
The following tab has missing or duplicate content:

Install using native package management > [Red Hat-based distributions](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#kubectl-install-1)

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
/language en

**Comment by sftim** [comment]
The tabs don't seem to be working right in that page.

Fixes are welcome. I am wary to triage this as Accepted though as I'm worried that the bug description is unclear.

**Comment by dipesh-rawat** [comment]
In addition to the tab content, there seems to be an issue with the overall [page](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/) layout, which appears to be disrupted. This might have been unintentionally caused by the changes introduced in https://github.com/kubernetes/website/pull/42022. It's possible that this occurred because the release documentation deadline was approaching, leading us to merge it based on an older Netlify build preview instead of verifying it with the latest Netlify preview build.

**Comment by dipesh-rawat** [comment]
I've opened https://github.com/kubernetes/website/pull/42655 to address and rectify this [page](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/) layout.
/assign

**Comment by sftim** [comment]
There's a shortcoming around merges and Netlify. The preview from Netlify shows how the branch renders; it doesn't show (merge train style) how the site would look after the merge.
