### ISSUE TITLE
Incorporate yaml example demonstrating how to create a CSR in "Certificates and Certificate Signing Requests" page

### ISSUE THREAD

**Issue by amannjain** [kubernetes/website#42662]
**This is a Feature Request**

**What would you like to be added**
A code section which displays the yaml format to create a new Certificate Signing Request. 

**Why is this needed**
Some people want to create some certificate signing requests manually, therefore they need the steps to be followed to create one. that is why it is needed to have a section which displays how to create a certificate signing request as well as the yaml format of the file.

**Comments**

**Comment by amannjain** [comment]
I would like to help and work on this issue.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Incorporate yaml example demonstrating how to create a CSR in "Certificates and Certificate Signing Requests" page

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/14725

**Comment by sftim** [comment]
Rather than make https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/ longer, I might recommend adding a new task page about requesting a certificate using the CertificateSigningRequest API.

However, if https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#create-a-certificatesigningrequest-object-to-send-to-the-kubernetes-api is already good enough, then we should instead change https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/ to opviously link there.
