### ISSUE TITLE
Width of community page is more than 100%

### ISSUE THREAD

**Issue by priyanshuchaudhary53** [kubernetes/website#42900]
**This is a Bug Report**

**Problem:**
The width of the community page is larger than 100%. 
Some of the sections (#navigation-items, .community-section#values, etc.) of this page have a width of more than 100%

**Proposed Solution:**
Set `max-width: 100%` for these divs and add the `overflow-x: hidden` to html and body tag.

**Page to Update:**
https://kubernetes.io/community/

**Comment by priyanshuchaudhary53** [comment]
Can I contribute to fix this issue?

**Comment by dipesh-rawat** [comment]
Looks similar (possibly duplicate) of issues we already have #42314 #42795 #42854

**Comment by aj11anuj** [comment]
As far as per my understanding, @priyanshuchaudhary53 wants to say like there are several sections in "Community" Page for example- Community values, Code of Conduct, Videos, Discussion etc. out of which some sections formatting are getting out of page {that is there is a line in heading of each section (Have a look at "Community Values" section of [Community Page](https://kubernetes.io/community/)) and "Community Values", "Code of Conduct", "Global Community" sections line in heading are showing this formatting breakout}.

This issue is more clearly visible in mobile view rather than desktop and this issue could be possibly a reason of #42795, #42314, #42854. This issue #42900 should be taken as part of discussion of these 3 earlier issues and not as a separate issue.

/triage duplicate

**Comment by aj11anuj** [comment]
Refer discussion of above-mentioned issues, this is an exact duplicate of them except the solution you proposed. And that should be taken as part of those issues and not as a separate issue.

/close not-planned
