### ISSUE TITLE
Layout Issue: Default GitHub Links, Print Option and Table of Contents misplaced at bottom instead of right side on multiple pages

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#42947]
**This is a Bug Report**

**Problem:**
In the [kustomization] page,  [Edit this page, Create child page, Create an issue, Print entire section] links are displaying in the bottom of the page.

**Proposed Solution:**
It should be displayed in upper right of the page.

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

**Comment by aj11anuj** [comment]
This issue is legit but the link provided in issue is wrong. This issue is present in these below pages:-
[Declarative Config Page](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/)
[Imperative Command Page](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/)
[Imperative Config Page](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-config/)
[Update API object KubeCtl Page](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/)

/area web-development

**Comment by dipesh-rawat** [comment]
/retitle Layout Issue: Default GitHub Links, Print Option and Table of Contents misplaced at bottom instead of right side on multiple pages

**Comment by dipesh-rawat** [comment]
When the side navigation panel is resized to a smaller size or if the page is zoomed out sufficiently, the page layout reverts to its expected appearance (refer screenshots). 

It appears that this issue could also be inadvertently caused due to PR #41695, which aimed to added a splitter for resizing the left navigation panel.

-  Zoomed out

<img width="1461" alt="page-layout-zoom-out" src="https://github.com/kubernetes/website/assets/13051389/2f52651b-b591-486e-8c03-61ab16f11c26">



- Navigation panel resized
<img width="1466" alt="side-bar-small" src="https://github.com/kubernetes/website/assets/13051389/3d8b23de-2055-4b33-bc1c-2d6ae8ebd524">

**Comment by sftim** [comment]
@tamilselvan1102 a screenshot showing the problem would help us track this work. Would you be willing to add one?

**Comment by tamilselvan1102** [comment]
wrong layout
![image](https://github.com/kubernetes/website/assets/20103020/19847942-4e03-47b2-aac2-94e337383332)

**Comment by tamilselvan1102** [comment]
Expected Layout
![image](https://github.com/kubernetes/website/assets/20103020/867c2cdb-1f84-4bc2-ae60-3fb6f37a5a97)

**Comment by tamilselvan1102** [comment]
if you zoom out to 80%. it displaying as expected

**Comment by priyanshuchaudhary53** [comment]
This issue is fixed in the recent commit of PR #42943

**Comment by dipesh-rawat** [comment]
Thanks for the fix @priyanshuchaudhary53

**Comment by dipesh-rawat** [comment]
Looks like the issue reported here is fixed via #42943

/close
