### ISSUE TITLE
Kubernetes icon aligned right a little in mobile view

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/website#42983]
**This is a Bug Report**

**Problem:**
The Kubernetes icon seems to be aligned right but it should be in the centre.

![WhatsApp Image 2023-09-10 at 2 56 50 PM](https://github.com/kubernetes/website/assets/94950988/8a3b3fb6-7d8e-4063-b823-2b98cd257476)

**Proposed Solution:**
Centre the Kubernetes icon in the mobile view

**Page to Update:**
https://kubernetes.io/community/

I would like to work on this issue.

**Comment by aj11anuj** [comment]
It's at proper center, but it's looking a little on right side due to this issue #42795, if #42795 will be fixed it will look fine again. This issue is a subset of #42795. For confirmation you can zoom out your screen and that K8s icon will get aligned to proper center. And if #42983 will be fixed before #42795 than after fixing #42795 this issue will again occur.

/triage duplicate

**Comment by tengqm** [comment]
/close
as a dup.
