### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by hhhhssjdh** [kubernetes/website#43008]
There is a bit of a minor error with the command on this document.on the  Step 1 "Configure the kubelet to be a service manager for etcd." look up this context that cat ,this yaml file is a few indentations missing

**Comment by tamilselvan1102** [comment]
related page: https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

**Comment by tamilselvan1102** [comment]
please specify place where the indentations missing.

**Comment by rishavkankane** [comment]
> /language en

@tamilselvan1102  in the above issue The heading of the issue is pointing to the link which is rendering to the page where  @hhhhssjdh is facing issue. 
So  the language used and referring here in k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ is Chinese its not in english.

@hhhhssjdh  its better to add  ref page in the description of the issue. It will be more helpful for Contributor to contribute.

**Comment by hhhhssjdh** [comment]
> 请指出缺少
![1694503929565](https://github.com/kubernetes/website/assets/99572163/c9fed3df-9438-407d-9aa2-4b443411d778)
缩进的位置。
look this，thinks for your reply

**Comment by rishavkankane** [comment]
> > 请指出缺少
> > ![1694503929565](https://user-images.githubusercontent.com/99572163/267248795-c9fed3df-9438-407d-9aa2-4b443411d778.png)
> > 缩进的位置。
> > look this，thinks for your reply

@hhhhssjdh   my point is that this issue is not related to the doc in English language . The issue that you raised is in Chinese language doc so labelling language en is not a good practice. and asking you to add the link that you provided in the title of the issue inside the description of the issue also. Which will be more helpful.

**Comment by rishavkankane** [comment]
I investigated the issue and find that yes there is indentation  missing in authentication having  anonymous and authorization having mode.
Comparing the yaml file of the link Provided above by @tamilselvan1102  https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster and  https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-cluster
Yes the indentation is missing. I agree with @hhhhssjdh  issue.

**Comment by tamilselvan1102** [comment]
yes, it wrong in  Chinese  version. it has to be update

**Comment by rishavkankane** [comment]
> yes, it wrong in Chinese version. it has to be update

@tamilselvan1102   requesting you to please remove  the wrong labeling here .

**Comment by dipesh-rawat** [comment]
> /remove-language zh

oops wrong!
/language zh
/remove-language en

**Comment by rishavkankane** [comment]
Thank you @dipesh-rawat  . Please give your suggestion about the issue.

**Comment by tengqm** [comment]
The zh version of the YAML is identical to that of the English one.
/close
