### ISSUE TITLE
Standardisation of Opertion in k8s APi in volume snapshots

### ISSUE THREAD

**Issue by rishavkankane** [kubernetes/website#43126]
How does the standardisation of snapshot operations in the kubernetes API benefit users, and how does it eliminate the need for users to bypass the kubernetes API to perform storage system-specific operations manually?

**Comment by thisisharrsh** [comment]
The standardisation of snapshot operations in the kubernetes API benefit users in the various ways: 

- Provides the simplicity and ease of use - We can use a single unified API for all the snapshot operations of different storage systems. 
- Provides the Portability of the API - we can use the kubernetes API across different storage systems.

**Comment by thisisharrsh** [comment]
It eliminate the need for users to bypass the kubernetes API to perform storage system-specific operations manually by providing a unified API to perform the storage task. 
Before it was a very complex and time consuming task as it requires to know about the specific API of the storage system, hence user may have needed to bypass the Kubernetes API to perform storage specific operation in order to manage snapshots of their volumes.

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/concepts/storage/volume-snapshots/_ 

/sig storage
