### ISSUE TITLE
Issue with k8s.io/docs/contribute/

### ISSUE THREAD

**Issue by iairu** [kubernetes/website#43339]
Since when is this an english word? "kustomize"

**Comment by sftim** [comment]
[Kustomize](https://kustomize.io/) is a [proper noun](https://en.wikipedia.org/wiki/Proper_noun) in English.

/kind support

**Comment by aj11anuj** [comment]
Does it matter if it's an English word or not?

"Customize" and "Kustomize" are two different words. Here "Kustomize" is a tool named by their community (Maybe it does K8s related stuff that's why "K" is used as unconventional convention followed by cloud-native based projects/tools to use "K" or "Kube" in their name), even if it's a Chinese word nobody has authority to change name of a tool that is set by their community. So, it doesn't matter whether it's an English word or not.

Btw, the page link that you have provided for this issue is wrong. In Contribute page, nowhere "Kustomize" word is written.

**Comment by tengqm** [comment]
`kustomize` is the name of a tool, just like `kubelet` is the name of a binary.
/close wont-fix
