### ISSUE TITLE
Creation of a Shadow Program for Issue Wrangler 

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43586]
**This is a Feature Request**

**What would you like to be added**
First of all congrats for merge of #42273
This feature request is for creation of a Shadow Program for Issue Wrangler like PR Wrangler. Currently, there maybe no need of it but maybe in future. Refer docs of PR Wrangler Shadow program as a reference for it.

Triage/accepted label is a must before working on this issue.

**Comment by divya-mohan0209** [comment]
Hello @aj11anuj , thank you for your interest in this role and the shadow program. However, I'd request that you do not open issues about roles/programs within the community without seeking community consensus first and understanding if there's a need. 
There is potential for a shadow program, however, the next steps would be to get the issue wrangler role formalized under [this issue](https://github.com/kubernetes/website/issues/41601). I'll be sending out a notification shortly on the email DL regarding nominations.
After this, we need to assess if it makes sense to have this role run for a longer time like the PR Wrangler because dynamics of contribution keep changing all the time. This could take anywhere between 4-6 months or maybe even a year.
Only after that assessment, would I suggest having an issue tracking shadow programs to discuss further. 
I'll be closing this as not planned and reusing it if and when we plan to commence a shadow program. 
Thank you, once again!
