### ISSUE TITLE
Inline code blocks are not rendered correctly in a table on page "Style Guide"

### ISSUE THREAD

**Issue by able8** [kubernetes/website#43638]
https://kubernetes.io/docs/contribute/style/style-guide/#use-code-style-for-filenames-directories-and-paths

It should render inline code block style like this `envars.yaml`. Seem an issue related to the Docsy theme.
<img width="906" alt="Screenshot 2023-10-22 at 20 17 15" src="https://github.com/kubernetes/website/assets/26692080/1afb35bf-e363-4e04-b292-789202005cdb">

**Comment by dipesh-rawat** [comment]
The way inline code blocks are currently displayed within tables is related to a particular CSS rule that is part of the website's assets. Specifically, there is a CSS rule in place with "[background-color: inherit!important; ](https://github.com/kubernetes/website/blob/main/assets/scss/_custom.scss#L875C3-L875C3)" that overrides the background color of the element and inherits the color from its parent element.

**Comment by dipesh-rawat** [comment]
I would be inclined to keep things as they are because changing the CSS rule might have widespread impact. One specific example that comes to mind is the [Feature Gate table](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features). It's important to ensure that any adjustments to the CSS do not unintentionally affect other parts of the website. 

I will let other maintainers/leads share their thoughts on this.

**Comment by kumarankit999** [comment]
I can work on this
/assign

**Comment by sftim** [comment]
/remove-triage accepted
/priority awaiting-more-evidence

To me, there is nothing to fix.
