### ISSUE TITLE
Enhance clarity with detailed steps for reflecting changes on control plane nodes via `kubeadm-config` changes

### ISSUE THREAD

**Issue by anthonyoride** [kubernetes/website#43715]
**This is a Feature Request**

**What would you like to be added**
The process to reflect changes on the control plane node after editing the kubeadm-config map isn't clear and should be stated in clearly defined steps

**Why is this needed**
This is really vital because it's a critical process and mistakes could literally be costly.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/#reflecting-clusterconfiguration-changes-on-control-plane-nodes

/language en

**Comment by dipesh-rawat** [comment]
/retitle Enhance clarity with detailed steps for reflecting changes on control plane nodes via `kubeadm-config` changes
/sig cluster-lifecycle

**Comment by neolit123** [comment]
> Page related to issue: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/#reflecting-clusterconfiguration-changes-on-control-plane-nodes

> The process to reflect changes on the control plane node after editing the kubeadm-config map isn't clear and should be stated in clearly defined steps

what has to be changed in that section to make the steps clearer?

**Comment by anthonyoride** [comment]
@neolit123 the docs explained changes to the ClusterConfiguration under the apiServer, controllerManager, scheduler or etcd keys must be reflected in the associated files in the manifests directory on a control plane node. it doesn't really tell us how you can actually make those changes in the manifests directory which on my side is currently empty i guess.

there's also `kubeadm init phase certs <component-name> --config <config-file>`  and `kubeadm init phase control-plane <component-name> --config <config-file>`. is the generation of certificate mandatory when you make those changes? does reflecting the changes means writing a new manifest (say after making changes to the ClusterConfiguration)? what is the `<config-file>`? is the `<config-file>` a copy of the updated ClusterConfiguration?

I think it may make sense for experience admins but complex for newbies.

**Comment by neolit123** [comment]
> @neolit123 the docs explained changes to the ClusterConfiguration under the apiServer, controllerManager, scheduler or etcd keys must be reflected in the associated files in the manifests directory on a control plane node. it doesn't really tell us how you can actually make those changes in the manifests directory which on my side is currently empty i guess.
> 

if the directory is empty you should **not be** following this guide, because this node is not being managed by kubeadm.
that is the problem....
why is the directory empty, i cannot answer, but "kubeadm init" or "kubeadm join" can create control plane nodes.

to reflect changes, there is nothing to document, IMO - just open a text editor and edit a manifest Pod yaml file.
we assume that k8s users know what a Pod yaml file is.

> there's also `kubeadm init phase certs <component-name> --config <config-file>` and `kubeadm init phase control-plane <component-name> --config <config-file>`.

yes, there are such commands, but they should not be run prior to editing /etc/kubernetes/manifests files.
the page does not talk about them.

> is the generation of certificate mandatory when you make those changes?

no, updating /etc/kubernetes/manifests files does not require updating certificates or running manifest regeneration commands.

does reflecting the changes means writing a new manifest (say after making changes to the ClusterConfiguration)? what is the `<config-file>`? is the `<config-file>` a copy of the updated ClusterConfiguration?
> 
> I think it may make sense for experience admins but complex for newbies.
> 

what is a newbie in k8s terms, exactly?
we assume users can follow the denoted steps which apply to everyone on a similar level - run kubectl and kubeadm commands, edit local files, restart containers.

> I feel it should have been explained better as one can simply mess up the cluster configuration if not done correctly.

still not clear to me what should be explained better.
this seems more like a request for support, and less like a docs change request.

/kind support

**Comment by neolit123** [comment]
> no, updating /etc/kubernetes/manifests files does not require updating certificates or running manifest regeneration commands. but if you want new cert SANS, you obviously must regenerate certificates.

is this the part that is not clear to you?
if yes, something that can be added is a note:

>> Updating cert SANs requires you to regenerate certificates after you have updated
>> the local manifests files for control plane components.
>> Once certificates are regenerated, you must restart the control plane components again.
>> This can be done by restarting the kubelet service with `systemctl restart kubelet`, or by
>> restarting individual containers.

**Comment by anthonyoride** [comment]
@neolit123 Okay so i get maybe its because the manifests directory is empty. but then again the cluster was bootstrapped using kubeadm so i don't understand why the node won't be managed by kubeadm...but in summary, are you saying all it takes to `Reflecting ClusterConfiguration changes on control plane nodes` is simply just updating the associated files in the manifest directory and that's all?

**Comment by neolit123** [comment]
> I think it may make sense for experience admins but complex for newbies.

@anthonyoride i remember you posted some questions on slack related to load balancers and changing the IP of apiserver. i replied to that changing the same IPs is really not a simple task. in such cases it's much simpler to backup the cluster, create a new cluster, and restore from backup. it will introduce a few minutes of downtime, but it might save you weeks of poking at multiple problems.

> @neolit123 Okay so i get maybe its because the manifests directory is empty. but then again the cluster was bootstrapped using kubeadm so i don't understand why the node won't be managed by kubeadm...

i think this node is no longer usable as is. if it was a control plane node managed by kubeadm, it no longer works as there are no control plane components on it. you must call `kubeadm reset` on it and `kubeadm join` it again...

> but in summary, are you saying all it takes to Reflecting ClusterConfiguration changes on control plane nodes is simply just updating the associated files in the manifest directory and that's all?

yes, but if you have updated cert SANs you must also update certificates on each control plane node.
i do agree this is not a very noob-friendly task, that's why i suggested a new note here:
https://github.com/kubernetes/website/issues/43715#issuecomment-1784730627

**Comment by anthonyoride** [comment]
@neolit123 i have actually recreated the cluster a couple of times with `kubeadm reset` and `kubeadm join` though. `/etc/kubernetes/manifests` directory exists on all nodes but they are all empty

**Comment by neolit123** [comment]
actually, reading https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/#reflecting-clusterconfiguration-changes-on-control-plane-nodes again, the steps seem accurate. once the config map is updated the user can pass a local config file that has the same changes. they can generate new certificates and new manifest files, as non-optional steps.



> @neolit123 i have actually recreated the cluster a couple of times with `kubeadm reset` and `kubeadm join` though. `/etc/kubernetes/manifests` directory exists on all nodes but they are all empty

we have a variety of tests that make sure `/etc/kubernetes/manifests`  works...
if you are passing a --rootfs flag it can modify the k8s root dir.

closing as this is purely a support request without concrete actionable changes.
please, don't log github issues unless you have concrete proposals for something to be changed - "not enough clarity" is not a good proposal for a change.

slack, discuss.k8s,io, reddit, etc are the places to get help.

/close
