### ISSUE TITLE
Limit Search Results to current language

### ISSUE THREAD

**Issue by runofthemill** [kubernetes/website#43817]
**This is a Feature Request**

**What would you like to be added**
Filter `https://kubernetes.io/search/?q=` queries by current site language.

**Why is this needed**
As a visitor searching the English language version of the site, getting results back from search in other languages adds a lot of noise/reduces the quality of the search results. I'd imagine (assume) that visitors to the site who select a different language would similarly find English results noisy.

**Comments**
Perhaps a multi-select language option could be useful for anyone interested in viewing results in multiple languages? Cheers!

**Comment by kumarankit999** [comment]
Yes @runofthemill , it would be a great feature in various languages if we work on it.

**Comment by sftim** [comment]
/area web-development

It sounds tricky to achieve, but nice to have.

**Comment by jpetazzo** [comment]
I found this issue because I was trying to limit search results by language, too!

And here is what I found.

As of December 2023, it looks like K8S docs search is using Bing behind the scenes (I saw that because I saw requests to https://kubernetes-io-search.azurewebsites.net/api/bingsearchproxy in my browser dev tab when searching the docs).

And it looks like we can use [Bing advanced search keywords](https://support.microsoft.com/en-us/topic/advanced-search-keywords-ea595928-5d63-4a0b-9c6b-0b769865e78a), so for instance `rbac language:en` to see only results in English or `proxy language:pt` for results in Portuguese only.

Note that when there are no results, nothing shows up, so from the user's perspective, it looks like there was a bug or issue, though.

I don't know what would be the best option: code something to automatically search in the current language, or add a link to the advanced search syntax, or... I don't know :)

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/44653

**Comment by lindhe** [comment]
@divya-mohan0209 [you mentioned](https://github.com/kubernetes/website/issues/44653#issuecomment-1907549032) that this is "due to the detection of firewall/VPN settings". Can you expand on that? I don't think I'm using any particular firewall or VPN that should be affecting the traffic between kubernetes.io and my computer…

**Comment by divya-mohan0209** [comment]
@lindhe Crosspollinating between issues here but [this comment](https://github.com/kubernetes/website/issues/37451#issuecomment-1289486631) should provide further context. K8s defaults to Bing search in case Google search isn't accessible due to ad blockers, state-level censorship, or corporate network access filter. In one of the subsequent comments on that PR (#37451 ) the exact code snippet that does the fallback has also been provided. However, as aforementioned, we are exploring alternatives alongside CNCF in #44475  and are hopeful of fixing this user experience with that alternative.

**Comment by lindhe** [comment]
Noo, this needs to be fixed! :(

**Comment by lindhe** [comment]
Is there a clearer road ahead on this ticket now that https://github.com/kubernetes/website/issues/44475 is closed?

**Comment by TPXP** [comment]
I think you may be getting results in mandarin because the kubernetes search was calling Bing instead of Google (`is_china=true` cookie). Could you check the value of `is_china` on your side?
Try searching again by forcing Google custom search instead: paste `document.cookie="is_china=false;expires=Sun, 09 Nov 3023 09:39:28 GMT;path=/"` in the JS console and restart the page

**Comment by jpetazzo** [comment]
FWIW: I'm now getting English-only results, instead of the mix of English and Chinese results.
(So from my perspective, the issue is solved; I hope that similarly, folks from China - or using a browser configured to accept Chinese language - get the Chinese results :))

**Comment by lindhe** [comment]
It works for me too now! I assumed it wasn't fixed, since this ticket was still open and last I tried it showed Chinese results. But I probably tested before the new version was fully rolled out.

I guess this Issue can soon be marked as resolved then?

**Comment by runofthemill** [comment]
The updates on this ticket got lost in my notifications, but I can also confirm the search is returning the expected language results (English) for me, so I'll close this up! Cheers
