### ISSUE TITLE
cgroupDriver defaults to systemd instead of cgroupfs in config-api/kubelet-config.v1beta1

### ISSUE THREAD

**Issue by bingoct** [kubernetes/website#43859]
<html>
<body>

​​cgroupDriver​ 是 kubelet 用来操控宿主系统上控制组（CGroup） 的驱动程序（cgroupfs 或 systemd）。默认值："cgroupfs"
--

​
</body>
</html>
1.22 后默认值应该是systemd

**Comment by sftim** [comment]
@bingoct  Please raise the issue in English language so that it can be easy for contributors to understand. This project's working language is English.

If you wish to, you could use a machine translation from your native language to explain the problem. Please do that even if you are reporting that a localized page is wrong.

**Comment by windsonsea** [comment]
In [config-api/kubelet-config.v1beta1/](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/), a description is:

```
cgroupDriver is the driver kubelet uses to manipulate CGroups on the host (cgroupfs or systemd). Default: "cgroupfs"
```

This issue author pointed out:

- The default shall be "systemd".

/retitle cgroupDriver defaults to systemd instead of cgroupfs in config-api/kubelet-config.v1beta1
