### ISSUE TITLE
Highlight the significance of `apiserver-advertise-address` in kubeadm join for HA cluster setup

### ISSUE THREAD

**Issue by manh-vv** [kubernetes/website#43862]
I have a catastrophic problem with my production control-plane just because I naive believe in the instruction of the output of `kubeadm init`.

```log
kubeadm join <control-plane-ip>:6443 --token ro___9.6h___x \
	--discovery-token-ca-cert-hash sha256:___7 \
	--control-plane --certificate-key ___bb8c
```
My control-plane was gone and I couldn't recover from the failure because `apiserver` could not restart.
After some tests, I found that `apiserver-advertise-address` need to be added so that it tell the `kubeadm` to use the **correct internal IP that allow both new control plane and the current plane to talk to each other**. Specifically, those IPs should allow **etcd** to communicate throw both servers. Without `apiserver-advertise-address` the default IP interface was used, but the firewall that I set on the default IP did not allow **etcd** to connect through.

```log
kubeadm join <control-plane-ip>:6443 --token ro___9.6h___x --apiserver-advertise-address=<valid-ip> \
	--discovery-token-ca-cert-hash sha256:___7 \
	--control-plane --certificate-key ___bb8c
```

At this point, I would like to make a change to the document in a way that it emphasize the importance of `apiserver-advertise-address` in the `kubeadm join` command.

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
/sig cluster-lifecycle

**Comment by dipesh-rawat** [comment]
/retitle Highlight the significance of `apiserver-advertise-address` in kubeadm join for HA cluster setup

**Comment by neolit123** [comment]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

> (Optional) Unless otherwise specified, kubeadm uses the network interface associated with the default gateway 

all k8s components work like that. not only kubeadm. if you want custom IP from a different interface you need to pass it to the advertise address flag, but also as --node-ip to the kubelet.

overall this setup with private IPs is not recommended and is difficult to manage. instead you should make the setup so that the public IP is the default route.

PRs for the above "create cluster" page with a note fix are welcome. the note can talk about "init" and "join".

/help
/sig network

**Comment by neolit123** [comment]
actually, let me try to send the note.

/remove-help
