### ISSUE TITLE
Static cpu manage policy

### ISSUE THREAD

**Issue by axi-lyp** [kubernetes/website#44014]
Is dynamic resizing cpu supported when using static CPU management policies? If yes, is the additional CPU exclusive to the current container?
dynamic resizing cpu :Resize CPU and Memory Resources assigned to Containers-FEATURE STATE: Kubernetes v1.27 [alpha]

**Comment by tamilselvan1102** [comment]
Please describe the issue in English

**Comment by axi-lyp** [comment]
Is dynamic resizing cpu supported when using static CPU management policies?  If yes, is the additional CPU exclusive to the current container?
dynamic resizing cpu :Resize CPU and Memory Resources assigned to Containers-FEATURE STATE: Kubernetes v1.27 [alpha]

**Comment by axi-lyp** [comment]
> Is dynamic resizing cpu supported when using static CPU management policies? If yes, is the additional CPU exclusive to the current container?
> dynamic resizing cpu :Resize CPU and Memory Resources assigned to Containers-FEATURE STATE: Kubernetes v1.27 [alpha]

**Comment by sftim** [comment]
/remove-language zh

This sounds like a support query.
/kind support

**Comment by aj11anuj** [comment]
@axi-lyp resolving support/query related issues on K8s github repo sometimes take months and months due to large volume of Issue and PR's we get. It is recommended for query and support related issues, reach out to [Kubernetes slack](https://communityinviter.com/apps/kubernetes/community) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum for faster resolution.

/close not-planned
