### ISSUE TITLE
Section headers for Hindi localization aren't being rendered correctly leading to broken links

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#44056]
The link in the page https://kubernetes.io/hi/docs/home/ is not correct. 
THe link for 
`[सीखने का वातावरण] ` and `प्रोडक्शन वातावरण` under `एक कुबेरनेट्स क्लस्टर सेटअप करें` is not correct .

Page to be update:
 It should be updated with the corrct link.

**Comment by niranjandarshann** [comment]
Page related issue  https://kubernetes.io/hi/docs/home/

**Comment by kumarankit999** [comment]
Hey @niranjandarshann, Can you more elaborate this issue, I don't see any vulnerability/issue there!!

**Comment by niranjandarshann** [comment]
> Hey @niranjandarshann, Can you more elaborate this issue, I don't see any vulnerability/issue there!!

Hi @kumarankit999 , The links which were provided should be redirecting to the particular path but it is redirecting to the whole page not particular heading.

**Comment by niranjandarshann** [comment]
In hindi doc home page we have 
एक कुबेरनेट्स क्लस्टर सेटअप करें which is having two link name as सीखने का वातावरण and प्रोडक्शन वातावरण whose link should be 

[सीखने का वातावरण](https://kubernetes.io/hi/docs/setup/#%E0%A4%B8-%E0%A4%96%E0%A4%A8-%E0%A4%95-%E0%A4%B5-%E0%A4%A4-%E0%A4%B5%E0%A4%B0%E0%A4%A3)
and 

[प्रोडक्शन वातावरण](https://kubernetes.io/hi/docs/setup/#%E0%A4%AA-%E0%A4%B0-%E0%A4%A1%E0%A4%95-%E0%A4%B6%E0%A4%A8-%E0%A4%B5-%E0%A4%A4-%E0%A4%B5%E0%A4%B0%E0%A4%A3)

which should redirect to the proper heading.

**Comment by Tooba-Amjad** [comment]
Hye ! I find it interesting . Can you assign this issue to me?

**Comment by professorabhay** [comment]
@Tooba-Amjad it still needs triage and I checked the issue already and found that it's not a valid problem!

**Comment by Tooba-Amjad** [comment]
Alright

**Comment by Gauravpadam** [comment]
@Tooba-Amjad thanks for showing your interest on volunteering! We do have some [active issues](https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Atriage%2Faccepted) where help will be much appreciated

**Comment by sftim** [comment]
/priority awaiting-more-evidence
/retitle [hi] Broken link on Hindi docs home page

**Comment by divya-mohan0209** [comment]
Thank you for the report, @niranjandarshann !

If we need for the links to work correctly and redirect to the relevant sections,

[सीखने का वातावरण]  should redirect to (#स-खन-क-व-त-वरण) 

AND

[प्रोडक्शन वातावरण] redirects to (#प-र-डक-शन-व-त-वरण)

**HOWEVER**

While this yields the expected result, this is **NOT** OPTIMAL from a maintenance & technical writing perspective. This is because the section headers are not being rendered in the links correctly and is due to the difference in the scripts(English alphabet vs Devnagari) being used. 

It is likely that other localizations using an alphabet/script that aren't similar to English will be facing the same issues. 

For anyone wishing to take on this issue, a simple change in the link will **not be the fix**. Instead, the expectation is outlined below:

- Check with other localizations with an alphabet that's not similar to English how they're rendering their section headers & if they're facing the same problems. Some live localizations that I can think of are Chinese and Korean. 
- If not, understand what are their workarounds to the problem.
- Bring back the results of the research to this issue and the Slack channel to see how we can implement it.

**Comment by divya-mohan0209** [comment]
/retitle Section headers for Hindi localization aren't being rendered correctly leading to broken links

**Comment by coder12git** [comment]
Wow, good issue to work on, taking this :)

/assign

**Comment by sftim** [comment]
> For anyone wishing to take on this issue, a simple change in the link will **not be the fix**. Instead, the expectation is outlined below:
> 
>     * Check with other localizations with an alphabet that's not similar to English how they're rendering their section headers & if they're facing the same problems. Some live localizations that I can think of are Chinese and Korean.
> 
>     * If not, understand what are their workarounds to the problem.
> 
>     * Bring back the results of the research to this issue and the Slack channel to see how we can implement it.

BTW, the channel in question is #sig-docs-localizations

**Comment by coder12git** [comment]
> * Check with other localizations with an alphabet that's not similar to English how they're rendering their section headers & if they're facing the same problems. Some live localizations that I can think of are Chinese and Korean.

I checked other localizations which are not in English, here is what i got 
-  Chinese: They have their section headers links in English ( e.g: `https://kubernetes.io/zh-cn/docs/setup/#learning-environment`)
-  Korean: Section headers link in korean and it's working (e.g:  check [here](https://kubernetes.io/ko/docs/setup/#%ed%94%84%eb%a1%9c%eb%8d%95%ec%85%98-%ed%99%98%ea%b2%bd))


> * If not, understand what are their workarounds to the problem.
- Chinese: They are dealing with this problem by having their section header links in English ( check [here](https://github.com/kubernetes/website/blob/7c1c1b3c2ee4ffe5595f46f0fdf5b0f239e9f41d/content/zh-cn/docs/setup/_index.md?plain=1#L79C1-L79C1) )
- Korean: They are not facing this problem. (check [here](https://github.com/kubernetes/website/blob/7c1c1b3c2ee4ffe5595f46f0fdf5b0f239e9f41d/content/ko/docs/setup/_index.md?plain=1#L44) )

> Possible Solution

To deal in hindi, my approach will be to use the same approach used in chinese i.e having the section header links in english.
