### ISSUE TITLE
[hi] Localize the training page (https://kubernetes.io/training/) to Hindi.

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#44064]
The button in the homepage of https://kubernetes.io/hi/docs/home/ having प्रशिक्षण whose button is `प्रशिक्षण देखें` is broken its redirect  to the 404 page not found error. 

what you want to update
Page should be updated with the correct link having list of training in kubernetes. 
![Screenshot from 2023-11-23 21-51-17](https://github.com/kubernetes/website/assets/124760321/312d987e-3ac7-480e-a029-55a0e778546f)

**Comment by niranjandarshann** [comment]
oops!! 
/kind bug

**Comment by niranjandarshann** [comment]
Page related issue : https://kubernetes.io/hi/docs/home/

According to me Possible Solution: https://kubernetes.io/training/

WDYT?

**Comment by professorabhay** [comment]
We don't have a training section under the hi right now.
It should be developed in future probably!

**Comment by dipesh-rawat** [comment]
> According to me Possible Solution: https://kubernetes.io/training/

I think that rather than linking to a different language page _(English in this case),_ we should look to localize [Training page](https://kubernetes.io/training/) in Hindi.

**Comment by niranjandarshann** [comment]
> We don't have a training section under the hi right now. It should be developed in future probably!

@professorabhay  Agree but i think broken link may disturb reader So we can put the english training instead. until and unless  we localize Training page in hindi WDYT?

**Comment by niranjandarshann** [comment]
> > According to me Possible Solution: https://kubernetes.io/training/
> 
> I think that rather than linking to a different language page _(English in this case),_ we should look to localize [Training page](https://kubernetes.io/training/) in Hindi.

Hi @dipesh-rawat  It sounds good to me. I agree with your idea. We can localize Training Page.

**Comment by niranjandarshann** [comment]
If triage get accepted then i would like to work on the issue.

**Comment by lauradavidd** [comment]
@niranjandarshann I think it would be good to assign the issue and start your work on it. 
Because these are priority backlog issue but is needful
If the localization will be valid then  triage can get  accepted.
/assign @niranjandarshann

**Comment by niranjandarshann** [comment]
> @niranjandarshann I think it would be good to assign the issue and start your work on it. Because these are priority backlog issue but is needful If the localization will be valid then triage can get accepted. /assign @niranjandarshann

@dipesh-rawat  will it be good ? WDYT??

**Comment by divya-mohan0209** [comment]
@niranjandarshann I would recommend leveraging this issue to localize the training page instead of just changing the link. The reason, instead of a simple break-fix, you are fixing it forward and improving the user experience for readers of the Hindi Localization. Additionally, there are less than 10 sentences across 6 sections that need translating on the training page if you navigate to it and will, probably, take a contributor 5 more mins to work on as opposed to just fixing the link.

Section 1:
<img width="1429" alt="Screenshot 2023-12-07 at 10 00 49 AM" src="https://github.com/kubernetes/website/assets/21279125/97b95ce9-0bc0-4a8e-aec7-8e0b62d6c8d1">


Section 2: 

<img width="1357" alt="Screenshot 2023-12-07 at 9 57 26 AM" src="https://github.com/kubernetes/website/assets/21279125/c24cfad7-2156-42b4-a622-bc8b29c1432b">

Section 3: 

<img width="1175" alt="Screenshot 2023-12-07 at 9 58 11 AM" src="https://github.com/kubernetes/website/assets/21279125/f0cf7ab7-3fa3-40fb-9b9f-72bb9b19d0c6">

Section 4:

<img width="1427" alt="Screenshot 2023-12-07 at 9 58 38 AM" src="https://github.com/kubernetes/website/assets/21279125/299042c1-08ad-43e3-9405-97fcc5a9f800">

Section 5:

<img width="1283" alt="Screenshot 2023-12-07 at 9 59 12 AM" src="https://github.com/kubernetes/website/assets/21279125/3005f874-36a0-4949-a418-5c19ed0a3778">

Section 6:

<img width="1384" alt="Screenshot 2023-12-07 at 9 59 41 AM" src="https://github.com/kubernetes/website/assets/21279125/3311bd08-b1d4-429f-8d87-4307437206e6">

**Comment by divya-mohan0209** [comment]
/retitle [hi] Localize the [training page](https://kubernetes.io/training/) to Hindi.

**Comment by haripriya9647** [comment]
@niranjandarshann are you still working on this ??

**Comment by niranjandarshann** [comment]
@haripriya9647  Yes I am working on this issue.

**Comment by niranjandarshann** [comment]
Raised PR #44629

**Comment by Sourav131313** [comment]
[hi] Localize the training page (https://kubernetes.io/training/) to Hindi.
I've solved this issue 
please review.

**Comment by niranjandarshann** [comment]
> [hi] Localize the training page (https://kubernetes.io/training/) to Hindi. I've solved this issue

@Sourav131313  The PR https://github.com/kubernetes/website/pull/44699 raised by you is redirecting every buttons to the Wrong button Path.

**Comment by niranjandarshann** [comment]
@Sourav131313   please   follow the need mentioned by @divya-mohan0209 in the https://github.com/kubernetes/website/issues/44064#issuecomment-1844334350

**Comment by niranjandarshann** [comment]
Thank You everyone for such a informative discussion.
The issue is resolved and it get merged in main so closing this issue.
