### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by Engelch** [kubernetes/website#44430]
I don't immediately understand what the encryption shall serve for:

1. protect against users of the K8s API service?
2. protect against access of secrets from other Pods?

What happens is a Pod is to be restarted? Can the pod read the secrets as required?

I suggest showing some scenarios or a risk matrix. Then, shortly, show why secrets at rest are a mitigation for it.

**Comment by reylejano** [comment]
This issue is part support and part feature request 

Encrypting secrets in etcd at-rest is a part of the security good practice guide: https://kubernetes.io/docs/concepts/security/security-checklist/ so I don't think we need a risk matrix as it's already stated to encrypt secrets at-rest for good security practice -- if you feel otherwise, feel free to reopen this issue with `/reopen` in a comment

Pods will still be able to read secrets as required.

/kind support
/close
