### ISSUE TITLE
Kubernetes cronjob documentation out of date?

### ISSUE THREAD

**Issue by roychen7** [kubernetes/website#44525]
I noticed its written in the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#job-creation) that:

"For every CronJob, the CronJob [Controller](https://kubernetes.io/docs/concepts/architecture/controller/) checks how many schedules it missed in the duration from its last scheduled time until now. If there are more than 100 missed schedules, then it does not start the job and logs the error."
```
Cannot determine if job needs to be started. Too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew.
```
"It is important to note that if the startingDeadlineSeconds field is set (not nil), the controller counts how many missed jobs occurred from the value of startingDeadlineSeconds until now rather than from the last scheduled time until now. For example, if startingDeadlineSeconds is 200, the controller counts how many missed jobs occurred in the last 200 seconds."

I understand this was expected behaviour before, eg. in [release-1.19](https://github.com/kubernetes/kubernetes/blob/release-1.19/pkg/controller/cronjob/utils.go#L142-L145)

However from [referencing the source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/utils.go#L219-L222) for the most recent master branch, it seems that only a warning is logged when this is the case, and the job should start normally even in the case where there are more than 100 missed schedules. Is this documentation not up to date? Or am I interpreting the source code wrong?

**Comment by 2rs2ts** [comment]
(Not a sig member, so take what I say with a grain of salt, but this was a huge problem at my company so we were pretty keenly watching for fixes to it.)

I do distinctly recall that the new v2 controller was supposed to fix a bunch of problems related to how the "too many missed starts" logic worked, because it caused a variety of headaches for people, for example: https://github.com/kubernetes/kubernetes/issues/42649

Our company stopped experiencing this kind of issue, IIRC, once we switched to the new controller. Although, it should be said that at the time, the new controller [still had the problematic logic](https://github.com/kubernetes/kubernetes/pull/81557#issuecomment-1066804148), so I am not sure when things _officially_ changed.

Thanks for pointing this out anyway. I do agree with your assessment of the source code, and, simply as another random user, agree that the docs should be updated.

**Comment by mengjiao-liu** [comment]
> However from [referencing the source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/utils.go#L219-L222) for the most recent master branch, it seems that only a warning is logged when this is the case, and the job should start normally even in the case where there are more than 100 missed schedules. Is this documentation not up to date? Or am I interpreting the source code wrong?

My understanding is that the job missed before (> 100) will not start, but the next scheduling will schedule will continue.
/cc @soltysh
