### ISSUE TITLE
Unable to see Netlify Build logs for pull requests

### ISSUE THREAD

**Issue by steve-hardman** [kubernetes/website#44611]
**This is a Bug Report**

**Problem:**

I can't see logs from this neltfiy hugo build at link https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6594a8398c43840008a4b062 It just says **"You do not have permissions to view logs for this resource".** 
For any PR i can't see the logs!!!

It might be some new setting for PR that I don't know but i think for old PRs I saw the logs and it was useful for seeing failures. Maybe something is changed now to restrcit access.

**Proposed Solution:**

The build logs should be made visible to see the errors or log message when change in pull request is build.

**Comment by divya-mohan0209** [comment]
@steve-hardman - Have you logged in to Netlify with your GitHub a/c to see the logs? Could you please paste a screencap of what you see when trying to view it after logging in with the a/c?

**Comment by sftim** [comment]
You need to be a Netlify user in our organization to see the build logs. As far as I know, we don't have an easy way to change that.

We could look at building a complicated way, but:
- you can build any branch locally (and documenting how to do that is way easier)
- we don't really have a good use case for it IMO, especially given the effort and extra costs it would involve

**Comment by sftim** [comment]
Tangentially:
/sig testing

**Comment by sftim** [comment]
(I wonder if Netlify changed a setting about default visibility)

**Comment by dipesh-rawat** [comment]
I've observed a similar behavior over the past few weeks. However, as of today _(at the time of writing this comment)_, it seems like the issue has been resolved, and the Deploy Preview logs are once again visible. This could have been due to an intermittent Netlify glitch or perhaps someone has restored the deploy log visibility to public logs in the [build settings](https://docs.netlify.com/configure-builds/overview/), as it was before. 

@steve-hardman, could you kindly confirm whether the issue still persists for you? It looks like things are back to normal.

**Comment by steve-hardman** [comment]
Clsoing this issue as resolved. Thanks for help with this.
