### ISSUE TITLE
Documentation search results in wrong language

### ISSUE THREAD

**Issue by murleo** [kubernetes/website#44653]
**Bug**

Why documentation search results are all in Chinese when the selected language is English?

https://kubernetes.io/search/?q=job&page=1
![image](https://github.com/kubernetes/website/assets/12598936/2ef03fb5-a644-4654-9e0b-41b5c642371b)

**Comment by Gauravpadam** [comment]
/remove-kind support
/kind bug

This is a bug @murleo, you can change the issue description to say so

**Comment by utkarsh-singh1** [comment]
I think it needs better sorting, it also shows result in Korean and Indonesian languages also.

- https://kubernetes.io/search/?q=node&page=10
- https://kubernetes.io/search/?q=node&page=9

**Comment by vidbaz** [comment]
This is definitely anoying...

**Comment by lindhe** [comment]
I agree! It should be scoped to the language selected in the top right corner by default! It's less than helpful to have half of the search results turn up hits from the Chinese pages when searching in English…

**Comment by divya-mohan0209** [comment]
The result is owing to the website switching over to Bing search due to the detection of firewall/VPN settings @murleo & isn't a bug.

As part of a bigger problem, we are exploring options with the CNCF under [another issue](https://github.com/kubernetes/website/issues/44475). Also, this issue has already been reported [here](https://github.com/kubernetes/website/issues/43817) in great detail previously.

**Comment by lindhe** [comment]
Thanks for clarifying, @divya-mohan0209 ! I agree that this is indeed a duplicate of #43817 so we should probably close this issue then?

In any case, I don't see what you mean with this "isn't a bug". Surely it's not the intended behavior, so then it's a bug?

**Comment by divya-mohan0209** [comment]
My bad, I can see why the statement was unclear. What I intended to convey was that the switching to Bing wasn't a bug, but a feature for folks with no access to Google due to ad blockers, network access rules, and state level censorship. The unfortunate outcome that everyone's facing is **definitely** a bug. 
Yep, I've marked this one as a duplicate and will be closing this issue. We will be tracking progress on the other one.
/close
