### ISSUE TITLE
Incorrect information on 'imagePullPolicy' update restrictions in 'Pod' reference page

### ISSUE THREAD

**Issue by BrucePeng92** [kubernetes/website#44706]
I found that there are parts in the document that do not match the description here：https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#image
**imagePullPolicy** can be updated, but the document says it cannot be updated.

**Comment by BrucePeng92** [comment]
Chinese documents have the same issue.

**Comment by dipesh-rawat** [comment]
_Page related to issue (**Auto-generated page**):_ https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1

**Comment by dipesh-rawat** [comment]
/retitle Incorrect information on 'imagePullPolicy' update restrictions in 'Pod' reference page

**Comment by sftim** [comment]
See https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#auto-generated-edit-notice

We might need to fix the Kubernetes' projects OpenAPI details for Pod, and then update the website.

**Comment by adityasamant25** [comment]
@sftim @dipesh-rawat,
Please share your inputs if this bug is to be moved to triage accepted.

Once triage is accepted, I would like to take a stab at the fix by issuing a PR to upstream Kubernetes.

**Comment by tamilselvan1102** [comment]
@adityasamant25 
This page content is auto generated and you can't directly fix it from this page.

**Comment by adityasamant25** [comment]
> @adityasamant25 This page content is auto generated and you can't directly fix it from this page.

Yes, I am aware of that.
To fix it, we need to change the code in the [upstream kubernetes](https://github.com/kubernetes/kubernetes) project. If the triage is accepted, I would like to go ahead and do that.

**Comment by sftim** [comment]
@adityasamant25 this project, Kubernetes, is open source.

You're welcome to open a PR against [k/k](https://github.com/kubernetes/kubernetes/), without needing to wait for permission from anyone. The invititation to contribute is implicit.

**Comment by adityasamant25** [comment]
@BrucePeng92 I am checking this issue.
After performing a small test, I feel this issue is not valid.

Steps to test:
1. Create a Pod and wait for it to be running
`kubectl run nginx-pull-image --image=nginx`

2. Edit the Pod and try to update the imagePullPolicy from Always to IfNotPresent
`kubectl edit pod nginx-pull-image`
Change to
`imagePullPolicy: IfNotPresent`
Save the change

It results in the following error:
`# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)`

So the documentation stating that the field value `Cannot be updated` seems correct.

To change the imagePullPolicy, the Pod will have to be deleted and recreated.

As things stand, I do not think any fix is needed here.

/unassign

**Comment by T-Lakshmi** [comment]
I also tried to reproduce the issue and found results are matching with current docs.

![podspec-error](https://github.com/kubernetes/website/assets/56723673/9c983492-7c54-454c-91c8-c225fcc1cb0d)
