### ISSUE TITLE
kube-apiserver: Document how to restart

### ISSUE THREAD

**Issue by StCyr** [kubernetes/website#44791]
It would be good if this (auto-generated) page, https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver, could explain how to restart kube-apiserver.

Google doesn't directly gives a link to some official doc. And answers on SO say to move the file `/etc/kubernetes/manifests/kube-api-server.yaml`, which seems a bit hacky.

**Comment by sftim** [comment]
Right now we don't have a way to customise the autogenerated pages. However, if someone wants to add a mechanism for doing that, I can help explain how.

As an interim thing, we could document how to restart a static pod using `crictl` (I haven't checked if we already do).

**Comment by sftim** [comment]
(want to arrange a conversation about making the web development improvement? At least for the next couple of months: say Hi in #sig-docs on Kubernetes' Slack workspace, mention me @sftim and this issue, and that you're looking to get some coaching on adding the feature).

_If you're reading this after the end of 2024, and this issue is still open, the situation may have changed - please take that into account_
