### ISSUE TITLE
[zh-cn] Chinese page displays abnormally `content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`

### ISSUE THREAD

**Issue by guoiaoang** [kubernetes/website#44848]
Problem description: The Chinese version of the kubernetes installation guide page displays abnormally.
Page link : [安装 kubeadm](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)
environment：Windows 11 Chrome 120.0.6099.225 no extensions are enabled.

Problem details:
Even in the latest non-extension Chrome browser, the table switching under the [安装 kubeadm、kubelet 和 kubectl](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) chapter is abnormal, affecting the following articles, the navigation on the right side of the page, and the footer at the bottom of the article, causing the subsequent chapter levels to be confusing and affecting normal operation. read.

There is no switching content following tags, the layout of subsequent chapters is confusing, and there is no chapter navigation on the right:
![image](https://github.com/kubernetes/website/assets/9270265/9b0e8ff0-d952-49b9-ab57-5c8f9f88645f)

Footer exception:
![image](https://github.com/kubernetes/website/assets/9270265/a1667b61-8ab9-41b8-b20f-cbfc31a9e747)

**Comment by tamilselvan1102** [comment]
please describe the issue in English

**Comment by guoiaoang** [comment]
The page displays abnormally under Windows system.

Due to the abnormal format of the table, the layout of subsequent chapters is disordered, which affects reading. And it affects the display at the bottom of the page, so that the chapter navigation is not displayed on the right side.

**Comment by azn-abel** [comment]
This abnormal table format issue is occuring due to the improper indentation of a `{{ < note > }}` element in number 2 in [this section](https://github.com/azn-abel/kubernetes-website/blob/main/content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md#%E5%AE%89%E8%A3%85-kubeadmkubelet-%E5%92%8C-kubectl---installing-kubeadm-kubelet-and-kubectl) of the markdown.

I would like to work on this
/assign

**Comment by azn-abel** [comment]
Issues have been fixed in #44853, which can be previewed [here](https://deploy-preview-44853--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/).

It may also be worth noting that when testing locally on Windows using the following command, clicking on any tabs doesn't change the content in them.
```
npm ci
hugo.exe server --buildFuture --environment development
```

**Comment by azn-abel** [comment]
@guoiaoang any other problems here? If not we can close this issue.

**Comment by guoiaoang** [comment]
There are no more questions, you can close this issue.
