### ISSUE TITLE
Update Garbage Collection Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4510]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Take a look at these two topics:
* [Configuring kubelet Garbage Collection](https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/)
* [Garbage Collection]( https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/)

Are they redundant?
Do they belong under Concepts, or could some of this material be a Task?

**Comment by tengqm** [comment]
My feeling is that the two pages should be remixed. We will still need a concept page because most of the garbage collection behavior are not controllable by a user but they need some high-level knowledge about the concept and how GC operations can be indirectly affected. We will need a task page dedicated to operators, for deeper involvement into the GC behavior tuning.

/remove-lifecycle rotten
/lifecycle frozen

**Comment by sftim** [comment]
In https://github.com/kubernetes/website/pull/15374#discussion_r303918833, @jaypipes suggests a new page “Understanding object relationships”.

I like that idea so I'm mentioning it here.

**Comment by jaypipes** [comment]
@sftim are you interested in spearheading that effort in a new PR? or are you looking for an assist there?

**Comment by sftim** [comment]
Just wanting to track work that I think is worth doing. I don't particularly plan to pick this up myself.

**Comment by sftim** [comment]
This largely duplicates #4322

/triage duplicate
/remove-triage accepted
