### ISSUE TITLE
Documentation layout issue on Ingress page

### ISSUE THREAD

**Issue by JessieTeng89** [kubernetes/website#45191]
**This is a Bug Report**

**Problem:**
Documentation layout issue in [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope) page under IngressClass scope Namespaced section, see following screenshot:
<img width="912" alt="image" src="https://github.com/kubernetes/website/assets/101035990/3ea2d703-2742-4d09-ab33-e4a2f94f61de">

**Proposed Solution:**
I would like to create a PR to fix it, the solution is to remove `pre` and `code` outside of `feature-state` template

**Page to Update:**
Documentation layout issue in [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope

**Comment by JessieTeng89** [comment]
I would like to create a PR to fix it, kindly assign it to me if possible, Thanks

**Comment by sftim** [comment]
@JessieTeng89 This is an open source project. Anyone can work on a fix for any issue, and you don't need money or permission to start working on a fix.

See https://kubernetes.io/docs/contribute/docs/ for some more guidance.

**Comment by dipesh-rawat** [comment]
Thanks for reporting this issue. Just wanted to mention that in the [source code](https://github.com/kubernetes/website/blob/a74574fa8b962eea83a9767a9f9ebda98aa9b7bc/content/en/docs/concepts/services-networking/ingress.md?plain=1#L293), the lines of code block isn't enclosed within `pre` or `code` tags; rather, it's rendered via shortcode. I suspect that due to the recent update to the `feature-state` shortcode, there might be some spacing (whitespaces) causing compatibility issues with the tab layout _(just like with note shortcode inside tab)_. 

/area web-development

**Comment by dipesh-rawat** [comment]
While it might seem a bit complex for first-time contributors, anyone is welcome to tackle this if they'd like. Let me also see if I can assist in resolving this.
