### ISSUE TITLE
Trrrrr

### ISSUE THREAD

**Issue by Raen123** [kubernetes/website#45967]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by thisisharrsh** [comment]
Hi @Raen123 , Could you please explain the issue that you are facing in the [description](https://github.com/kubernetes/website/issues/45967#issue-2256580524) box?
/triage needs-information

**Comment by sftim** [comment]
Maybe https://github.com/kubernetes/website/pull/45866#issuecomment-2069742169 will help?

**Comment by niranjandarshann** [comment]
As the issue raised by @Raen123  is not having proper title and description in it. 
@Raen123  Please raise the issue with proper description that you face in documentation of kubernetes. Provide all the description so that it can be easy to address your issue.
For now closing  this issue. You can raise separate issue if you face any difficulty in understanding and working in kubernetes doc. over here. 
/close
