### ISSUE TITLE
"kubectl attach" command hangs without providing interactive shell following "Share Process Namespace between Containers in a Pod" task

### ISSUE THREAD

**Issue by novellat** [kubernetes/website#46478]
attaching doesn't work -
when i run `kubectl attach -it nginx -c shell`
I get

`If you don't see a command prompt, try pressing enter.`

 and pressing enter doens't help

**Comment by dipesh-rawat** [comment]
_Page reported in issue (based on issue title):_ https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/
/language en

**Comment by Aaina26** [comment]
I ran these commands on k8s v1.29 cluster
`kubectl attach -it nginx -c shell` command does give the following output. I think it needs to be changed.
![image](https://github.com/kubernetes/website/assets/54260570/3fbd2b6e-07aa-44a2-a166-df9bdcf6d03c)

The suggested command `kubectl exec -it nginx -c shell -- /bin/sh` works fine
![Screenshot from 2024-05-28 15-31-06](https://github.com/kubernetes/website/assets/54260570/292cdbbe-ce6c-4a5c-bf14-f3a4a0190615)

**Comment by Aaina26** [comment]
I see that this issue is yet to be resolved..If replacing the command in documentation is the right solution then I will raise a PR for the same.

**Comment by Aaina26** [comment]
I tried kubectl attach command with various options. It seems like there is some issue with the command itself at the moment. It gets stuck as shared in screenshots above. Since, kubectl exec command is working fine, I think it can be used without affecting the task in [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/). So I think `kubectl attach` can be replaced with `kubectl exec` for now.
@dipesh-rawat what are your views on this? I can raise a PR for the same.

**Comment by dipesh-rawat** [comment]
Fixed as part of PR [48267](https://github.com/kubernetes/website/pull/48267/files)
/close
