### ISSUE TITLE
Style guide violates its own rules

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#46665]
**Problem:**

The style guide asks to use direct language https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language

However, the same page has at least 4 uses of "please". There is probably a lot of similar cases throughout the documentation.

**Proposed Solution:**

Remove use of "please"

**Page to Update:**

https://kubernetes.io/docs/contribute/style/style-guide/

**Comment by aryasoni98** [comment]
@sftim @alculquicondor This issue is still open. IF yes can I work on it .

**Comment by sftim** [comment]
- this issue is **open**
  look for this mark at the top of the issue: ![Open](https://github.com/kubernetes/website/assets/22591623/cfcd3d1d-9c03-4e81-96e0-ba2d44793a4e)
- Kubernetes is open source; anyone can contribute
  For this repository in particular you don't need permission, you just need to follow our community [code of conduct](https://kubernetes.io/community/code-of-conduct/).

**Comment by network-charles** [comment]
I'll work on it since @aryasoni98 hasn't opened a PR yet.
/assign

**Comment by network-charles** [comment]
This issue has been resolved.
/close

**Comment by network-charles** [comment]
Hi @alculquicondor, I’ve resolved the issue and it has been merged. You can close the issue.
