### ISSUE TITLE
Documentation link for 'Weave Scope' broken in 'Installing Addons' page

### ISSUE THREAD

**Issue by kirenpillay** [kubernetes/website#47421]
Weave-scope link is broken.

**Comment by dipesh-rawat** [comment]
/retitle Documentation link for 'Weave Scope' broken in 'Installing Addons' page
/kind bug

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/concepts/cluster-administration/addons/
/language en

**Comment by dipesh-rawat** [comment]
Since Weaveworks company has [shut down ](https://www.linkedin.com/posts/richardsonalexis_hi-everyone-i-am-very-sad-to-announce-activity-7160295096825860096-ZS67) and the latest release of Weave Scope was in 2021 [(here)](https://github.com/weaveworks/scope/releases), it seems reasonable to consider removing the link to Weave Scope from our documentation.

**Comment by utkarsh-singh1** [comment]
Seems like a need of Umbrella issue.

**Comment by utkarsh-singh1** [comment]
> _Page reported in issue:_ https://kubernetes.io/docs/concepts/cluster-administration/addons/ /language en

Currently, this doc has localized in 9 languages including English, so it would be favourable to have an issue to track to remove the weavenet links.

**Comment by sftim** [comment]
I largely see this as a duplicate of https://github.com/kubernetes/website/issues/45482

**Comment by reylejano** [comment]
Closing since this is a duplicate of https://github.com/kubernetes/website/issues/45482
/close
