### ISSUE TITLE
Access control didn't work after setting uid and gid in annotations -- pv.beta.kubernetes.io

### ISSUE THREAD

**Issue by tonysken** [kubernetes/website#47527]
### Environment
  - kubectl version
     - Client Version: v1.30.3
     - Server Version: v1.30.0
  - minikube version: v1.33.1
  - MacOS m3 14.6

### Problem
  - After setting uid and gid in annotations of pv and pod, the output of ```id``` command in container are still 0
  - The other pod without annotations setting still can write in the node

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control is using a deprecated annotation (all annotations that match `*.beta.kubernetes.io` are deprecated, because the whole idea of putting alpha or beta in the key is deprecated). Maybe we can update the tutorial?

/remove-kind support
/sig storage
/language en

**Comment by tonysken** [comment]
That's perfect. Thanks!
