### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore-interactive/

### ISSUE THREAD

**Issue by gaf3** [kubernetes/website#5907]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

In the third tutorial, it first asks to make sure the previous application was running and it wasn't. I tried twice (went back, restarted 2nd, restarted 3rd, no dice). 

**Proposed Solution:**

I don't think whatever sessions mechanism is being retained between interactive tutorials. 

**Page to Update:**
http://kubernetes.io/...

**Comment by heckj** [comment]
thanks for the report @gaf3 !

The content should be loading the relevant commands from earlier tutorial stages as you enter a new session (as a setup step). The browser-based tutorials don't otherwise maintain any specific state. 

/cc @BenHall 

Ben - could you check the module4 deployment - the source would seem to indicate that it should be loading the app at initialization, but when I hit the 3rd scenario the same issue is happening to me. Steps to repro:

 - navigate to https://k8s.io/docs/tutorials/kubernetes-basics/explore-interactive/
 - click "start scenario"
 - click "get pods" (or type it in)

result: nothing there, should have `kubernetes-bootcamp` kicking there

**Comment by BenHall** [comment]
Yes, we do this for other scenarios. Will add feedback to the UI that says Kubernetes is still starting until the Pod is live.

**Comment by heckj** [comment]
@gaf3  since this isn't an issue specific to updating the documentation, I'm going to go ahead and close this here. Thanks for letting us know!
