### ISSUE TITLE
When switching versions, maintain page/topic

### ISSUE THREAD

**Issue by jbeda** [kubernetes/website#5930]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
When switching to a different version of the docs, I get redirected to the root of the doc tree.

**Proposed Solution:**
Would be nice to redirect users to an equivalent page in the previous version of docs.  Easy way to get started would be to just support pages that haven't moved or been refactored.  Could get fancier after that.

**Comment by heckj** [comment]
Also related (found while I was reproducing this), the drop-down mechanism that allows version changing doesn't render correctly on safari (mobile or laptop) so that you can't choose the older versions, and the same happens in Chrome (IOS) - you see part of 1.8, but the rest of the list is cut off. 

See embedded screenshot (from Chrome IOS)
![4cdd31b0-19bc-4f2b-a0b1-910d18c1f476](https://user-images.githubusercontent.com/43388/32016431-cd3444bc-b978-11e7-90ef-1e73d1f50345.jpeg)

**Comment by rowleyaj** [comment]
I've attempted to implement a solution to this in #6712. 

> Easy way to get started would be to just support pages that haven't moved or been refactored.

This part works by default

> Could get fancier after that.

This part requires setting data on the page as to where to send the person.

**Comment by kylehodgetts** [comment]
This is issue is still present on the current version of the website.

**Comment by rowleyaj** [comment]
@steveperry-53 not sure if we should reopen this issue or file a new one as a bug report but this no longer works. from what I can tell during the migration to hugo the header file was removed https://github.com/kubernetes/website/pull/8316/files#diff-822e9cf54ee310f9a7ebd0d16c9ae066
