### ISSUE TITLE
Anchor links included with glossary terms are broken

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/website#5989]
**This is a...** 
- [x] Bug Report

**Problem:**
In [StatefulSet page](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) there is a broken link to Deployment description.
> Like a Deployment, a StatefulSet manages Pods ...

This text with anchor link is included from glossary, so there is no easy fix.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by heckj** [comment]
The relevant file to be tweaked is _data/glossary/statefulset.yml. What I'm not entirely sure of is if the glossary links that are within the content should be linked up appropriately - in which case, there's a bug with the linking rather than the content, which attempts to link to another glossary term

Jessica - need your eyes on this one...

/cc abiogenesis-now

**Comment by abiogenesis-now** [comment]
Thanks for the catch! I'm going to make a hotfix for this now, and come up with a more sustainable solution (e.g. full-length-content links vs glossary links) in the next week or so

**Comment by abiogenesis-now** [comment]
It's going to lead to a bit of inconsistency on the glossary page itself, but at least all the links will be valid.
