### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by roberteikermann** [kubernetes/website#6092]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Last step  in before you begin section says:
 `set /proc/sys/net/bridge/bridge-nf-call-iptables to 1 `
On my fresh Ubuntu 16.04 (not 16.04.3) the folder /proc/sys/net/bridge was not available, but after installing Docker which is one of the next steps the setting was done automatically. SO maybe the step is too early in "before you begin"?

**Proposed Solution:**
Delay the check
`set /proc/sys/net/bridge/bridge-nf-call-iptables to 1 `
after Docker installation

**Page to Update:**
http://kubernetes.io/docs/setup/independent/install-kubeadm/

Kubernetes Version: Documentation v1.8

**Comment by samynathan17** [comment]
1.kubeadm using cluster steup:

I has been tried to setup kubernetes on ubuntu 16.04 with kubeadm

Steps to setup:

* Install a secure Kubernetes cluster on your machines
* Install a pod network on the cluster so that application components (pods) can talk to each other
* Install a sample  application (custom app) on the cluster

Prerequisites:

One or more machines running Ubuntu 16.04 or CentOS 7
1GB or more of RAM per machine (any less will leave little room for your apps)
Full network connectivity between all machines in the cluster (public or private network is fine)


Machine-1 —master
Machine-2 -worker1
Machine-3 -worker2
Etc…

Step -1:

Please proceed with executing the following commands based on your OS as root. You may become the root user by executing sudo -i after SSH-ing to each host.

Install Docker from Ubuntu’s repositories:
Sudo su -
apt-get update
apt-get install -y docker.io

(or) install Docker CE 17.03 from Docker’s repositories for Ubuntu or Debian:


apt-get update && apt-get install -y curl apt-transport-https
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/docker.list
deb https://download.docker.com/linux/$(lsb_release -si | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable
EOF
apt-get update && apt-get install -y docker-ce=$(apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}')



Step-2:
apt-get update && apt-get install -y apt-transport-https

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF

apt-get update


Step-3:

apt-get install -y kubelet kubeadm kubectl kubernetes-cni


The above steps all are same to do all kubernete cluster AWS machines .

Step-4:

The step for do only in master node AWS instance

Use any one command:

The following command token not expire

kubeadm init --token-ttl 0 

(Or)
use this token will be expire 24 houres

kubeadm init


Finally result look like this:

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token fa7ff3.e26b3c59a0558f5b 192.168.1.120:6443 --discovery-token-ca-cert-hash sha256:a0d5b66036199f700a3cbe86af34b9f623df93f28870e57dfbec75d6498df060



Step-5:

as a regular user means: 

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you could run this:

export KUBECONFIG=/etc/kubernetes/admin.conf


Step-6:Installing a pod network:

Choose any pod CNI & Install

flannel
Canal
Calico
Weave Net

Etc...

Here weave Net

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

export kubever=$(kubectl version | base64 | tr -d '\n')

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"


Once a pod network has been installed, you can confirm that it is working by checking that the kube-dns pod is Running in the output of kubectl get pods --all-namespaces. And once the kube-dns pod is up and running, you can continue by joining your nodes


kubectl get pods --all-namespaces

If your network is not working or kube-dns is not in the Running state, check out our troubleshooting docs

Step-7- Joining your nodes:

Open your all worker nodes in different terminals
Become root (e.g. sudo su -)

Copy & paste the master node init output token in your all worker nodes instance terminal

Like e.g.: kubeadm join --token fa7ff3.e26b3c59a0558f5b 192.168.1.120:6443 --discovery-token-ca-cert-hash sha256:a0d5b66036199f700a3cbe86af34b9f623df93f28870e57dfbec75d6498df060

Output:

root@ip-192-168-1-198:~# kubeadm join --token fa7ff3.e26b3c59a0558f5b 192.168.1.120:6443 --discovery-token-ca-cert-hash sha256:a0d5b66036199f700a3cbe86af34b9f623df93f28870e57dfbec75d6498df060

[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] WARNING: hostname "ip-192-168-1-198" could not be reached
[preflight] WARNING: hostname "ip-192-168-1-198" lookup ip-192-168-1-198 on 192.168.0.2:53: no such host
[discovery] Trying to connect to API Server "192.168.1.120:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.1.120:6443"
[discovery] Requesting info from "https://192.168.1.120:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "192.168.1.120:6443"
[discovery] Successfully established connection with API Server "192.168.1.120:6443"
[bootstrap] Detected server version: v1.8.2
[bootstrap] The server supports the Certificates API (certificates.k8s.io/v1beta1)

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.


Finally check your kubernetes cluster nodes in your master machine

kubectl get nodes


Output:
 e.g.:

root@ip-192-168-1-120:~# kubectl get nodes
NAME               STATUS    ROLES     AGE       VERSION
ip-172-16-1-250    Ready     <none>    1m        v1.8.2
ip-172-16-1-254    Ready     <none>    2m        v1.8.2
ip-172-16-1-83     Ready     <none>    2m        v1.8.2
ip-192-168-1-101   Ready     <none>    3m        v1.8.2
ip-192-168-1-120   Ready     master    6m        v1.8.2
ip-192-168-1-198   Ready     <none>    3m        v1.8.2
ip-192-168-1-44    Ready     <none>    3m        v1.8.2



Step-8 : Dashboard Setup

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml


Granting admin privileges to Dashboard's Service Account:

Give master instance in root user in terminal run cmd

$ cat <<EOF | kubectl create -f -
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
EOF

Start server
kubectl proxy --address 0.0.0.0 --accept-hosts '.*'

Dashboard can be loaded at http://localhost:8001/ui

Afterwards you can use Skip option on login page to access Dashboard.


Done!!!!

**Comment by roberteikermann** [comment]
@samynathan17 How does your comment relate to my report?

**Comment by roberteikermann** [comment]
@zacharysarah I think this can be closed as the "before you begin" sections in documentation for versions 1.8 and 1.9 doesn't mention the check  `set /proc/sys/net/bridge/bridge-nf-call-iptables to 1 ` anymore
