### ISSUE TITLE
Conflicting docker version instructions

### ISSUE THREAD

**Issue by cjellick** [kubernetes/website#6530]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Doc contains conflicting instructions regarding docker version.
This line indicates that 17.09 is not one of the officially support docker version:
> On each of your machines, install Docker. Version v1.12 is recommended, but v1.11, v1.13 and 17.03 are known to work as well. Versions 17.06+ might work, but have not yet been tested and verified by the Kubernetes node team.

But then the installation instructions for debian explictly call out version 17.09 for installation.

> or install Docker CE 17.09 from Docker’s repositories for Ubuntu or Debian:

This is confusing. An unsupported docker version shouldn't be used in the installation instructions.

**Proposed Solution:**
Update debian installation instructions to be version agnostic or have instructions for installing an officially supported version.

**Page to Update:**
http://kubernetes.io/...

**Comment by rowleyaj** [comment]
@cjellick, this was changed to 17.09 in #6430 due to the issue reported on #6113. However it looks to have been changed back for the 1.9 release in this PR: https://github.com/kubernetes/website/pull/6645/files#diff-6144d8041be16a6621e6f0e82a35f661R100

Since thats the case I think this can be closed out?
