### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by Hariprasadnaidu** [kubernetes/website#6763]
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubelet : Depends: init-system-helpers (>= 1.18~) but 1.14ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by chuckbutler** [comment]
This happens when you have an incorrect system version specified in your `apt/sources.list.d/kubernetes` list.

You will need to tweak that sources line from the following:

```
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
```

to 

```
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-trusty main
EOF
```

I think this was implied that the operator would be able to discern the difference, but its likely hidden by the fact that xenial is the current LTS release of Ubuntu (soon to be supplanted by bionic). Which will likely change that command even further forward.

**Comment by zacharysarah** [comment]
@Hariprasadnaidu :wave: This issue sounds more like a request for support and less like an issue specifically for docs. You can bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/). You can also search resources like [Stack Overflow](https://stackoverflow.com/) for answers to similar questions.
