### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by zegl** [kubernetes/website#6827]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/getting-started-guides/scratch/ recommends "Set --configure-cbr0=false on kubelet and restart.".

The `--configure-cbr0` was removed from kubelet in 1.9

**Proposed Solution:**

Update the documentation to match reality.

**Page to Update:**

https://kubernetes.io/docs/getting-started-guides/scratch/

**Comment by aburdenthehand** [comment]
Hello,
Thanks for raising this bug.
I can confirm this flag is not available in 1.9 
It appears in a couple of places in docs but I can't find any discussion on the subject, are you able to answer a couple of questions?

1) I'm guessing that in both https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ and https://kubernetes.io/docs/admin/high-availability/default-kubelet it's a simple matter of removing the '--configure-cbr0=true' flag and preserving the rest. Can you please confirm?

2) In the Networking section of https://kubernetes.io/docs/getting-started-guides/scratch/ we have:
----
Recommended, automatic approach:

1. Set --configure-cbr0=true option in kubelet init script and restart kubelet service. Kubelet will configure cbr0 automatically. It will wait to do this until the node controller has set Node.Spec.PodCIDR. Since you have not setup apiserver and node controller yet, the bridge will not be setup immediately.
----
Since '--configure-cbr0=true' is central to the automatic approach, do we scrap the whole para? Or is there a replacement automatic procedure for 1.9?

3) In the same section:
----
Alternate, manual approach:

1. Set --configure-cbr0=false on kubelet and restart.
2. Create a bridge.
...
----
Is this procedure otherwise unaffected if we remove step 1?

Cheers!

**Comment by aburdenthehand** [comment]
@zegl This has since been handled by #7518 (thanks for the cc @islinwb - sorry for the delay, was recovering from car accident).

This issue can be closed.
