### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by brentpearson** [kubernetes/website#6973]
**This is a...** 

- [ ] Bug Report

**Problem:**

Following the procedure given by this guide

```
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
minikube start
```

Results in:
```
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Downloading Minikube ISO
E0115 15:43:32.194415    3441 start.go:150] Error starting host: Error attempting to cache minikube ISO from URL: Error downloading Minikube ISO: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.23.6.iso: x509: certificate signed by unknown authority
```

**Proposed Solution:**
Explain how to get rid of the errors.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/minikube/

**Comment by heckj** [comment]
thanks for the report @brentpearson, but I'm afraid it's not an error with Minikube, but an issue with your local network. Your github profile doesn't include any details about where you work, but from personal experience if you're behind a network that does MitM SSL intercept and re-encryption (typically with Cisco firewall borders), then you will often see this kind of error - and with quite a few different toolings.

If you're working from Linux, you can frequently get the SSL certificates from your IT team and install them locally so that the SSL certificate chains aren't invalidated by the MitM system you're residing behind. For an example of how this can work, check out the notes entitled [For EMC employees](https://github.com/codedellemc/training/blob/0d310c8e97dd1976c384b2a4950e09d6c0020549/docker-workshops/docker-platform-intro/lab1-your-first-container/README.md#for-emc-employees-only) only in that docker tutorial. Hopefully it matches your environment and you can get everything installed locally.

**Comment by zacharysarah** [comment]
@brentpearson :wave: This issue sounds more like a request for support and less like an issue specifically for docs. You can bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/). You can also search resources like [Stack Overflow](https://stackoverflow.com/) for answers to similar questions.
