### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by vishveshv** [kubernetes/website#6976]
**This is a correction request in kubernetes documentation** 

- [ ] Feature Request
- [ X] Bug Report

**Kubernetes documentation on pull-image-private-registry should be updated as docker config has different json response than what is mentioned in document:**

**Kubernetes imagePullSecret doesn't support new docker config i.e. it doesn't support config with {"auths":..} object. **

**Page to Update:**
https://kubernetes.io/editdocs/#docs/tasks/configure-pod-container/pull-image-private-registry.md

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by aburdenthehand** [comment]
Thanks for raising this @vishveshv.

It looks like there was a problem with the registry secret type and datakey in kubectl 1.9.0 (see https://github.com/kubernetes/kubernetes/issues/57427#issuecomment-353765345 for more info and for workaround for 1.9.0), and fixed in 1.9.1. From what I can tell, the 'auths' element in the docs json representation is correct, however there are some other changes related to the 'regsecret' yaml example and the .dockercfg (now .dockerconfigjson) json output. 
 - 
I've addressed these corrections in https://github.com/kubernetes/website/pull/7248
Hopefully that resolves the issue.

**Comment by aburdenthehand** [comment]
#7248 has been merged. 
I believe this issue can be closed.
