### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by YDD9** [kubernetes/website#7355]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

As instructed if kubernetes is 1.9+, `apiServerExtraArgs` needs to be updated as below in config.yaml. But `kubeadm init --config=config.yaml` won't parse config.yaml if the `apiServerExtraArgs` is added in config.yaml:
```
apiServerExtraArgs:
  endpoint-reconciler-type=lease
```

**Proposed Solution:**
endpoint-reconciler-type: lease
should be used.

**Page to Update:**
https://kubernetes.io/...

**Comment by bart0sh** [comment]
As discovered [here](https://github.com/kubernetes/kubeadm/issues/322) the documentation suggested wrong yaml line "endpoint-reconciler-type=lease"

This is already fixed by [this PR](https://github.com/kubernetes/website/pull/7370/files#diff-882a2f00a1e48794c57974b92121984aR445) so we can close this issue.
