### ISSUE TITLE
Develop long-term solution for URLs for generated docs per version

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#7904]
- [X] Feature Request
- [ ] Bug Report

**Problem:**
The URLs for generated docs change with every release because of the way that we manage versioned docs. This means high potential for 404s on release.

**Proposed Solution:**
https://github.com/kubernetes/website/pull/7890 offers a partial short-term solution to cover the gap, which we should document for the release docs meister role. Let's also consider a long-term solution that doesn't require either redirects or lots of changes per the referenced PR.

**Comment by lon-io** [comment]
Can I infer this Feature will address #7903 ?

**Comment by tengqm** [comment]
Considering that all previous versions of the site are archived into a site like `http://v1-8.docs.kubernetes.io`, it doesn't make a lot sense to put generated docs into a path which contains a version number. Once version number is killed across the website map, no further redirection will need to be fixed because either a doc is generated and found, or it is not found (thus not generated). There won't be a situation where generated docs need further care about references to them.
