### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by acatejr** [kubernetes/website#8018]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
On the deploy app page of the kubernetes basics tutorial there are instructions that say: 
"To list your deployments use the get deployments command:"

**Proposed Solution:**
Suggested edit to the quoted text:

"To list your app deployments use the get deployments command:"

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by heckj** [comment]
Thanks for the feedback @acatejr - I'm curious why "app" helps for you there. My impression is that "app" means a lot of different things to different people, and there's a significant set of folks for whom "app" is actually multiple deployments together.

**Comment by acatejr** [comment]
My pleasure and good question.  In the context of the tutorial it makes things clearer for me. 

Here is some context from my perspective.  I am taking an online grad-level data mining program through a large state university.  Most of my classes are taught by TAs who are non-native English speakers.  Frankly, some have such a poor grasp of English that they should not be allowed to teach the class.

I actually have to use Kubernetes for a project, which is why I am trying to learn it and for that particular class the reading material we have to go through is riddled with so many writing errors that I have a hard time taking the class seriously.

Given all of this, I suspect I may have become hyper-sensitive to even small issues where something could be vague.

Also, I am just trying Kubernetes for the first time and if there are other usage contexts that I don’t know about where “app” might muddy the waters then you have a good point.

Averill

**Comment by heckj** [comment]
Got it - I tracked it back to module 2, step 2, where it's clearly referencing "app" in several places, and trying to make a distinction between "app" as the general concept of what you want to run and a "deployment" which is one specific object to get you there. 

The katacoda demo's are great because you can try things out, but the content portion is tightly constrained... I'll see if I can't come up with some alternate wording that tries to call that out more specifically and get it updated on the hosted tutorial
