### ISSUE TITLE
Validate/correct documentation for reserving compute resources and eviction policy

### ISSUE THREAD

**Issue by embano1** [kubernetes/website#8174]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
As a user I want to reserve resources on my node (kubelet) for critical system components, e.g. kubelet, container runtime, system daemons, etc. This can be achieved with `--kube-reserved` and/or `--system-reserved` flags as described here: https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/.

However, the documentation seems to be wrong or misleading when it comes to eviction thresholds. The example given in the documentation (https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#example-scenario) states:

> Here is an example to illustrate Node Allocatable computation:
>
> - Node has 32Gi of memory, 16 CPUs and 100Gi of Storage
> - --kube-reserved is set to cpu=1,memory=2Gi,ephemeral-storage=1Gi
> - --system-reserved is set to cpu=500m,memory=1Gi,ephemeral-storage=1Gi
> - --eviction-hard is set to memory.available<500Mi,nodefs.available<10%
>
> Under this scenario, Allocatable will be 14.5 CPUs, 28.5Gi of memory and 98Gi of local storage. Scheduler ensures that the total memory requests across all pods on this node does not exceed 28.5Gi and storage doesn’t exceed 88Gi. Kubelet evicts pods whenever the overall memory usage across pods exceeds 28.5Gi, or if overall disk usage exceeds 88Gi If all processes on the node consume as much CPU as they can, pods together cannot consume more than 14.5 CPUs.

This makes sense (e.g. start eviction at 28.5GB mem usage). The documentation continues with:

> If kube-reserved and/or system-reserved is ***not enforced*** and system daemons exceed their reservation, kubelet evicts pods whenever the overall node memory usage is higher than 31.5Gi or storage is greater than 90Gi

Either I am not correctly understanding eviction behavior or the `31.5GB` value in the example is wrong. Even without enforcing kube/system-reserved, shouldn't eviction start at `allocatable + eviction-hard`, i.e. 28.5GB? Or does `not enforced` mean kube/system-reserved are not specified? I read `enforced` as setting `--enforce-node-allocatable` to include kube/system-reserved on the kubelet.

The OpenShift documentation seems to support this fact: https://docs.openshift.com/container-platform/3.9/admin_guide/allocating_node_resources.html#eviction-thresholds-1

**What you expected to happen**:
Pod eviction should start at `28.5GB` memory pressure as per the example even without setting `--enforce-node-allocatable` to include kube/system-reserved.

**Proposed Solution:**
Validate and update docs if my understanding is correct.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources

**Comment by dashpole** [comment]
There are two enforcement levels here, one at the node level, and one at the "allocatable" level.
Node Level enforces that `sum(everything on the node) < capacity - eviction threshold`
Allocatable level enforces that `sum(pods) < capacity - reserved - eviction threshold`
What this is saying is that if system daemonse are using more than was reserved for them: `sum(everything on the node) - sum(pods) > reserved`,
then the Node Level threshold will be hit first.

**Comment by embano1** [comment]
Thx David for jumping in. Not sure the documentation is clear enough here (OpenShift documentation also deviates in my opinion from k8s.io docs).

Let's first agree on enforcement levels and eviction.

As I understand it, there's three ways to influence out of resource handling on the node/kubelet, e.g. one of these scenarios:

1) Capacity - eviction threshold (hard)
2) Capacity - kube/system reserved - eviction threshold (hard)
3) Capacity - kube/system reserved - eviction threshold (hard) and also `--enforce-node-allocatable` for kube/system reserved

Let's say we have the following specifications for memory:

- Capacity = 32GB
- eviction threshold hard = 500MB
- kube-reserved = 1GB
- system-reserved = 1GB

I would expect eviction to begin in the scenarios:

- Scenario 1: >31.5GB mem usage
- Scenario 2: >29.5GB mem usage
- Scenario 3: >29.5GB mem usage

According to k8s.io docs (as I understand them) scenario 2 (kube/system reserved not enforced via `--enforce-node-allocatable=kube-system,kube-reserved,pods`) would be 31.5GB instead of 29.5GB.

What do you think?

**Comment by dashpole** [comment]
/cc
Sorry, didn't get an email notification from your comment, and saw this in slack.
It isn't clear in your examples what the memory usage is from, which is important.

In scenario 2, we now have 2 eviction thresholds we are monitoring at the same time.  If the total usage of everything on the node exceeds 31.5, we will evict a pod.  Or, if the total usage of *only pods* exceeds 29.5, we will also evict a pod.

The key phrase in the documentation is:
If kube-reserved and/or system-reserved is not enforced *and system daemons exceed their reservation* kubelet evicts pods whenever the overall node memory usage is higher than 31.5GB ...

Since there are 2 thresholds in our scenario, pod usage could trigger either of them, depending on the usage of kubelet/system relative to kube-reserved and system-reserved.  In your scenario, if kubelet uses 2GB, and system uses 2GB, pods will be evicted when the total pod usage exceeds 31.5 - 2 - 2 = 27.5 GB.  This is lower than allocatable of 29.5GB because kubelet and system processes are exceeding their reservations.  If, on the other hand, kubelet uses 0.5GB, and system uses 0.5GB, pods would run into the allocatable threshold (29.5 GB) before the node threshold because 31.5 - 0.5 - 0.5 = 30.5 > 29.5.
