### ISSUE TITLE
Hugo migration - Home button wrong on top nav

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8236]
This is a bug to track the "Home" navigation button displaying as "Documentation".

- [ ] Feature Request
- [X] Bug Report

**Problem:** This is a bug to track the "Home" navigation button displaying as "Documentation".

**Proposed Solution:** Change "Documentation" to "Home".

**Page to Update:**
https://k8sio-hugo-migration.netlify.com/docs/home/?path=users&persona=app-developer&level=foundational

**Comment by bep** [comment]
I have written about this in another issue, but I will take it here as well. Menus, table of content etc. are now built from the content section tree. Titles and link titles are taken from the page content front matter. 

This avoids hardcoding/double maintenance etc. and it enables translations ("home" isn't "home" in Norwegian).

Hugo has 2 standard titles:

* title: What most themes show as the content page title/header
* linkTitle: What most themes show in listings/menus etc.

You can, of course, add custom titles as params, I would think a little before doing it. Because you kind of need to make it a standard.

So: "Documentation" is the `linkTitle` for the documentation home page. It matches mostly with production, but not in the documentation menu.

**Comment by steveperry-53** [comment]
Moving to P3. Other issues, like getting each of the left navs correct, are more important.
