### ISSUE TITLE
Hugo Migration - Many CSS issues in User Journeys

### ISSUE THREAD

**Issue by jaredbhatti** [kubernetes/website#8244]
Looks like there are some CSS and markdown parsing issues in the user journeys from the Hugo migration. 

https://hugo-migration.docs.kubernetes.io/docs/user-journeys/users/application-developer/intermediate/

1. The CSS for the user journeys page gets applied to the header and changes the font for Docs, Setup, Tasks, etc.
![screen shot 2018-05-01 at 12 15 07 pm](https://user-images.githubusercontent.com/6146946/39469601-57a4f480-4d39-11e8-9fc5-75dececb1a01.png)

2. Bulleted lists don't seem to render correctly - likely a markdown issue. Need to be fixed. 
3. Code formatting showing up in strange places. - I noticed some other markdown issues: For example, the section that starts with " However, StatefulSets can provide stronger guarantees about "recovery" behavior than Deployments. StatefulSets maintain a sticky, stable identity for their Pods. The following table provides some concrete examples of what this might look like:" is all in code text.

**Comment by zacharysarah** [comment]
It looks like there's a font sizing issue on the Home (Documentation) pane relative to other panes in the top nav.

**Comment by bep** [comment]
As to 1) I think that is fixed with the same fix that fixed the "resize issue". I forgot to compare before/after. 

As to the other issues:

There are some subtle whitespace/indentation differences with lists and code indented blocks (4, 8 spaces etc.). Jekyll's markdown parser is more lenient in some areas (table is another: Everything that looks remotely like a table is a table according to Jekyll).

I have looked at your "StatefulSets example". And while that is easy to adjust and fix by hand, it is next to impossible to do by "search and replace".

It's worth noting that

1. I have been careful about not adding/removing any leading spaces in my replacements.
2. Shortcodes also need to be indented in these situations to get them numbered correctly in lists.

**Comment by chenopis** [comment]
This looks fixed now. See https://kubernetes.io/docs/user-journeys/users/application-developer/intermediate/
