### ISSUE TITLE
Hugo website - Updating declarative API link in custom resources

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8268]
This issue is to discuss a link that in the custom resources section to point to a place that provides more information regarding declarative APIs.

```
On their own, custom resources simply let you store and retrieve structured data. It is only when combined with a controller that they become a true declarative API. 
```

The declarative API link goes to "understanding kubernetes" but no obvious reference to the declarativeness.

- [ ] Feature Request
- [X] Bug Report

**Comment by nikhita** [comment]
> The declarative API link goes to "understanding kubernetes" but no obvious reference to the declarativeness.

A paragraph under the ["Understanding Kubernetes Objects" link](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#understanding-kubernetes-objects) says this:

> A Kubernetes object is a “record of intent”–once you create the object, the Kubernetes system will constantly work to ensure that object exists. By creating an object, you’re effectively telling the Kubernetes system what you want your cluster’s workload to look like; this is your cluster’s desired state.

...

> At any given time, the Kubernetes Control Plane actively manages an object’s actual state to match the desired state you supplied.

This is what is meant by the "declarativeness" here i.e. Kuberentes objects are declarative and the Kubernetes API is a declarative API since you _declare_ your desired state. And there is something (in this case, a controller) to bring your current, actual state to the desired state.

But I agree that it might not be immediately obvious since the word "declarative" is not used in the link at all. Unless you are very familiar with the terms, it is not easy to draw the connection to what declarative means.

**Comment by nikhita** [comment]
Sent a PR https://github.com/kubernetes/website/pull/8543
/assign
