### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/cloud-providers/

### ISSUE THREAD

**Issue by edqallen** [kubernetes/website#8304]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Only AWS and OpenStack configurations are documented.  There is no documentation available on how to set up clusters with other providers such as Azure, EC2, or vSphere.

**Proposed Solution:**
Create the documentation, even beta engineer-style documentation from those that tested those cloud providers before activating them.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

**Comment by hogepodge** [comment]
wg-cloud-provider, in collaboration with sig-docs, is formulating a general way to handle this issue. The cloud-provider group is working on setting documentation standards for the providers that will do a few things:

- Create a minimum set of required documentation, including "getting started" an "configuration" guides.
- Establish a known location for documents to reside, so that sig-docs can automatically generate documentation for each wg-cloud-provider approved set of documents
- Make wg-cloud-provider the owner of the documentation standards, with clear guidelines for adding and removing documents.

Currently wg-cloud-provider is investigation transitioning to a SIG, and converting the existing SIG-<providers> into working groups. Individual cloud-provider additions in the meantime should be caveated with those governance changes in mind.

The end goal is to provide a positive and consistent user experience for identifying, installing, and using any particular cloud provider.

Initial work in this PR https://github.com/kubernetes/community/pull/1942

**Comment by karataliu** [comment]
Please consider `known location` to be docs dir under each cloud provider. Otherwise every document would have two copies.

Also posted the question here: https://github.com/kubernetes/features/issues/88#issuecomment-384539732
```
There would be a docs dir in every single provider:
https://github.com/kubernetes/community/blob/master/wg-cloud-provider/cloud-provider-requirements.md

What's the relationship with the kubernetes website? Shall the document be periodly synced?
https://github.com/kubernetes/website/blob/master/docs/concepts/cluster-administration/cloud-providers.md
```

**Comment by jagosan** [comment]
/cc @chenopis 
/cc @jaredbhatti 
FYI

**Comment by timothysc** [comment]
xref https://github.com/kubernetes/kubeadm/issues/526

**Comment by andrewsykim** [comment]
/remove-lifecycle stale

cc @hogepodge @chenopis for updates on some progress we made during KubeCON :)

**Comment by hogepodge** [comment]
At the developer summit at KubeCon Seattle, we make plans to refocus efforts between /sig cloud-provider and /sig cluster-lifecycle to consolidate the getting started pages. The plan is for SIG-Docs to act as a high level project manager, setting goals and tasks for the corresponding SIGs to take back to their teams to accomplish. @zacharysarah did I capture that right?
