### ISSUE TITLE
Containers within a pod are not able to access each other by localhost

### ISSUE THREAD

**Issue by shbhsngh** [kubernetes/website#8815]
Below is the content of my yaml file
`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
spec:
  selector:
    matchLabels:
      run: driver
  replicas: 2
  template:
    metadata:
      labels:
        run: driver
    spec:
      containers:
      - name: driver
        image: shbh/driver
        ports:
        - containerPort: 80
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
`

Error logs from pod:
`
failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
`

**Comment by ajaeger** [comment]
/kind support

Please re-post your question to [Stack Overflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Stack Overflow to field support
requests. Before posting a new question, please search Stack Overflow for answers 
to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team
