### ISSUE TITLE
Content Type error causing pages to download instead of render

### ISSUE THREAD

**Issue by andrewwatson** [kubernetes/website#8953]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

the "next" button at the bottom of https://kubernetes.io/blog/2017/05/managing-microservices-with-istio-service-mesh/ doesn't work

it's a link to https://kubernetes.io/blog/2017/06/kubernetes-1.7-security-hardening-stateful-application-extensibility-updates 

**Proposed Solution:**
It could be a configuration problem but i'm not sure exactly

**Page to Update:**
https://kubernetes.io/blog/2017/06/kubernetes-1.7-security-hardening-stateful-application-extensibility-updates

**Comment by ajaeger** [comment]
I can reproduced this on my system. "Prev" works fine on that page but "next" fails.

**Comment by tengqm** [comment]
@lucperkins It looks like hugo is confused by the "." in the blog name. It is treating the rest of the file name as an extension name. You may want to rename the file so that we don't have dots in it.

Similar problems exist for following posts:

- 2016-03-00-Building-Highly-Available-Applications-Using-Kubernetes-New-Multi-Zone-Clusters-A.K.A-Ubernetes-Lite.md
- 2016-03-00-Kubernetes-1.2-And-Simplifying-Advanced-Networking-With-Ingress.md
- 2016-03-00-Kubernetes-1.2-Even-More-Performance-Upgrades-Plus-Easier-Application-Deployment-And-Management-.md
- 2016-07-00-Five-Days-Of-Kubernetes-1.3.md
- 2016-07-00-Kubernetes-1.3-Bridging-Cloud-Native-And-Enterprise-Workloads.md
- 2016-09-00-Kubernetes-1.4-Making-It-Easy-To-Run-On-Kuberentes-Anywhere.md
- 2016-10-00-Production-Kubernetes-Dashboard-UI-1.4-improvements_3.md
- 2016-12-00-Cluster-Federation-In-Kubernetes-1.5.md
- 2016-12-00-Five-Days-Of-Kubernetes-1.5.md
- 2016-12-00-Kubernetes-1.5-Supporting-Production-Workloads.md
- 2017-03-00-Five-Days-Of-Kubernetes-1.6.md
- 2017-03-00-Kubernetes-1.6-Multi-User-Multi-Workloads-At-Scale.md
- 2017-03-00-Scalability-Updates-In-Kubernetes-1.6.md
- 2017-06-00-Kubernetes-1.7-Security-Hardening-Stateful-Application-Extensibility-Updates.md
- 2018-03-26-kubernetes-1.10-stabilizing-storage-security-networking.md
- 2018-05-04-Announcing-Kubeflow-0.1.md
- 2018-06-26-kubernetes-1.11-release-announcement.md
- 2018-07-16-kubernetes-1.11-release-interview.md
