### ISSUE TITLE
Blog RSS is no longer updated

### ISSUE THREAD

**Issue by stevenewey** [kubernetes/website#9026]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The RSS feed for the Blog at http://blog.kubernetes.io/feeds/posts/default is no longer updated with new posts.

**Proposed Solution:**
Resume updating the RSS feed (or offer a new one)

**Page to Update:**
https://kubernetes.io/blog

**Comment by zparnold** [comment]
Hey there! Have you checked out this link? https://kubernetes.io/feed.xml It seems to have the most up-to-date information. We've recently changed the way Kubernetes.io works under the hood and you may have found something we need to get rid of. Thanks!

**Comment by stevenewey** [comment]
@zparnold perfect, thanks! Sorry I hadn't spotted that. Dropping a redirect at the old feed address could help redirect feed readers subscribed to the old address.

**Comment by craigbox** [comment]
Reopening as I have the same problem and a care to fix it.

I am subscribed to http://kubernetesio.blogspot.com/feeds/posts/default.  That is a redirect to http://blog.kubernetes.io/feeds/posts/default.

* blog.kubernetes.io redirects to https://kubernetes.io/blog/.
* http://blog.kubernetes.io/feeds/posts/default gives a completely different RSS than is at https://kubernetes.io/feed.xml.

Can someone please look into configuring Blogger to redirect the feed?  Otherwise we have potentially thousands of users who aren't getting the latest blog posts.

**Comment by zacharysarah** [comment]
@craigbox Is there anything prohibiting you from updating your own subscription?

At this point, unless there's an obvious fix that's trivial to implement, we're not willing to devote time or resources to customizing Blogger. Closing this issue.

**Comment by craigbox** [comment]
[Cool URIs don't change.](https://www.w3.org/Provider/Style/URI)

I updated my own subscription because I work in this space and noticed there was a problem. **There was no indication that I would have to** - at the very least we could have posted something on Blogger saying "This feed isn't being updated any more, please resubscribe.

I don't know how many people have just been orphaned by this but it could conceivably be in the thousands.

https://support.google.com/feedburner/answer/78465?hl=en suggests that it is probably as easy as a new URL in the Blogger console.  I would be very happy to test and actuate this.  Who has access to the Blogger installation?

**Comment by zacharysarah** [comment]
> https://support.google.com/feedburner/answer/78465?hl=en suggests that it is probably as easy as a new URL in the Blogger console.

I added a FeedBurner URL pointing to `https://kubernetes.io/feed.xml`. Can you verify whether it's working?

**Comment by craigbox** [comment]
31 new posts showed up in the old feed yesterday

(Hopefully the dates are OK going forward; I'll check in on this)

![image](https://user-images.githubusercontent.com/132510/42724051-69bf8eaa-8763-11e8-9306-21ef9d778e5f.png)
