### ISSUE TITLE
kubeadm setup out of date compared to task of kubeadm install

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#9209]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I know there's some heavy work being done to the kubeadm docs, but it appears that the task of installing kubeadm (https://kubernetes.io/docs/tasks/tools/install-kubeadm/) is more up to date than the docs of creating a kubeadm cluster (https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/). I haven't gone through its entirety but first noticed the "Before you begin" is more detailed in the installing kubeadm.

**Proposed Solution:**
Compare the two docs to make sure they reflect accurate information

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubeadm/
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by jimangel** [comment]
I will work on this and create an updated PR as long as it's not a duplicate...

**Comment by neolit123** [comment]
@jimangel 
thanks for having a look.

we and sig-docs are in the process of refactoring all kubeadm pages. it could take some time, so it would be best if you **hold on this PR**, because it could create issues with the coordination of our efforts.

frankly, i still don't know what pages we are going to merge / move / remove, but the recent discussions suggested that most of our items in `tasks` should be moved to `setup` and some new items would be added to `tasks`.

/cc @Bradamant3
