### ISSUE TITLE
Stabilization: Improve code in numbered lists.

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#9353]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
In numbered lists, code snippets are not always aligned correctly. Also, the code in the snippet is not always aligned with the left edge of the snippet box. We have the same problem with yaml files displayed as part of a list item. The alignment of the yaml block is not correct.

**Proposed Solution:**
Figure out how to get code snippets and yaml blocks to appear correctly in numbered lists. Find topics where this is a problem, and fix the topics.

**Page to Update:**
Here's an example topic, but I suspect there are several other topics that have the same problem:
https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

**Comment by ajaeger** [comment]
@steveperry-53 , I went over the referenced list and it all looked fine to me - what did I miss? Could you attach a screenshot perhaps, please?

**Comment by tengqm** [comment]
@ajaeger I believe Steve is referring to a general problem that exists in many pages. There are many cases where the following elements will break a numbered list:
- A shortcode such as `note`, `warning` or `code`
- A code snippet where the code is (not) wrapped with three backticks etc.

The page Steve used as reference has been fixed in #9258 (see:
https://github.com/kubernetes/website/pull/9258/files ) when I was moving the YAML files out of the docs tree. That is the reason why you are not seeing the problem Steve mentioned.

**Comment by ajaeger** [comment]
@tengqm , thanks for explanation.
