### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/

### ISSUE THREAD

**Issue by alexxa** [kubernetes/website#9367]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
I'm not sure if the page [1] is autogenerated, since it doesn't match the list of kube-apiserver flags in the latest Kubernetes release. Some are there, others don't, different names, different type, different description.

For example, the [source code says there is a --addmission-control](https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/kubeapiserver/options/admission.go#L68) flag. There is no such flag on page [1]. 

Flag `--alsologtostderr` is not mentioned on [1].

I don't see flags `--audit-log-batch*` in the source code or `kube-apiserver --flags` output, but page [1] says they are there, and so on.

**Proposed Solution:**
Don't include output of such menus in docs. It requires extra time and effort to maintain it. If it's not autogenerated from the source code, it can be outdated any moment.

**Page to Update:**
[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

v1.9.9

**Comment by alexxa** [comment]
@tengqm Hi, maybe I don't follow smth but I compare website V1.11 and the source code of release 1.11. For example, option: https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/kubeapiserver/options/admission.go#L68 is not mentioned on https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ which is V1.11

**Comment by tengqm** [comment]
@alexxa Thanks for the reference. Investigating ... The case is not straightforward because there have been some struggling on whether "deprecated" flags should be shown, AND where "hidden" flags should be shown. Some time ago, the recommended practice was to HIDE the "hidden" flags, but that practice has received many complaints. Will look into this and see if we need to regenerate all the reference docs again.

**Comment by alexxa** [comment]
Thanks @tengqm
