### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-scheduler/

### ISSUE THREAD

**Issue by johanot** [kubernetes/website#9612]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/#options

A lot of cmdline options on kube-scheduler has been listed as DEPRECATED, but what to use instead? 
`--kubeconfig` for example? Is it prefered to configure the scheduler by passing a file to `--config`?

`--port` is deprecated as well. The description seems like it is c/p'ed from apiserver and controller-manager. It says:
> See --secure-port instead.

.. but `--secure-port` is not in the options list for kube-scheduler?

.. and, if TLS is to be used, doesn't kube-scheduler lack flags like `--tls-cert-file` and `tls-key-file`? Or perhaps communication from the scheduler is only one-way, from scheduler => apiserver. Maybe it doesn't need a listening port at all (besides metrics)? .. I'm guessing here :).

Same problem for `--address`, i.e. `--bind-address` does not exist.

**Proposed Solution:**
- All deprecated flags should provide "use instead"-alternatives
- The `--config` flag should provide a link to some sort of config file reference doc, like: https://godoc.org/k8s.io/kubernetes/pkg/apis/componentconfig#KubeSchedulerConfiguration
- I don't think `--write-config-to` counts as documentation for the config file
- The `--bind-address` and `--port` flags should not reference other flags that don't exist

**Page to Update:**
https://kubernetes.io/...

**Comment by tommyknows** [comment]
Agreed. 
The kubelet allows the `--config` flag, and there is a [page](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) the docs that describes this file. 

The config file reference doc you attached does not show the json-names, but [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/componentconfig/v1alpha1/types.go#L75) does. 

I think this needs to be assigned to
/sig docs

There should be at least on place that references the above link, so that people do not have to search for it.

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/componentconfig/v1alpha1/types.go#L75
