### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by KlavsKlavsen** [kubernetes/website#9655]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
You say one can continue with "external etcd" approach to HA k8 cluster, but that fails with:
[preflight] Some fatal errors occurred:
        [ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
        [ERROR Port-10250]: Port 10250 is in use

and kubelet is obviously already running, because its running etcd :)

**Proposed Solution:**
fix so init can handle when people followed the documentation, and setup etcd using kubelet/docker?

**Comment by KlavsKlavsen** [comment]
I ended up setting up etcd myself - and then running kubeadm - which gives same port conflict, but that was resolved by doing: ```
kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=Port-10250
```

**Comment by ReSearchITEng** [comment]
yes, you need both.
Here is our ansible project for k8s with master HA. The line: https://github.com/ReSearchITEng/kubeadm-playbook/blob/fea83b68b8035f946bfa138c4cad25a35d34f6a7/roles/master/tasks/main.yml#L185

**Comment by Ramane19** [comment]
How do i get rid of this error? 

[preflight] Some fatal errors occurred:
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists

**Comment by neolit123** [comment]
call `kubeadm reset` first.

**Comment by Ramane19** [comment]
> call `kubeadm reset` first.

I did, it did not work. I went up to rebuilding it from scratch but get the same error

**Comment by neolit123** [comment]
that's unlikely, `kubeadm reset` deletes the manifests under `/etc/kubernetes/manifests/`.

**Comment by Ramane19** [comment]
After rebuilding and using the kubeadm reset feature, i get this error as root 

kubectl get pods --all-namespaces
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

But get this as user
kubectl get pods --all-namespacesNAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
kube-system   coredns-fb8b8dccf-d9pp8                   0/1     CrashLoopBackOff   5          7m13s
kube-system   coredns-fb8b8dccf-rkqcj                   0/1     CrashLoopBackOff   5          7m13s
kube-system   etcd-mola-virtualbox                      1/1     Running            0          6m22s
kube-system   kube-apiserver-mola-virtualbox            1/1     Running            0          6m29s
kube-system   kube-controller-manager-mola-virtualbox   1/1     Running            0          6m20s
kube-system   kube-proxy-t4ld7                          1/1     Running            0          7m13s
kube-system   kube-scheduler-mola-virtualbox            1/1     Running            0          6m27s
kube-system   weave-net-kc79d                           2/2     Running            0          3m52s

Did i miss something?

**Comment by neolit123** [comment]
google the "kubeadm troubleshooting". there are some potential fixes for coredns crashloop.
