### ISSUE TITLE
Issue with k8s.io//docs/tasks/tools/install-kubectl/ [File: /content/en/docs/tasks/tools/install-kubectl.md]

### ISSUE THREAD

**Issue by lyongjn** [kubernetes/website#9877]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The section of "[Install with Powershell from PSGallery](https://kubernetes.io/docs/tasks/tools/install-kubectl/)" includes a powershell named install-kubectl.ps1, which can be found at this website : https://www.powershellgallery.com/packages/install-kubectl/1.6/Content/install-kubectl.ps1.

My os version is Windows 10, when I executes install-kubectl.ps1, one error occurs : 
    Invoke-WebRequest : 基础连接已经关闭: 发送时发生错误。

**Proposed Solution:**
I googled this error and found a solution for this by adding this scripts to install-kubectl.ps1.
$AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
[System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
This reason is the k8s website uses the tls1.2 protocal, but .NET only support ssl v3 and tls 1.0.
See this  website for further information : https://stackoverflow.com/questions/36265534/invoke-webrequest-ssl-fails/36266735#36266735.

**Page to Update:**
https://kubernetes.io/...

**Comment by eelco-de-boer** [comment]
@lucperkins Well the problem lies in this package that you link to on the website.
Do you know or does one of maintainers of this repo have contact with the maintainer of this installation package on the PSGallery? He needs to fix this on PSGallery, but it has not seen an update since a year there.

So there are two options:
1. Remove the PSGallery installation option from https://kubernetes.io/docs/tasks/tools/install-kubectl/
2. Wake up the maintainer of the package on PSGallery to update the install script with the appropriate TLS1.2 setting like @lyongjn said.

**Comment by it-praktyk** [comment]
The script install-kubectl.ps1 was updated to v. 1.7 by @bottkars yesterday. I've tested it, works correctly on W2K8 R2 and PowerShell 3.0.

IMHO, the issue can be closed now.

**Comment by Aprilmei** [comment]
The same issue on my windows 10. v1.7 doesn't work there
